#!/usr/bin/env python3
"""Generate docs/php/compatibility.md — the elephc vs PHP comparison chart.

Sources (all under scripts/docs/):
- builtin_registry.json     the elephc side (generated by extract_builtins.py)
- php_baseline.json         real PHP snapshot (generated by extract_php_baseline.py)
- comparison_catalog.toml   hand-curated language/extension/limitation entries

Deterministic: identical inputs produce byte-identical output; the only date
shown is the snapshot date stored in php_baseline.json. Exits non-zero with
actionable errors on any validation failure.
"""
from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

VALID_STATUSES = ("supported", "partial", "planned", "unsupported")
STATUS_LABELS = {
    "supported": "✅ Supported",
    "partial": "🟡 Partial",
    "planned": "🔜 Planned",
    "unsupported": "❌ Not supported",
}

# Registry names that are PHP language constructs, not functions: they never
# appear in get_defined_functions(), so the baseline invariant must not flag
# them. Adjust ONLY for genuine constructs (extend from Task 1 step 3's probe).
LANGUAGE_CONSTRUCTS = frozenset({
    "isset", "empty", "unset", "exit", "die", "eval", "print", "echo",
    "list", "array", "include", "include_once", "require", "require_once",
})

# Public registry builtins that are genuinely absent from baseline PHP —
# verified against php.net and the PHP 8.5 release notes on 2026-08-11. They
# render in the "Beyond PHP" section with these notes instead of failing the
# baseline invariant. Flagging them `extension: true` in src/builtins would be
# the single-source fix, but that also hides them under --strict-php — a
# compiler behavior change deferred to the maintainer (see ledger).
NOT_IN_BASELINE = {
    "clamp": "No PHP equivalent (not in PHP 8.4/8.5)",
    "grapheme_strrev": "No PHP equivalent (not in PHP 8.4/8.5 intl)",
    "is_real": "Removed in PHP 8.0; kept as a compatibility alias of is_float()",
    "log2": "No PHP equivalent (PHP has log(), log10(), log1p())",
}

# Public registry builtins that PHP DOES define, but only in a release NEWER than
# the vendored baseline snapshot. They are neither a coverage gap nor a "Beyond
# PHP" extension: counting them against the older baseline's denominator would
# claim coverage of functions that baseline never had, so they are reported in
# their own sentence instead. Name -> the PHP release that added it.
NEWER_THAN_BASELINE = {
    "curl_multi_get_handles": "8.5",
    "curl_share_init_persistent": "8.5",
}


def _load_json(path: Path, required_keys: tuple[str, ...], errors: list[str]):
    if not path.exists():
        errors.append(f"{path}: missing file")
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    for key in required_keys:
        if isinstance(data, dict) and key not in data:
            errors.append(
                f"{path.name}: missing key '{key}' "
                f"(regenerate with scripts/docs/extract_php_baseline.py)"
            )
    return data


class EvidenceChecker:
    """Evidence is a repo path, or a test fn name found as `fn <name>` under tests/."""

    def __init__(self, repo_root: Path):
        self.repo_root = repo_root
        self._corpus: str | None = None

    def exists(self, evidence: str) -> bool:
        if (self.repo_root / evidence).exists():
            return True
        if self._corpus is None:
            parts = []
            tests_dir = self.repo_root / "tests"
            if tests_dir.is_dir():
                for rs in sorted(tests_dir.rglob("*.rs")):
                    parts.append(rs.read_text(encoding="utf-8", errors="ignore"))
            self._corpus = "\n".join(parts)
        return f"fn {evidence}(" in self._corpus


def validate_catalog(catalog: dict, repo_root: Path, baseline_extensions=()) -> list[str]:
    errors: list[str] = []
    checker = EvidenceChecker(repo_root)
    for section in ("language", "extensions"):
        for i, entry in enumerate(catalog.get(section, []), start=1):
            feature = entry.get("feature")
            where = f"comparison_catalog.toml [[{section}]] " + (
                f"'{feature}'" if feature else f"#{i}"
            )
            if not feature:
                errors.append(f"{where}: missing 'feature'")
                continue
            status = entry.get("status")
            if status not in VALID_STATUSES:
                errors.append(f"{where}: status {status!r} is not one of {'|'.join(VALID_STATUSES)}")
            if status in ("supported", "partial"):
                evidence = entry.get("evidence")
                if not evidence:
                    errors.append(f"{where}: status '{status}' requires 'evidence'")
                elif not checker.exists(evidence):
                    errors.append(
                        f"{where}: evidence '{evidence}' not found "
                        f"(no such repo path and no `fn {evidence}` under tests/)"
                    )
            docs = entry.get("docs")
            if docs and not (repo_root / docs).exists():
                errors.append(f"{where}: docs path '{docs}' does not exist")
            if section == "extensions" and "modules" in entry:
                modules = entry["modules"]
                if not isinstance(modules, list) or not all(isinstance(m, str) for m in modules):
                    errors.append(f"{where}: 'modules' must be a list of strings")
                else:
                    for m in modules:
                        if m not in baseline_extensions:
                            errors.append(
                                f"{where}: modules entry '{m}' is not a baseline extension"
                            )
    for i, entry in enumerate(catalog.get("limitations", []), start=1):
        if not entry.get("title") or not entry.get("notes"):
            errors.append(f"comparison_catalog.toml [[limitations]] #{i}: needs 'title' and 'notes'")
    return errors


def match_builtins(registry: list, baseline_functions: dict):
    """Split registry entries into per-PHP-extension supported lists,
    elephc-specific extensions ('Beyond PHP'), language constructs, and
    functions that postdate the baseline snapshot."""
    # Staleness guard: NOT_IN_BASELINE is only correct while every name in it
    # is genuinely absent from the baseline. If a baseline refresh adds one
    # back (e.g. a new PHP release ships it), the escape hatch has gone
    # stale and must be pruned rather than silently keep swallowing it.
    dead = sorted(set(NOT_IN_BASELINE) & set(baseline_functions))
    assert not dead, f"NOT_IN_BASELINE entries now exist in the baseline; remove them: {dead}"
    # Same guard for the newer-than-baseline hatch: once the snapshot is refreshed
    # onto a PHP that ships these, they must be counted in coverage, not excused.
    dead = sorted(set(NEWER_THAN_BASELINE) & set(baseline_functions))
    assert not dead, f"NEWER_THAN_BASELINE entries now exist in the baseline; remove them: {dead}"

    errors: list[str] = []
    per_ext: dict[str, list] = {}
    beyond: list = []
    constructs: list = []
    newer: list = []
    for entry in registry:
        if entry["is_internal"]:
            continue
        if entry["is_extension"]:
            beyond.append(entry)
            continue
        name = entry["name"]
        ext = baseline_functions.get(name)
        if ext is None:
            if name in LANGUAGE_CONSTRUCTS:
                constructs.append(entry)
            elif name in NOT_IN_BASELINE:
                beyond.append(entry)
            elif name in NEWER_THAN_BASELINE:
                newer.append(entry)
            else:
                errors.append(
                    f"builtin '{name}' is public in builtin_registry.json but absent from "
                    f"php_baseline.json: flag it (is_extension/is_internal), add it to "
                    f"LANGUAGE_CONSTRUCTS if it is a PHP construct, list it in "
                    f"NEWER_THAN_BASELINE if a newer PHP added it, or refresh the baseline "
                    f"with scripts/docs/extract_php_baseline.py"
                )
            continue
        per_ext.setdefault(ext, []).append(entry)
    return per_ext, beyond, constructs, newer, errors


def _pct(part: int, whole: int) -> str:
    return f"{100 * part / whole:.0f}%" if whole else "—"


def _feature_cell(entry: dict) -> str:
    name = entry["feature"]
    docs = entry.get("docs", "")
    if docs.startswith("docs/php/"):
        # The page lives in docs/php/, so sibling pages link relative to it.
        cell = f"[{name}](./{docs.removeprefix('docs/php/')})"
    else:
        cell = name
    php = entry.get("php")
    if php:
        cell += f" ([PHP]({php}))"
    return cell


def _catalog_table(entries: list) -> list[str]:
    lines = ["| Feature | Status | Notes |", "|---|---|---|"]
    for entry in entries:
        notes = entry.get("notes", "")
        lines.append(f"| {_feature_cell(entry)} | {STATUS_LABELS[entry['status']]} | {notes} |")
    return lines


def render(baseline, per_ext, beyond, constructs, newer, catalog) -> str:
    functions = baseline["functions"]
    totals: dict[str, int] = {}
    for ext in functions.values():
        totals[ext] = totals.get(ext, 0) + 1

    matched = sum(len(v) for v in per_ext.values())
    baseline_total = len(functions)

    # Modules whose functions are (partly or fully) implemented outside the
    # registry — via compiler rewrites or runtime preludes — so the registry
    # count alone understates them. Curated per-entry in the catalog rather
    # than hardcoded here, so this stays data-driven.
    module_notes = {
        m: entry["feature"]
        for entry in catalog.get("extensions", [])
        for m in entry.get("modules", [])
    }

    lines = [
        "---",
        'title: "PHP Compatibility"',
        'description: "How much of PHP elephc covers: builtin coverage by module, language constructs, extensions, and known limitations."',
        "sidebar:",
        "  order: 21",
        "---",
        "",
        "<!-- GENERATED FILE — do not edit by hand. -->",
        "<!-- Regenerate with: python3 scripts/docs/gen_php_comparison.py -->",
        "",
        f"Baseline: **PHP {baseline['php_version']}** (CLI snapshot of "
        f"{baseline['generated_at']}, {len(baseline['extensions'])} extensions, "
        f"{baseline_total} internal functions).",
        "",
        f"Overall builtin coverage: **{matched} / {baseline_total}** "
        f"({_pct(matched, baseline_total)}).",
        "",
        "## Builtin coverage by PHP module",
        "",
        "| PHP module | Supported | Coverage | AOT | eval() |",
        "|---|---|---|---|---|",
    ]
    for ext in sorted(totals):
        supported = per_ext.get(ext, [])
        in_aot = sum(1 for b in supported if not b["eval_only"])
        in_eval = sum(1 for b in supported if b["eval"]["supported"])
        marker = "†" if ext in module_notes else ""
        lines.append(
            f"| `{ext}`{marker} | {len(supported)} / {totals[ext]} "
            f"| {_pct(len(supported), totals[ext])} | {in_aot} | {in_eval} |"
        )
    if module_notes:
        lines += [
            "",
            "The table counts functions implemented as native registry "
            "builtins. Modules marked † have some or all of their functions "
            "implemented through other elephc mechanisms (compiler rewrites "
            "or runtime preludes); their real support status is tracked in "
            "the Extensions section below.",
        ]
    functionless = sorted(set(baseline["extensions"]) - set(totals))
    if functionless:
        names = ", ".join(f"`{e}`" for e in functionless)
        lines += [
            "",
            f"The remaining {len(functionless)} baseline extensions expose "
            f"classes but no procedural functions, so they have no row above: "
            f"{names}.",
        ]
    missing_bundled = baseline.get("missing_bundled", [])
    if missing_bundled:
        names = ", ".join(f"`{e}`" for e in missing_bundled)
        lines += [
            "",
            f"{len(missing_bundled)} extensions bundled with php-src were not "
            f"loaded by the PHP build that produced this snapshot and are not "
            f"counted: {names}.",
        ]
    if constructs:
        names = ", ".join(f"`{b['name']}()`" for b in sorted(constructs, key=lambda b: b["name"]))
        lines += [
            "",
            f"In addition, elephc implements {len(constructs)} PHP language "
            f"constructs that PHP does not count as functions: {names}.",
        ]
    if newer:
        names = ", ".join(
            f"`{b['name']}()` (PHP {NEWER_THAN_BASELINE[b['name']]})"
            for b in sorted(newer, key=lambda b: b["name"])
        )
        lines += [
            "",
            f"elephc also implements {len(newer)} function(s) that PHP added "
            f"AFTER this baseline release, so they cannot be counted against it: "
            f"{names}.",
        ]

    lines += ["", "## Language constructs", ""]
    lines += _catalog_table(catalog.get("language", []))
    lines += ["", "## Extensions", ""]
    lines += _catalog_table(catalog.get("extensions", []))

    if beyond:
        lines += [
            "",
            "## Beyond PHP",
            "",
            "elephc-specific builtins with no PHP equivalent (not counted in "
            "coverage above):",
            "",
            "| Builtin | Area | Description |",
            "|---|---|---|",
        ]
        for b in sorted(beyond, key=lambda b: (b["area"], b["name"])):
            desc = b["description"]
            note = NOT_IN_BASELINE.get(b["name"])
            if note:
                desc = f"{desc} *({note})*"
            lines.append(f"| `{b['name']}()` | {b['area']} | {desc} |")

    limitations = catalog.get("limitations", [])
    if limitations:
        lines += ["", "## Known limitations", ""]
        for entry in limitations:
            lines += [f"**{entry['title']}.** {entry['notes']}", ""]

    # Render self-check: the summary numbers must equal the table's sums.
    table_supported = sum(len(v) for v in per_ext.values())
    table_total = sum(totals.values())
    assert table_supported == matched, (table_supported, matched)
    assert table_total == baseline_total, (table_total, baseline_total)
    assert set(totals) <= set(baseline["extensions"]), sorted(set(totals) - set(baseline["extensions"]))

    return "\n".join(lines).rstrip() + "\n"


def run(repo_root: Path = REPO_ROOT) -> int:
    scripts_docs = repo_root / "scripts" / "docs"
    errors: list[str] = []

    registry = _load_json(scripts_docs / "builtin_registry.json", (), errors)
    baseline = _load_json(
        scripts_docs / "php_baseline.json",
        ("php_version", "generated_at", "extensions", "functions"),
        errors,
    )
    catalog_path = scripts_docs / "comparison_catalog.toml"
    catalog = None
    if catalog_path.exists():
        with catalog_path.open("rb") as fh:
            catalog = tomllib.load(fh)
    else:
        errors.append(f"{catalog_path}: missing file")
    if errors:
        return _fail(errors)

    errors.extend(validate_catalog(catalog, repo_root, baseline["extensions"]))
    per_ext, beyond, constructs, newer, match_errors = match_builtins(
        registry, baseline["functions"]
    )
    errors.extend(match_errors)
    if errors:
        return _fail(errors)

    page = render(baseline, per_ext, beyond, constructs, newer, catalog)
    output = repo_root / "docs" / "php" / "compatibility.md"
    output.write_text(page, encoding="utf-8")
    print(f"wrote {output.relative_to(repo_root)}")
    return 0


def _fail(errors: list[str]) -> int:
    for error in errors:
        print(f"error: {error}", file=sys.stderr)
    print(f"{len(errors)} error(s); docs/php/compatibility.md not written", file=sys.stderr)
    return 1


def main() -> int:
    return run()


if __name__ == "__main__":
    raise SystemExit(main())
