#!/usr/bin/env python3
"""Generate docs/php/compatibility.md — the elephc vs PHP comparison chart.

Sources (all under scripts/docs/):
- builtin_registry.json     elephc functions (generated by extract_builtins.py)
- symbol_registry.json      elephc classes and constants (generated by extract_builtins.py)
- php_baseline.json         real PHP snapshot: functions, classes, constants per module
                            (generated by extract_php_baseline.py)
- comparison_catalog.toml   hand-curated language/extension/limitation entries

Every elephc symbol carries the PHP module its shared contract declares, so the page
groups by that module and uses the baseline only for the denominators and as a
cross-check: a symbol whose module or existence disagrees with PHP fails generation.

Deterministic: identical inputs produce byte-identical output; the only date shown is
the snapshot date stored in php_baseline.json. Exits non-zero with actionable errors on
any validation failure.
"""
from __future__ import annotations

import json
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

VALID_STATUSES = ("supported", "partial", "planned", "unsupported")
STATUS_LABELS = {
    "supported": "✅ Supported",
    "partial": "🟡 Partial",
    "planned": "🔜 Planned",
    "unsupported": "❌ Not supported",
}

# AOT routes that are PHP language constructs rather than functions: PHP never lists
# them in get_defined_functions(), so they are reported in their own sentence.
CONSTRUCT_KINDS = frozenset({"language-construct", "dedicated-syntax"})

# Notes for elephc-only functions rendered in the "Beyond PHP" section.
BEYOND_PHP_NOTES = {
    "clamp": "No PHP equivalent (not in PHP 8.4/8.5)",
    "grapheme_strrev": "No PHP equivalent (not in PHP 8.4/8.5 intl)",
    "is_real": "Removed in PHP 8.0; kept as a compatibility alias of is_float()",
    "log2": "No PHP equivalent (PHP has log(), log10(), log1p())",
}

# Constants whose elephc value deliberately differs from the baseline PHP build, with the
# reason. Any other integer value mismatch fails generation.
KNOWN_VALUE_DIVERGENCES = {
    "CURLINFO_LASTONE": "pinned to the frozen libcurl 8.21.0 header (71) rather than the baseline build's older libcurl",
    "CURLAUTH_ANY": "unsigned bitmask spelling of PHP's negative long",
    "CURLAUTH_ANYSAFE": "unsigned bitmask spelling of PHP's negative long",
    "CURLPROTO_ALL": "unsigned bitmask spelling of PHP's negative long",
    "CURLSSH_AUTH_ANY": "unsigned bitmask spelling of PHP's negative long",
    "CURLSSH_AUTH_DEFAULT": "unsigned bitmask spelling of PHP's negative long",
    "E_ALL": "PHP 8.4 value (32767); PHP 8.5 dropped E_STRICT from the mask",
    "EXIF_USE_MBSTRING": "PHP reports 1 only when built with mbstring; elephc's Exif reader never routes through mbstring",
    "IMAGETYPE_COUNT": "elephc's image-type table stops at PHP 8.4's 20 entries (no HEIC/HEIF)",
}


def _load_json(path: Path, required_keys: tuple[str, ...], errors: list[str]):
    if not path.exists():
        errors.append(f"{path}: missing file")
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    for key in required_keys:
        if isinstance(data, dict) and key not in data:
            errors.append(
                f"{path.name}: missing key '{key}' "
                f"(regenerate with scripts/docs/extract_php_baseline.py)"
            )
    return data


class EvidenceChecker:
    """Evidence is a repo path, or a test fn name found as `fn <name>` under tests/."""

    def __init__(self, repo_root: Path):
        self.repo_root = repo_root
        self._corpus: str | None = None

    def exists(self, evidence: str) -> bool:
        if (self.repo_root / evidence).exists():
            return True
        if self._corpus is None:
            parts = []
            tests_dir = self.repo_root / "tests"
            if tests_dir.is_dir():
                for rs in sorted(tests_dir.rglob("*.rs")):
                    parts.append(rs.read_text(encoding="utf-8", errors="ignore"))
            self._corpus = "\n".join(parts)
        return f"fn {evidence}(" in self._corpus


def validate_catalog(catalog: dict, repo_root: Path, baseline_extensions=()) -> list[str]:
    errors: list[str] = []
    checker = EvidenceChecker(repo_root)
    for section in ("language", "extensions"):
        for i, entry in enumerate(catalog.get(section, []), start=1):
            feature = entry.get("feature")
            where = f"comparison_catalog.toml [[{section}]] " + (
                f"'{feature}'" if feature else f"#{i}"
            )
            if not feature:
                errors.append(f"{where}: missing 'feature'")
                continue
            status = entry.get("status")
            if status not in VALID_STATUSES:
                errors.append(f"{where}: status {status!r} is not one of {'|'.join(VALID_STATUSES)}")
            if status in ("supported", "partial"):
                evidence = entry.get("evidence")
                if not evidence:
                    errors.append(f"{where}: status '{status}' requires 'evidence'")
                elif not checker.exists(evidence):
                    errors.append(
                        f"{where}: evidence '{evidence}' not found "
                        f"(no such repo path and no `fn {evidence}` under tests/)"
                    )
            docs = entry.get("docs")
            if docs and not (repo_root / docs).exists():
                errors.append(f"{where}: docs path '{docs}' does not exist")
            if section == "extensions" and "modules" in entry:
                modules = entry["modules"]
                if not isinstance(modules, list) or not all(isinstance(m, str) for m in modules):
                    errors.append(f"{where}: 'modules' must be a list of strings")
                else:
                    for m in modules:
                        if m not in baseline_extensions:
                            errors.append(
                                f"{where}: modules entry '{m}' is not a baseline extension"
                            )
    for i, entry in enumerate(catalog.get("limitations", []), start=1):
        if not entry.get("title") or not entry.get("notes"):
            errors.append(f"comparison_catalog.toml [[limitations]] #{i}: needs 'title' and 'notes'")
    return errors


def _minor(version: str) -> tuple[int, int]:
    major, minor = version.split(".")[:2]
    return int(major), int(minor)


class Coverage:
    """Per-module tallies of one symbol kind (functions, classes, or constants)."""

    def __init__(self):
        self.supported: dict[str, list] = defaultdict(list)

    def add(self, module: str, symbol: dict):
        self.supported[module].append(symbol)

    def count(self, module: str) -> int:
        return len(self.supported.get(module, []))

    def total(self) -> int:
        return sum(len(v) for v in self.supported.values())

    def aot(self, module: str) -> int:
        return sum(1 for s in self.supported.get(module, []) if s["_aot"])

    def eval(self, module: str) -> int:
        return sum(1 for s in self.supported.get(module, []) if s["_eval"])


def classify(registry: list, symbols: dict, baseline: dict):
    """Attribute every elephc symbol to its PHP module and cross-check it with the baseline.

    Returns (functions, classes, constants) coverage, plus the lists of constructs,
    elephc-only symbols, PECL symbols, symbols newer than the baseline, and errors.
    """
    errors: list[str] = []
    baseline_minor = _minor(baseline["php_version"])
    functions, classes, constants = Coverage(), Coverage(), Coverage()
    constructs: list = []
    beyond: dict[str, list] = {"functions": [], "classes": [], "constants": []}
    pecl: dict[str, dict[str, list]] = defaultdict(lambda: {"functions": [], "classes": [], "constants": []})
    newer: dict[str, list] = {"functions": [], "classes": [], "constants": []}
    dynamic: list = []
    bundled_modules = set(baseline["extensions"]) | set(baseline.get("missing_bundled", []))

    def place(kind: str, symbol: dict, coverage: Coverage, present, module_of):
        name = symbol["name"]
        module = symbol["module"]
        since = symbol.get("since")
        if symbol.get("internal"):
            return
        if module == "elephc" or symbol.get("extension"):
            beyond[kind].append(symbol)
            return
        if module not in bundled_modules:
            pecl[module][kind].append(symbol)
            return
        if since and _minor(since) > baseline_minor:
            newer[kind].append(symbol)
            return
        if not present(name):
            errors.append(
                f"{kind[:-1]} '{name}' is public in elephc's catalog (module '{module}', "
                f"since {since or 'always'}) but absent from php_baseline.json: fix its module or "
                f"`since` in the shared contract, mark it extension/internal, or refresh the "
                f"baseline with scripts/docs/extract_php_baseline.py"
            )
            return
        php_module = module_of(name)
        if php_module != module:
            errors.append(
                f"{kind[:-1]} '{name}' is catalogued under module '{module}' but PHP "
                f"{baseline['php_version']} attributes it to '{php_module}'"
            )
            return
        coverage.add(module, symbol)

    baseline_functions = baseline["functions"]
    for entry in registry:
        if entry.get("is_internal"):
            continue
        aot = entry.get("aot") or {}
        symbol = {
            "name": entry["canonical_name"],
            "module": entry["module"],
            "since": entry.get("since"),
            "extension": entry.get("is_extension", False),
            "internal": False,
            "area": entry.get("area", ""),
            "description": entry.get("description", ""),
            "_aot": not entry.get("eval_only", False),
            "_eval": bool((entry.get("eval") or {}).get("supported")),
        }
        if aot.get("kind") in CONSTRUCT_KINDS and not (
            symbol["module"] == "elephc" or symbol["extension"]
        ):
            constructs.append(symbol)
            continue
        place(
            "functions", symbol, functions,
            lambda n: n in baseline_functions,
            lambda n: baseline_functions[n],
        )

    baseline_classes = baseline.get("classes", {})
    for entry in symbols.get("classes", []):
        symbol = dict(entry)
        symbol["_aot"] = bool(entry["aot"]["supported"])
        symbol["_eval"] = bool(entry["eval"]["supported"])
        place(
            "classes", symbol, classes,
            lambda n: n.lower() in baseline_classes,
            lambda n: baseline_classes[n.lower()]["extension"],
        )

    baseline_constants = baseline.get("constants", {})
    for entry in symbols.get("constants", []):
        symbol = dict(entry)
        symbol["_aot"] = bool(entry["aot"]["supported"])
        symbol["_eval"] = bool(entry["eval"]["supported"])
        if entry.get("route") == "dynamic":
            # Defined at runtime by an elephc mechanism (`SID` at session start); PHP's
            # Reflection never lists such constants, so the baseline cannot count them.
            dynamic.append(symbol)
            continue
        place(
            "constants", symbol, constants,
            lambda n: n in baseline_constants,
            lambda n: baseline_constants[n]["extension"],
        )
        php = baseline_constants.get(entry["name"])
        value = entry.get("value")
        if (
            php is not None
            and isinstance(value, int) and not isinstance(value, bool)
            and isinstance(php["value"], int) and not isinstance(php["value"], bool)
            and value != php["value"]
            and entry["name"] not in KNOWN_VALUE_DIVERGENCES
        ):
            errors.append(
                f"constant '{entry['name']}' is {value} in elephc's catalog but "
                f"{php['value']} in PHP {baseline['php_version']}: fix the catalog value or "
                f"record the divergence in KNOWN_VALUE_DIVERGENCES with its reason"
            )
    return functions, classes, constants, constructs, beyond, pecl, newer, dynamic, errors


def _pct(part: int, whole: int) -> str:
    return f"{100 * part / whole:.0f}%" if whole else "—"


def _cell(part: int, whole: int) -> str:
    if not whole:
        return "—"
    return f"{part} / {whole} · {_pct(part, whole)}"


def _feature_cell(entry: dict) -> str:
    name = entry["feature"]
    docs = entry.get("docs", "")
    if docs.startswith("docs/php/"):
        # The page lives in docs/php/, so sibling pages link relative to it.
        cell = f"[{name}](./{docs.removeprefix('docs/php/')})"
    else:
        cell = name
    php = entry.get("php")
    if php:
        cell += f" ([PHP]({php}))"
    return cell


def _catalog_table(entries: list) -> list[str]:
    lines = ["| Feature | Status | Notes |", "|---|---|---|"]
    for entry in entries:
        notes = entry.get("notes", "")
        lines.append(f"| {_feature_cell(entry)} | {STATUS_LABELS[entry['status']]} | {notes} |")
    return lines


def _symbol_label(kind: str, symbol: dict) -> str:
    if kind == "functions":
        return f"`{symbol['name']}()`"
    return f"`{symbol['name']}`"


def render(baseline, functions, classes, constants, constructs, beyond, pecl, newer, dynamic, catalog) -> str:
    totals = {
        "functions": defaultdict(int),
        "classes": defaultdict(int),
        "constants": defaultdict(int),
    }
    for ext in baseline["functions"].values():
        totals["functions"][ext] += 1
    for entry in baseline.get("classes", {}).values():
        totals["classes"][entry["extension"]] += 1
    for entry in baseline.get("constants", {}).values():
        totals["constants"][entry["extension"]] += 1
    grand = {kind: sum(t.values()) for kind, t in totals.items()}
    matched = {"functions": functions.total(), "classes": classes.total(), "constants": constants.total()}
    coverages = {"functions": functions, "classes": classes, "constants": constants}

    lines = [
        "---",
        'title: "PHP Compatibility"',
        'description: "How much of PHP elephc covers: functions, classes, and constants by module, language constructs, extensions, and known limitations."',
        "sidebar:",
        "  order: 21",
        "---",
        "",
        "<!-- GENERATED FILE — do not edit by hand. -->",
        "<!-- Regenerate with: python3 scripts/docs/gen_php_comparison.py -->",
        "",
        f"Baseline: **PHP {baseline['php_version']}** (CLI snapshot of "
        f"{baseline['generated_at']}, {len(baseline['extensions'])} extensions, "
        f"{grand['functions']} functions, {grand['classes']} classes, "
        f"{grand['constants']} constants).",
        "",
        "Overall coverage: functions **"
        f"{matched['functions']} / {grand['functions']}** ({_pct(matched['functions'], grand['functions'])}), "
        f"classes **{matched['classes']} / {grand['classes']}** ({_pct(matched['classes'], grand['classes'])}), "
        f"constants **{matched['constants']} / {grand['constants']}** ({_pct(matched['constants'], grand['constants'])}).",
        "",
        "## Coverage by PHP module",
        "",
        "Each cell counts the PHP-visible symbols elephc implements against the symbols the "
        "module exposes in the baseline build, whatever mechanism elephc implements them "
        "with. `—` marks a kind the module does not have.",
        "",
        "| PHP module | Functions | Classes | Constants |",
        "|---|---|---|---|",
    ]
    modules = sorted(set(totals["functions"]) | set(totals["classes"]) | set(totals["constants"]))
    for ext in modules:
        cells = [
            _cell(coverages[kind].count(ext), totals[kind][ext])
            for kind in ("functions", "classes", "constants")
        ]
        lines.append(f"| `{ext}` | {cells[0]} | {cells[1]} | {cells[2]} |")

    divergences = []
    for ext in modules:
        for kind in ("functions", "classes", "constants"):
            coverage = coverages[kind]
            in_aot, in_eval = coverage.aot(ext), coverage.eval(ext)
            if in_aot != in_eval:
                divergences.append(f"`{ext}` {kind}: {in_aot} / {in_eval}")
    if divergences:
        lines += [
            "",
            "Every count above holds for compiled programs. Code run through `eval()` sees "
            "fewer symbols in these modules (compiled / eval()):",
            "",
        ]
        lines += [f"- {item}" for item in divergences]
    empty = sorted(set(baseline["extensions"]) - set(modules))
    if empty:
        names = ", ".join(f"`{e}`" for e in empty)
        lines += [
            "",
            f"The remaining {len(empty)} baseline extensions expose no functions, classes, "
            f"or constants of their own, so they have no row above: {names}.",
        ]
    missing_bundled = baseline.get("missing_bundled", [])
    if missing_bundled:
        names = ", ".join(f"`{e}`" for e in missing_bundled)
        lines += [
            "",
            f"{len(missing_bundled)} extensions bundled with php-src were not "
            f"loaded by the PHP build that produced this snapshot and are not "
            f"counted: {names}.",
        ]
    if constructs:
        names = ", ".join(f"`{b['name']}()`" for b in sorted(constructs, key=lambda b: b["name"]))
        lines += [
            "",
            f"In addition, elephc implements {len(constructs)} PHP language "
            f"constructs that PHP does not count as functions: {names}.",
        ]
    if dynamic:
        names = ", ".join(f"`{c['name']}`" for c in sorted(dynamic, key=lambda c: c["name"]))
        lines += [
            "",
            f"elephc also defines {len(dynamic)} constant(s) at runtime that PHP registers "
            f"only in specific states and never lists statically: {names}.",
        ]
    newer_all = [(kind, s) for kind in ("functions", "classes", "constants") for s in newer[kind]]
    if newer_all:
        names = ", ".join(
            f"{_symbol_label(kind, s)} (PHP {s['since']})"
            for kind, s in sorted(newer_all, key=lambda item: item[1]["name"])
        )
        lines += [
            "",
            f"elephc also implements {len(newer_all)} symbol(s) that PHP added AFTER this "
            f"baseline release, so they cannot be counted against it: {names}.",
        ]
    if pecl:
        parts = []
        for module in sorted(pecl):
            kinds = pecl[module]
            counts = ", ".join(
                f"{len(kinds[kind])} {kind}" for kind in ("functions", "classes", "constants") if kinds[kind]
            )
            parts.append(f"`{module}` ({counts})")
        total = sum(len(v) for kinds in pecl.values() for v in kinds.values())
        lines += [
            "",
            f"elephc also provides {total} symbols from PECL extensions php-src does not "
            f"bundle, which the baseline cannot measure: {', '.join(parts)}.",
        ]

    lines += ["", "## Language constructs", ""]
    lines += _catalog_table(catalog.get("language", []))
    lines += ["", "## Extensions", ""]
    lines += _catalog_table(catalog.get("extensions", []))

    if any(beyond.values()):
        lines += [
            "",
            "## Beyond PHP",
            "",
            "elephc-specific builtins with no PHP equivalent (not counted in "
            "coverage above):",
            "",
        ]
        if beyond["functions"]:
            lines += ["| Builtin | Area | Description |", "|---|---|---|"]
            for b in sorted(beyond["functions"], key=lambda b: (b["area"], b["name"])):
                desc = b["description"]
                note = BEYOND_PHP_NOTES.get(b["name"])
                if note:
                    desc = f"{desc} *({note})*"
                lines.append(f"| `{b['name']}()` | {b['area']} | {desc} |")
        for kind, label in (("classes", "Classes"), ("constants", "Constants")):
            if beyond[kind]:
                names = ", ".join(
                    f"`{s['name']}` (`{s['module']}`)" if s["module"] != "elephc" else f"`{s['name']}`"
                    for s in sorted(beyond[kind], key=lambda s: s["name"])
                )
                lines += ["", f"{label}: {names}."]

    limitations = catalog.get("limitations", [])
    if limitations:
        lines += ["", "## Known limitations", ""]
        for entry in limitations:
            lines += [f"**{entry['title']}.** {entry['notes']}", ""]

    # Render self-check: the summary numbers must equal the table's sums.
    for kind in ("functions", "classes", "constants"):
        table_supported = sum(coverages[kind].count(ext) for ext in modules)
        assert table_supported == matched[kind], (kind, table_supported, matched[kind])
        assert set(totals[kind]) <= set(baseline["extensions"]), sorted(
            set(totals[kind]) - set(baseline["extensions"])
        )

    return "\n".join(lines).rstrip() + "\n"


def run(repo_root: Path = REPO_ROOT) -> int:
    scripts_docs = repo_root / "scripts" / "docs"
    errors: list[str] = []

    registry = _load_json(scripts_docs / "builtin_registry.json", (), errors)
    symbols = _load_json(scripts_docs / "symbol_registry.json", ("classes", "constants"), errors)
    baseline = _load_json(
        scripts_docs / "php_baseline.json",
        ("php_version", "generated_at", "extensions", "functions", "classes", "constants"),
        errors,
    )
    catalog_path = scripts_docs / "comparison_catalog.toml"
    catalog = None
    if catalog_path.exists():
        with catalog_path.open("rb") as fh:
            catalog = tomllib.load(fh)
    else:
        errors.append(f"{catalog_path}: missing file")
    if errors:
        return _fail(errors)

    errors.extend(validate_catalog(catalog, repo_root, baseline["extensions"]))
    functions, classes, constants, constructs, beyond, pecl, newer, dynamic, match_errors = classify(
        registry, symbols, baseline
    )
    errors.extend(match_errors)
    if errors:
        return _fail(errors)

    page = render(
        baseline, functions, classes, constants, constructs, beyond, pecl, newer, dynamic, catalog
    )
    output = repo_root / "docs" / "php" / "compatibility.md"
    output.write_text(page, encoding="utf-8")
    print(f"wrote {output.relative_to(repo_root)}")
    return 0


def _fail(errors: list[str]) -> int:
    for error in errors:
        print(f"error: {error}", file=sys.stderr)
    print(f"{len(errors)} error(s); docs/php/compatibility.md not written", file=sys.stderr)
    return 1


def main() -> int:
    return run()


if __name__ == "__main__":
    raise SystemExit(main())
