//! Purpose:
//! PHP's argument-count contract for builtin calls made from eval: the accepted range, the
//! `ArgumentCountError` message, and the two checks that raise it before any handler runs.
//!
//! Called from:
//! - `crate::interpreter::expressions::calls::eval_call()` for direct source calls.
//! - `crate::interpreter::builtins::registry::dispatch` and callable dispatch for evaluated
//!   arguments (`call_user_func`, `call_user_func_array`, `$f()`, spread calls, callbacks).
//!
//! Key details:
//! - The range is the eval signature's (required parameters, fixed parameters, variadic), except
//!   for the builtins in `PHP_ARITY_OVERRIDES`. Their eval signature lists fewer parameters than
//!   PHP 8.5 declares (`array_keys` stops at `$array`, `mktime` marks all six required), and a
//!   check driven by it would refuse calls PHP accepts. The table was generated by comparing
//!   every registry builtin against `ReflectionFunction` on PHP 8.5, then every refused count
//!   was replayed there to pin the exact message (1216 calls, all matching).
//! - Older profiles only differ by trailing optional parameters PHP added later (`fputcsv`'s
//!   `$eol` is 8.1), so they accept a few counts reference PHP would refuse; they never refuse
//!   one it accepts.
//! - A handler that does not implement every count PHP accepts keeps its own `RuntimeFatal`
//!   check: this module only answers the counts PHP itself refuses.
//! - A direct call evaluates its arguments before raising, as PHP sends them first.

use super::super::super::*;

/// How PHP words a refused argument count for one builtin.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(in crate::interpreter) enum EvalArityWording {
    /// `exactly` when the range is one count, else `at least` / `at most`.
    Ranged,
    /// `exactly <violated bound>` for either side (`strtr`, `pcntl_setqos_class`).
    Exact,
    /// Zero arguments, or exactly `min`; any other count reads `exactly <min>` (`rand`).
    ZeroOrExact,
}

/// The argument counts PHP accepts for one builtin, plus its refusal wording.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(in crate::interpreter) struct EvalBuiltinArity {
    /// Fewest arguments accepted.
    pub(in crate::interpreter) min: usize,
    /// Most arguments accepted; `None` for a variadic builtin.
    pub(in crate::interpreter) max: Option<usize>,
    /// Message shape for a refused count.
    pub(in crate::interpreter) wording: EvalArityWording,
}

impl EvalBuiltinArity {
    /// Builds the ordinary range PHP's parameter parser enforces.
    pub(in crate::interpreter) const fn ranged(min: usize, max: Option<usize>) -> Self {
        Self { min, max, wording: EvalArityWording::Ranged }
    }

    /// Builds a range whose refusal always reads `exactly <violated bound>`.
    const fn exact(min: usize, max: usize) -> Self {
        Self { min, max: Some(max), wording: EvalArityWording::Exact }
    }

    /// Builds the `rand()` shape: no arguments, or exactly `count` of them.
    const fn zero_or_exactly(count: usize) -> Self {
        Self { min: count, max: Some(count), wording: EvalArityWording::ZeroOrExact }
    }

    /// Returns the arity for one registry builtin from its eval signature and the PHP table.
    pub(in crate::interpreter) fn for_signature(
        name: &str,
        required: usize,
        fixed: usize,
        variadic: bool,
    ) -> Self {
        php_arity_override(name, PHP_ARITY_OVERRIDES).unwrap_or_else(|| {
            Self::ranged(required, (!variadic).then_some(fixed))
        })
    }

    /// Returns PHP's `ArgumentCountError` message when `supplied` is refused, else `None`.
    pub(in crate::interpreter) fn refusal(&self, name: &str, supplied: usize) -> Option<String> {
        let too_few = supplied < self.min;
        let too_many = self.max.is_some_and(|max| supplied > max);
        let (kind, bound) = match self.wording {
            EvalArityWording::ZeroOrExact if supplied == 0 || supplied == self.min => return None,
            EvalArityWording::ZeroOrExact => ("exactly", self.min),
            _ if !too_few && !too_many => return None,
            EvalArityWording::Exact if too_few => ("exactly", self.min),
            EvalArityWording::Exact => ("exactly", self.max.unwrap_or(self.min)),
            EvalArityWording::Ranged if self.max == Some(self.min) => ("exactly", self.min),
            EvalArityWording::Ranged if too_few => ("at least", self.min),
            EvalArityWording::Ranged => ("at most", self.max.unwrap_or(self.min)),
        };
        let plural = if bound == 1 { "" } else { "s" };
        Some(format!("{name}() expects {kind} {bound} argument{plural}, {supplied} given"))
    }
}

/// Builtins whose eval signature does not state PHP 8.5's arity (see the module docs).
pub(super) const PHP_ARITY_OVERRIDES: &[(&str, EvalBuiltinArity)] = &[
    ("array_keys", EvalBuiltinArity::ranged(1, Some(3))),
    ("array_rand", EvalBuiltinArity::ranged(1, Some(2))),
    ("array_unique", EvalBuiltinArity::ranged(1, Some(2))),
    ("array_walk", EvalBuiltinArity::ranged(2, Some(3))),
    ("arsort", EvalBuiltinArity::ranged(1, Some(2))),
    ("asort", EvalBuiltinArity::ranged(1, Some(2))),
    ("closedir", EvalBuiltinArity::ranged(0, Some(1))),
    ("copy", EvalBuiltinArity::ranged(2, Some(3))),
    ("define", EvalBuiltinArity::ranged(2, Some(3))),
    ("exec", EvalBuiltinArity::ranged(1, Some(3))),
    ("fgetcsv", EvalBuiltinArity::ranged(1, Some(5))),
    ("fgets", EvalBuiltinArity::ranged(1, Some(2))),
    ("file", EvalBuiltinArity::ranged(1, Some(3))),
    ("file_put_contents", EvalBuiltinArity::ranged(2, Some(4))),
    ("fputcsv", EvalBuiltinArity::ranged(2, Some(6))),
    ("fsockopen", EvalBuiltinArity::ranged(1, Some(5))),
    ("fwrite", EvalBuiltinArity::ranged(2, Some(3))),
    ("glob", EvalBuiltinArity::ranged(1, Some(2))),
    ("gmmktime", EvalBuiltinArity::ranged(1, Some(6))),
    ("gzcompress", EvalBuiltinArity::ranged(1, Some(3))),
    ("gzdeflate", EvalBuiltinArity::ranged(1, Some(3))),
    ("hash", EvalBuiltinArity::ranged(2, Some(4))),
    ("hash_file", EvalBuiltinArity::ranged(2, Some(4))),
    ("hash_init", EvalBuiltinArity::ranged(1, Some(4))),
    ("html_entity_decode", EvalBuiltinArity::ranged(1, Some(3))),
    ("htmlentities", EvalBuiltinArity::ranged(1, Some(4))),
    ("htmlspecialchars", EvalBuiltinArity::ranged(1, Some(4))),
    ("mkdir", EvalBuiltinArity::ranged(1, Some(4))),
    ("mktime", EvalBuiltinArity::ranged(1, Some(6))),
    ("mt_rand", EvalBuiltinArity::zero_or_exactly(2)),
    ("opendir", EvalBuiltinArity::ranged(1, Some(2))),
    ("passthru", EvalBuiltinArity::ranged(1, Some(2))),
    ("pcntl_setqos_class", EvalBuiltinArity::exact(0, 1)),
    ("pfsockopen", EvalBuiltinArity::ranged(1, Some(5))),
    ("preg_match", EvalBuiltinArity::ranged(2, Some(5))),
    ("preg_match_all", EvalBuiltinArity::ranged(2, Some(5))),
    ("preg_replace", EvalBuiltinArity::ranged(3, Some(5))),
    ("preg_replace_callback", EvalBuiltinArity::ranged(3, Some(6))),
    ("rand", EvalBuiltinArity::zero_or_exactly(2)),
    ("readdir", EvalBuiltinArity::ranged(0, Some(1))),
    ("readfile", EvalBuiltinArity::ranged(1, Some(3))),
    ("rename", EvalBuiltinArity::ranged(2, Some(3))),
    ("rewinddir", EvalBuiltinArity::ranged(0, Some(1))),
    ("rmdir", EvalBuiltinArity::ranged(1, Some(2))),
    ("rsort", EvalBuiltinArity::ranged(1, Some(2))),
    ("scandir", EvalBuiltinArity::ranged(1, Some(3))),
    ("sort", EvalBuiltinArity::ranged(1, Some(2))),
    ("stream_socket_client", EvalBuiltinArity::ranged(1, Some(6))),
    ("stream_socket_server", EvalBuiltinArity::ranged(1, Some(5))),
    ("strtr", EvalBuiltinArity::exact(2, 3)),
    ("system", EvalBuiltinArity::ranged(1, Some(2))),
    ("unlink", EvalBuiltinArity::ranged(1, Some(2))),
];

/// The OPcache functions: prelude-provided natively and plain runtime handlers in eval, so no
/// registry signature carries them.
const OPCACHE_ARITY: &[(&str, EvalBuiltinArity)] = &[
    ("opcache_compile_file", EvalBuiltinArity::ranged(1, Some(1))),
    ("opcache_get_configuration", EvalBuiltinArity::ranged(0, Some(0))),
    ("opcache_get_status", EvalBuiltinArity::ranged(0, Some(1))),
    ("opcache_invalidate", EvalBuiltinArity::ranged(1, Some(2))),
    ("opcache_is_script_cached", EvalBuiltinArity::ranged(1, Some(1))),
    ("opcache_is_script_cached_in_file_cache", EvalBuiltinArity::ranged(1, Some(1))),
    ("opcache_jit_blacklist", EvalBuiltinArity::ranged(1, Some(1))),
    ("opcache_reset", EvalBuiltinArity::ranged(0, Some(0))),
];

/// Finds `name` in one arity table.
fn php_arity_override(
    name: &str,
    table: &'static [(&'static str, EvalBuiltinArity)],
) -> Option<EvalBuiltinArity> {
    table.iter().find(|(entry, _)| *entry == name).map(|(_, arity)| *arity)
}

/// Returns the canonical PHP name and arity of a builtin reachable by `name`, if any.
///
/// Language constructs (`isset`, `exit`, ...) are not functions to PHP and answer `None`, as
/// does any name the active runtime hides (strict-PHP extensions, a missing regex provider).
pub(in crate::interpreter) fn eval_builtin_call_arity(
    name: &str,
) -> Option<(&'static str, EvalBuiltinArity)> {
    if let Some(spec) = eval_declared_builtin_spec(name) {
        return (!spec.is_language_construct()).then_some((spec.name, spec.php_arity()));
    }
    let key = name.trim_start_matches('\\').to_ascii_lowercase();
    OPCACHE_ARITY
        .iter()
        .find(|(entry, _)| *entry == key)
        .map(|(entry, arity)| (*entry, *arity))
}

/// Throws PHP's `ArgumentCountError` when `supplied` evaluated arguments are refused.
pub(in crate::interpreter) fn eval_check_builtin_arity(
    name: &str,
    supplied: usize,
    context: &mut ElephcEvalContext,
    values: &mut impl RuntimeValueOps,
) -> Result<(), EvalStatus> {
    if eval_opcache_is_user_function(name, context) {
        return Ok(());
    }
    let Some((canonical, arity)) = eval_builtin_call_arity(name) else {
        return Ok(());
    };
    match arity.refusal(canonical, supplied) {
        Some(message) => eval_throw_argument_count_error(&message, context, values),
        None => Ok(()),
    }
}

/// Checks a direct positional builtin call before any specialised handler sees its arguments.
///
/// A refused call still evaluates every argument in source order, then releases it, before the
/// error is thrown. A plain variable in a by-reference slot is skipped: PHP binds it without
/// reading it, so reading it here would emit an `Undefined variable` warning PHP does not.
/// Calls with named or spread arguments are left to `eval_check_builtin_arity` once bound.
pub(in crate::interpreter) fn eval_check_builtin_source_arity(
    name: &str,
    args: &[EvalCallArg],
    context: &mut ElephcEvalContext,
    scope: &mut ElephcEvalScope,
    values: &mut impl RuntimeValueOps,
) -> Result<(), EvalStatus> {
    if eval_opcache_is_user_function(name, context) || !eval_call_args_are_plain_positional(args) {
        return Ok(());
    }
    let Some((canonical, arity)) = eval_builtin_call_arity(name) else {
        return Ok(());
    };
    let Some(message) = arity.refusal(canonical, args.len()) else {
        return Ok(());
    };
    let spec = eval_declared_builtin_spec(name);
    let evaluated = args
        .iter()
        .enumerate()
        .filter(|(position, arg)| {
            let by_ref = spec.is_some_and(|spec| spec.param_is_by_ref(*position));
            !(by_ref && matches!(arg.value(), EvalExpr::LoadVar(_)))
        })
        .map(|(_, arg)| arg.value())
        .collect::<Vec<_>>();
    with_eval_void_operands(&evaluated, context, scope, values, |_, context, _, values| {
        eval_throw_argument_count_error(&message, context, values)
    })
}
