//! Purpose:
//! Worker-mode handler storage. Holds the opaque process-static slots for the
//! compiled worker trampoline (`WORKER_HANDLER`), the top-level boot function
//! (`WORKER_BOOT`), and the boot-completed flag used by the master supervision
//! loop to distinguish startup vs runtime crashes.
//!
//! Called from:
//! - `crate::worker_mode::enter_worker_loop()` via `elephc_web_worker_register`.
//! - The compiled `--web-worker` binary's top-level PHP boot, which calls
//!   `elephc_web_worker_register` after registering its request handler.
//!
//! Key details:
//! - All slots are process-local and written once per worker before serving
//!   begins (from `spawn_worker` / the PHP boot, on the main thread). Plain
//!   `static mut` with `addr_of_mut!` is race-free (no `&mut` on a `static mut`,
//!   per the `static_mut_refs` hard-error lint): without `--handler-offload` one
//!   worker = one thread; with `--handler-offload` these slots are written before
//!   the `php-handler` thread is spawned (whose `std::thread::spawn` happens-before
//!   publishes them), and the handler thread is the only reader thereafter.
//! - `elephc_web_worker_register` is `-> !`: it transfers control to the Rust
//!   worker loop and never returns to PHP.

use std::ffi::c_int;

/// Type of the worker-handler trampoline generated by the compiler. Receives no
/// arguments (request state is already populated via `request_state::set_request`
/// and captured via `elephc_web_capture`). Returns 0 on success, non-zero on
/// error. The trampoline will be emitted in Phase 2/3.
pub type WorkerHandler = unsafe extern "C" fn() -> c_int;

/// Type of the script-mode handler: the compiled top-level PHP body
/// (`_elephc_web_handler`), a void-returning C function. Distinct from
/// `WorkerHandler` (which returns `c_int` for the worker trampoline) so the
/// bridge never type-puns a `fn()` through a `fn() -> c_int` pointer.
pub type ScriptHandler = unsafe extern "C" fn();

/// Stores the script-mode handler for the current worker process. Written once
/// per forked child by `register_script_handler`; read by the per-request loop.
static mut SCRIPT_HANDLER: Option<ScriptHandler> = None;

/// Returns the script-mode handler stored for this worker, if any.
pub(crate) fn script_handler() -> Option<ScriptHandler> {
    // SAFETY: single-threaded per worker; read through a raw pointer.
    unsafe { *core::ptr::addr_of!(SCRIPT_HANDLER) }
}

/// Type of the top-level PHP boot function for worker mode. Runs once per worker
/// process to initialize the application, caches, and register the handler via
/// `elephc_web_worker_register`.
pub type WorkerBoot = extern "C" fn();

/// Handler registered by the PHP boot, invoked once per request. Process-static
/// (single-threaded per worker). Set through `addr_of_mut!`, never borrowed.
static mut WORKER_HANDLER: Option<WorkerHandler> = None;

/// Boot function, process-static. Called once at worker startup before the
/// accept loop begins. Set by `worker_mode::set_worker_config`/boot dispatch.
static mut WORKER_BOOT: Option<WorkerBoot> = None;

/// Flag indicating whether the boot function has completed (i.e.
/// `elephc_web_worker_register` was reached). Lets the master distinguish a
/// startup failure (crash before register → backoff) from a runtime crash
/// (crash after register → immediate respawn). Refinement comes in Phase 4.
static mut WORKER_BOOTED: bool = false;

/// Process-static write end of the boot-signal pipe. Set by the master via
/// `set_boot_pipe` in the forked child before the boot runs. When
/// `elephc_web_worker_register` is reached, `signal_boot` writes one byte and
/// closes the fd so the master can distinguish a startup crash (pipe empty) from
/// a runtime crash (pipe had data). Accessed only through `addr_of_mut!`.
static mut BOOT_PIPE_WR: Option<i32> = None;

/// Stores the boot-pipe write-end fd in the process-static slot. Called by the
/// master in the forked child after fork and before the boot runs. Writes through
/// `addr_of_mut!`; never borrows the `static mut`.
pub(crate) fn set_boot_pipe(fd: i32) {
    // SAFETY: single-threaded per worker; written through a raw pointer.
    unsafe {
        core::ptr::write(core::ptr::addr_of_mut!(BOOT_PIPE_WR), Some(fd));
    }
}

/// Returns the registered worker handler, or `None` if `register` has not run.
/// Read through a raw pointer; never forms a reference to the `static mut`.
pub(crate) fn worker_handler() -> Option<WorkerHandler> {
    // SAFETY: single-threaded per worker; read through a raw pointer.
    unsafe { *core::ptr::addr_of!(WORKER_HANDLER) }
}

/// Returns the registered worker boot function, or `None` if not yet set. Read
/// through a raw pointer; never forms a reference to the `static mut`. Reserved
/// for the Phase 4 startup-vs-runtime crash-loop distinction.
#[allow(dead_code)]
pub(crate) fn worker_boot() -> Option<WorkerBoot> {
    // SAFETY: single-threaded per worker; read through a raw pointer.
    unsafe { *core::ptr::addr_of!(WORKER_BOOT) }
}

/// Stores the worker boot function so the worker loop can invoke it once before
/// entering the accept loop. Called by `server::spawn_worker` in the child
/// process after fork and before the boot runs.
pub(crate) fn set_worker_boot(boot: WorkerBoot) {
    // SAFETY: single-threaded per worker; written through a raw pointer.
    unsafe {
        core::ptr::write(core::ptr::addr_of_mut!(WORKER_BOOT), Some(boot));
    }
}

/// Returns whether the worker has completed boot (i.e. `register` was reached).
/// Read through a raw pointer; never forms a reference to the `static mut`.
/// Reserved for the Phase 4 startup-vs-runtime crash-loop distinction; the
/// master will consult this to decide backoff vs immediate respawn.
#[allow(dead_code)]
pub(crate) fn worker_booted() -> bool {
    // SAFETY: single-threaded per worker; read through a raw pointer.
    unsafe { *core::ptr::addr_of!(WORKER_BOOTED) }
}

/// Writes one byte to the boot-pipe write end (if set) and closes it, signaling
/// the master that the worker has reached `elephc_web_worker_register` and is
/// about to enter the accept loop. This lets the master distinguish a startup
/// crash (pipe stays empty → counts toward `MAX_FAST_DEATHS`) from a runtime
/// crash (pipe had data → immediate respawn, counter reset). Called from
/// `elephc_web_worker_register` just before transferring to the worker loop.
/// No-op in test builds where no pipe is installed.
fn signal_boot() {
    // SAFETY: single-threaded per worker; take the fd through a raw pointer,
    // never forming a reference to the `static mut`.
    let fd = unsafe { (*core::ptr::addr_of_mut!(BOOT_PIPE_WR)).take() };
    if let Some(fd) = fd {
        // SAFETY: write(2) a single byte to the pipe; the fd is valid and owned
        // by this process. Closing after the write so the master's read end
        // sees EOF once the byte is drained.
        let buf: [u8; 1] = [1];
        unsafe {
            libc::write(fd, buf.as_ptr() as *const libc::c_void, 1);
            libc::close(fd);
        }
    }
}

/// Registers the worker handler and transfers control to the Rust worker loop.
/// Called by the compiled PHP builtin `elephc_worker_register`. After this call
/// returns (it doesn't — it is `-> !`), PHP never resumes; Rust drives the HTTP
/// accept → invoke → respond loop.
///
/// # Safety
/// `handler` must be the compiler-emitted `elephc_worker_handle_request`
/// trampoline. This function never returns.
#[no_mangle]
pub extern "C" fn elephc_web_worker_register(handler: WorkerHandler) -> ! {
    // SAFETY: single-threaded per worker; written through raw pointers, never
    // forming a reference to a `static mut`.
    unsafe {
        core::ptr::write(core::ptr::addr_of_mut!(WORKER_HANDLER), Some(handler));
        core::ptr::write(core::ptr::addr_of_mut!(WORKER_BOOTED), true);
    }
    // Signal the master that boot completed (pipe-based boot signal), then
    // transfer to the Rust-driven worker loop; never returns. The mode label
    // `"web-worker"` is passed by the call site (T1#3 metrics `mode` field).
    signal_boot();
    crate::worker_mode::enter_worker_loop("web-worker");
}

/// Registers the script-mode handler in the forked child, signals boot
/// completion to the master, and transfers to the per-request worker loop.
/// Mirrors `elephc_web_worker_register` but is called directly from the child's
/// `spawn_worker` arm (no PHP boot phase, no `elephc_worker_register` FFI call):
/// the handler IS the top-level body, passed straight through from
/// `elephc_web_run_script`. Never returns.
pub(crate) fn register_script_handler(handler: ScriptHandler) -> ! {
    // SAFETY: single-threaded per worker; written through raw pointers.
    unsafe {
        core::ptr::write(core::ptr::addr_of_mut!(SCRIPT_HANDLER), Some(handler));
        core::ptr::write(core::ptr::addr_of_mut!(WORKER_BOOTED), true);
    }
    signal_boot();
    // The mode label `"web-worker-script"` is passed by the call site (T1#3
    // metrics `mode` field); distinguishes script mode from the registered-
    // handler `--web-worker` mode.
    crate::worker_mode::enter_worker_loop("web-worker-script");
}

#[cfg(test)]
mod tests {
    use super::*;

    // Purpose:
    // Unit tests for the worker handler/boot storage slots.
    //
    // Called from:
    // - `cargo test` through Rust's test harness.
    //
    // Key details:
    // - These tests mutate process-static state; they must not run in parallel
    //   with each other. Each test uses a distinct slot write/read cycle and
    //   relies on single-threaded test execution within the module.

    /// A dummy handler trampoline used by the storage tests. Returns 0.
    unsafe extern "C" fn dummy_handler() -> c_int {
        0
    }

    /// A dummy boot function used by the storage tests. Does nothing.
    extern "C" fn dummy_boot() {}

    /// Verifies `set_worker_boot`/`worker_boot` round-trip the boot function.
    #[test]
    fn boot_storage_roundtrip() {
        set_worker_boot(dummy_boot);
        assert!(worker_boot().is_some());
        // Re-setting overwrites cleanly through addr_of_mut!.
        set_worker_boot(dummy_boot);
        assert!(worker_boot().is_some());
    }

    /// Verifies `worker_booted` starts false and is observable after a write.
    #[test]
    fn booted_flag_observable() {
        // The flag is process-static and may have been set by a prior test that
        // called elephc_web_worker_register indirectly; we only assert the read
        // path is sound (no borrow of a `static mut`).
        let _ = worker_booted();
    }

    /// Verifies `worker_handler` reads return the stored value after a write via
    /// the same raw-pointer pattern the register entry uses.
    #[test]
    fn handler_storage_via_raw_pointer() {
        // SAFETY: single-threaded test; mirrors register's write path.
        unsafe {
            core::ptr::write(core::ptr::addr_of_mut!(WORKER_HANDLER), Some(dummy_handler));
        }
        assert!(worker_handler().is_some());
    }
}