mod arrays;
mod buffers;
mod data;
mod exceptions;
mod io;
mod pointers;
mod strings;
mod system;

use super::emit::Emitter;
use super::platform::{Arch, Platform};
pub(crate) use data::emit_runtime_data_fixed;
pub(crate) use data::emit_runtime_data_user;

pub(crate) fn emit_runtime(emitter: &mut Emitter) {
    if emitter.target.arch == Arch::X86_64 {
        emit_runtime_linux_x86_64_minimal(emitter);
        return;
    }

    emit_optional_linux_crypto_decls(emitter);

    // String runtime functions
    strings::emit_itoa(emitter);
    strings::emit_ftoa(emitter);
    strings::emit_concat(emitter);
    strings::emit_atoi(emitter);
    strings::emit_str_eq(emitter);
    strings::emit_number_format(emitter);
    strings::emit_strcopy(emitter);
    strings::emit_str_persist(emitter);
    strings::emit_strtolower(emitter);
    strings::emit_strtoupper(emitter);
    strings::emit_trim(emitter);
    strings::emit_ltrim(emitter);
    strings::emit_rtrim(emitter);
    strings::emit_strpos(emitter);
    strings::emit_strrpos(emitter);
    strings::emit_str_repeat(emitter);
    strings::emit_strrev(emitter);
    strings::emit_chr(emitter);
    strings::emit_strcmp(emitter);
    strings::emit_strcasecmp(emitter);
    strings::emit_str_starts_with(emitter);
    strings::emit_str_ends_with(emitter);
    strings::emit_str_replace(emitter);
    strings::emit_explode(emitter);
    strings::emit_implode(emitter);
    strings::emit_implode_int(emitter);
    strings::emit_ucwords(emitter);
    strings::emit_str_ireplace(emitter);
    strings::emit_substr_replace(emitter);
    strings::emit_str_pad(emitter);
    strings::emit_str_split(emitter);
    strings::emit_addslashes(emitter);
    strings::emit_stripslashes(emitter);
    strings::emit_nl2br(emitter);
    strings::emit_wordwrap(emitter);
    strings::emit_bin2hex(emitter);
    strings::emit_hex2bin(emitter);
    strings::emit_htmlspecialchars(emitter);
    strings::emit_html_entity_decode(emitter);
    strings::emit_urlencode(emitter);
    strings::emit_urldecode(emitter);
    strings::emit_rawurlencode(emitter);
    strings::emit_md5(emitter);
    strings::emit_sha1(emitter);
    strings::emit_hash(emitter);
    strings::emit_base64_encode(emitter);
    strings::emit_base64_decode(emitter);
    strings::emit_sprintf(emitter);
    strings::emit_md5(emitter);
    strings::emit_sha1(emitter);
    strings::emit_hash(emitter);
    strings::emit_sscanf(emitter);
    strings::emit_rtrim_mask(emitter);
    strings::emit_ltrim_mask(emitter);
    strings::emit_trim_mask(emitter);

    // System runtime functions
    system::emit_build_argv(emitter);
    system::emit_time(emitter);
    system::emit_microtime(emitter);
    system::emit_getenv(emitter);
    system::emit_shell_exec(emitter);
    system::emit_date(emitter);
    system::emit_mktime(emitter);
    system::emit_strtotime(emitter);
    system::emit_json_encode_bool(emitter);
    system::emit_json_encode_null(emitter);
    system::emit_json_encode_str(emitter);
    system::emit_json_encode_mixed(emitter);
    system::emit_json_encode_array_dynamic(emitter);
    system::emit_json_encode_array_int(emitter);
    system::emit_json_encode_array_str(emitter);
    system::emit_json_encode_assoc(emitter);
    system::emit_json_decode(emitter);
    system::emit_preg_strip(emitter);
    system::emit_pcre_to_posix(emitter);
    system::emit_preg_match(emitter);
    system::emit_preg_match_all(emitter);
    system::emit_preg_replace(emitter);
    system::emit_preg_split(emitter);
    system::emit_match_unhandled(emitter);
    system::emit_enum_from_fail(emitter);

    // Exception runtime functions
    exceptions::emit_exception_cleanup_frames(emitter);
    exceptions::emit_exception_matches(emitter);
    exceptions::emit_throw_current(emitter);
    exceptions::emit_rethrow_current(emitter);

    // Array runtime functions
    arrays::emit_heap_alloc(emitter);
    arrays::emit_heap_debug_fail(emitter);
    arrays::emit_heap_debug_check_live(emitter);
    arrays::emit_heap_debug_validate_free_list(emitter);
    arrays::emit_heap_debug_report(emitter);
    arrays::emit_heap_kind(emitter);
    arrays::emit_heap_free(emitter);
    arrays::emit_array_free_deep(emitter);
    arrays::emit_array_clone_shallow(emitter);
    arrays::emit_array_ensure_unique(emitter);
    arrays::emit_array_grow(emitter);
    arrays::emit_array_new(emitter);
    arrays::emit_array_push_int(emitter);
    arrays::emit_array_push_refcounted(emitter);
    arrays::emit_array_push_str(emitter);
    arrays::emit_random_u32(emitter);
    arrays::emit_random_uniform(emitter);
    arrays::emit_sort_int(emitter, false);
    arrays::emit_sort_int(emitter, true);
    arrays::emit_hash_fnv1a(emitter);
    arrays::emit_hash_clone_shallow(emitter);
    arrays::emit_hash_ensure_unique(emitter);
    arrays::emit_hash_new(emitter);
    arrays::emit_hash_grow(emitter);
    arrays::emit_hash_may_have_cyclic_values(emitter);
    arrays::emit_hash_set(emitter);
    arrays::emit_hash_insert_owned(emitter);
    arrays::emit_hash_get(emitter);
    arrays::emit_hash_iter(emitter);
    arrays::emit_hash_count(emitter);
    arrays::emit_hash_free_deep(emitter);
    arrays::emit_array_key_exists(emitter);
    arrays::emit_array_search(emitter);
    arrays::emit_array_reverse(emitter);
    arrays::emit_array_reverse_refcounted(emitter);
    arrays::emit_array_sum(emitter);
    arrays::emit_array_product(emitter);
    arrays::emit_array_shift(emitter);
    arrays::emit_array_unshift(emitter);
    arrays::emit_array_merge(emitter);
    arrays::emit_array_merge_refcounted(emitter);
    arrays::emit_array_slice(emitter);
    arrays::emit_array_slice_refcounted(emitter);
    arrays::emit_range(emitter);
    arrays::emit_shuffle(emitter);
    arrays::emit_array_unique(emitter);
    arrays::emit_array_unique_refcounted(emitter);
    arrays::emit_array_rand(emitter);
    arrays::emit_array_fill(emitter);
    arrays::emit_array_fill_refcounted(emitter);
    arrays::emit_array_pad(emitter);
    arrays::emit_array_pad_refcounted(emitter);
    arrays::emit_array_diff(emitter);
    arrays::emit_array_diff_refcounted(emitter);
    arrays::emit_array_intersect(emitter);
    arrays::emit_array_intersect_refcounted(emitter);
    arrays::emit_array_flip(emitter);
    arrays::emit_array_combine(emitter);
    arrays::emit_array_combine_refcounted(emitter);
    arrays::emit_array_fill_keys(emitter);
    arrays::emit_array_fill_keys_refcounted(emitter);
    arrays::emit_array_chunk(emitter);
    arrays::emit_array_chunk_refcounted(emitter);
    arrays::emit_array_column(emitter);
    arrays::emit_array_column_ref(emitter);
    arrays::emit_array_column_str(emitter);
    arrays::emit_array_splice(emitter);
    arrays::emit_array_splice_refcounted(emitter);
    arrays::emit_array_diff_key(emitter);
    arrays::emit_array_intersect_key(emitter);
    arrays::emit_asort(emitter);
    arrays::emit_ksort(emitter);
    arrays::emit_natsort(emitter);
    arrays::emit_array_map(emitter);
    arrays::emit_array_map_str(emitter);
    arrays::emit_array_filter(emitter);
    arrays::emit_array_filter_refcounted(emitter);
    arrays::emit_array_reduce(emitter);
    arrays::emit_array_walk(emitter);
    arrays::emit_usort(emitter);
    arrays::emit_array_merge_into(emitter);
    arrays::emit_array_merge_into_refcounted(emitter);
    arrays::emit_decref_any(emitter);
    arrays::emit_decref_mixed(emitter);
    arrays::emit_gc_note_child_ref(emitter);
    arrays::emit_gc_mark_reachable(emitter);
    arrays::emit_gc_collect_cycles(emitter);
    arrays::emit_mixed_from_value(emitter);
    arrays::emit_mixed_cast_bool(emitter);
    arrays::emit_mixed_cast_int(emitter);
    arrays::emit_mixed_cast_string(emitter);
    arrays::emit_mixed_free_deep(emitter);
    arrays::emit_mixed_is_empty(emitter);
    arrays::emit_mixed_strict_eq(emitter);
    arrays::emit_mixed_unbox(emitter);
    arrays::emit_mixed_write_stdout(emitter);
    arrays::emit_object_free_deep(emitter);
    arrays::emit_refcount(emitter);

    // Buffer runtime functions
    buffers::emit_buffer_new(emitter);
    buffers::emit_buffer_len(emitter);
    buffers::emit_buffer_bounds_fail(emitter);
    buffers::emit_buffer_use_after_free(emitter);

    // I/O runtime functions
    io::emit_cstr(emitter);
    io::emit_fopen(emitter);
    io::emit_fgets(emitter);
    io::emit_feof(emitter);
    io::emit_fread(emitter);
    io::emit_file_get_contents(emitter);
    io::emit_file_put_contents(emitter);
    io::emit_file(emitter);
    io::emit_stat(emitter);
    io::emit_fs(emitter);
    io::emit_getcwd(emitter);
    io::emit_scandir(emitter);
    io::emit_glob(emitter);
    io::emit_tempnam(emitter);
    io::emit_fgetcsv(emitter);
    io::emit_fputcsv(emitter);

    // Pointer runtime functions
    pointers::emit_ptoa(emitter);
    pointers::emit_ptr_check_nonnull(emitter);
    pointers::emit_str_to_cstr(emitter);
    pointers::emit_cstr_to_str(emitter);
}

fn emit_runtime_linux_x86_64_minimal(emitter: &mut Emitter) {
    emit_optional_linux_crypto_decls(emitter);
    arrays::emit_heap_alloc(emitter);
    arrays::emit_heap_free(emitter);
    arrays::emit_array_clone_shallow(emitter);
    arrays::emit_array_ensure_unique(emitter);
    arrays::emit_array_grow(emitter);
    arrays::emit_array_free_deep(emitter);
    arrays::emit_random_u32(emitter);
    arrays::emit_random_uniform(emitter);
    arrays::emit_sort_int(emitter, false);
    arrays::emit_sort_int(emitter, true);
    arrays::emit_shuffle(emitter);
    arrays::emit_asort(emitter);
    strings::emit_itoa(emitter);
    strings::emit_ftoa(emitter);
    strings::emit_concat(emitter);
    strings::emit_atoi(emitter);
    strings::emit_str_persist(emitter);
    strings::emit_str_eq(emitter);
    strings::emit_trim(emitter);
    strings::emit_ltrim(emitter);
    strings::emit_rtrim(emitter);
    strings::emit_strcopy(emitter);
    strings::emit_addslashes(emitter);
    strings::emit_stripslashes(emitter);
    strings::emit_bin2hex(emitter);
    strings::emit_hex2bin(emitter);
    strings::emit_implode(emitter);
    strings::emit_implode_int(emitter);
    strings::emit_explode(emitter);
    strings::emit_ucwords(emitter);
    strings::emit_strtoupper(emitter);
    strings::emit_str_repeat(emitter);
    strings::emit_chr(emitter);
    strings::emit_nl2br(emitter);
    strings::emit_htmlspecialchars(emitter);
    strings::emit_html_entity_decode(emitter);
    strings::emit_urlencode(emitter);
    strings::emit_urldecode(emitter);
    strings::emit_rawurlencode(emitter);
    strings::emit_md5(emitter);
    strings::emit_sha1(emitter);
    strings::emit_hash(emitter);
    strings::emit_base64_encode(emitter);
    strings::emit_base64_decode(emitter);
    strings::emit_rtrim_mask(emitter);
    strings::emit_ltrim_mask(emitter);
    strings::emit_trim_mask(emitter);
    system::emit_date(emitter);
    system::emit_mktime(emitter);
    system::emit_strtotime(emitter);
    arrays::emit_array_new(emitter);
    arrays::emit_array_fill(emitter);
    arrays::emit_array_fill_refcounted(emitter);
    arrays::emit_array_push_int(emitter);
    arrays::emit_array_push_refcounted(emitter);
    arrays::emit_array_push_str(emitter);
    arrays::emit_array_merge_into(emitter);
    arrays::emit_array_merge_into_refcounted(emitter);
    arrays::emit_range(emitter);
    arrays::emit_array_diff(emitter);
    arrays::emit_array_diff_refcounted(emitter);
    arrays::emit_array_intersect(emitter);
    arrays::emit_array_intersect_refcounted(emitter);
    arrays::emit_array_merge(emitter);
    arrays::emit_array_merge_refcounted(emitter);
    arrays::emit_array_pad(emitter);
    arrays::emit_array_pad_refcounted(emitter);
    arrays::emit_array_product(emitter);
    arrays::emit_array_rand(emitter);
    arrays::emit_array_reverse(emitter);
    arrays::emit_array_reverse_refcounted(emitter);
    arrays::emit_array_shift(emitter);
    arrays::emit_array_slice(emitter);
    arrays::emit_array_slice_refcounted(emitter);
    arrays::emit_array_splice(emitter);
    arrays::emit_array_splice_refcounted(emitter);
    arrays::emit_array_sum(emitter);
    arrays::emit_array_chunk(emitter);
    arrays::emit_array_chunk_refcounted(emitter);
    arrays::emit_array_combine(emitter);
    arrays::emit_array_combine_refcounted(emitter);
    arrays::emit_array_flip(emitter);
    arrays::emit_array_unshift(emitter);
    arrays::emit_array_unique(emitter);
    arrays::emit_array_unique_refcounted(emitter);
    arrays::emit_array_map(emitter);
    arrays::emit_array_map_str(emitter);
    arrays::emit_array_filter(emitter);
    arrays::emit_array_filter_refcounted(emitter);
    arrays::emit_array_reduce(emitter);
    arrays::emit_array_walk(emitter);
    arrays::emit_hash_fnv1a(emitter);
    arrays::emit_hash_new(emitter);
    arrays::emit_hash_insert_owned(emitter);
    arrays::emit_hash_clone_shallow(emitter);
    arrays::emit_hash_ensure_unique(emitter);
    arrays::emit_hash_set(emitter);
    arrays::emit_hash_get(emitter);
    arrays::emit_hash_iter(emitter);
    arrays::emit_array_fill_keys(emitter);
    arrays::emit_array_fill_keys_refcounted(emitter);
    arrays::emit_decref_array(emitter);
    arrays::emit_array_key_exists(emitter);
    arrays::emit_array_search(emitter);
    arrays::emit_array_column(emitter);
    arrays::emit_array_column_ref(emitter);
    arrays::emit_array_column_str(emitter);
    arrays::emit_mixed_is_empty(emitter);
    arrays::emit_array_diff_key(emitter);
    arrays::emit_array_intersect_key(emitter);
    arrays::emit_decref_hash(emitter);
    arrays::emit_hash_free_deep(emitter);
    arrays::emit_decref_any(emitter);
    arrays::emit_object_free_deep(emitter);
    system::emit_build_argv(emitter);
    system::emit_getenv(emitter);
    system::emit_shell_exec(emitter);
    arrays::emit_incref(emitter);
    arrays::emit_decref_mixed(emitter);
    arrays::emit_decref_object(emitter);
    arrays::emit_gc_mark_reachable(emitter);
    arrays::emit_gc_collect_cycles(emitter);
    arrays::emit_mixed_from_value(emitter);
    arrays::emit_mixed_cast_bool(emitter);
    arrays::emit_mixed_cast_int(emitter);
    arrays::emit_mixed_free_deep(emitter);
    arrays::emit_mixed_unbox(emitter);
    arrays::emit_mixed_cast_string(emitter);
    arrays::emit_mixed_write_stdout(emitter);
    arrays::emit_mixed_strict_eq(emitter);
    buffers::emit_buffer_new(emitter);
    buffers::emit_buffer_len(emitter);
    buffers::emit_buffer_bounds_fail(emitter);
    buffers::emit_buffer_use_after_free(emitter);
    io::emit_cstr(emitter);
    io::emit_fopen(emitter);
    io::emit_fgets(emitter);
    io::emit_feof(emitter);
    io::emit_fread(emitter);
    io::emit_fgetcsv(emitter);
    io::emit_fputcsv(emitter);
    io::emit_scandir(emitter);
    io::emit_glob(emitter);
    io::emit_tempnam(emitter);
    io::emit_file_get_contents(emitter);
    io::emit_file_put_contents(emitter);
    io::emit_file(emitter);
    io::emit_stat(emitter);
    io::emit_fs(emitter);
    io::emit_getcwd(emitter);
    pointers::emit_ptr_check_nonnull(emitter);
    pointers::emit_str_to_cstr(emitter);
    pointers::emit_cstr_to_str(emitter);
    exceptions::emit_exception_cleanup_frames(emitter);
    exceptions::emit_exception_matches(emitter);
    exceptions::emit_throw_current(emitter);
    exceptions::emit_rethrow_current(emitter);
    system::emit_json_encode_bool(emitter);
    system::emit_json_encode_null(emitter);
    system::emit_json_encode_str(emitter);
    system::emit_json_encode_mixed(emitter);
    system::emit_json_decode(emitter);
    system::emit_json_encode_array_int(emitter);
    system::emit_json_encode_array_str(emitter);
    system::emit_json_encode_array_dynamic(emitter);
    system::emit_json_encode_assoc(emitter);
    system::emit_match_unhandled(emitter);
    system::emit_enum_from_fail(emitter);
}

fn emit_optional_linux_crypto_decls(emitter: &mut Emitter) {
    if emitter.target.platform == Platform::Linux {
        emitter.raw(".weak MD5");
        emitter.raw(".weak SHA1");
        emitter.raw(".weak SHA256");
        emitter.blank();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::platform::{Arch, Platform, Target};

    #[test]
    fn test_linux_runtime_marks_crypto_symbols_weak() {
        let mut emitter = Emitter::new(Target::new(Platform::Linux, Arch::AArch64));
        emit_runtime(&mut emitter);
        let asm = emitter.output();

        assert!(asm.contains(".weak MD5\n"));
        assert!(asm.contains(".weak SHA1\n"));
        assert!(asm.contains(".weak SHA256\n"));
        assert!(!asm.contains("arc4random_uniform"));
    }

    #[test]
    fn test_linux_x86_64_runtime_is_minimal_for_now() {
        let mut emitter = Emitter::new(Target::new(Platform::Linux, Arch::X86_64));
        emit_runtime(&mut emitter);
        let asm = emitter.output();

        assert!(asm.contains("__rt_heap_alloc:\n"));
        assert!(asm.contains("__rt_heap_free:\n"));
        assert!(asm.contains("__rt_array_clone_shallow:\n"));
        assert!(asm.contains("__rt_array_ensure_unique:\n"));
        assert!(asm.contains("__rt_array_grow:\n"));
        assert!(asm.contains("__rt_random_u32:\n"));
        assert!(asm.contains("__rt_random_uniform:\n"));
        assert!(asm.contains("__rt_sort_int:\n"));
        assert!(asm.contains("__rt_rsort_int:\n"));
        assert!(asm.contains("__rt_shuffle:\n"));
        assert!(asm.contains("__rt_asort:\n"));
        assert!(asm.contains("__rt_arsort:\n"));
        assert!(asm.contains("__rt_itoa:\n"));
        assert!(asm.contains("__rt_ftoa:\n"));
        assert!(asm.contains("__rt_concat:\n"));
        assert!(asm.contains("__rt_atoi:\n"));
        assert!(asm.contains("__rt_str_persist:\n"));
        assert!(asm.contains("__rt_str_eq:\n"));
        assert!(asm.contains("__rt_exception_cleanup_frames:\n"));
        assert!(asm.contains("__rt_exception_matches:\n"));
        assert!(asm.contains("__rt_throw_current:\n"));
        assert!(asm.contains("__rt_rethrow_current:\n"));
        assert!(asm.contains("__rt_trim:\n"));
        assert!(asm.contains("__rt_ltrim:\n"));
        assert!(asm.contains("__rt_rtrim:\n"));
        assert!(asm.contains("__rt_addslashes:\n"));
        assert!(asm.contains("__rt_stripslashes:\n"));
        assert!(asm.contains("__rt_bin2hex:\n"));
        assert!(asm.contains("__rt_hex2bin:\n"));
        assert!(asm.contains("__rt_implode:\n"));
        assert!(asm.contains("__rt_implode_int:\n"));
        assert!(asm.contains("__rt_explode:\n"));
        assert!(asm.contains("__rt_strtoupper:\n"));
        assert!(asm.contains("__rt_str_repeat:\n"));
        assert!(asm.contains("__rt_chr:\n"));
        assert!(asm.contains("__rt_base64_encode:\n"));
        assert!(asm.contains("__rt_base64_decode:\n"));
        assert!(asm.contains("__rt_date:\n"));
        assert!(asm.contains("__rt_mktime:\n"));
        assert!(asm.contains("__rt_strtotime:\n"));
        assert!(asm.contains("__rt_array_new:\n"));
        assert!(asm.contains("__rt_array_fill:\n"));
        assert!(asm.contains("__rt_array_fill_refcounted:\n"));
        assert!(asm.contains("__rt_array_push_int:\n"));
        assert!(asm.contains("__rt_array_push_refcounted:\n"));
        assert!(asm.contains("__rt_array_push_str:\n"));
        assert!(asm.contains("__rt_array_merge_into:\n"));
        assert!(asm.contains("__rt_array_merge_into_refcounted:\n"));
        assert!(asm.contains("__rt_range:\n"));
        assert!(asm.contains("__rt_array_diff:\n"));
        assert!(asm.contains("__rt_array_intersect:\n"));
        assert!(asm.contains("__rt_array_merge:\n"));
        assert!(asm.contains("__rt_array_pad:\n"));
        assert!(asm.contains("__rt_array_product:\n"));
        assert!(asm.contains("__rt_array_rand:\n"));
        assert!(asm.contains("__rt_array_reverse:\n"));
        assert!(asm.contains("__rt_array_shift:\n"));
        assert!(asm.contains("__rt_array_slice:\n"));
        assert!(asm.contains("__rt_array_splice:\n"));
        assert!(asm.contains("__rt_array_sum:\n"));
        assert!(asm.contains("__rt_array_chunk:\n"));
        assert!(asm.contains("__rt_array_combine:\n"));
        assert!(asm.contains("__rt_array_flip:\n"));
        assert!(asm.contains("__rt_array_unshift:\n"));
        assert!(asm.contains("__rt_array_unique:\n"));
        assert!(asm.contains("__rt_array_map:\n"));
        assert!(asm.contains("__rt_array_map_str:\n"));
        assert!(asm.contains("__rt_array_filter:\n"));
        assert!(asm.contains("__rt_array_filter_refcounted:\n"));
        assert!(asm.contains("__rt_array_reduce:\n"));
        assert!(asm.contains("__rt_array_walk:\n"));
        assert!(asm.contains("__rt_hash_fnv1a:\n"));
        assert!(asm.contains("__rt_hash_new:\n"));
        assert!(asm.contains("__rt_hash_set:\n"));
        assert!(asm.contains("__rt_hash_get:\n"));
        assert!(asm.contains("__rt_array_fill_keys:\n"));
        assert!(asm.contains("__rt_array_fill_keys_refcounted:\n"));
        assert!(asm.contains("__rt_array_column:\n"));
        assert!(asm.contains("__rt_array_column_ref:\n"));
        assert!(asm.contains("__rt_array_column_str:\n"));
        assert!(asm.contains("__rt_mixed_is_empty:\n"));
        assert!(asm.contains("__rt_decref_hash:\n"));
        assert!(asm.contains("__rt_hash_free_deep:\n"));
        assert!(asm.contains("__rt_decref_any:\n"));
        assert!(asm.contains("__rt_object_free_deep:\n"));
        assert!(asm.contains("__rt_decref_object:\n"));
        assert!(asm.contains("__rt_build_argv:\n"));
        assert!(asm.contains("__rt_incref:\n"));
        assert!(asm.contains("__rt_decref_mixed:\n"));
        assert!(asm.contains("__rt_mixed_from_value:\n"));
        assert!(asm.contains("__rt_mixed_cast_bool:\n"));
        assert!(asm.contains("__rt_mixed_cast_int:\n"));
        assert!(asm.contains("__rt_mixed_free_deep:\n"));
        assert!(asm.contains("__rt_mixed_unbox:\n"));
        assert!(asm.contains("__rt_mixed_cast_string:\n"));
        assert!(asm.contains("__rt_mixed_strict_eq:\n"));
        assert!(asm.contains("__rt_buffer_new:\n"));
        assert!(asm.contains("__rt_buffer_len:\n"));
        assert!(asm.contains("__rt_buffer_bounds_fail:\n"));
        assert!(asm.contains("__rt_buffer_use_after_free:\n"));
        assert!(asm.contains("__rt_cstr:\n"));
        assert!(asm.contains("__rt_ptr_check_nonnull:\n"));
        assert!(asm.contains("__rt_str_to_cstr:\n"));
        assert!(asm.contains("__rt_cstr_to_str:\n"));
        assert!(asm.contains("__rt_fopen:\n"));
        assert!(asm.contains("__rt_fgets:\n"));
        assert!(asm.contains("__rt_feof:\n"));
        assert!(asm.contains("__rt_fread:\n"));
        assert!(asm.contains("__rt_fgetcsv:\n"));
        assert!(asm.contains("__rt_fputcsv:\n"));
        assert!(asm.contains("__rt_scandir:\n"));
        assert!(asm.contains("__rt_glob:\n"));
        assert!(asm.contains("__rt_tempnam:\n"));
        assert!(asm.contains("__rt_file_get_contents:\n"));
        assert!(asm.contains("__rt_file_put_contents:\n"));
        assert!(asm.contains("__rt_file:\n"));
        assert!(asm.contains("__rt_file_exists:\n"));
        assert!(asm.contains("__rt_is_file:\n"));
        assert!(asm.contains("__rt_is_dir:\n"));
        assert!(asm.contains("__rt_is_readable:\n"));
        assert!(asm.contains("__rt_is_writable:\n"));
        assert!(asm.contains("__rt_filesize:\n"));
        assert!(asm.contains("__rt_filemtime:\n"));
        assert!(asm.contains("__rt_unlink:\n"));
        assert!(asm.contains("__rt_mkdir:\n"));
        assert!(asm.contains("__rt_rmdir:\n"));
        assert!(asm.contains("__rt_chdir:\n"));
        assert!(asm.contains("__rt_copy:\n"));
        assert!(asm.contains("__rt_getcwd:\n"));
        assert!(asm.contains("__rt_json_decode:\n"));
        assert!(asm.contains("__rt_json_encode_array_int:\n"));
        assert!(asm.contains("__rt_json_encode_array_str:\n"));
        assert!(asm.contains("__rt_enum_from_fail:\n"));
    }
}
