//! Purpose:
//! Builds a static libxml2 2.15.3 archive plus the Elephc-owned `elephc_libxml2_v1_*` shim the
//! `elephc-xml` bridge links, and retains libxml2's complete public header set.
//!
//! Called from:
//! - `crate::native_deps::recipe::CuratedRecipes` for libxml2 recipe revision 1.
//!
//! Key details:
//! - Out-of-tree autoconf build, static/PIC only. Python bindings, zlib, ICU, readline/history
//!   and dynamic modules are switched off BY NAME so a build machine that happens to have them
//!   installed cannot change what the artifact contains. iconv comes from the platform: glibc
//!   builds it into libc, Apple ships it as `-liconv` (which the bridge adds on Apple targets).
//!   Everything else (SAX1, push parser, HTML, XPath, XInclude, schemas, xmlreader, xmlwriter,
//!   ...) stays at libxml2's defaults because future extensions compile against it.
//! - THERE IS NO `--without-lzma`. libxml2 2.14 removed liblzma (xz-compressed I/O) support
//!   entirely (`NEWS`: "The built-in HTTP client and support for LZMA compression were
//!   removed"), so the 2.15.3 configure knows no such option and passing it would only imply
//!   a defense it does not provide — the reasoning `curl.rs` applies to `--without-librtmp`.
//! - Only `make libxml2.la` runs: the top-level Makefile would also build xmllint/xmlcatalog
//!   and descend into `example/`, none of which is retained.
//! - `xmlversion.h` is GENERATED by configure into the build tree (from `xmlversion.h.in`)
//!   while the other 45 public headers stay in the pristine source tree, so the retained set
//!   is copied from two places — the split `nghttp2.rs` and `openssl.rs` handle the same way.
//! - The shim is compiled against the headers just staged, never a system libxml2, because it
//!   reads `xmlParserCtxt`/`xmlEntity` members whose layout is version-specific.
//! - CFLAGS ARE EXPLICIT, AND PASSED AS A CONFIGURE ARGUMENT. The toolchain environment hands
//!   every recipe a bare `CFLAGS=-fPIC` (`toolchain.rs`), and autoconf only adds its `-g -O2`
//!   default when CFLAGS is UNSET, so an inherited value would build libxml2 at -O0 — which is
//!   what the first artifacts were (verified by disassembly). A `CFLAGS=...` operand on the
//!   configure command line is a precious-variable assignment that overrides the environment,
//!   so the recipe owns the flags: `-O2 -fPIC` plus two `-ffile-prefix-map=` entries that
//!   rename the per-run staging paths (home directory, pid, nonce; see `materialize.rs`) to
//!   `libxml2-<version>` and `build`. Without the maps `xpath.c`, which embeds `__FILE__`
//!   through an error macro, bakes the builder's staging directory into `libxml2.a`, making
//!   the artifact non-reproducible and leaking that path. gcc >= 8, clang >= 10 and Apple
//!   clang all accept `-ffile-prefix-map`. The shim is compiled by hand with the same flags.
//!   `recipe_revision` stays at 1: no artifact built without these flags was ever released.

use std::ffi::OsString;
use std::fs;
use std::path::Path;

use crate::codegen_support::platform::Target;

use super::super::error::NativeError;
use super::super::recipe::RecipeRequest;
use super::super::toolchain::run_checked;
use super::util::{copy_regular, require_regular};

/// Embedded shim source used by installed Elephc binaries without repository access.
pub const SHIM_SOURCE: &str = include_str!("libxml2_shim.c");

/// The exact configure switches revision 1 passes, in order, before the `CFLAGS=` operand and
/// any cross `--host=`.
const CONFIGURE_FLAGS: &[&str] = &[
    "--disable-shared",
    "--enable-static",
    "--without-python",
    "--without-zlib",
    "--with-iconv",
    "--without-icu",
    "--without-readline",
    "--without-history",
    "--without-modules",
];

/// The optimization and code-model flags revision 1 compiles libxml2 and the shim with. They
/// are spelled out because a set CFLAGS makes autoconf skip its own `-g -O2` default (see the
/// module preamble); `-g` is deliberately absent so no debug paths reach the archive either.
const BASE_CFLAGS: &[&str] = &["-O2", "-fPIC"];

/// Builds the two `-ffile-prefix-map=<old>=<new>` arguments that scrub the per-run staging
/// paths from every object: the extracted source tree becomes `libxml2-<version>` and the
/// out-of-tree build directory `build`, so `__FILE__` (which `xpath.c` embeds) and any macro or
/// debug path read the same whoever built the artifact.
fn prefix_map_flags(source: &Path, version: &str, build: &Path) -> [OsString; 2] {
    [prefix_map(source, &format!("libxml2-{version}")), prefix_map(build, "build")]
}

/// Formats one `-ffile-prefix-map=<old>=<new>` argument without lossy path conversion.
fn prefix_map(old: &Path, new: &str) -> OsString {
    let mut flag = OsString::from("-ffile-prefix-map=");
    flag.push(old.as_os_str());
    flag.push("=");
    flag.push(new);
    flag
}

/// Builds the `CFLAGS=...` configure operand from [`BASE_CFLAGS`] and the prefix maps. autoconf
/// treats a `VAR=value` operand as a precious-variable assignment that overrides the
/// environment, which is what lets the recipe win over the toolchain's bare `CFLAGS=-fPIC`;
/// the generated Makefile then records the value, so `make` inherits it too.
fn configure_cflags(prefix_maps: &[OsString]) -> OsString {
    let mut flag = OsString::from("CFLAGS=");
    flag.push(BASE_CFLAGS.join(" "));
    for map in prefix_maps {
        flag.push(" ");
        flag.push(map);
    }
    flag
}

/// Builds libxml2 and its shim into the catalog-declared staging prefix.
pub fn build(request: &RecipeRequest<'_>) -> Result<(), NativeError> {
    let build = request.staging_prefix.join("build");
    let include_root = request.staging_prefix.join("include");
    let include = include_root.join("libxml");
    let library = request.staging_prefix.join("lib");
    fs::create_dir_all(&build)
        .map_err(|error| NativeError::io("create libxml2 build directory", &build, error))?;
    fs::create_dir_all(&include)
        .map_err(|error| NativeError::io("create libxml2 include directory", &include, error))?;
    fs::create_dir_all(&library)
        .map_err(|error| NativeError::io("create libxml2 library directory", &library, error))?;

    let configure = request.source.join("configure");
    require_regular("libxml2", &configure)?;
    let prefix_maps = prefix_map_flags(request.source, request.version.version, &build);
    let mut command = request.toolchain.command(Path::new("/bin/sh"));
    command.current_dir(&build).arg(&configure).args(CONFIGURE_FLAGS).arg(configure_cflags(&prefix_maps));
    if request.target != Target::detect_host() {
        // `abi`, not `target_tuple`: autoconf feeds --host through config.sub, which rejects
        // the clang triple an Apple cross compiler reports (see the pcre2 recipe).
        command.arg(format!("--host={}", request.toolchain.autoconf_host()));
    }
    run_checked(&mut command, "configure trusted libxml2 recipe")?;

    let mut make = request.toolchain.command(Path::new("make"));
    make.current_dir(&build).arg("libxml2.la");
    run_checked(&mut make, "build trusted libxml2 static library")?;

    copy_regular("libxml2", &build.join(".libs/libxml2.a"), &library.join("libxml2.a"))?;
    for header in request.version.retained_headers {
        let Some(name) = header.strip_prefix("include/libxml/") else {
            continue;
        };
        let source = if name == "xmlversion.h" {
            build.join("include/libxml/xmlversion.h")
        } else {
            request.source.join("include/libxml").join(name)
        };
        copy_regular("libxml2", &source, &include.join(name))?;
    }

    let archive = library.join("libxml2.a");
    let mut inspect = request.toolchain.command(&request.toolchain.ar);
    inspect.arg("t").arg(&archive);
    run_checked(&mut inspect, "validate trusted libxml2 static archive")?;
    build_shim(request, &include_root, &library, &prefix_maps)?;
    fs::remove_dir_all(&build)
        .map_err(|error| NativeError::io("remove trusted libxml2 build tree", &build, error))?;
    Ok(())
}

/// Compiles the opaque shim with [`BASE_CFLAGS`] and the same prefix maps as libxml2 against
/// the staged headers and archives it with the selected target tools; the source and object
/// intermediates never reach the artifact.
fn build_shim(request: &RecipeRequest<'_>, include_root: &Path, library: &Path, prefix_maps: &[OsString]) -> Result<(), NativeError> {
    let source = request.staging_prefix.join("elephc_libxml2_shim.c");
    let object = request.staging_prefix.join("elephc_libxml2_shim.o");
    let archive = library.join("libelephc_libxml2_shim.a");
    fs::write(&source, SHIM_SOURCE)
        .map_err(|error| NativeError::io("write embedded libxml2 shim", &source, error))?;
    let mut compile = request.toolchain.command(&request.toolchain.cc);
    compile.args(BASE_CFLAGS).args(prefix_maps).arg("-I").arg(include_root).arg("-c").arg(&source).arg("-o").arg(&object);
    run_checked(&mut compile, "compile Elephc libxml2 shim")?;
    let mut archive_command = request.toolchain.command(&request.toolchain.ar);
    archive_command.arg("crs").arg(&archive).arg(&object);
    run_checked(&mut archive_command, "archive Elephc libxml2 shim")?;
    let mut ranlib = request.toolchain.command(&request.toolchain.ranlib);
    ranlib.arg(&archive);
    run_checked(&mut ranlib, "index Elephc libxml2 shim")?;
    let mut inspect = request.toolchain.command(&request.toolchain.ar);
    inspect.arg("t").arg(&archive);
    run_checked(&mut inspect, "validate Elephc libxml2 shim archive")?;
    fs::remove_file(&source)
        .map_err(|error| NativeError::io("remove libxml2 shim source intermediate", &source, error))?;
    fs::remove_file(&object)
        .map_err(|error| NativeError::io("remove libxml2 shim object intermediate", &object, error))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verifies installed binaries embed the exact versioned opaque shim ABI and that the shim
    /// compiles against libxml2's own headers rather than redeclaring its structs.
    #[test]
    fn shim_source_is_embedded_and_versioned() {
        assert!(SHIM_SOURCE.contains("elephc_libxml2_v1_parser_create"));
        assert!(SHIM_SOURCE.contains("elephc_libxml2_v1_parse_chunk"));
        assert!(SHIM_SOURCE.contains("elephc_libxml2_v1_current_tag"));
        assert!(SHIM_SOURCE.contains("#include <libxml/parser.h>"));
        assert!(!SHIM_SOURCE.contains("struct _xmlParserCtxt {"));
    }

    /// Verifies the configure switch set is static-only, pins every optional dependency off by
    /// name, keeps the platform iconv, and never passes the option libxml2 2.14 removed.
    #[test]
    fn configure_flags_pin_optional_dependencies_by_name() {
        assert_eq!(CONFIGURE_FLAGS[..2], ["--disable-shared", "--enable-static"]);
        for flag in ["--without-python", "--without-zlib", "--without-icu", "--without-readline", "--without-history", "--without-modules"] {
            assert!(CONFIGURE_FLAGS.contains(&flag), "missing {flag}");
        }
        assert!(CONFIGURE_FLAGS.contains(&"--with-iconv"));
        assert!(!CONFIGURE_FLAGS.iter().any(|flag| flag.contains("lzma")));
        assert!(!CONFIGURE_FLAGS.iter().any(|flag| flag.starts_with("--host=")));
        assert!(!CONFIGURE_FLAGS.iter().any(|flag| flag.starts_with("CFLAGS=")), "CFLAGS is derived, not a static switch");
    }

    /// Verifies the recipe owns its optimization level instead of inheriting the toolchain's
    /// bare `-fPIC` (which would silence autoconf's `-O2` default), stays PIC, and never asks
    /// for debug info that would carry paths into the archive.
    #[test]
    fn base_cflags_optimize_without_debug_paths() {
        assert_eq!(BASE_CFLAGS, &["-O2", "-fPIC"]);
        assert!(!BASE_CFLAGS.contains(&"-g"));
        assert!(!BASE_CFLAGS.contains(&"-O0"));
    }

    /// Verifies the prefix maps rename BOTH per-run staging trees to fixed names with no path
    /// separator in the replacement, so `__FILE__` in `xpath.c` (and any other embedded
    /// path) cannot carry the builder's home directory, pid or nonce into `libxml2.a`.
    #[test]
    fn prefix_maps_scrub_source_and_build_staging_paths() {
        let source = Path::new("/home/builder/.cache/elephc/native/artifacts/libxml2/.abc.stage.4242.99/.source");
        let build = Path::new("/home/builder/.cache/elephc/native/artifacts/libxml2/.abc.stage.4242.99/build");
        let maps = prefix_map_flags(source, "2.15.3", build);
        assert_eq!(
            maps[0].to_str().unwrap(),
            "-ffile-prefix-map=/home/builder/.cache/elephc/native/artifacts/libxml2/.abc.stage.4242.99/.source=libxml2-2.15.3"
        );
        assert_eq!(
            maps[1].to_str().unwrap(),
            "-ffile-prefix-map=/home/builder/.cache/elephc/native/artifacts/libxml2/.abc.stage.4242.99/build=build"
        );
        for map in &maps {
            let replacement = map.to_str().unwrap().rsplit('=').next().unwrap();
            assert!(!replacement.contains('/') && !replacement.contains(".stage."), "{replacement}");
        }
    }

    /// Verifies the configure operand is a `CFLAGS=` variable assignment (the form autoconf
    /// lets override the environment) carrying the base flags first and both prefix maps.
    #[test]
    fn configure_cflags_is_an_overriding_assignment_with_both_maps() {
        let maps = prefix_map_flags(Path::new("/stage/.source"), "2.15.3", Path::new("/stage/build"));
        let operand = configure_cflags(&maps);
        assert_eq!(
            operand.to_str().unwrap(),
            "CFLAGS=-O2 -fPIC -ffile-prefix-map=/stage/.source=libxml2-2.15.3 -ffile-prefix-map=/stage/build=build"
        );
    }
}
