//! Purpose:
//! Builds a static libnghttp2 1.70.0 archive, the HTTP/2 framing library libcurl's
//! `--with-nghttp2` build links against.
//!
//! Called from:
//! - `crate::native_deps::recipe::CuratedRecipes` for nghttp2 recipe revision 1.
//!
//! Key details:
//! - `--enable-lib-only` is nghttp2's own documented short-hand for "build `lib/` and
//!   nothing else" (`configure.ac`: it forces `request_app`, `request_hpack_tools`,
//!   `request_examples`, `request_http3`, `request_libxml2`, `request_jansson`,
//!   `request_zlib`, `request_libevent_openssl`, `request_libcares`, `request_openssl`,
//!   `request_libev`, `request_jemalloc`, `request_systemd` and `request_mruby` to `no`).
//!   That is what keeps this recipe DEPENDENCY-FREE: the nghttp2 *applications* need
//!   zlib/OpenSSL/libev/c-ares, the library itself needs none of them, so `nghttp2` has an
//!   empty `dependencies` list in the catalog even though `curl` links both it and OpenSSL.
//! - nghttp2 1.70.0's `src/` requires a C++23 compiler; `lib/` is plain C99 and
//!   `AX_CXX_COMPILE_STDCXX([23], [], [optional])` is what makes the C++ probe
//!   non-fatal, so a toolchain with no usable C++23 still builds this recipe.
//! - `nghttp2ver.h` is GENERATED by configure into the build tree while `nghttp2.h` stays
//!   in the pristine source tree, so the two retained headers are copied from different
//!   places — the same split `openssl.rs` handles for its `.h.in` templates.

use std::fs;
use std::path::Path;

use crate::codegen_support::platform::Target;

use super::super::error::NativeError;
use super::super::recipe::RecipeRequest;
use super::super::toolchain::run_checked;
use super::util::{copy_regular, require_regular};

/// Builds nghttp2 into the catalog-declared staging prefix.
pub fn build(request: &RecipeRequest<'_>) -> Result<(), NativeError> {
    let build = request.staging_prefix.join("build");
    let include = request.staging_prefix.join("include/nghttp2");
    let library = request.staging_prefix.join("lib");
    fs::create_dir_all(&build)
        .map_err(|error| NativeError::io("create nghttp2 build directory", &build, error))?;
    fs::create_dir_all(&include)
        .map_err(|error| NativeError::io("create nghttp2 include directory", &include, error))?;
    fs::create_dir_all(&library)
        .map_err(|error| NativeError::io("create nghttp2 library directory", &library, error))?;

    let configure = request.source.join("configure");
    require_regular("nghttp2", &configure)?;
    let mut command = request.toolchain.command(Path::new("/bin/sh"));
    command.current_dir(&build).arg(&configure).args([
        "--disable-shared",
        "--enable-static",
        "--enable-lib-only",
    ]);
    if request.target != Target::detect_host() {
        command.arg(format!("--host={}", request.toolchain.target_tuple));
    }
    run_checked(&mut command, "configure trusted nghttp2 recipe")?;

    let mut make = request.toolchain.command(Path::new("make"));
    make.current_dir(&build).args(["-C", "lib"]);
    run_checked(&mut make, "build trusted libnghttp2 static library")?;

    copy_regular(
        "nghttp2",
        &build.join("lib/.libs/libnghttp2.a"),
        &library.join("libnghttp2.a"),
    )?;
    copy_regular(
        "nghttp2",
        &request.source.join("lib/includes/nghttp2/nghttp2.h"),
        &include.join("nghttp2.h"),
    )?;
    copy_regular(
        "nghttp2",
        &build.join("lib/includes/nghttp2/nghttp2ver.h"),
        &include.join("nghttp2ver.h"),
    )?;

    let archive = library.join("libnghttp2.a");
    let mut inspect = request.toolchain.command(&request.toolchain.ar);
    inspect.arg("t").arg(&archive);
    run_checked(&mut inspect, "validate trusted libnghttp2 static archive")?;
    fs::remove_dir_all(&build)
        .map_err(|error| NativeError::io("remove trusted nghttp2 build tree", &build, error))?;
    Ok(())
}
