mod heap_alloc;
mod array_new;
mod array_push_int;
mod array_push_str;
mod sort_int;
mod hash_fnv1a;
mod hash_new;
mod hash_set;
mod hash_get;
mod hash_iter;
mod hash_count;

pub use heap_alloc::emit_heap_alloc;
pub use array_new::emit_array_new;
pub use array_push_int::emit_array_push_int;
pub use array_push_str::emit_array_push_str;
pub use sort_int::emit_sort_int;
pub use hash_fnv1a::emit_hash_fnv1a;
pub use hash_new::emit_hash_new;
pub use hash_set::emit_hash_set;
pub use hash_get::emit_hash_get;
pub use hash_iter::emit_hash_iter;
pub use hash_count::emit_hash_count;
