use crate::codegen::emit::Emitter;
use crate::codegen::platform::Platform;

/// __rt_random_u32: return a pseudo-random 32-bit unsigned integer in x0.
pub fn emit_random_u32(emitter: &mut Emitter) {
    emitter.blank();
    emitter.comment("--- runtime: random_u32 ---");
    emitter.label_global("__rt_random_u32");

    match emitter.platform {
        Platform::MacOS => {
            emitter.instruction("sub sp, sp, #16");                             // reserve a tiny frame so the nested libc call can preserve our return address
            emitter.instruction("str x30, [sp, #0]");                           // save the caller's return address before bl clobbers x30
            emitter.bl_c("arc4random");                                         // use libc's arc4random() on macOS
            emitter.instruction("mov w0, w0");                                  // zero-extend the uint32 result into x0
            emitter.instruction("ldr x30, [sp, #0]");                           // restore the caller's return address after the libc call returns
            emitter.instruction("add sp, sp, #16");                             // release the temporary frame
            emitter.instruction("ret");                                         // return the random uint32
        }
        Platform::Linux => {
            emitter.instruction("sub sp, sp, #32");                             // allocate stack space for the syscall buffer and saved frame
            emitter.instruction("stp x29, x30, [sp, #16]");                     // save frame pointer and return address
            emitter.instruction("add x29, sp, #16");                            // set up a frame pointer for the fallback path

            emitter.instruction("mov x0, sp");                                  // buffer = stack scratch space
            emitter.instruction("mov x1, #4");                                  // request 4 random bytes
            emitter.instruction("mov x2, #0");                                  // flags = 0
            emitter.instruction("mov x8, #278");                                // Linux aarch64 getrandom syscall number
            emitter.instruction("svc #0");                                      // ask the kernel for random bytes
            emitter.instruction("cmp x0, #4");                                  // did getrandom fill the full uint32 buffer?
            emitter.instruction("b.eq __rt_random_u32_linux_ok");               // yes — use the kernel-generated bytes

            // -- fallback: mix time(NULL) into a 32-bit value if getrandom is unavailable --
            emitter.instruction("mov x0, #0");                                  // pass NULL to time() to request only the return value
            emitter.bl_c("time");                                               // get coarse wall-clock seconds from libc
            emitter.instruction("mov x9, x0");                                  // preserve the low half for mixing
            emitter.instruction("lsl x0, x0, #32");                             // move the timestamp into the high half
            emitter.instruction("eor x0, x0, x9");                              // fold high and low halves together into one word
            emitter.instruction("b __rt_random_u32_linux_done");                // skip loading the syscall buffer

            emitter.label("__rt_random_u32_linux_ok");
            emitter.instruction("ldr w0, [sp, #0]");                            // load the generated uint32 from the stack buffer

            emitter.label("__rt_random_u32_linux_done");
            emitter.instruction("ldp x29, x30, [sp, #16]");                     // restore frame pointer and return address
            emitter.instruction("add sp, sp, #32");                             // release the temporary stack frame
            emitter.instruction("ret");                                         // return the random uint32
        }
    }
}
