//! Purpose:
//! Statement builders for the synthetic DatePeriod method bodies.
//!
//! Called from:
//! - The sibling module's method assembly.
//!
//! Key details:
//! - BUILT, not parsed. Each function reproduces the AST its `*_SRC` PHP constant parses to;
//!   the oracle test in the parent module compares them node by node, which is what makes
//!   these hand-reviewable transcriptions safe to rely on.
//! - Generated by `synthetic_class::transcribe`, then reviewed.

use crate::parser::ast::{BinOp, Stmt};
use crate::synthetic_class::{
    e_binop,
    e_call,
    e_float,
    e_index,
    e_int,
    e_method_call,
    e_named_class,
    e_new,
    e_not,
    e_null,
    e_str,
    e_static_call,
    e_static_class,
    e_this_prop,
    e_var,
    s_assign,
    s_expr,
    s_if,
    s_prop_assign,
    s_return,
    s_throw,
};

/// Reproduces `CREATE_FROM_ISO8601_SRC`.
pub(super) fn create_from_iso8601() -> Vec<Stmt> {
    vec![
        s_assign("result", e_null()),
        s_if(
            e_binop(e_static_class(), BinOp::StrictEq, e_named_class("DatePeriod")),
            vec![
                s_assign("result", e_call("__elephc_new_instance_without_constructor", vec![e_str("DatePeriod")])),
            ],
            vec![],
            Some(vec![
                s_assign("result", e_call("__elephc_new_instance_without_constructor", vec![e_static_class()])),
            ]),
        ),
        s_assign("typedResult", e_method_call(e_var("result"), "__elephc_factory_result", vec![])),
        s_expr(e_call("unset", vec![e_var("result")])),
        s_assign("parsed", e_call("__elephc_timelib_period_parse", vec![e_var("specification")])),
        s_if(
            e_binop(e_index(e_var("parsed"), e_str("status")), BinOp::StrictNotEq, e_str("P")),
            vec![
                s_throw(e_new("DateMalformedPeriodStringException", vec![e_binop(e_binop(e_str("Unknown or bad format ("), BinOp::Concat, e_var("specification")), BinOp::Concat, e_str(")"))])),
            ],
            vec![],
            None,
        ),
        s_if(
            e_not(e_index(e_var("parsed"), e_str("has_start"))),
            vec![
                s_throw(e_new("DateMalformedPeriodStringException", vec![e_binop(e_binop(e_str("DatePeriod::createFromISO8601String(): ISO interval must contain a start date, \""), BinOp::Concat, e_var("specification")), BinOp::Concat, e_str("\" given"))])),
            ],
            vec![],
            None,
        ),
        s_if(
            e_not(e_index(e_var("parsed"), e_str("has_interval"))),
            vec![
                s_throw(e_new("DateMalformedPeriodStringException", vec![e_binop(e_binop(e_str("DatePeriod::createFromISO8601String(): ISO interval must contain an interval, \""), BinOp::Concat, e_var("specification")), BinOp::Concat, e_str("\" given"))])),
            ],
            vec![],
            None,
        ),
        s_if(
            e_binop(e_not(e_index(e_var("parsed"), e_str("has_end"))), BinOp::And, e_binop(e_index(e_var("parsed"), e_str("recurrences")), BinOp::StrictEq, e_int(0))),
            vec![
                s_throw(e_new("DateMalformedPeriodStringException", vec![e_binop(e_binop(e_str("DatePeriod::createFromISO8601String(): ISO interval must contain an end date or a recurrence count, \""), BinOp::Concat, e_var("specification")), BinOp::Concat, e_str("\" given"))])),
            ],
            vec![],
            None,
        ),
        s_assign("start", e_static_call("DateTimeImmutable", "createFromTimestamp", vec![e_index(e_var("parsed"), e_str("start"))])),
        s_assign("endTimestamp", e_int(0)),
        s_if(
            e_index(e_var("parsed"), e_str("has_end")),
            vec![
                s_assign("endTimestamp", e_index(e_var("parsed"), e_str("end"))),
            ],
            vec![],
            None,
        ),
        s_assign("interval", e_new("DateInterval", vec![e_str("PT0S")])),
        s_prop_assign(e_var("interval"), "y", e_index(e_var("parsed"), e_str("y"))),
        s_prop_assign(e_var("interval"), "m", e_index(e_var("parsed"), e_str("m"))),
        s_prop_assign(e_var("interval"), "d", e_index(e_var("parsed"), e_str("d"))),
        s_prop_assign(e_var("interval"), "h", e_index(e_var("parsed"), e_str("h"))),
        s_prop_assign(e_var("interval"), "i", e_index(e_var("parsed"), e_str("i"))),
        s_prop_assign(e_var("interval"), "s", e_index(e_var("parsed"), e_str("s"))),
        s_prop_assign(e_var("interval"), "f", e_binop(e_index(e_var("parsed"), e_str("us")), BinOp::Div, e_float(1000000.0))),
        s_if(
            e_index(e_var("parsed"), e_str("has_end")),
            vec![
                s_expr(e_method_call(e_var("typedResult"), "__elephc_initialize_end_components", vec![e_var("start"), e_var("interval"), e_var("endTimestamp"), e_var("options")])),
            ],
            vec![],
            Some(vec![
                s_expr(e_method_call(e_var("typedResult"), "__elephc_initialize_recurrence_components", vec![e_var("start"), e_var("interval"), e_index(e_var("parsed"), e_str("recurrences")), e_var("options")])),
            ]),
        ),
        s_expr(e_call("unset", vec![e_var("interval")])),
        s_expr(e_call("unset", vec![e_var("start")])),
        s_expr(e_call("unset", vec![e_var("parsed")])),
        s_return(e_var("typedResult")),
    ]
}

/// Reproduces `CURRENT_SRC`.
pub(super) fn current() -> Vec<Stmt> {
    vec![
        s_if(
            e_this_prop("startIsImmutable"),
            vec![
                s_assign("d", e_new("DateTimeImmutable", vec![])),
                s_return(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("curTs")])),
            ],
            vec![],
            None,
        ),
        s_assign("d", e_new("DateTime", vec![])),
        s_expr(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("curTs")])),
        s_return(e_var("d")),
    ]
}

/// Reproduces `GET_END_DATE_SRC`.
pub(super) fn get_end_date() -> Vec<Stmt> {
    vec![
        s_if(
            e_this_prop("useCount"),
            vec![
                s_return(e_null()),
            ],
            vec![],
            None,
        ),
        s_assign("d", e_new("DateTime", vec![])),
        s_expr(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("endTs")])),
        s_return(e_var("d")),
    ]
}

/// Reproduces `GET_START_DATE_SRC`.
pub(super) fn get_start_date() -> Vec<Stmt> {
    vec![
        s_if(
            e_this_prop("startIsImmutable"),
            vec![
                s_assign("d", e_new("DateTimeImmutable", vec![])),
                s_return(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("startTs")])),
            ],
            vec![],
            None,
        ),
        s_assign("d", e_new("DateTime", vec![])),
        s_expr(e_method_call(e_var("d"), "setTimestamp", vec![e_this_prop("startTs")])),
        s_return(e_var("d")),
    ]
}
