"""Data model for the builtins registry.

A *registry* is the single source of truth for everything we render into
docs/php/builtins/*.md and docs/internals/builtins/*.md. It is generated
from the Elephc source tree by `extract.py` and consumed by `render.py`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


# Areas used to group builtins in the sidebar. Order matters: this is the
# order they appear in the generated navigation.
AREAS: list[str] = [
    "String",
    "Array",
    "Math",
    "Type",
    "JSON",
    "Regex",
    "Date",
    "Hash",
    "IO",
    "Filesystem",
    "Streams",
    "Network",
    "Process",
    "SPL",
    "Class",
    "Pointer",
    "Buffer",
    "Misc",
]


# Sub-area mapping: file path under src/codegen_ir/lower_inst/builtins/ or
# src/types/checker/builtins/ → (area, sub_area). When multiple files match
# the same key, the first one wins.
AREA_BY_FILE: Dict[str, Optional[Tuple[str, str]]] = {
    "strings.rs": ("String", "String"),
    "arrays.rs": ("Array", "Array"),
    "arrays/column.rs": ("Array", "Array"),
    "arrays/key_exists.rs": ("Array", "Array"),
    "arrays/keys.rs": ("Array", "Array"),
    "arrays/search.rs": ("Array", "Array"),
    "arrays/shift.rs": ("Array", "Array"),
    "arrays/unshift.rs": ("Array", "Array"),
    "arrays/values.rs": ("Array", "Array"),
    "math.rs": ("Math", "Math"),
    "math/binary.rs": ("Math", "Math"),
    "math/libm.rs": ("Math", "Math"),
    "math/random.rs": ("Math", "Math"),
    "ctype.rs": ("Type", "Ctype"),
    "is_numeric.rs": ("Type", "Type"),
    "types.rs": ("Type", "Type"),
    "attributes.rs": ("Class", "Attributes"),
    "class_relations.rs": ("Class", "Class"),
    "json.rs": ("JSON", "JSON"),
    "regex.rs": ("Regex", "Regex"),
    "io.rs": ("IO", "IO"),
    "debug.rs": ("IO", "IO"),
    "system.rs": ("Misc", "System"),
    "pointers.rs": ("Pointer", "Pointer"),
    "buffers.rs": ("Buffer", "Buffer"),
    "spl.rs": ("SPL", "SPL"),
    "isset.rs": ("Misc", "Variable"),
    # builtins/builtins.rs is the *root* dispatcher; area comes from the dispatch arm, not the file.
    "builtins.rs": None,  # sentinel — caller falls back to AREA_BY_LOWERING_FN / AREA_BY_MODULE
}


# Map the submodule prefix in a dispatch arm (e.g. "math" from "math::lower_abs")
# to an area. Used for builtins lowered inline in builtins.rs that have no
# dedicated submodule file to infer the area from.
AREA_BY_MODULE: Dict[str, Tuple[str, str]] = {
    "math": ("Math", "Math"),
    "strings": ("String", "String"),
    "arrays": ("Array", "Array"),
    "json": ("JSON", "JSON"),
    "regex": ("Regex", "Regex"),
    "ctype": ("Type", "Ctype"),
    "is_numeric": ("Type", "Type"),
    "types": ("Type", "Type"),
    "pointers": ("Pointer", "Pointer"),
    "buffers": ("Buffer", "Buffer"),
    "system": ("Misc", "System"),
    "io": ("IO", "IO"),
    "debug": ("IO", "IO"),
    "spl": ("SPL", "SPL"),
    "callables": ("Misc", "Callables"),
    "isset": ("Misc", "Variable"),
    "attributes": ("Class", "Attributes"),
    "class_relations": ("Class", "Class"),
    "scoped_constants": ("Misc", "Constants"),
    "static_locals": ("Misc", "Statics"),
    "static_properties": ("Misc", "Statics"),
}


# Hand-curated overrides for the few lowering functions defined inline in
# builtins.rs whose area is not obvious from the function name.
AREA_BY_LOWERING_FN: Dict[str, Tuple[str, str]] = {
    # Generic libm dispatcher in builtins.rs catches sin/cos/tan/asin/acos/atan/
    # sinh/cosh/tanh/log2/log10/exp — they all live in Math.
    "lower_unary_libm": ("Math", "Math"),
}


# Per-builtin area overrides for names that have no dedicated dispatch arm in
# builtins.rs. Use this when the function name itself carries strong area
# semantics (e.g. every `sin*`/`cos*`/`tan*` is Math).
AREA_BY_NAME: Dict[str, Tuple[str, str]] = {
    # String
    "strlen": ("String", "String"),
    "strtolower": ("String", "String"),
    "strtoupper": ("String", "String"),
    "ucfirst": ("String", "String"),
    "lcfirst": ("String", "String"),
    "ucwords": ("String", "String"),
    "trim": ("String", "String"),
    "ltrim": ("String", "String"),
    "rtrim": ("String", "String"),
    "chop": ("String", "String"),
    "strrev": ("String", "String"),
    "str_repeat": ("String", "String"),
    "str_split": ("String", "String"),
    "str_pad": ("String", "String"),
    "str_contains": ("String", "String"),
    "str_starts_with": ("String", "String"),
    "str_ends_with": ("String", "String"),
    "ord": ("String", "String"),
    "chr": ("String", "String"),
    "crc32": ("String", "String"),
    "md5": ("String", "String"),
    "sha1": ("String", "String"),
    # Math
    "sin": ("Math", "Math"),
    "cos": ("Math", "Math"),
    "tan": ("Math", "Math"),
    "asin": ("Math", "Math"),
    "acos": ("Math", "Math"),
    "atan": ("Math", "Math"),
    "sinh": ("Math", "Math"),
    "cosh": ("Math", "Math"),
    "tanh": ("Math", "Math"),
    "log2": ("Math", "Math"),
    "log10": ("Math", "Math"),
    "exp": ("Math", "Math"),
    # Date
    "strtotime": ("Date", "Date"),
    "mktime": ("Date", "Date"),
    "gmmktime": ("Date", "Date"),
    "checkdate": ("Date", "Date"),
    "date": ("Date", "Date"),
    "gmdate": ("Date", "Date"),
    "microtime": ("Date", "Date"),
    "getdate": ("Date", "Date"),
    "localtime": ("Date", "Date"),
    "hrtime": ("Date", "Date"),
    "date_default_timezone_get": ("Date", "Date"),
    "date_default_timezone_set": ("Date", "Date"),
    "idate": ("Date", "Date"),
    "time": ("Date", "Date"),
    "gettimeofday": ("Date", "Date"),
    # Filesystem
    "file_exists": ("Filesystem", "Filesystem"),
    "is_file": ("Filesystem", "Filesystem"),
    "is_dir": ("Filesystem", "Filesystem"),
    "is_readable": ("Filesystem", "Filesystem"),
    "is_writable": ("Filesystem", "Filesystem"),
    "is_writeable": ("Filesystem", "Filesystem"),
    "is_executable": ("Filesystem", "Filesystem"),
    "is_link": ("Filesystem", "Filesystem"),
    "filesize": ("Filesystem", "Filesystem"),
    "filemtime": ("Filesystem", "Filesystem"),
    "fileatime": ("Filesystem", "Filesystem"),
    "filectime": ("Filesystem", "Filesystem"),
    "fileperms": ("Filesystem", "Filesystem"),
    "fileowner": ("Filesystem", "Filesystem"),
    "filegroup": ("Filesystem", "Filesystem"),
    "fileinode": ("Filesystem", "Filesystem"),
    "filetype": ("Filesystem", "Filesystem"),
    "lstat": ("Filesystem", "Filesystem"),
    "stat": ("Filesystem", "Filesystem"),
    "disk_free_space": ("Filesystem", "Filesystem"),
    "disk_total_space": ("Filesystem", "Filesystem"),
    "clearstatcache": ("Filesystem", "Filesystem"),
    "realpath_cache_get": ("Filesystem", "Filesystem"),
    "realpath_cache_size": ("Filesystem", "Filesystem"),
    "pathinfo": ("Filesystem", "Filesystem"),
    "dirname": ("Filesystem", "Filesystem"),
    "basename": ("Filesystem", "Filesystem"),
    "tempnam": ("Filesystem", "Filesystem"),
    "tmpfile": ("Filesystem", "Filesystem"),
    "touch": ("Filesystem", "Filesystem"),
    "unlink": ("Filesystem", "Filesystem"),
    "rename": ("Filesystem", "Filesystem"),
    "copy": ("Filesystem", "Filesystem"),
    "chmod": ("Filesystem", "Filesystem"),
    "chown": ("Filesystem", "Filesystem"),
    "chgrp": ("Filesystem", "Filesystem"),
    "lchown": ("Filesystem", "Filesystem"),
    "lchgrp": ("Filesystem", "Filesystem"),
    "mkdir": ("Filesystem", "Filesystem"),
    "rmdir": ("Filesystem", "Filesystem"),
    "chdir": ("Filesystem", "Filesystem"),
    "getcwd": ("Filesystem", "Filesystem"),
    "getenv": ("Filesystem", "Filesystem"),
    "putenv": ("Filesystem", "Filesystem"),
    "sys_get_temp_dir": ("Filesystem", "Filesystem"),
    "link": ("Filesystem", "Filesystem"),
    "symlink": ("Filesystem", "Filesystem"),
    "linkinfo": ("Filesystem", "Filesystem"),
    "readlink": ("Filesystem", "Filesystem"),
    "readfile": ("Filesystem", "Filesystem"),
    "umask": ("Filesystem", "Filesystem"),
    "fnmatch": ("Filesystem", "Filesystem"),
    "glob": ("Filesystem", "Filesystem"),
    "scandir": ("Filesystem", "Filesystem"),
    "realpath": ("Filesystem", "Filesystem"),
    # Process
    "exec": ("Process", "Process"),
    "system": ("Process", "Process"),
    "passthru": ("Process", "Process"),
    "shell_exec": ("Process", "Process"),
    "popen": ("Process", "Process"),
    "pclose": ("Process", "Process"),
    "proc_open": ("Process", "Process"),
    "proc_close": ("Process", "Process"),
    "proc_get_status": ("Process", "Process"),
    "proc_terminate": ("Process", "Process"),
    "proc_nice": ("Process", "Process"),
    "sleep": ("Process", "Process"),
    "usleep": ("Process", "Process"),
    "exit": ("Process", "Process"),
    "die": ("Process", "Process"),
    "readline": ("Process", "Process"),
    # Variable handling
    "empty": ("Misc", "Variable"),
    "isset": ("Misc", "Variable"),
    "unset": ("Misc", "Variable"),
    "print_r": ("Misc", "Variable"),
    "var_dump": ("Misc", "Variable"),
    "var_export": ("Misc", "Variable"),
    # Type predicates and casts
    "boolval": ("Type", "Casts"),
    "floatval": ("Type", "Casts"),
    "intval": ("Type", "Casts"),
    "settype": ("Type", "Casts"),
    "strval": ("Type", "Casts"),
    "gettype": ("Type", "Type"),
    "is_array": ("Type", "Type"),
    "is_bool": ("Type", "Type"),
    "is_callable": ("Type", "Type"),
    "is_countable": ("Type", "Type"),
    "is_float": ("Type", "Type"),
    "is_int": ("Type", "Type"),
    "is_integer": ("Type", "Type"),
    "is_iterable": ("Type", "Type"),
    "is_long": ("Type", "Type"),
    "is_null": ("Type", "Type"),
    "is_numeric": ("Type", "Type"),
    "is_object": ("Type", "Type"),
    "is_scalar": ("Type", "Type"),
    "is_string": ("Type", "Type"),
    "is_a": ("Class", "Class"),
    "is_subclass_of": ("Class", "Class"),
    # Constants
    "define": ("Misc", "Constants"),
    "defined": ("Misc", "Constants"),
    "constant": ("Misc", "Constants"),
    # Lowered inline in builtins.rs; route by lowering-fn-name.
    "pi": ("Math", "Math"),
    "phpversion": ("Misc", "Info"),
    "php_uname": ("Misc", "Info"),
    "php_sapi_name": ("Misc", "Info"),
    "phpinfo": ("Misc", "Info"),
    "strlen": ("String", "String"),
    "count": ("Array", "Array"),
    "sizeof": ("Array", "Array"),
    # Class / object introspection
    "class_alias": ("Class", "Class"),
    "class_exists": ("Class", "Class"),
    "class_implements": ("Class", "Class"),
    "class_parents": ("Class", "Class"),
    "class_uses": ("Class", "Class"),
    "enum_exists": ("Class", "Class"),
    "function_exists": ("Class", "Class"),
    "get_class": ("Class", "Class"),
    "get_declared_classes": ("Class", "Class"),
    "get_declared_interfaces": ("Class", "Class"),
    "get_declared_traits": ("Class", "Class"),
    "get_parent_class": ("Class", "Class"),
    "interface_exists": ("Class", "Class"),
    "trait_exists": ("Class", "Class"),
    # Random
    "rand": ("Math", "Math"),
    "mt_rand": ("Math", "Math"),
    # String
    "str_ireplace": ("String", "String"),
    "strcasecmp": ("String", "String"),
    # Streams
    "fsockopen": ("Streams", "Streams"),
    "pfsockopen": ("Streams", "Streams"),
    "stream_bucket_append": ("Streams", "Streams"),
    "stream_bucket_prepend": ("Streams", "Streams"),
    "stream_filter_append": ("Streams", "Streams"),
    "stream_filter_prepend": ("Streams", "Streams"),
}


# Per-builtin parameter type overrides. The key is the lowercase canonical
# name; the value is a list of types, one per positional parameter, where
# the value `None` means "leave the parsed `mixed` alone".
#
# These are the types the user can rely on. Builtins that accept any value
# stay at `mixed` (so e.g. `strtolower($x)` keeps `mixed $x`, because the
# argument is converted internally regardless of its static type).
# Each entry is either:
#   - a `str` type (e.g. `"string"`) — the param is named `value` (default), or
#   - a 2-tuple `(type, name)` — the param is named explicitly, or
#   - `None` — leave whatever the parser produced alone (skip refinement).
ParamSpec = object  # str | Tuple[str, str] | None — kept loose for legibility
PARAM_TYPES: Dict[str, List[Optional[ParamSpec]]] = {
    # --- String ---
    "strlen": ["string"],
    "strtolower": ["string"],
    "strtoupper": ["string"],
    "ucfirst": ["string"],
    "lcfirst": ["string"],
    "ucwords": ["string", "string"],
    "strrev": ["string"],
    "trim": ["string", "string"],
    "ltrim": ["string", "string"],
    "rtrim": ["string", "string"],
    "chop": ["string", "string"],
    "str_repeat": ["string", "int"],
    "str_pad": ["string", "int", "string", "int"],
    "str_split": ["string", "int"],
    "str_contains": ["string", "string"],
    "str_starts_with": ["string", "string"],
    "str_ends_with": ["string", "string"],
    "substr": ["string", "int", "int"],
    "substr_replace": ["string", "string", "int", "int"],
    "str_replace": ["string", "string", "string", "int"],
    "str_ireplace": ["string", "string", "string", "int"],
    "wordwrap": ["string", "int", "string", "bool"],
    "ord": ["string"],
    "chr": ["int"],
    "crc32": ["string"],
    "md5": ["string", "bool"],
    "sha1": ["string", "bool"],
    "hash": ["string", "string", "bool", "array"],
    "hash_hmac": ["string", "string", "string", "bool"],
    "hash_file": ["string", "string", "bool", "array"],
    "hash_equals": ["string", "string"],
    "hash_update": ["resource", "string"],
    "hash_final": ["resource", "bool"],
    "hash_copy": ["resource"],
    "base64_encode": ["string"],
    "base64_decode": ["string", "bool"],
    "bin2hex": ["string"],
    "hex2bin": ["string"],
    "urlencode": ["string"],
    "urldecode": ["string"],
    "rawurlencode": ["string"],
    "rawurldecode": ["string"],
    "addslashes": ["string"],
    "stripslashes": ["string"],
    "htmlspecialchars": ["string", "int", "string", "bool"],
    "htmlentities": ["string", "int", "string", "bool"],
    "html_entity_decode": ["string", "int", "string"],
    "nl2br": ["string", "bool"],
    "implode": ["string", "array"],
    "explode": ["string", "string", "int"],
    "sprintf": ["string"],
    "printf": ["string"],
    "vsprintf": ["string", "array"],
    "vprintf": ["string", "array"],
    "vfprintf": ["resource", "string", "array"],
    "fprintf": ["resource", "string"],
    "sscanf": ["string", "string"],
    "fscanf": ["resource", "string"],
    "number_format": ["float", "int", "string", "string"],
    "ctype_alpha": ["string"],
    "ctype_digit": ["string"],
    "ctype_alnum": ["string"],
    "ctype_space": ["string"],
    "ctype_upper": ["string"],
    "ctype_lower": ["string"],
    "ctype_cntrl": ["string"],
    "ctype_graph": ["string"],
    "ctype_print": ["string"],
    "ctype_punct": ["string"],
    "ctype_xdigit": ["string"],
    # --- Array ---
    "count": ["array"],
    "sizeof": ["array"],
    "array_keys": ["array", "string", "bool"],
    "array_values": ["array"],
    "array_key_exists": ["string", "array"],
    "array_key_first": ["array"],
    "array_key_last": ["array"],
    "array_search": ["mixed", "array", "bool"],
    "array_unique": ["array", "int"],
    "array_sum": ["array"],
    "array_product": ["array"],
    "array_flip": ["array"],
    "array_reverse": ["array", "bool"],
    "array_change_key_case": ["array", "int"],
    "array_chunk": ["array", "int", "bool"],
    "array_combine": ["array", "array"],
    "array_count_values": ["array"],
    "array_diff": ["array", "array"],
    "array_diff_key": ["array", "array"],
    "array_diff_assoc": ["array", "array"],
    "array_diff_uassoc": ["array", "array", "callable"],
    "array_diff_ukey": ["array", "array", "callable"],
    "array_fill": ["int", "int", "mixed"],
    "array_fill_keys": ["array", "mixed"],
    "array_filter": ["array", "callable", "int"],
    "array_intersect": ["array", "array"],
    "array_intersect_key": ["array", "array"],
    "array_intersect_assoc": ["array", "array"],
    "array_intersect_uassoc": ["array", "array", "callable"],
    "array_intersect_ukey": ["array", "array", "callable"],
    "array_map": ["callable", "array"],
    "array_merge": ["array"],
    "array_merge_recursive": ["array"],
    "array_multisort": ["array", "int"],
    "array_pad": ["array", "int", "mixed"],
    "array_pop": ["array"],
    "array_push": ["array"],
    "array_rand": ["array", "int"],
    "array_reduce": ["array", "callable", "mixed"],
    "array_replace": ["array", "array"],
    "array_replace_recursive": ["array", "array"],
    "array_shift": ["array"],
    "array_slice": ["array", "int", "int", "bool"],
    "array_splice": ["array", "int", "int", "array"],
    "array_udiff": ["array", "array", "callable"],
    "array_udiff_assoc": ["array", "array", "callable"],
    "array_udiff_uassoc": ["array", "array", "callable", "callable"],
    "array_uintersect": ["array", "array", "callable"],
    "array_uintersect_assoc": ["array", "array", "callable"],
    "array_uintersect_uassoc": ["array", "array", "callable", "callable"],
    "array_unshift": ["array"],
    "array_walk": ["array", "callable", ("mixed", "userdata")],
    "array_walk_recursive": ["array", "callable", "mixed"],
    "arsort": ["array", "int"],
    "asort": ["array", "int"],
    "compact": ["string"],
    "current": ["array"],
    "end": ["array"],
    "extract": ["array", "int", "string"],
    "in_array": ["mixed", "array", "bool"],
    "key": ["array"],
    "key_exists": ["string", "array"],
    "krsort": ["array", "int"],
    "ksort": ["array", "int"],
    "list": ["mixed"],
    "natcasesort": ["array"],
    "natsort": ["array"],
    "next": ["array"],
    "pos": ["array"],
    "prev": ["array"],
    "range": ["mixed", "mixed", "int"],
    "reset": ["array"],
    "rsort": ["array", "int"],
    "shuffle": ["array"],
    "sort": ["array", "int"],
    "uasort": ["array", "callable"],
    "uksort": ["array", "callable"],
    "usort": ["array", "callable"],
    "call_user_func": ["callable"],
    "call_user_func_array": ["callable", "array"],
    # --- Math ---
    "abs": ["int"],
    "ceil": ["float"],
    "floor": ["float"],
    "round": ["float", "int"],
    "sqrt": ["float"],
    "pow": ["float", "float"],
    "exp": ["float"],
    "log": ["float", "float"],
    "log10": ["float"],
    "log2": ["float"],
    "sin": ["float"],
    "cos": ["float"],
    "tan": ["float"],
    "asin": ["float"],
    "acos": ["float"],
    "atan": ["float"],
    "atan2": ["float", "float"],
    "sinh": ["float"],
    "cosh": ["float"],
    "tanh": ["float"],
    "deg2rad": ["float"],
    "rad2deg": ["float"],
    "hypot": ["float", "float"],
    "intdiv": ["int", "int"],
    "fdiv": ["float", "float"],
    "fmod": ["float", "float"],
    "min": ["mixed"],
    "max": ["mixed"],
    "rand": ["int", "int"],
    "mt_rand": ["int", "int"],
    "random_int": ["int", "int"],
    "is_nan": ["float"],
    "is_finite": ["float"],
    "is_infinite": ["float"],
    "clamp": ["int", "int", "int"],
    # --- Type predicates ---
    "is_array": ["mixed"],
    "is_bool": ["mixed"],
    "is_callable": ["mixed", "bool"],
    "is_float": ["mixed"],
    "is_int": ["mixed"],
    "is_integer": ["mixed"],
    "is_long": ["mixed"],
    "is_string": ["mixed"],
    "is_object": ["mixed"],
    "is_null": ["mixed"],
    "is_numeric": ["mixed"],
    "is_scalar": ["mixed"],
    "is_iterable": ["mixed"],
    "is_resource": ["mixed"],
    "is_countable": ["mixed"],
    "is_dir": ["string"],
    "is_file": ["string"],
    "is_link": ["string"],
    "is_readable": ["string"],
    "is_writable": ["string"],
    "is_writeable": ["string"],
    "is_executable": ["string"],
    "file_exists": ["string"],
    # --- Casts ---
    "intval": ["mixed", ("int", "base")],
    "floatval": ["mixed"],
    "doubleval": ["mixed"],
    "boolval": ["mixed"],
    "strval": ["mixed"],
    "settype": ["mixed", "string"],
    "gettype": ["mixed"],
    # --- JSON ---
    "json_encode": ["mixed", "int", "int"],
    "json_decode": ["string", "bool", "int", "int"],
    "json_validate": ["string", "int", "int"],
    # --- Regex ---
    "preg_match": ["string", "string", "array"],
    "preg_match_all": ["string", "string", ("array", "matches")],
    "preg_replace": ["string", "string", "string", "int", "int"],
    "preg_replace_callback": ["string", "callable", "string", "int", "int", "int"],
    "preg_split": ["string", "string", "int", "int"],
    "preg_quote": ["string", "string"],
    "preg_grep": ["string", "array", "int"],
    "preg_last_error": [],
    "preg_last_error_msg": [],
    # --- Filesystem ---
    "fopen": ["string", "string", ("bool", "use_include_path"), ("mixed", "context")],
    "fclose": ["resource"],
    "fread": ["resource", "int"],
    "fwrite": ["resource", "string", "int"],
    "fgets": ["resource", "int"],
    "fgetc": ["resource"],
    "feof": ["resource"],
    "fflush": ["resource"],
    "ftell": ["resource"],
    "fseek": ["resource", "int", "int"],
    "rewind": ["resource"],
    "ftruncate": ["resource", "int"],
    "flock": ["resource", "int", "bool"],
    "fstat": ["resource"],
    "fpassthru": ["resource"],
    "fputcsv": ["resource", "array", "string", "string", "string", "string"],
    "fgetcsv": ["resource", "int", "string", "string", "string"],
    "tempnam": ["string", "string"],
    "touch": ["string", "int", "int"],
    "copy": ["string", "string", ("mixed", "context")],
    "rename": ["string", "string", "mixed"],
    "unlink": ["string"],
    "mkdir": ["string", "int", "bool", "bool"],
    "rmdir": ["string", "mixed"],
    "chdir": ["string"],
    "chmod": ["string", "int"],
    "chown": ["string", "mixed"],
    "chgrp": ["string", "mixed"],
    "lchown": ["string", "mixed"],
    "lchgrp": ["string", "mixed"],
    "link": ["string", "string"],
    "symlink": ["string", "string"],
    "readlink": ["string"],
    "linkinfo": ["string"],
    "realpath": ["string"],
    "realpath_cache_size": [],
    "pathinfo": ["string", "int"],
    "dirname": ["string", "int"],
    "basename": ["string", "string"],
    "glob": ["string", "int"],
    "scandir": ["string", "int", "mixed"],
    "stat": ["string"],
    "lstat": ["string"],
    "filesize": ["string"],
    "filemtime": ["string"],
    "filectime": ["string"],
    "fileatime": ["string"],
    "filetype": ["string"],
    "fileperms": ["string"],
    "fileowner": ["string"],
    "filegroup": ["string"],
    "fileinode": ["string"],
    "clearstatcache": ["bool", "string"],
    "disk_free_space": ["string"],
    "disk_total_space": ["string"],
    "readfile": ["string", ("bool", "use_include_path"), ("mixed", "context")],
    "file_get_contents": ["string", ("bool", "use_include_path"), ("mixed", "context"), ("int", "offset"), ("int", "length")],
    "file_put_contents": ["string", "mixed", ("int", "flags"), ("mixed", "context")],
    "file": ["string", ("int", "flags"), ("mixed", "context")],
    # --- Date ---
    "date": ["string", "int"],
    "gmdate": ["string", "int"],
    "mktime": ["int", "int", "int", "int", "int", "int"],
    "gmmktime": ["int", "int", "int", "int", "int", "int"],
    "strtotime": ["string", "int"],
    "checkdate": ["int", "int", "int"],
    "getdate": ["int"],
    "localtime": ["int", "bool"],
    "microtime": ["bool"],
    "hrtime": ["bool"],
    "idate": ["string", "int"],
    "date_default_timezone_set": ["string"],
    "gettimeofday": ["bool"],
    # --- Process ---
    "exec": ["string", "array", "int"],
    "system": ["string", "int"],
    "passthru": ["string", "int"],
    "shell_exec": ["string"],
    "popen": ["string", "string"],
    "pclose": ["resource"],
    "proc_open": ["string", "array", "array", "string", "array", "array"],
    "proc_close": ["resource"],
    "proc_get_status": ["resource"],
    "proc_terminate": ["resource", "int"],
    "proc_nice": ["int"],
    "sleep": ["int"],
    "usleep": ["int"],
    "exit": ["int"],
    "die": ["int"],
    "readline": ["string"],
    # --- Misc ---
    "empty": ["mixed"],
    "isset": ["mixed"],
    "unset": ["mixed"],
    "print_r": ["mixed", ("bool", "return")],
    "var_dump": ["mixed"],
    "var_export": ["mixed", "bool"],
    "define": ["string", "mixed", ("bool", "case_insensitive")],
    "defined": ["string"],
    "constant": ["string"],
    "sprintf": ["string"],
    "printf": ["string"],
    "vprintf": ["string", "array"],
    "vsprintf": ["string", "array"],
    "vfprintf": ["resource", "string", "array"],
    "fprintf": ["resource", "string"],
    "getenv": ["string", "bool"],
    "putenv": ["string"],
    "getopt": ["string", "array"],
    "getrusage": ["int"],
    "memory_get_usage": ["bool"],
    "memory_get_peak_usage": ["bool"],
    "php_uname": ["string"],
    "php_sapi_name": [],
    "phpversion": ["string"],
    "phpinfo": ["int"],
    "getmypid": [],
    "getmyuid": [],
    "getmygid": [],
    "getmyinode": [],
    "get_current_user": [],
    "chroot": ["string"],
    "get_loaded_extensions": ["bool"],
    "get_extension_funcs": ["string"],
    "get_defined_functions": ["bool"],
    "get_defined_vars": [],
    "get_defined_constants": ["bool"],
    "get_included_files": [],
    "get_required_files": [],
    "assert": ["mixed", "string"],
    # --- Class / object introspection (round 2) ---
    "class_alias": ["string", "string", "bool"],
    "class_exists": ["string", "bool"],
    "class_implements": [("mixed", "object_or_class"), "bool"],
    "class_parents": [("mixed", "object_or_class"), "bool"],
    "class_uses": [("mixed", "object_or_class"), "bool"],
    "interface_exists": ["string", "bool"],
    "trait_exists": ["string", "bool"],
    "enum_exists": ["string", "bool"],
    "get_class": ["object"],
    "get_parent_class": [("mixed", "object_or_class")],
    "function_exists": ["string"],
    "is_a": ["mixed", "string", "bool"],
    "is_subclass_of": ["mixed", "string", "bool"],
    "get_resource_id": ["resource"],
    "get_resource_type": ["resource"],
    # --- Network / DNS ---
    "gethostbyname": ["string"],
    "gethostbyaddr": ["string"],
    "getprotobyname": ["string"],
    "getprotobynumber": ["int"],
    "getservbyname": ["string", "string"],
    "getservbyport": ["int", "string"],
    "ip2long": ["string"],
    "long2ip": ["int"],
    "inet_ntop": ["string"],
    "inet_pton": ["string"],
    # --- Filesystem (round 2) ---
    "fnmatch": ["string", "string", "int"],
    "opendir": ["string"],
    "closedir": ["resource"],
    "readdir": ["resource"],
    "rewinddir": ["resource"],
    "fdatasync": ["resource"],
    "fsync": ["resource"],
    "fsockopen": ["string", "int", "int", "string", "float"],
    "pfsockopen": ["string", "int", "int", "string", "float"],
    # --- Hash (round 2) ---
    "hash_init": ["string", "int", "string", "array"],
    # --- Compression ---
    "gzcompress": ["string", "int", "int"],
    "gzdeflate": ["string", "int", "int"],
    "gzinflate": ["string", "int"],
    "gzuncompress": ["string", "int"],
    # --- Iterators ---
    "iterator_apply": ["traversable", "callable", "array"],
    "iterator_count": ["traversable"],
    "iterator_to_array": ["traversable", "bool"],
    # --- Array (round 2) ---
    "array_column": ["array", "string", "string"],
    "compact": ["string"],
    "extract": ["array", "int", "string"],
    "list": ["mixed"],
    # --- Buffers (Elephc extension) ---
    "buffer_new": ["int"],
    "buffer_free": ["buffer"],
    # --- Image (Elephc extension) ---
    "imagecreate": ["int", "int"],
    "imagecreatetruecolor": ["int", "int"],
    "imagecolorallocate": ["resource", "int", "int", "int"],
    "imagefill": ["resource", "int", "int", "int"],
    "imagedestroy": ["resource"],
    "imagepng": ["resource", "string"],
    "imagejpeg": ["resource", "string", "int"],
    "imagegif": ["resource", "string"],
    "imagewbmp": ["resource", "string"],
    "imagesx": ["resource"],
    "imagesy": ["resource"],
    "imagecolorat": ["resource", "int", "int"],
    "imagecolorset": ["resource", "int", "int", "int", "int"],
    "imagecolorsforindex": ["resource", "int"],
    "imagecolorstotal": ["resource"],
    "imagecolortransparent": ["resource", "int"],
    "imagecopy": ["resource", "resource", "int", "int", "int", "int", "int", "int"],
    "imagecopymerge": ["resource", "resource", "int", "int", "int", "int", "int", "int"],
    "imagecreatefrompng": ["string"],
    "imagecreatefromjpeg": ["string"],
    "imagecreatefromgif": ["string"],
    "imagecreatefromstring": ["string"],
    "imagefilledrectangle": ["resource", "int", "int", "int", "int", "int"],
    "imagefilledellipse": ["resource", "int", "int", "int", "int", "int"],
    "imagefilledpolygon": ["resource", "array", "int"],
    "imagepolygon": ["resource", "array", "int"],
    "imagestring": ["resource", "int", "int", "int", "string", "int"],
    "imagettftext": ["resource", "float", "float", "int", "int", "int", "string", "string"],
    "imageline": ["resource", "int", "int", "int", "int", "int"],
    "imageellipse": ["resource", "int", "int", "int", "int", "int"],
    "imagerectangle": ["resource", "int", "int", "int", "int", "int"],
    "imagesetpixel": ["resource", "int", "int", "int"],
    "imagefontwidth": ["int"],
    "imagefontheight": ["int"],
    "imageloadfont": ["string"],
    "imagecolorclosest": ["resource", "int", "int", "int"],
    "imagecolordeallocate": ["resource", "int"],
    "imagecolorresolve": ["resource", "int", "int", "int"],
    "imagecolorsforindex": ["resource", "int"],
    # --- PDO ---
    "pdo": ["string", "string", "string", "array"],
    # --- Streams (round 2) ---
    "stream_socket_server": ["string", "int", "int"],
    "stream_socket_client": ["string", "int", "int", "string", "float"],
    "stream_socket_accept": ["resource", "float", "string"],
    "stream_socket_enable_crypto": ["resource", "bool", "int", "resource"],
    "stream_socket_shutdown": ["resource", "int"],
    "stream_socket_sendto": ["resource", "string", "int", "string"],
    "stream_socket_recvfrom": ["resource", "int", "int", "string"],
    "stream_socket_get_name": ["resource", "bool"],
    "stream_socket_pair": ["int", "int", "int"],
    "stream_set_blocking": ["resource", "bool"],
    "stream_set_timeout": ["resource", "int", "int"],
    "stream_set_chunk_size": ["resource", "int"],
    "stream_set_read_buffer": ["resource", "int"],
    "stream_set_write_buffer": ["resource", "int"],
    "stream_select": ["array", "array", "array", "int", "int"],
    "stream_resolve_include_path": ["string"],
    "stream_supports_lock": ["resource"],
    "stream_is_local": ["resource"],
    "stream_get_contents": ["resource", "int", "int"],
    "stream_get_line": ["resource", "int", "string"],
    "stream_get_meta_data": ["resource"],
    "stream_copy_to_stream": ["resource", "resource", "int", "int"],
    "stream_filter_append": ["resource", "string", "int", "mixed"],
    "stream_filter_prepend": ["resource", "string", "int", "mixed"],
    "stream_filter_remove": ["resource"],
    "stream_bucket_append": ["mixed", "mixed"],
    "stream_bucket_prepend": ["mixed", "mixed"],
    "stream_bucket_make_writeable": ["mixed"],
    "stream_bucket_new": ["resource", "string"],
    "stream_wrapper_register": ["string", "string", "int"],
    "stream_wrapper_unregister": ["string"],
    "stream_wrapper_restore": ["string"],
    "stream_get_transports": [],
    "stream_get_wrappers": [],
    "stream_get_filters": [],
    "stream_register_wrapper": ["string", "string", "int"],
    "stream_isatty": ["resource"],
    "stream_notification_callback": ["resource", "int", "callable", "int", "int", "bool", "mixed"],
    "stream_context_create": ["array", "array"],
    "stream_context_get_default": ["array"],
    "stream_context_set_default": ["array"],
    "stream_context_get_options": ["resource"],
    "stream_context_get_params": ["resource"],
    "stream_context_set_params": ["resource", "array"],
    "stream_context_set_option": ["resource", "string", "string", "mixed"],
    "stream_context_get_option": ["resource", "string", "string"],
    # --- SPL ---
    "class_implements": [("mixed", "object_or_class"), "bool"],
    "class_parents": [("mixed", "object_or_class"), "bool"],
    "class_uses": [("mixed", "object_or_class"), "bool"],
    "iterator_apply": ["traversable", "callable", "array"],
    "iterator_count": ["traversable"],
    "iterator_to_array": ["traversable", "bool"],
    "spl_object_id": ["object"],
    "spl_object_hash": ["object"],
    "spl_autoload": ["string", "string"],
    "spl_autoload_register": ["callable", "bool", "bool"],
    "spl_autoload_unregister": ["callable"],
    "spl_autoload_functions": [],
    "spl_autoload_call": ["string"],
    "spl_classes": [],
    # --- Date (round 2) ---
    "date_create": ["string", "string"],
    "date_create_from_format": ["string", "string", "string"],
    "date_format": ["object", "string"],
    "date_modify": ["object", "string"],
    "date_add": ["object", "object"],
    "date_sub": ["object", "object"],
    "date_diff": ["object", "object", "bool"],
    "date_format": ["object", "string"],
    "date_get_timestamp": ["object"],
    "date_timestamp_set": ["object", "int"],
    "date_create_immutable": ["string", "string"],
    "date_create_immutable_from_format": ["string", "string", "string"],
    "date_isodate_set": ["object", "int", "int"],
    "date_set": ["object", "int", "int", "int", "int", "int"],
    "date_sunrise": ["string", "int"],
    "date_sunset": ["string", "int"],
    "date_time_set": ["object", "int", "int", "int"],
    "date_timezone_get": ["object"],
    "date_timezone_set": ["object", "string"],
    "date_offset_get": ["object"],
    "date_format": ["object", "string"],
    "date_parse": ["string"],
    "date_parse_from_format": ["string", "string"],
    "date_sun_info": ["int", "int"],
    # --- Process (round 2) ---
    "proc_open": ["string", "array", "array", "string", "array", "array"],
    "proc_close": ["resource"],
    "proc_get_status": ["resource"],
    "proc_terminate": ["resource", "int"],
    "proc_nice": ["int"],
    "readline": ["string"],
    "readline_add_history": ["string"],
    "readline_clear_history": [],
    "readline_list_history": [],
    "readline_read_history": ["string"],
    "readline_write_history": ["string"],
    "readline_completion_function": ["callable"],
    "readline_info": ["string", "string"],
    "readline_interaction_handler_install": ["string", "callable"],
    "readline_interaction_handler_remove": ["string"],
    "readline_callback_handler_install": ["string", "callable"],
    "readline_callback_handler_remove": [],
    "readline_redisplay": [],
    "readline_on_new_line": [],
    # --- Misc (round 2) ---
    "compact": ["string"],
    "extract": ["array", "int", "string"],
    "assert": ["mixed", "string"],
    "cli_set_process_title": ["string"],
    "cli_get_process_title": [],
    "getopt": ["string", "array"],
    "getenv": ["string", "bool"],
    "putenv": ["string"],
    "memory_get_usage": ["bool"],
    "memory_get_peak_usage": ["bool"],
    "php_sapi_name": [],
    "php_uname": ["string"],
    "phpinfo": ["int"],
    "phpcredits": ["int", "string"],
    "getmypid": [],
    "getmyuid": [],
    "getmygid": [],
    "getmyinode": [],
    "get_current_user": [],
    "getmyhn": [],
    "php_ini_scanned_files": [],
    "get_cfg_var": ["string"],
    "getenv": ["string", "bool"],
    "putenv": ["string"],
    "get_include_path": [],
    "set_include_path": ["string"],
    "restore_include_path": [],
    "ini_get": ["string"],
    "ini_set": ["string", "string"],
    "ini_restore": ["string"],
    "ini_get_all": ["string", "bool"],
    "ini_alter": ["string", "string"],
    "error_reporting": ["int"],
    "error_log": ["string", "int", "string", "string"],
    "error_get_last": [],
    "set_error_handler": ["callable", "int"],
    "restore_error_handler": [],
    "set_exception_handler": ["callable"],
    "restore_exception_handler": [],
    "trigger_error": ["string", "int"],
    "user_error": ["string", "int"],
    "debug_backtrace": ["int", "int"],
    "debug_print_backtrace": ["int", "int"],
    "error_clear_last": [],
    "constant": ["string"],
    "defined": ["string"],
    "define": ["string", "mixed", ("bool", "case_insensitive")],
    # --- String (round 3) ---
    "strpos": ["string", "string", "int"],
    "strrpos": ["string", "string", "int"],
    "strstr": ["string", "string", "bool"],
    "strpbrk": ["string", "string"],
    "strcmp": ["string", "string"],
    "strcasecmp": ["string", "string"],
    "strnatcmp": ["string", "string"],
    "strnatcasecmp": ["string", "string"],
    "strncasecmp": ["string", "string", "int"],
    "strncmp": ["string", "string", "int"],
    "substr_count": ["string", "string"],
    "substr_compare": ["string", "string", "int", "int"],
    "similar_text": ["string", "string", "float"],
    "soundex": ["string"],
    "levenshtein": ["string", "string", "int", "int"],
    "metaphone": ["string", "int"],
    "str_word_count": ["string", "int", "string"],
    "parse_str": ["string", "array"],
    "setlocale": ["int", "string"],
    "localeconv": [],
    # --- Pointer / buffer (Elephc extension) ---
    "ptr": ["mixed"],
    "ptr_is_null": ["pointer"],
    "ptr_get": ["pointer"],
    "ptr_set": ["pointer", "mixed"],
    "ptr_offset": ["pointer", "int"],
    "ptr_sizeof": ["string"],
    "ptr_read8": ["pointer"],
    "ptr_read16": ["pointer"],
    "ptr_read32": ["pointer"],
    "ptr_read_string": ["pointer", "int"],
    "ptr_write8": ["pointer", "int"],
    "ptr_write16": ["pointer", "int"],
    "ptr_write32": ["pointer", "int"],
    "ptr_write_string": ["pointer", "string"],
    "buffer_new": ["int"],
    "buffer_free": ["buffer"],
    "buffer_len": ["buffer"],
    # --- SPL (round 2) ---
    "spl_autoload_extensions": ["string"],
    # --- IO (round 3) ---
    "stream_filter_register": ["string", "string"],
    "stream_filter_remove": ["resource"],
    "stream_filter_append": ["resource", "string", "int", "mixed"],
    "stream_filter_prepend": ["resource", "string", "int", "mixed"],
    "stream_bucket_make_writeable": ["mixed"],
    "stream_bucket_new": ["resource", "string"],
    "stream_bucket_append": ["mixed", "mixed"],
    "stream_bucket_prepend": ["mixed", "mixed"],
    # --- Filesystem (round 3) ---
    "umask": ["int"],
    # --- Internal (compiler helpers) ---
    "__elephc_mktime_raw": ["int", "int", "int", "int", "int", "int"],
    "__elephc_gmmktime_raw": ["int", "int", "int", "int", "int", "int"],
    "__elephc_strtotime_raw": ["string", "int"],
    # --- Single-param stubs (round 4: extend PARAM_TYPES to also cover
    # signatures that signatures.rs left as `…` so the guard applies) ---
    "abs": ["int"],  # or float; int is the common case
    "acos": ["float"],
    "asin": ["float"],
    "atan": ["float"],
    "atan2": ["float", "float"],
    "ceil": ["float"],
    "cos": ["float"],
    "cosh": ["float"],
    "deg2rad": ["float"],
    "exp": ["float"],
    "floor": ["float"],
    "log2": ["float"],
    "log10": ["float"],
    "pow": ["float", "float"],
    "rad2deg": ["float"],
    "round": ["float", "int"],
    "sin": ["float"],
    "sinh": ["float"],
    "sqrt": ["float"],
    "tan": ["float"],
    "tanh": ["float"],
    "array_combine": ["array", "array"],
    "array_diff": ["array", "array"],
    "array_diff_key": ["array", "array"],
    "array_intersect": ["array", "array"],
    "array_intersect_key": ["array", "array"],
    "array_merge": ["array"],
    "array_merge_recursive": ["array"],
    "array_push": ["array", "mixed"],
    "array_replace": ["array", "array"],
    "array_replace_recursive": ["array", "array"],
    "array_search": ["mixed", "array", "bool"],
    "array_udiff": ["array", "array", "callable"],
    "array_uintersect": ["array", "array", "callable"],
    "array_unshift": ["array", "mixed"],
    "array_walk": ["array", "callable", ("mixed", "userdata")],
    "array_walk_recursive": ["array", "callable", "mixed"],
    "uasort": ["array", "callable"],
    "uksort": ["array", "callable"],
    "usort": ["array", "callable"],
    "boolval": ["mixed"],
    "call_user_func": ["callable", "mixed"],
    "count": ["array", "int"],
    "sizeof": ["array"],
    "empty": ["mixed"],
    "floatval": ["mixed"],
    "intval": ["mixed", ("int", "base")],
    "is_a": ["object", "string", "bool"],
    "is_array": ["mixed"],
    "is_bool": ["mixed"],
    "is_callable": ["mixed", "bool", "string"],
    "is_countable": ["mixed"],
    "is_finite": ["float"],
    "is_float": ["mixed"],
    "is_infinite": ["float"],
    "is_int": ["mixed"],
    "is_integer": ["mixed"],
    "is_iterable": ["mixed"],
    "is_long": ["mixed"],
    "is_nan": ["float"],
    "is_null": ["mixed"],
    "is_numeric": ["mixed"],
    "is_object": ["mixed"],
    "is_resource": ["mixed"],
    "is_scalar": ["mixed"],
    "is_string": ["mixed"],
    "isset": ["mixed"],
    "settype": ["mixed", "string"],
    "gettype": ["mixed"],
    "ctype_alnum": ["string"],
    "ctype_alpha": ["string"],
    "ctype_cntrl": ["string"],
    "ctype_digit": ["string"],
    "ctype_graph": ["string"],
    "ctype_lower": ["string"],
    "ctype_print": ["string"],
    "ctype_punct": ["string"],
    "ctype_space": ["string"],
    "ctype_upper": ["string"],
    "ctype_xdigit": ["string"],
    "date_default_timezone_set": ["string"],
    "gmdate": ["string", "int"],
    "gmmktime": ["int", "int", "int", "int", "int", "int"],
    "hrtime": ["bool"],
    "localtime": ["int", "bool"],
    "microtime": ["bool"],
    "mktime": ["int", "int", "int", "int", "int", "int"],
    "strtotime": ["string", "int"],
    "function_exists": ["string"],
    "realpath_cache_size": [],
    "readfile": ["string", ("bool", "use_include_path"), ("mixed", "context")],
    "flock": ["resource", "int", "bool"],
    "fsockopen": ["string", "int", "int", "string", "float"],
    "pfsockopen": ["string", "int", "int", "string", "float"],
    "hash_equals": ["string", "string"],
    "str_contains": ["string", "string"],
    "str_ends_with": ["string", "string"],
    "str_starts_with": ["string", "string"],
    "str_ireplace": ["mixed", "mixed", "mixed", "int"],
    "preg_match": ["string", "string", "array"],
    "preg_match_all": ["string", "string", ("array", "matches")],
    "print_r": ["mixed", ("bool", "return")],
    "var_dump": ["mixed"],
    "var_export": ["mixed", "bool"],
    "spl_autoload_call": ["string"],
    "spl_autoload_extensions": ["string"],
    "spl_autoload_functions": [],
    "spl_classes": [],
    "stream_context_get_default": ["array"],
    "stream_context_set_default": ["array"],
    "stream_filter_append": ["resource", "string", "int", "mixed"],
    "stream_filter_prepend": ["resource", "string", "int", "mixed"],
    "stream_get_contents": ["resource", "int", "int"],
    "stream_get_filters": [],
    "stream_get_transports": [],
    "stream_get_wrappers": [],
    "stream_is_local": ["resource"],
    "stream_isatty": ["resource"],
    "stream_select": ["array", "array", "array", "int", "int"],
    "stream_set_blocking": ["resource", "bool"],
    "stream_socket_accept": ["resource", "float", "string"],
    "stream_socket_get_name": ["resource", "bool"],
    "stream_socket_recvfrom": ["resource", "int", "int", "string"],
    "stream_supports_lock": ["resource"],
    "stream_wrapper_register": ["string", "string", "int"],
    "ptr": ["mixed"],
    "ptr_get": ["pointer"],
    "ptr_set": ["pointer", "mixed"],
    "ptr_is_null": ["pointer"],
    "ptr_read8": ["pointer"],
    "ptr_read16": ["pointer"],
    "ptr_read32": ["pointer"],
    "ptr_read_string": ["pointer", "int"],
    "ptr_write8": ["pointer", "int"],
    "ptr_write16": ["pointer", "int"],
    "ptr_write32": ["pointer", "int"],
    "ptr_write_string": ["pointer", "string"],
}


@dataclass
class Parameter:
    """A single positional parameter of a builtin signature."""

    name: str
    php_type: str  # displayed type, e.g. "string", "int", "mixed", "array"
    by_ref: bool = False
    default: Optional[str] = None  # rendered as PHP literal, e.g. "true", "0", "''"
    optional: bool = False


@dataclass
class BuiltinSig:
    """Resolved call signature for a builtin (parameters + return type)."""

    params: List[Parameter] = field(default_factory=list)
    variadic: Optional[str] = None  # name of the variadic parameter, if any
    return_type: str = "mixed"  # PHP-style rendered type
    return_is_intersect: bool = False  # whether the return is conditional (e.g. abs preserves type)


@dataclass
class LoweringInfo:
    """Where the builtin is implemented in the compiler source."""

    sig_file: Optional[str] = None
    sig_line: Optional[int] = None
    sig_arm: Optional[str] = None  # e.g. "\"strlen\" => Some(fixed(&[\"string\"]))"
    checker_file: Optional[str] = None
    checker_line: Optional[int] = None
    codegen_file: Optional[str] = None
    codegen_line: Optional[int] = None
    codegen_function: Optional[str] = None  # e.g. "lower_strlen"
    runtime_helpers: List[str] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)  # pulled from the /// doc comment of the lowering fn


@dataclass
class Builtin:
    """A single PHP builtin known to the Elephc compiler."""

    name: str
    area: str
    sub_area: str
    canonical_name: str  # always lowercase
    in_catalog: bool  # present in SUPPORTED_BUILTIN_FUNCTIONS
    is_internal: bool  # compiler-only helper with no user-facing page
    sig: BuiltinSig = field(default_factory=BuiltinSig)
    lowering: LoweringInfo = field(default_factory=LoweringInfo)
    description: str = ""  # filled by hand, or left empty for the stub
    examples: List[str] = field(default_factory=list)  # raw ```php ... ``` blocks
    see_also: List[str] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)


def slug(name: str) -> str:
    """Filename-safe slug for a builtin name."""
    return name.replace("\\", "-").replace("::", "-")


# Hand-curated return-type overrides. These win over anything parsed from
# `check_builtin()` arms (which sometimes narrow to the wrong type, e.g.
# `array_shift` returns `mixed`, not the array element type).
RETURN_TYPE_OVERRIDES: Dict[str, str] = {
    # array_shift / array_pop return the shifted element which is `mixed`
    # in PHP's loose type system.
    "array_shift": "mixed",
    "array_pop": "mixed",
    "current": "mixed",
    "end": "mixed",
    "next": "mixed",
    "prev": "mixed",
    "reset": "mixed",
    # in_array returns the value if found, false otherwise → mixed.
    "in_array": "mixed",
    # String functions with a concrete string return type.
    "addslashes": "string",
    "bin2hex": "string",
    "chr": "string",
    "lcfirst": "string",
    "nl2br": "string",
    "stripslashes": "string",
    "strrev": "string",
    "strtolower": "string",
    "strtoupper": "string",
    "ucfirst": "string",
    "ucwords": "string",
    "str_repeat": "string",
    # Array functions with a concrete array return type.
    "array_combine": "array",
    "array_diff_key": "array",
    "array_fill_keys": "array",
    "array_intersect_key": "array",
    "array_merge": "array",
    "array_reverse": "array",
    "array_splice": "array",
    "array_unique": "array",
    "getdate": "array",
    "localtime": "array",
    "realpath_cache_get": "array",
    "stream_context_get_options": "array",
    "stream_context_get_params": "array",
    "stream_get_meta_data": "array",
    "iterator_to_array": "array",
    # Sorting/array mutating functions that return true on success.
    "arsort": "bool",
    "asort": "bool",
    "krsort": "bool",
    "ksort": "bool",
    "rsort": "bool",
    "shuffle": "bool",
    "sort": "bool",
    "natcasesort": "bool",
    "natsort": "bool",
    "uasort": "bool",
    "uksort": "bool",
    "usort": "bool",
    # Other concrete return types confirmed by PHP reflection.
    "class_alias": "bool",
    "define": "bool",
    "touch": "bool",
    "fseek": "int",
    "vprintf": "int",
    "vsprintf": "string",
    "iterator_apply": "int",
}


# Hand-curated by-reference parameter overrides. signatures.rs does not always
# mark parameters that PHP passes by reference; these overrides make the
# generated docs match the actual PHP calling convention.
REF_PARAM_OVERRIDES: Dict[str, List[bool]] = {
    "exec": [False, True, True],
    "is_callable": [False, False, True],
    "passthru": [False, True],
    "preg_match_all": [False, False, True],
    "preg_replace": [False, False, False, False, True],
    "preg_replace_callback": [False, False, False, False, True, False],
    "str_ireplace": [False, False, False, True],
    "str_replace": [False, False, False, True],
    "system": [False, True],
    "stream_socket_client": [False, True, True, False, False],
    "stream_socket_server": [False, True, True],
}


# Hand-curated optional-parameter overrides. Each entry is a list parallel to
# the parameter list: None = required, string = optional with that PHP default.
OPTIONAL_PARAM_OVERRIDES: Dict[str, List[Optional[str]]] = {
    "file_put_contents": [None, None, "0", "null"],
    "fputcsv": [None, None, "','", "'\"'", "'\\\\'", "'\\n'"],
    "hash": [None, None, "false", "[]"],
    "hash_file": [None, None, "false", "[]"],
    "hash_init": [None, "0", "''", "[]"],
    "is_callable": [None, "false", "null"],
    "phpversion": ["null"],
    "preg_replace": [None, None, None, "-1", "null"],
    "preg_replace_callback": [None, None, None, "-1", "null", "0"],
    "print_r": [None, "false"],
    "rmdir": [None, "null"],
}


# Hand-curated parameter-name overrides. signatures.rs sometimes uses generic
# names like `value`; these match the PHP manual names.
PARAM_NAME_OVERRIDES: Dict[str, List[Optional[str]]] = {
    "array_chunk": [None, None, "preserve_keys"],
    "array_column": [None, None, "index_key"],
    "array_keys": [None, "filter_value", "strict"],
    "array_rand": [None, "num"],
    "array_reverse": [None, "preserve_keys"],
    "array_slice": [None, None, None, "preserve_keys"],
    "array_splice": [None, None, None, "replacement"],
    "array_unique": [None, "flags"],
    "array_walk": [None, None, "arg"],
    "arsort": [None, "flags"],
    "asort": [None, "flags"],
    "base64_decode": [None, "strict"],
    "exec": [None, "output", "result_code"],
    "fgetcsv": [None, None, None, "enclosure", "escape"],
    "fgets": [None, "length"],
    "fwrite": [None, None, "length"],
    "getenv": [None, "local_only"],
    "glob": [None, "flags"],
    "html_entity_decode": [None, "flags", "encoding"],
    "htmlentities": [None, "flags", "encoding", "double_encode"],
    "htmlspecialchars": [None, "flags", "encoding", "double_encode"],
    "is_callable": [None, "syntax_only"],
    "krsort": [None, "flags"],
    "ksort": [None, "flags"],
    "mkdir": [None, "permissions", "recursive", "context"],
    "nl2br": [None, "use_xhtml"],
    "passthru": [None, "result_code"],
    "preg_replace": [None, None, None, "limit"],
    "preg_replace_callback": [None, None, None, "limit"],
    "range": [None, None, "step"],
    "rename": [None, None, "context"],
    "rsort": [None, "flags"],
    "scandir": [None, "sorting_order", "context"],
    "sort": [None, "flags"],
    "stream_context_get_options": ["stream_or_context"],
    "stream_filter_append": [None, "filter_name", "mode"],
    "stream_filter_prepend": [None, "filter_name", "mode"],
    "stream_socket_client": [None, "error_code", "error_message", "timeout", "flags"],
    "stream_socket_server": [None, "error_code", "error_message"],
    "system": [None, "result_code"],
    "fputcsv": [None, None, None, None, "escape", "eol"],
    "gzcompress": [None, None, "encoding"],
    "gzdeflate": [None, None, "encoding"],
    "hash": [None, None, None, "options"],
    "hash_file": [None, None, None, "options"],
    "hash_init": [None, None, None, "options"],
    "is_callable": [None, "syntax_only", "callable_name"],
    "phpversion": ["extension"],
    "preg_replace": [None, None, None, "limit", "count"],
    "preg_replace_callback": [None, None, None, "limit", "count", "flags"],
    "rmdir": [None, "context"],
}


# Hand-curated one-line descriptions for the user-facing pages. When a
# builtin has no override here, the renderer falls back to the first line of
# the lowering function's `///` doc comment, if available.
DESCRIPTION_OVERRIDES: Dict[str, str] = {
    "class_exists": "Checks whether the given class has been defined.",
    "define": "Defines a named constant at runtime.",
    "defined": "Checks whether a given named constant exists.",
    "empty": "Determines whether a variable is considered empty.",
    "isset": "Determines whether a variable is set and is not null.",
    "unset": "Unsets the given variables.",
    "print_r": "Prints human-readable information about a variable.",
    "var_dump": "Dumps information about a variable, including its type and value.",
    "var_export": "Outputs or returns a parsable string representation of a variable.",
    "phpversion": "Returns the current PHP version information.",
    "php_uname": "Returns information about the operating system PHP is running on.",
}


# Notes for compiler-internal helpers. These appear on the internals pages for
# the __elephc_* builtins that have no user-facing reference.
INTERNAL_NOTES: Dict[str, List[str]] = {
    "__elephc_mktime_raw": [
        "Internal helper used by the mktime() builtin.",
        "Bypasses timezone handling and calls the runtime mktime helper directly.",
    ],
    "__elephc_gmmktime_raw": [
        "Internal helper used by the gmmktime() builtin.",
        "Bypasses timezone handling and calls the runtime gmmktime helper directly.",
    ],
    "__elephc_strtotime_raw": [
        "Internal helper used by the strtotime() builtin.",
        "Provides a raw timestamp parsing path for the runtime strtotime helper.",
    ],
    "__elephc_phar_list_entries": [
        "Internal helper used by the built-in Phar / PharData support to enumerate archive entries.",
        "Calls the native PHAR listing bridge and returns the entries as an array.",
    ],
    "__elephc_phar_set_compression": [
        "Internal helper used by the built-in Phar / PharData support to change archive compression.",
        "Calls the native PHAR compression-control bridge and returns whether the update succeeded.",
    ],
}


# Hand-curated variadic overrides. signatures.rs says `fixed(&["value"])`
# for these but PHP actually accepts any number of arguments.
# Note: printf/sprintf/fprintf are already variadic in signatures.rs,
# so they do not need an override.
VARIADIC_OVERRIDES: Dict[str, str] = {
    "var_dump": "values",
    "print_r": "values",
}
