//! Purpose:
//! Per-builtin string, hash, encoding, compression, and stream-introspection eval
//! builtins.
//!
//! Called from:
//! - `crate::interpreter::builtins` module loading and re-exports.
//!
//! Key details:
//! - Leaf files register metadata through `eval_builtin!` and own the matching
//!   eval implementation or delegate to the closest builtin owner for shared code.

mod addslashes;
mod base64_decode;
mod base64_encode;
mod bin2hex;
mod chop;
mod chr;
mod chunk_split;
mod count_chars;
mod crc32;
mod ctype_alnum;
mod ctype_alpha;
mod ctype_digit;
mod ctype_space;
mod explode;
mod grapheme_strrev;
mod gzcompress;
mod gzdeflate;
mod gzinflate;
mod gzuncompress;
mod hash;
mod hash_algos;
mod hash_copy;
mod hash_equals;
mod hash_file;
mod hash_final;
mod hash_hmac;
mod hash_init;
mod hash_update;
mod hex2bin;
mod html_entity_decode;
mod htmlentities;
mod htmlspecialchars;
mod iconv;
mod iconv_get_encoding;
mod iconv_mime_decode;
mod iconv_mime_decode_headers;
mod iconv_mime_encode;
mod iconv_set_encoding;
mod iconv_strlen;
mod iconv_strpos;
mod iconv_strrpos;
mod iconv_substr;
mod implode;
mod lcfirst;
mod ltrim;
mod mb_strwidth;
mod mb_strtoupper;
mod mb_strtolower;
mod mb_convert_case;
mod mb_ucfirst;
mod mb_lcfirst;
mod mb_strimwidth;
mod mb_substr;
mod mb_strcut;
mod mb_scrub;
mod mb_trim;
mod mb_ltrim;
mod mb_rtrim;
mod mb_str_pad;
mod mb_convert_kana;
mod mb_substr_count;
mod mb_ord;
mod mb_chr;
mod mb_strpos;
mod mb_stripos;
mod mb_strrpos;
mod mb_strripos;
mod mb_strstr;
mod mb_stristr;
mod mb_strrchr;
mod mb_strrichr;
mod mb_language;
mod mb_internal_encoding;
mod mb_http_output;
mod mb_encoding_aliases;
mod mb_list_encodings;
mod mb_detect_order;
mod mb_detect_encoding;
mod mb_convert_encoding;
mod mb_encode_numericentity;
mod mb_decode_numericentity;
mod mb_decode_mimeheader;
mod mb_encode_mimeheader;
mod mb_get_info;
mod shared_ini;
mod mb_http_input;
mod mb_regex_encoding;
mod mb_regex_set_options;
mod mb_ereg_match;
mod mb_ereg;
mod mb_parse_str;
mod mb_output_handler;
mod mb_eregi;
mod mb_ereg_search_init;
mod mb_ereg_search;
mod mb_ereg_search_pos;
mod mb_ereg_search_regs;
mod mb_ereg_search_getpos;
mod mb_ereg_search_getregs;
mod mb_ereg_search_setpos;
mod mb_split;
mod mb_ereg_replace;
mod mb_ereg_replace_callback;
mod mb_eregi_replace;
mod mb_str_split;
mod mb_preferred_mime_name;
mod mb_check_encoding;
mod mb_substitute_character;
mod mb_strlen;
mod md5;
mod nl2br;
mod ord;
mod openssl_cipher_iv_length;
mod openssl_decrypt;
mod openssl_encrypt;
mod openssl_get_cipher_methods;
mod parse_url;
mod quoted_printable_encode;
mod quotemeta;
mod rawurldecode;
mod rawurlencode;
mod rtrim;
mod sha1;
mod str_contains;
mod str_ends_with;
mod str_ireplace;
mod str_pad;
mod str_repeat;
mod str_replace;
mod str_split;
mod str_starts_with;
mod str_word_count;
mod strcasecmp;
mod strcmp;
mod stream_get_filters;
mod stream_get_transports;
mod stream_get_wrappers;
mod stream_is_local;
mod stream_supports_lock;
mod stripslashes;
mod strlen;
mod stripos;
mod strpos;
mod strrev;
mod strripos;
mod strrpos;
mod strstr;
mod strtolower;
mod strtr;
mod strtoupper;
mod substr;
mod substr_replace;
mod trim;
mod ucfirst;
mod ucwords;
mod urldecode;
mod urlencode;
mod wordwrap;

pub(in crate::interpreter) use addslashes::*;
pub(in crate::interpreter) use base64_decode::*;
pub(in crate::interpreter) use base64_encode::*;
pub(in crate::interpreter) use bin2hex::*;
pub(in crate::interpreter) use chop::*;
pub(in crate::interpreter) use chr::*;
pub(in crate::interpreter) use chunk_split::*;
pub(in crate::interpreter) use count_chars::*;
pub(in crate::interpreter) use crc32::*;
pub(in crate::interpreter) use ctype_alnum::*;
pub(in crate::interpreter) use ctype_alpha::*;
pub(in crate::interpreter) use ctype_digit::*;
pub(in crate::interpreter) use ctype_space::*;
pub(in crate::interpreter) use explode::*;
pub(in crate::interpreter) use grapheme_strrev::*;
pub(in crate::interpreter) use gzcompress::*;
pub(in crate::interpreter) use gzdeflate::*;
pub(in crate::interpreter) use gzinflate::*;
pub(in crate::interpreter) use gzuncompress::*;
pub(in crate::interpreter) use hash::*;
pub(in crate::interpreter) use hash_algos::*;
pub(in crate::interpreter) use hash_copy::*;
pub(in crate::interpreter) use hash_equals::*;
pub(in crate::interpreter) use hash_file::*;
pub(in crate::interpreter) use hash_final::*;
pub(in crate::interpreter) use hash_hmac::*;
pub(in crate::interpreter) use hash_init::*;
pub(in crate::interpreter) use hash_update::*;
pub(in crate::interpreter) use hex2bin::*;
pub(in crate::interpreter) use html_entity_decode::*;
pub(in crate::interpreter) use htmlentities::*;
pub(in crate::interpreter) use htmlspecialchars::*;
pub(in crate::interpreter) use iconv::*;
pub(in crate::interpreter) use implode::*;
pub(in crate::interpreter) use lcfirst::*;
pub(in crate::interpreter) use ltrim::*;
pub(in crate::interpreter) use md5::*;
pub(in crate::interpreter) use nl2br::*;
pub(in crate::interpreter) use ord::*;
pub(in crate::interpreter) use openssl_encrypt::*;
pub(in crate::interpreter) use parse_url::*;
pub(in crate::interpreter) use quoted_printable_encode::*;
pub(in crate::interpreter) use quotemeta::*;
pub(in crate::interpreter) use rawurldecode::*;
pub(in crate::interpreter) use rawurlencode::*;
pub(in crate::interpreter) use rtrim::*;
pub(in crate::interpreter) use sha1::*;
pub(in crate::interpreter) use str_contains::*;
pub(in crate::interpreter) use str_ends_with::*;
pub(in crate::interpreter) use str_ireplace::*;
pub(in crate::interpreter) use str_pad::*;
pub(in crate::interpreter) use str_repeat::*;
pub(in crate::interpreter) use str_replace::*;
pub(in crate::interpreter) use str_split::*;
pub(in crate::interpreter) use str_starts_with::*;
pub(in crate::interpreter) use str_word_count::*;
pub(in crate::interpreter) use strcasecmp::*;
pub(in crate::interpreter) use strcmp::*;
pub(in crate::interpreter) use stream_get_filters::*;
pub(in crate::interpreter) use stream_get_transports::*;
pub(in crate::interpreter) use stream_get_wrappers::*;
pub(in crate::interpreter) use stream_is_local::*;
pub(in crate::interpreter) use stream_supports_lock::*;
pub(in crate::interpreter) use stripslashes::*;
pub(in crate::interpreter) use strlen::*;
pub(in crate::interpreter) use stripos::*;
pub(in crate::interpreter) use strpos::*;
pub(in crate::interpreter) use strripos::*;
pub(in crate::interpreter) use strrpos::*;
pub(in crate::interpreter) use strstr::*;
pub(in crate::interpreter) use strtolower::*;
pub(in crate::interpreter) use strtr::*;
pub(in crate::interpreter) use strtoupper::*;
pub(in crate::interpreter) use substr::*;
pub(in crate::interpreter) use substr_replace::*;
pub(in crate::interpreter) use trim::*;
pub(in crate::interpreter) use ucfirst::*;
pub(in crate::interpreter) use ucwords::*;
pub(in crate::interpreter) use urldecode::*;
pub(in crate::interpreter) use urlencode::*;
pub(in crate::interpreter) use wordwrap::*;
