//! Purpose:
//! Canonical contracts for every `ext/curl` global constant (`CURLOPT_*`, `CURLINFO_*`, `CURLE_*`,
//! ...). GENERATED from the frozen `scripts/docs/curl_surface.json`; the
//! `curl_constants_match_frozen_surface` test in `crate::symbol_registry` pins the two
//! together in both directions (every name and value). DO NOT HAND-EDIT.
//!
//! Called from:
//! - `crate::symbol_registry` for validation and lookup.
//! - Both backends, which resolve predefined constant names and values from this table.
//!
//! Key details:
//! - Entries are sorted by exact name; the registry rejects any other order.
//! - Always published, independent of the `curl` feature: constants are values, not calls, and
//!   PHP programs mention them without linking libcurl. Values are frozen against the pinned
//!   libcurl headers; `CURLINFO_LASTONE` is the pinned 71 on purpose.

use crate::{
    BuiltinId, ConstValue, ConstantContract, ConstantRoute, PhpModule, PhpVersion,
};

macro_rules! constant {
    (
        $name:literal, $module:ident, $value:expr
        $(, since: $since:ident)? $(, route: $route:ident)? $(, extension: $extension:literal)? $(,)?
    ) => {
        ConstantContract {
            id: BuiltinId::from_canonical_name($name),
            name: $name,
            module: PhpModule::$module,
            since: constant!(@since $($since)?),
            value: $value,
            route: constant!(@route $($route)?),
            extension: constant!(@flag $($extension)?),
            internal: false,
        }
    };
    (@since $since:ident) => { Some(PhpVersion::$since) };
    (@since) => { None };
    (@route $route:ident) => { ConstantRoute::$route };
    (@route) => { ConstantRoute::Predefined };
    (@flag $value:literal) => { $value };
    (@flag) => { false };
}

pub(crate) static CURL_CONSTANTS: &[ConstantContract] = &[
    constant!("CURLALTSVC_H1", Curl, ConstValue::Int(8), since: Php82),
    constant!("CURLALTSVC_H2", Curl, ConstValue::Int(16), since: Php82),
    constant!("CURLALTSVC_H3", Curl, ConstValue::Int(32), since: Php82),
    constant!("CURLALTSVC_READONLYFILE", Curl, ConstValue::Int(4), since: Php82),
    constant!("CURLAUTH_ANY", Curl, ConstValue::Int(4294967279)),
    constant!("CURLAUTH_ANYSAFE", Curl, ConstValue::Int(4294967278)),
    constant!("CURLAUTH_AWS_SIGV4", Curl, ConstValue::Int(128), since: Php82),
    constant!("CURLAUTH_BASIC", Curl, ConstValue::Int(1)),
    constant!("CURLAUTH_BEARER", Curl, ConstValue::Int(64)),
    constant!("CURLAUTH_DIGEST", Curl, ConstValue::Int(2)),
    constant!("CURLAUTH_DIGEST_IE", Curl, ConstValue::Int(16)),
    constant!("CURLAUTH_GSSAPI", Curl, ConstValue::Int(4)),
    constant!("CURLAUTH_GSSNEGOTIATE", Curl, ConstValue::Int(4)),
    constant!("CURLAUTH_NEGOTIATE", Curl, ConstValue::Int(4)),
    constant!("CURLAUTH_NONE", Curl, ConstValue::Int(0)),
    constant!("CURLAUTH_NTLM", Curl, ConstValue::Int(8)),
    constant!("CURLAUTH_NTLM_WB", Curl, ConstValue::Int(32)),
    constant!("CURLAUTH_ONLY", Curl, ConstValue::Int(2147483648)),
    constant!("CURLE_ABORTED_BY_CALLBACK", Curl, ConstValue::Int(42)),
    constant!("CURLE_BAD_CALLING_ORDER", Curl, ConstValue::Int(44)),
    constant!("CURLE_BAD_CONTENT_ENCODING", Curl, ConstValue::Int(61)),
    constant!("CURLE_BAD_DOWNLOAD_RESUME", Curl, ConstValue::Int(36)),
    constant!("CURLE_BAD_FUNCTION_ARGUMENT", Curl, ConstValue::Int(43)),
    constant!("CURLE_BAD_PASSWORD_ENTERED", Curl, ConstValue::Int(46)),
    constant!("CURLE_COULDNT_CONNECT", Curl, ConstValue::Int(7)),
    constant!("CURLE_COULDNT_RESOLVE_HOST", Curl, ConstValue::Int(6)),
    constant!("CURLE_COULDNT_RESOLVE_PROXY", Curl, ConstValue::Int(5)),
    constant!("CURLE_FAILED_INIT", Curl, ConstValue::Int(2)),
    constant!("CURLE_FILESIZE_EXCEEDED", Curl, ConstValue::Int(63)),
    constant!("CURLE_FILE_COULDNT_READ_FILE", Curl, ConstValue::Int(37)),
    constant!("CURLE_FTP_ACCESS_DENIED", Curl, ConstValue::Int(9)),
    constant!("CURLE_FTP_BAD_DOWNLOAD_RESUME", Curl, ConstValue::Int(36)),
    constant!("CURLE_FTP_CANT_GET_HOST", Curl, ConstValue::Int(15)),
    constant!("CURLE_FTP_CANT_RECONNECT", Curl, ConstValue::Int(16)),
    constant!("CURLE_FTP_COULDNT_GET_SIZE", Curl, ConstValue::Int(32)),
    constant!("CURLE_FTP_COULDNT_RETR_FILE", Curl, ConstValue::Int(19)),
    constant!("CURLE_FTP_COULDNT_SET_ASCII", Curl, ConstValue::Int(29)),
    constant!("CURLE_FTP_COULDNT_SET_BINARY", Curl, ConstValue::Int(17)),
    constant!("CURLE_FTP_COULDNT_STOR_FILE", Curl, ConstValue::Int(25)),
    constant!("CURLE_FTP_COULDNT_USE_REST", Curl, ConstValue::Int(31)),
    constant!("CURLE_FTP_PARTIAL_FILE", Curl, ConstValue::Int(18)),
    constant!("CURLE_FTP_PORT_FAILED", Curl, ConstValue::Int(30)),
    constant!("CURLE_FTP_QUOTE_ERROR", Curl, ConstValue::Int(21)),
    constant!("CURLE_FTP_SSL_FAILED", Curl, ConstValue::Int(64)),
    constant!("CURLE_FTP_USER_PASSWORD_INCORRECT", Curl, ConstValue::Int(10)),
    constant!("CURLE_FTP_WEIRD_227_FORMAT", Curl, ConstValue::Int(14)),
    constant!("CURLE_FTP_WEIRD_PASS_REPLY", Curl, ConstValue::Int(11)),
    constant!("CURLE_FTP_WEIRD_PASV_REPLY", Curl, ConstValue::Int(13)),
    constant!("CURLE_FTP_WEIRD_SERVER_REPLY", Curl, ConstValue::Int(8)),
    constant!("CURLE_FTP_WEIRD_USER_REPLY", Curl, ConstValue::Int(12)),
    constant!("CURLE_FTP_WRITE_ERROR", Curl, ConstValue::Int(20)),
    constant!("CURLE_FUNCTION_NOT_FOUND", Curl, ConstValue::Int(41)),
    constant!("CURLE_GOT_NOTHING", Curl, ConstValue::Int(52)),
    constant!("CURLE_HTTP_NOT_FOUND", Curl, ConstValue::Int(22)),
    constant!("CURLE_HTTP_PORT_FAILED", Curl, ConstValue::Int(45)),
    constant!("CURLE_HTTP_POST_ERROR", Curl, ConstValue::Int(34)),
    constant!("CURLE_HTTP_RANGE_ERROR", Curl, ConstValue::Int(33)),
    constant!("CURLE_HTTP_RETURNED_ERROR", Curl, ConstValue::Int(22)),
    constant!("CURLE_LDAP_CANNOT_BIND", Curl, ConstValue::Int(38)),
    constant!("CURLE_LDAP_INVALID_URL", Curl, ConstValue::Int(62)),
    constant!("CURLE_LDAP_SEARCH_FAILED", Curl, ConstValue::Int(39)),
    constant!("CURLE_LIBRARY_NOT_FOUND", Curl, ConstValue::Int(40)),
    constant!("CURLE_MALFORMAT_USER", Curl, ConstValue::Int(24)),
    constant!("CURLE_OBSOLETE", Curl, ConstValue::Int(50)),
    constant!("CURLE_OK", Curl, ConstValue::Int(0)),
    constant!("CURLE_OPERATION_TIMEDOUT", Curl, ConstValue::Int(28)),
    constant!("CURLE_OPERATION_TIMEOUTED", Curl, ConstValue::Int(28)),
    constant!("CURLE_OUT_OF_MEMORY", Curl, ConstValue::Int(27)),
    constant!("CURLE_PARTIAL_FILE", Curl, ConstValue::Int(18)),
    constant!("CURLE_PROXY", Curl, ConstValue::Int(97), since: Php82),
    constant!("CURLE_READ_ERROR", Curl, ConstValue::Int(26)),
    constant!("CURLE_RECV_ERROR", Curl, ConstValue::Int(56)),
    constant!("CURLE_SEND_ERROR", Curl, ConstValue::Int(55)),
    constant!("CURLE_SHARE_IN_USE", Curl, ConstValue::Int(57)),
    constant!("CURLE_SSH", Curl, ConstValue::Int(79)),
    constant!("CURLE_SSL_CACERT", Curl, ConstValue::Int(60)),
    constant!("CURLE_SSL_CACERT_BADFILE", Curl, ConstValue::Int(77)),
    constant!("CURLE_SSL_CERTPROBLEM", Curl, ConstValue::Int(58)),
    constant!("CURLE_SSL_CIPHER", Curl, ConstValue::Int(59)),
    constant!("CURLE_SSL_CONNECT_ERROR", Curl, ConstValue::Int(35)),
    constant!("CURLE_SSL_ENGINE_NOTFOUND", Curl, ConstValue::Int(53)),
    constant!("CURLE_SSL_ENGINE_SETFAILED", Curl, ConstValue::Int(54)),
    constant!("CURLE_SSL_PEER_CERTIFICATE", Curl, ConstValue::Int(60)),
    constant!("CURLE_SSL_PINNEDPUBKEYNOTMATCH", Curl, ConstValue::Int(90)),
    constant!("CURLE_TELNET_OPTION_SYNTAX", Curl, ConstValue::Int(49)),
    constant!("CURLE_TOO_MANY_REDIRECTS", Curl, ConstValue::Int(47)),
    constant!("CURLE_UNKNOWN_TELNET_OPTION", Curl, ConstValue::Int(48)),
    constant!("CURLE_UNSUPPORTED_PROTOCOL", Curl, ConstValue::Int(1)),
    constant!("CURLE_URL_MALFORMAT", Curl, ConstValue::Int(3)),
    constant!("CURLE_URL_MALFORMAT_USER", Curl, ConstValue::Int(4)),
    constant!("CURLE_WEIRD_SERVER_REPLY", Curl, ConstValue::Int(8)),
    constant!("CURLE_WRITE_ERROR", Curl, ConstValue::Int(23)),
    constant!("CURLFOLLOW_ALL", Curl, ConstValue::Int(1), since: Php85),
    constant!("CURLFOLLOW_FIRSTONLY", Curl, ConstValue::Int(3), since: Php85),
    constant!("CURLFOLLOW_OBEYCODE", Curl, ConstValue::Int(2), since: Php85),
    constant!("CURLFTPAUTH_DEFAULT", Curl, ConstValue::Int(0)),
    constant!("CURLFTPAUTH_SSL", Curl, ConstValue::Int(1)),
    constant!("CURLFTPAUTH_TLS", Curl, ConstValue::Int(2)),
    constant!("CURLFTPMETHOD_DEFAULT", Curl, ConstValue::Int(0), since: Php82),
    constant!("CURLFTPMETHOD_MULTICWD", Curl, ConstValue::Int(1)),
    constant!("CURLFTPMETHOD_NOCWD", Curl, ConstValue::Int(2)),
    constant!("CURLFTPMETHOD_SINGLECWD", Curl, ConstValue::Int(3)),
    constant!("CURLFTPSSL_ALL", Curl, ConstValue::Int(3)),
    constant!("CURLFTPSSL_CCC_ACTIVE", Curl, ConstValue::Int(2)),
    constant!("CURLFTPSSL_CCC_NONE", Curl, ConstValue::Int(0)),
    constant!("CURLFTPSSL_CCC_PASSIVE", Curl, ConstValue::Int(1)),
    constant!("CURLFTPSSL_CONTROL", Curl, ConstValue::Int(2)),
    constant!("CURLFTPSSL_NONE", Curl, ConstValue::Int(0)),
    constant!("CURLFTPSSL_TRY", Curl, ConstValue::Int(1)),
    constant!("CURLFTP_CREATE_DIR", Curl, ConstValue::Int(1)),
    constant!("CURLFTP_CREATE_DIR_NONE", Curl, ConstValue::Int(0)),
    constant!("CURLFTP_CREATE_DIR_RETRY", Curl, ConstValue::Int(2)),
    constant!("CURLGSSAPI_DELEGATION_FLAG", Curl, ConstValue::Int(2)),
    constant!("CURLGSSAPI_DELEGATION_POLICY_FLAG", Curl, ConstValue::Int(1)),
    constant!("CURLHEADER_SEPARATE", Curl, ConstValue::Int(1)),
    constant!("CURLHEADER_UNIFIED", Curl, ConstValue::Int(0)),
    constant!("CURLHSTS_ENABLE", Curl, ConstValue::Int(1), since: Php82),
    constant!("CURLHSTS_READONLYFILE", Curl, ConstValue::Int(2), since: Php82),
    constant!("CURLINFO_APPCONNECT_TIME", Curl, ConstValue::Int(3145761)),
    constant!("CURLINFO_APPCONNECT_TIME_T", Curl, ConstValue::Int(6291512)),
    constant!("CURLINFO_CAINFO", Curl, ConstValue::Int(1048637), since: Php83),
    constant!("CURLINFO_CAPATH", Curl, ConstValue::Int(1048638), since: Php83),
    constant!("CURLINFO_CERTINFO", Curl, ConstValue::Int(4194338)),
    constant!("CURLINFO_CONDITION_UNMET", Curl, ConstValue::Int(2097187)),
    constant!("CURLINFO_CONNECT_TIME", Curl, ConstValue::Int(3145733)),
    constant!("CURLINFO_CONNECT_TIME_T", Curl, ConstValue::Int(6291508)),
    constant!("CURLINFO_CONN_ID", Curl, ConstValue::Int(6291520), since: Php85),
    constant!("CURLINFO_CONTENT_LENGTH_DOWNLOAD", Curl, ConstValue::Int(3145743)),
    constant!("CURLINFO_CONTENT_LENGTH_DOWNLOAD_T", Curl, ConstValue::Int(6291471)),
    constant!("CURLINFO_CONTENT_LENGTH_UPLOAD", Curl, ConstValue::Int(3145744)),
    constant!("CURLINFO_CONTENT_LENGTH_UPLOAD_T", Curl, ConstValue::Int(6291472)),
    constant!("CURLINFO_CONTENT_TYPE", Curl, ConstValue::Int(1048594)),
    constant!("CURLINFO_COOKIELIST", Curl, ConstValue::Int(4194332)),
    constant!("CURLINFO_DATA_IN", Curl, ConstValue::Int(3), since: Php84),
    constant!("CURLINFO_DATA_OUT", Curl, ConstValue::Int(4), since: Php84),
    constant!("CURLINFO_EFFECTIVE_METHOD", Curl, ConstValue::Int(1048634), since: Php82),
    constant!("CURLINFO_EFFECTIVE_URL", Curl, ConstValue::Int(1048577)),
    constant!("CURLINFO_FILETIME", Curl, ConstValue::Int(2097166)),
    constant!("CURLINFO_FILETIME_T", Curl, ConstValue::Int(6291470)),
    constant!("CURLINFO_FTP_ENTRY_PATH", Curl, ConstValue::Int(1048606)),
    constant!("CURLINFO_HEADER_IN", Curl, ConstValue::Int(1), since: Php84),
    constant!("CURLINFO_HEADER_OUT", Curl, ConstValue::Int(2)),
    constant!("CURLINFO_HEADER_SIZE", Curl, ConstValue::Int(2097163)),
    constant!("CURLINFO_HTTPAUTH_AVAIL", Curl, ConstValue::Int(2097175)),
    constant!("CURLINFO_HTTPAUTH_USED", Curl, ConstValue::Int(2097221), since: Php85),
    constant!("CURLINFO_HTTP_CODE", Curl, ConstValue::Int(2097154)),
    constant!("CURLINFO_HTTP_CONNECTCODE", Curl, ConstValue::Int(2097174)),
    constant!("CURLINFO_HTTP_VERSION", Curl, ConstValue::Int(2097198)),
    constant!("CURLINFO_LASTONE", Curl, ConstValue::Int(71)),
    constant!("CURLINFO_LOCAL_IP", Curl, ConstValue::Int(1048617)),
    constant!("CURLINFO_LOCAL_PORT", Curl, ConstValue::Int(2097194)),
    constant!("CURLINFO_NAMELOOKUP_TIME", Curl, ConstValue::Int(3145732)),
    constant!("CURLINFO_NAMELOOKUP_TIME_T", Curl, ConstValue::Int(6291507)),
    constant!("CURLINFO_NUM_CONNECTS", Curl, ConstValue::Int(2097178)),
    constant!("CURLINFO_OS_ERRNO", Curl, ConstValue::Int(2097177)),
    constant!("CURLINFO_POSTTRANSFER_TIME_T", Curl, ConstValue::Int(6291523), since: Php84),
    constant!("CURLINFO_PRETRANSFER_TIME", Curl, ConstValue::Int(3145734)),
    constant!("CURLINFO_PRETRANSFER_TIME_T", Curl, ConstValue::Int(6291509)),
    constant!("CURLINFO_PRIMARY_IP", Curl, ConstValue::Int(1048608)),
    constant!("CURLINFO_PRIMARY_PORT", Curl, ConstValue::Int(2097192)),
    constant!("CURLINFO_PRIVATE", Curl, ConstValue::Int(1048597)),
    constant!("CURLINFO_PROTOCOL", Curl, ConstValue::Int(2097200)),
    constant!("CURLINFO_PROXYAUTH_AVAIL", Curl, ConstValue::Int(2097176)),
    constant!("CURLINFO_PROXYAUTH_USED", Curl, ConstValue::Int(2097222), since: Php85),
    constant!("CURLINFO_PROXY_ERROR", Curl, ConstValue::Int(2097211), since: Php82),
    constant!("CURLINFO_PROXY_SSL_VERIFYRESULT", Curl, ConstValue::Int(2097199)),
    constant!("CURLINFO_QUEUE_TIME_T", Curl, ConstValue::Int(6291521), since: Php85),
    constant!("CURLINFO_REDIRECT_COUNT", Curl, ConstValue::Int(2097172)),
    constant!("CURLINFO_REDIRECT_TIME", Curl, ConstValue::Int(3145747)),
    constant!("CURLINFO_REDIRECT_TIME_T", Curl, ConstValue::Int(6291511)),
    constant!("CURLINFO_REDIRECT_URL", Curl, ConstValue::Int(1048607)),
    constant!("CURLINFO_REFERER", Curl, ConstValue::Int(1048636), since: Php82),
    constant!("CURLINFO_REQUEST_SIZE", Curl, ConstValue::Int(2097164)),
    constant!("CURLINFO_RESPONSE_CODE", Curl, ConstValue::Int(2097154)),
    constant!("CURLINFO_RETRY_AFTER", Curl, ConstValue::Int(6291513), since: Php82),
    constant!("CURLINFO_RTSP_CLIENT_CSEQ", Curl, ConstValue::Int(2097189)),
    constant!("CURLINFO_RTSP_CSEQ_RECV", Curl, ConstValue::Int(2097191)),
    constant!("CURLINFO_RTSP_SERVER_CSEQ", Curl, ConstValue::Int(2097190)),
    constant!("CURLINFO_RTSP_SESSION_ID", Curl, ConstValue::Int(1048612)),
    constant!("CURLINFO_SCHEME", Curl, ConstValue::Int(1048625)),
    constant!("CURLINFO_SIZE_DOWNLOAD", Curl, ConstValue::Int(3145736)),
    constant!("CURLINFO_SIZE_DOWNLOAD_T", Curl, ConstValue::Int(6291464)),
    constant!("CURLINFO_SIZE_UPLOAD", Curl, ConstValue::Int(3145735)),
    constant!("CURLINFO_SIZE_UPLOAD_T", Curl, ConstValue::Int(6291463)),
    constant!("CURLINFO_SPEED_DOWNLOAD", Curl, ConstValue::Int(3145737)),
    constant!("CURLINFO_SPEED_DOWNLOAD_T", Curl, ConstValue::Int(6291465)),
    constant!("CURLINFO_SPEED_UPLOAD", Curl, ConstValue::Int(3145738)),
    constant!("CURLINFO_SPEED_UPLOAD_T", Curl, ConstValue::Int(6291466)),
    constant!("CURLINFO_SSL_DATA_IN", Curl, ConstValue::Int(5), since: Php84),
    constant!("CURLINFO_SSL_DATA_OUT", Curl, ConstValue::Int(6), since: Php84),
    constant!("CURLINFO_SSL_ENGINES", Curl, ConstValue::Int(4194331)),
    constant!("CURLINFO_SSL_VERIFYRESULT", Curl, ConstValue::Int(2097165)),
    constant!("CURLINFO_STARTTRANSFER_TIME", Curl, ConstValue::Int(3145745)),
    constant!("CURLINFO_STARTTRANSFER_TIME_T", Curl, ConstValue::Int(6291510)),
    constant!("CURLINFO_TEXT", Curl, ConstValue::Int(0), since: Php84),
    constant!("CURLINFO_TOTAL_TIME", Curl, ConstValue::Int(3145731)),
    constant!("CURLINFO_TOTAL_TIME_T", Curl, ConstValue::Int(6291506)),
    constant!("CURLINFO_USED_PROXY", Curl, ConstValue::Int(2097218), since: Php85),
    constant!("CURLKHMATCH_LAST", Curl, ConstValue::Int(3), since: Php83),
    constant!("CURLKHMATCH_MISMATCH", Curl, ConstValue::Int(1), since: Php83),
    constant!("CURLKHMATCH_MISSING", Curl, ConstValue::Int(2), since: Php83),
    constant!("CURLKHMATCH_OK", Curl, ConstValue::Int(0), since: Php83),
    constant!("CURLMIMEOPT_FORMESCAPE", Curl, ConstValue::Int(1), since: Php83),
    constant!("CURLMOPT_CHUNK_LENGTH_PENALTY_SIZE", Curl, ConstValue::Int(30010)),
    constant!("CURLMOPT_CONTENT_LENGTH_PENALTY_SIZE", Curl, ConstValue::Int(30009)),
    constant!("CURLMOPT_MAXCONNECTS", Curl, ConstValue::Int(6)),
    constant!("CURLMOPT_MAX_CONCURRENT_STREAMS", Curl, ConstValue::Int(16), since: Php82),
    constant!("CURLMOPT_MAX_HOST_CONNECTIONS", Curl, ConstValue::Int(7)),
    constant!("CURLMOPT_MAX_PIPELINE_LENGTH", Curl, ConstValue::Int(8)),
    constant!("CURLMOPT_MAX_TOTAL_CONNECTIONS", Curl, ConstValue::Int(13)),
    constant!("CURLMOPT_PIPELINING", Curl, ConstValue::Int(3)),
    constant!("CURLMOPT_PUSHFUNCTION", Curl, ConstValue::Int(20014)),
    constant!("CURLMSG_DONE", Curl, ConstValue::Int(1)),
    constant!("CURLM_ADDED_ALREADY", Curl, ConstValue::Int(7)),
    constant!("CURLM_BAD_EASY_HANDLE", Curl, ConstValue::Int(2)),
    constant!("CURLM_BAD_HANDLE", Curl, ConstValue::Int(1)),
    constant!("CURLM_CALL_MULTI_PERFORM", Curl, ConstValue::Int(-1)),
    constant!("CURLM_INTERNAL_ERROR", Curl, ConstValue::Int(4)),
    constant!("CURLM_OK", Curl, ConstValue::Int(0)),
    constant!("CURLM_OUT_OF_MEMORY", Curl, ConstValue::Int(3)),
    constant!("CURLOPT_ABSTRACT_UNIX_SOCKET", Curl, ConstValue::Int(10264)),
    constant!("CURLOPT_ACCEPTTIMEOUT_MS", Curl, ConstValue::Int(212)),
    constant!("CURLOPT_ACCEPT_ENCODING", Curl, ConstValue::Int(10102)),
    constant!("CURLOPT_ADDRESS_SCOPE", Curl, ConstValue::Int(171)),
    constant!("CURLOPT_ALTSVC", Curl, ConstValue::Int(10287), since: Php82),
    constant!("CURLOPT_ALTSVC_CTRL", Curl, ConstValue::Int(286), since: Php82),
    constant!("CURLOPT_APPEND", Curl, ConstValue::Int(50)),
    constant!("CURLOPT_AUTOREFERER", Curl, ConstValue::Int(58)),
    constant!("CURLOPT_AWS_SIGV4", Curl, ConstValue::Int(10305), since: Php82),
    constant!("CURLOPT_BINARYTRANSFER", Curl, ConstValue::Int(19914)),
    constant!("CURLOPT_BUFFERSIZE", Curl, ConstValue::Int(98)),
    constant!("CURLOPT_CAINFO", Curl, ConstValue::Int(10065)),
    constant!("CURLOPT_CAINFO_BLOB", Curl, ConstValue::Int(40309), since: Php82),
    constant!("CURLOPT_CAPATH", Curl, ConstValue::Int(10097)),
    constant!("CURLOPT_CA_CACHE_TIMEOUT", Curl, ConstValue::Int(321), since: Php83),
    constant!("CURLOPT_CERTINFO", Curl, ConstValue::Int(172)),
    constant!("CURLOPT_CONNECTTIMEOUT", Curl, ConstValue::Int(78)),
    constant!("CURLOPT_CONNECTTIMEOUT_MS", Curl, ConstValue::Int(156)),
    constant!("CURLOPT_CONNECT_ONLY", Curl, ConstValue::Int(141)),
    constant!("CURLOPT_CONNECT_TO", Curl, ConstValue::Int(10243)),
    constant!("CURLOPT_COOKIE", Curl, ConstValue::Int(10022)),
    constant!("CURLOPT_COOKIEFILE", Curl, ConstValue::Int(10031)),
    constant!("CURLOPT_COOKIEJAR", Curl, ConstValue::Int(10082)),
    constant!("CURLOPT_COOKIELIST", Curl, ConstValue::Int(10135)),
    constant!("CURLOPT_COOKIESESSION", Curl, ConstValue::Int(96)),
    constant!("CURLOPT_CRLF", Curl, ConstValue::Int(27)),
    constant!("CURLOPT_CRLFILE", Curl, ConstValue::Int(10169)),
    constant!("CURLOPT_CUSTOMREQUEST", Curl, ConstValue::Int(10036)),
    constant!("CURLOPT_DEBUGFUNCTION", Curl, ConstValue::Int(20094), since: Php84),
    constant!("CURLOPT_DEFAULT_PROTOCOL", Curl, ConstValue::Int(10238)),
    constant!("CURLOPT_DIRLISTONLY", Curl, ConstValue::Int(48)),
    constant!("CURLOPT_DISALLOW_USERNAME_IN_URL", Curl, ConstValue::Int(278)),
    constant!("CURLOPT_DNS_CACHE_TIMEOUT", Curl, ConstValue::Int(92)),
    constant!("CURLOPT_DNS_INTERFACE", Curl, ConstValue::Int(10221)),
    constant!("CURLOPT_DNS_LOCAL_IP4", Curl, ConstValue::Int(10222)),
    constant!("CURLOPT_DNS_LOCAL_IP6", Curl, ConstValue::Int(10223)),
    constant!("CURLOPT_DNS_SERVERS", Curl, ConstValue::Int(10211)),
    constant!("CURLOPT_DNS_SHUFFLE_ADDRESSES", Curl, ConstValue::Int(275)),
    constant!("CURLOPT_DNS_USE_GLOBAL_CACHE", Curl, ConstValue::Int(91)),
    constant!("CURLOPT_DOH_SSL_VERIFYHOST", Curl, ConstValue::Int(307), since: Php82),
    constant!("CURLOPT_DOH_SSL_VERIFYPEER", Curl, ConstValue::Int(306), since: Php82),
    constant!("CURLOPT_DOH_SSL_VERIFYSTATUS", Curl, ConstValue::Int(308), since: Php82),
    constant!("CURLOPT_DOH_URL", Curl, ConstValue::Int(10279), since: Php81),
    constant!("CURLOPT_EGDSOCKET", Curl, ConstValue::Int(10077)),
    constant!("CURLOPT_ENCODING", Curl, ConstValue::Int(10102)),
    constant!("CURLOPT_EXPECT_100_TIMEOUT_MS", Curl, ConstValue::Int(227)),
    constant!("CURLOPT_FAILONERROR", Curl, ConstValue::Int(45)),
    constant!("CURLOPT_FILE", Curl, ConstValue::Int(10001)),
    constant!("CURLOPT_FILETIME", Curl, ConstValue::Int(69)),
    constant!("CURLOPT_FNMATCH_FUNCTION", Curl, ConstValue::Int(20200)),
    constant!("CURLOPT_FOLLOWLOCATION", Curl, ConstValue::Int(52)),
    constant!("CURLOPT_FORBID_REUSE", Curl, ConstValue::Int(75)),
    constant!("CURLOPT_FRESH_CONNECT", Curl, ConstValue::Int(74)),
    constant!("CURLOPT_FTPAPPEND", Curl, ConstValue::Int(50)),
    constant!("CURLOPT_FTPLISTONLY", Curl, ConstValue::Int(48)),
    constant!("CURLOPT_FTPPORT", Curl, ConstValue::Int(10017)),
    constant!("CURLOPT_FTPSSLAUTH", Curl, ConstValue::Int(129)),
    constant!("CURLOPT_FTP_ACCOUNT", Curl, ConstValue::Int(10134)),
    constant!("CURLOPT_FTP_ALTERNATIVE_TO_USER", Curl, ConstValue::Int(10147)),
    constant!("CURLOPT_FTP_CREATE_MISSING_DIRS", Curl, ConstValue::Int(110)),
    constant!("CURLOPT_FTP_FILEMETHOD", Curl, ConstValue::Int(138)),
    constant!("CURLOPT_FTP_RESPONSE_TIMEOUT", Curl, ConstValue::Int(112)),
    constant!("CURLOPT_FTP_SKIP_PASV_IP", Curl, ConstValue::Int(137)),
    constant!("CURLOPT_FTP_SSL", Curl, ConstValue::Int(119)),
    constant!("CURLOPT_FTP_SSL_CCC", Curl, ConstValue::Int(154)),
    constant!("CURLOPT_FTP_USE_EPRT", Curl, ConstValue::Int(106)),
    constant!("CURLOPT_FTP_USE_EPSV", Curl, ConstValue::Int(85)),
    constant!("CURLOPT_FTP_USE_PRET", Curl, ConstValue::Int(188)),
    constant!("CURLOPT_GSSAPI_DELEGATION", Curl, ConstValue::Int(210)),
    constant!("CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS", Curl, ConstValue::Int(271)),
    constant!("CURLOPT_HAPROXYPROTOCOL", Curl, ConstValue::Int(274)),
    constant!("CURLOPT_HEADER", Curl, ConstValue::Int(42)),
    constant!("CURLOPT_HEADERFUNCTION", Curl, ConstValue::Int(20079)),
    constant!("CURLOPT_HEADEROPT", Curl, ConstValue::Int(229)),
    constant!("CURLOPT_HSTS", Curl, ConstValue::Int(10300), since: Php82),
    constant!("CURLOPT_HSTS_CTRL", Curl, ConstValue::Int(299), since: Php82),
    constant!("CURLOPT_HTTP09_ALLOWED", Curl, ConstValue::Int(285)),
    constant!("CURLOPT_HTTP200ALIASES", Curl, ConstValue::Int(10104)),
    constant!("CURLOPT_HTTPAUTH", Curl, ConstValue::Int(107)),
    constant!("CURLOPT_HTTPGET", Curl, ConstValue::Int(80)),
    constant!("CURLOPT_HTTPHEADER", Curl, ConstValue::Int(10023)),
    constant!("CURLOPT_HTTPPROXYTUNNEL", Curl, ConstValue::Int(61)),
    constant!("CURLOPT_HTTP_CONTENT_DECODING", Curl, ConstValue::Int(158)),
    constant!("CURLOPT_HTTP_TRANSFER_DECODING", Curl, ConstValue::Int(157)),
    constant!("CURLOPT_HTTP_VERSION", Curl, ConstValue::Int(84)),
    constant!("CURLOPT_IGNORE_CONTENT_LENGTH", Curl, ConstValue::Int(136)),
    constant!("CURLOPT_INFILE", Curl, ConstValue::Int(10009)),
    constant!("CURLOPT_INFILESIZE", Curl, ConstValue::Int(14)),
    constant!("CURLOPT_INFILESIZE_LARGE", Curl, ConstValue::Int(30115), since: Php85),
    constant!("CURLOPT_INTERFACE", Curl, ConstValue::Int(10062)),
    constant!("CURLOPT_IPRESOLVE", Curl, ConstValue::Int(113)),
    constant!("CURLOPT_ISSUERCERT", Curl, ConstValue::Int(10170)),
    constant!("CURLOPT_ISSUERCERT_BLOB", Curl, ConstValue::Int(40295), since: Php81),
    constant!("CURLOPT_KEEP_SENDING_ON_ERROR", Curl, ConstValue::Int(245)),
    constant!("CURLOPT_KEYPASSWD", Curl, ConstValue::Int(10026)),
    constant!("CURLOPT_KRB4LEVEL", Curl, ConstValue::Int(10063)),
    constant!("CURLOPT_KRBLEVEL", Curl, ConstValue::Int(10063)),
    constant!("CURLOPT_LOCALPORT", Curl, ConstValue::Int(139)),
    constant!("CURLOPT_LOCALPORTRANGE", Curl, ConstValue::Int(140)),
    constant!("CURLOPT_LOGIN_OPTIONS", Curl, ConstValue::Int(10224)),
    constant!("CURLOPT_LOW_SPEED_LIMIT", Curl, ConstValue::Int(19)),
    constant!("CURLOPT_LOW_SPEED_TIME", Curl, ConstValue::Int(20)),
    constant!("CURLOPT_MAIL_AUTH", Curl, ConstValue::Int(10217)),
    constant!("CURLOPT_MAIL_FROM", Curl, ConstValue::Int(10186)),
    constant!("CURLOPT_MAIL_RCPT", Curl, ConstValue::Int(10187)),
    constant!("CURLOPT_MAIL_RCPT_ALLLOWFAILS", Curl, ConstValue::Int(290), since: Php82),
    constant!("CURLOPT_MAXAGE_CONN", Curl, ConstValue::Int(288), since: Php82),
    constant!("CURLOPT_MAXCONNECTS", Curl, ConstValue::Int(71)),
    constant!("CURLOPT_MAXFILESIZE", Curl, ConstValue::Int(114)),
    constant!("CURLOPT_MAXFILESIZE_LARGE", Curl, ConstValue::Int(30117), since: Php82),
    constant!("CURLOPT_MAXLIFETIME_CONN", Curl, ConstValue::Int(314), since: Php82),
    constant!("CURLOPT_MAXREDIRS", Curl, ConstValue::Int(68)),
    constant!("CURLOPT_MAX_RECV_SPEED_LARGE", Curl, ConstValue::Int(30146)),
    constant!("CURLOPT_MAX_SEND_SPEED_LARGE", Curl, ConstValue::Int(30145)),
    constant!("CURLOPT_MIME_OPTIONS", Curl, ConstValue::Int(315), since: Php83),
    constant!("CURLOPT_NETRC", Curl, ConstValue::Int(51)),
    constant!("CURLOPT_NETRC_FILE", Curl, ConstValue::Int(10118)),
    constant!("CURLOPT_NEW_DIRECTORY_PERMS", Curl, ConstValue::Int(160)),
    constant!("CURLOPT_NEW_FILE_PERMS", Curl, ConstValue::Int(159)),
    constant!("CURLOPT_NOBODY", Curl, ConstValue::Int(44)),
    constant!("CURLOPT_NOPROGRESS", Curl, ConstValue::Int(43)),
    constant!("CURLOPT_NOPROXY", Curl, ConstValue::Int(10177)),
    constant!("CURLOPT_NOSIGNAL", Curl, ConstValue::Int(99)),
    constant!("CURLOPT_PASSWORD", Curl, ConstValue::Int(10174)),
    constant!("CURLOPT_PATH_AS_IS", Curl, ConstValue::Int(234)),
    constant!("CURLOPT_PINNEDPUBLICKEY", Curl, ConstValue::Int(10230)),
    constant!("CURLOPT_PIPEWAIT", Curl, ConstValue::Int(237)),
    constant!("CURLOPT_PORT", Curl, ConstValue::Int(3)),
    constant!("CURLOPT_POST", Curl, ConstValue::Int(47)),
    constant!("CURLOPT_POSTFIELDS", Curl, ConstValue::Int(10015)),
    constant!("CURLOPT_POSTQUOTE", Curl, ConstValue::Int(10039)),
    constant!("CURLOPT_POSTREDIR", Curl, ConstValue::Int(161)),
    constant!("CURLOPT_PREQUOTE", Curl, ConstValue::Int(10093)),
    constant!("CURLOPT_PREREQFUNCTION", Curl, ConstValue::Int(20312), since: Php84),
    constant!("CURLOPT_PRE_PROXY", Curl, ConstValue::Int(10262)),
    constant!("CURLOPT_PRIVATE", Curl, ConstValue::Int(10103)),
    constant!("CURLOPT_PROGRESSFUNCTION", Curl, ConstValue::Int(20056)),
    constant!("CURLOPT_PROTOCOLS", Curl, ConstValue::Int(181)),
    constant!("CURLOPT_PROTOCOLS_STR", Curl, ConstValue::Int(10318), since: Php83),
    constant!("CURLOPT_PROXY", Curl, ConstValue::Int(10004)),
    constant!("CURLOPT_PROXYAUTH", Curl, ConstValue::Int(111)),
    constant!("CURLOPT_PROXYHEADER", Curl, ConstValue::Int(10228)),
    constant!("CURLOPT_PROXYPASSWORD", Curl, ConstValue::Int(10176)),
    constant!("CURLOPT_PROXYPORT", Curl, ConstValue::Int(59)),
    constant!("CURLOPT_PROXYTYPE", Curl, ConstValue::Int(101)),
    constant!("CURLOPT_PROXYUSERNAME", Curl, ConstValue::Int(10175)),
    constant!("CURLOPT_PROXYUSERPWD", Curl, ConstValue::Int(10006)),
    constant!("CURLOPT_PROXY_CAINFO", Curl, ConstValue::Int(10246)),
    constant!("CURLOPT_PROXY_CAINFO_BLOB", Curl, ConstValue::Int(40310), since: Php82),
    constant!("CURLOPT_PROXY_CAPATH", Curl, ConstValue::Int(10247)),
    constant!("CURLOPT_PROXY_CRLFILE", Curl, ConstValue::Int(10260)),
    constant!("CURLOPT_PROXY_ISSUERCERT", Curl, ConstValue::Int(10296), since: Php81),
    constant!("CURLOPT_PROXY_ISSUERCERT_BLOB", Curl, ConstValue::Int(40297), since: Php81),
    constant!("CURLOPT_PROXY_KEYPASSWD", Curl, ConstValue::Int(10258)),
    constant!("CURLOPT_PROXY_PINNEDPUBLICKEY", Curl, ConstValue::Int(10263)),
    constant!("CURLOPT_PROXY_SERVICE_NAME", Curl, ConstValue::Int(10235)),
    constant!("CURLOPT_PROXY_SSLCERT", Curl, ConstValue::Int(10254)),
    constant!("CURLOPT_PROXY_SSLCERTTYPE", Curl, ConstValue::Int(10255)),
    constant!("CURLOPT_PROXY_SSLCERT_BLOB", Curl, ConstValue::Int(40293), since: Php81),
    constant!("CURLOPT_PROXY_SSLKEY", Curl, ConstValue::Int(10256)),
    constant!("CURLOPT_PROXY_SSLKEYTYPE", Curl, ConstValue::Int(10257)),
    constant!("CURLOPT_PROXY_SSLKEY_BLOB", Curl, ConstValue::Int(40294), since: Php81),
    constant!("CURLOPT_PROXY_SSLVERSION", Curl, ConstValue::Int(250)),
    constant!("CURLOPT_PROXY_SSL_CIPHER_LIST", Curl, ConstValue::Int(10259)),
    constant!("CURLOPT_PROXY_SSL_OPTIONS", Curl, ConstValue::Int(261)),
    constant!("CURLOPT_PROXY_SSL_VERIFYHOST", Curl, ConstValue::Int(249)),
    constant!("CURLOPT_PROXY_SSL_VERIFYPEER", Curl, ConstValue::Int(248)),
    constant!("CURLOPT_PROXY_TLS13_CIPHERS", Curl, ConstValue::Int(10277)),
    constant!("CURLOPT_PROXY_TLSAUTH_PASSWORD", Curl, ConstValue::Int(10252)),
    constant!("CURLOPT_PROXY_TLSAUTH_TYPE", Curl, ConstValue::Int(10253)),
    constant!("CURLOPT_PROXY_TLSAUTH_USERNAME", Curl, ConstValue::Int(10251)),
    constant!("CURLOPT_PROXY_TRANSFER_MODE", Curl, ConstValue::Int(166)),
    constant!("CURLOPT_PUT", Curl, ConstValue::Int(54)),
    constant!("CURLOPT_QUICK_EXIT", Curl, ConstValue::Int(322), since: Php83),
    constant!("CURLOPT_QUOTE", Curl, ConstValue::Int(10028)),
    constant!("CURLOPT_RANDOM_FILE", Curl, ConstValue::Int(10076)),
    constant!("CURLOPT_RANGE", Curl, ConstValue::Int(10007)),
    constant!("CURLOPT_READDATA", Curl, ConstValue::Int(10009)),
    constant!("CURLOPT_READFUNCTION", Curl, ConstValue::Int(20012)),
    constant!("CURLOPT_REDIR_PROTOCOLS", Curl, ConstValue::Int(182)),
    constant!("CURLOPT_REDIR_PROTOCOLS_STR", Curl, ConstValue::Int(10319), since: Php83),
    constant!("CURLOPT_REFERER", Curl, ConstValue::Int(10016)),
    constant!("CURLOPT_REQUEST_TARGET", Curl, ConstValue::Int(10266)),
    constant!("CURLOPT_RESOLVE", Curl, ConstValue::Int(10203)),
    constant!("CURLOPT_RESUME_FROM", Curl, ConstValue::Int(21)),
    constant!("CURLOPT_RETURNTRANSFER", Curl, ConstValue::Int(19913)),
    constant!("CURLOPT_RTSP_CLIENT_CSEQ", Curl, ConstValue::Int(193)),
    constant!("CURLOPT_RTSP_REQUEST", Curl, ConstValue::Int(189)),
    constant!("CURLOPT_RTSP_SERVER_CSEQ", Curl, ConstValue::Int(194)),
    constant!("CURLOPT_RTSP_SESSION_ID", Curl, ConstValue::Int(10190)),
    constant!("CURLOPT_RTSP_STREAM_URI", Curl, ConstValue::Int(10191)),
    constant!("CURLOPT_RTSP_TRANSPORT", Curl, ConstValue::Int(10192)),
    constant!("CURLOPT_SAFE_UPLOAD", Curl, ConstValue::Int(-1)),
    constant!("CURLOPT_SASL_AUTHZID", Curl, ConstValue::Int(10289), since: Php82),
    constant!("CURLOPT_SASL_IR", Curl, ConstValue::Int(218)),
    constant!("CURLOPT_SERVER_RESPONSE_TIMEOUT", Curl, ConstValue::Int(112), since: Php84),
    constant!("CURLOPT_SERVICE_NAME", Curl, ConstValue::Int(10236)),
    constant!("CURLOPT_SHARE", Curl, ConstValue::Int(10100)),
    constant!("CURLOPT_SOCKS5_AUTH", Curl, ConstValue::Int(267)),
    constant!("CURLOPT_SOCKS5_GSSAPI_NEC", Curl, ConstValue::Int(180)),
    constant!("CURLOPT_SOCKS5_GSSAPI_SERVICE", Curl, ConstValue::Int(10179)),
    constant!("CURLOPT_SSH_AUTH_TYPES", Curl, ConstValue::Int(151)),
    constant!("CURLOPT_SSH_COMPRESSION", Curl, ConstValue::Int(268)),
    constant!("CURLOPT_SSH_HOSTKEYFUNCTION", Curl, ConstValue::Int(20316), since: Php83),
    constant!("CURLOPT_SSH_HOST_PUBLIC_KEY_MD5", Curl, ConstValue::Int(10162)),
    constant!("CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256", Curl, ConstValue::Int(10311), since: Php82),
    constant!("CURLOPT_SSH_KNOWNHOSTS", Curl, ConstValue::Int(10183)),
    constant!("CURLOPT_SSH_PRIVATE_KEYFILE", Curl, ConstValue::Int(10153)),
    constant!("CURLOPT_SSH_PUBLIC_KEYFILE", Curl, ConstValue::Int(10152)),
    constant!("CURLOPT_SSLCERT", Curl, ConstValue::Int(10025)),
    constant!("CURLOPT_SSLCERTPASSWD", Curl, ConstValue::Int(10026)),
    constant!("CURLOPT_SSLCERTTYPE", Curl, ConstValue::Int(10086)),
    constant!("CURLOPT_SSLCERT_BLOB", Curl, ConstValue::Int(40291), since: Php81),
    constant!("CURLOPT_SSLENGINE", Curl, ConstValue::Int(10089)),
    constant!("CURLOPT_SSLENGINE_DEFAULT", Curl, ConstValue::Int(90)),
    constant!("CURLOPT_SSLKEY", Curl, ConstValue::Int(10087)),
    constant!("CURLOPT_SSLKEYPASSWD", Curl, ConstValue::Int(10026)),
    constant!("CURLOPT_SSLKEYTYPE", Curl, ConstValue::Int(10088)),
    constant!("CURLOPT_SSLKEY_BLOB", Curl, ConstValue::Int(40292), since: Php81),
    constant!("CURLOPT_SSLVERSION", Curl, ConstValue::Int(32)),
    constant!("CURLOPT_SSL_CIPHER_LIST", Curl, ConstValue::Int(10083)),
    constant!("CURLOPT_SSL_EC_CURVES", Curl, ConstValue::Int(10298), since: Php82),
    constant!("CURLOPT_SSL_ENABLE_ALPN", Curl, ConstValue::Int(226)),
    constant!("CURLOPT_SSL_ENABLE_NPN", Curl, ConstValue::Int(225)),
    constant!("CURLOPT_SSL_FALSESTART", Curl, ConstValue::Int(233)),
    constant!("CURLOPT_SSL_OPTIONS", Curl, ConstValue::Int(216)),
    constant!("CURLOPT_SSL_SESSIONID_CACHE", Curl, ConstValue::Int(150)),
    constant!("CURLOPT_SSL_SIGNATURE_ALGORITHMS", Curl, ConstValue::Int(10328), since: Php85),
    constant!("CURLOPT_SSL_VERIFYHOST", Curl, ConstValue::Int(81)),
    constant!("CURLOPT_SSL_VERIFYPEER", Curl, ConstValue::Int(64)),
    constant!("CURLOPT_SSL_VERIFYSTATUS", Curl, ConstValue::Int(232)),
    constant!("CURLOPT_STDERR", Curl, ConstValue::Int(10037)),
    constant!("CURLOPT_STREAM_WEIGHT", Curl, ConstValue::Int(239)),
    constant!("CURLOPT_SUPPRESS_CONNECT_HEADERS", Curl, ConstValue::Int(265)),
    constant!("CURLOPT_TCP_FASTOPEN", Curl, ConstValue::Int(244)),
    constant!("CURLOPT_TCP_KEEPALIVE", Curl, ConstValue::Int(213)),
    constant!("CURLOPT_TCP_KEEPCNT", Curl, ConstValue::Int(326), since: Php84),
    constant!("CURLOPT_TCP_KEEPIDLE", Curl, ConstValue::Int(214)),
    constant!("CURLOPT_TCP_KEEPINTVL", Curl, ConstValue::Int(215)),
    constant!("CURLOPT_TCP_NODELAY", Curl, ConstValue::Int(121)),
    constant!("CURLOPT_TELNETOPTIONS", Curl, ConstValue::Int(10070)),
    constant!("CURLOPT_TFTP_BLKSIZE", Curl, ConstValue::Int(178)),
    constant!("CURLOPT_TFTP_NO_OPTIONS", Curl, ConstValue::Int(242)),
    constant!("CURLOPT_TIMECONDITION", Curl, ConstValue::Int(33)),
    constant!("CURLOPT_TIMEOUT", Curl, ConstValue::Int(13)),
    constant!("CURLOPT_TIMEOUT_MS", Curl, ConstValue::Int(155)),
    constant!("CURLOPT_TIMEVALUE", Curl, ConstValue::Int(34)),
    constant!("CURLOPT_TIMEVALUE_LARGE", Curl, ConstValue::Int(30270)),
    constant!("CURLOPT_TLS13_CIPHERS", Curl, ConstValue::Int(10276)),
    constant!("CURLOPT_TLSAUTH_PASSWORD", Curl, ConstValue::Int(10205)),
    constant!("CURLOPT_TLSAUTH_TYPE", Curl, ConstValue::Int(10206)),
    constant!("CURLOPT_TLSAUTH_USERNAME", Curl, ConstValue::Int(10204)),
    constant!("CURLOPT_TRANSFERTEXT", Curl, ConstValue::Int(53)),
    constant!("CURLOPT_TRANSFER_ENCODING", Curl, ConstValue::Int(207)),
    constant!("CURLOPT_UNIX_SOCKET_PATH", Curl, ConstValue::Int(10231)),
    constant!("CURLOPT_UNRESTRICTED_AUTH", Curl, ConstValue::Int(105)),
    constant!("CURLOPT_UPKEEP_INTERVAL_MS", Curl, ConstValue::Int(281), since: Php82),
    constant!("CURLOPT_UPLOAD", Curl, ConstValue::Int(46)),
    constant!("CURLOPT_UPLOAD_BUFFERSIZE", Curl, ConstValue::Int(280), since: Php82),
    constant!("CURLOPT_URL", Curl, ConstValue::Int(10002)),
    constant!("CURLOPT_USERAGENT", Curl, ConstValue::Int(10018)),
    constant!("CURLOPT_USERNAME", Curl, ConstValue::Int(10173)),
    constant!("CURLOPT_USERPWD", Curl, ConstValue::Int(10005)),
    constant!("CURLOPT_USE_SSL", Curl, ConstValue::Int(119)),
    constant!("CURLOPT_VERBOSE", Curl, ConstValue::Int(41)),
    constant!("CURLOPT_WILDCARDMATCH", Curl, ConstValue::Int(197)),
    constant!("CURLOPT_WRITEFUNCTION", Curl, ConstValue::Int(20011)),
    constant!("CURLOPT_WRITEHEADER", Curl, ConstValue::Int(10029)),
    constant!("CURLOPT_WS_OPTIONS", Curl, ConstValue::Int(320), since: Php83),
    constant!("CURLOPT_XFERINFOFUNCTION", Curl, ConstValue::Int(20219), since: Php82),
    constant!("CURLOPT_XOAUTH2_BEARER", Curl, ConstValue::Int(10220)),
    constant!("CURLPAUSE_ALL", Curl, ConstValue::Int(5)),
    constant!("CURLPAUSE_CONT", Curl, ConstValue::Int(0)),
    constant!("CURLPAUSE_RECV", Curl, ConstValue::Int(1)),
    constant!("CURLPAUSE_RECV_CONT", Curl, ConstValue::Int(0)),
    constant!("CURLPAUSE_SEND", Curl, ConstValue::Int(4)),
    constant!("CURLPAUSE_SEND_CONT", Curl, ConstValue::Int(0)),
    constant!("CURLPIPE_HTTP1", Curl, ConstValue::Int(1)),
    constant!("CURLPIPE_MULTIPLEX", Curl, ConstValue::Int(2)),
    constant!("CURLPIPE_NOTHING", Curl, ConstValue::Int(0)),
    constant!("CURLPROTO_ALL", Curl, ConstValue::Int(4294967295)),
    constant!("CURLPROTO_DICT", Curl, ConstValue::Int(512)),
    constant!("CURLPROTO_FILE", Curl, ConstValue::Int(1024)),
    constant!("CURLPROTO_FTP", Curl, ConstValue::Int(4)),
    constant!("CURLPROTO_FTPS", Curl, ConstValue::Int(8)),
    constant!("CURLPROTO_GOPHER", Curl, ConstValue::Int(33554432)),
    constant!("CURLPROTO_HTTP", Curl, ConstValue::Int(1)),
    constant!("CURLPROTO_HTTPS", Curl, ConstValue::Int(2)),
    constant!("CURLPROTO_IMAP", Curl, ConstValue::Int(4096)),
    constant!("CURLPROTO_IMAPS", Curl, ConstValue::Int(8192)),
    constant!("CURLPROTO_LDAP", Curl, ConstValue::Int(128)),
    constant!("CURLPROTO_LDAPS", Curl, ConstValue::Int(256)),
    constant!("CURLPROTO_MQTT", Curl, ConstValue::Int(268435456), since: Php82),
    constant!("CURLPROTO_POP3", Curl, ConstValue::Int(16384)),
    constant!("CURLPROTO_POP3S", Curl, ConstValue::Int(32768)),
    constant!("CURLPROTO_RTMP", Curl, ConstValue::Int(524288)),
    constant!("CURLPROTO_RTMPE", Curl, ConstValue::Int(2097152)),
    constant!("CURLPROTO_RTMPS", Curl, ConstValue::Int(8388608)),
    constant!("CURLPROTO_RTMPT", Curl, ConstValue::Int(1048576)),
    constant!("CURLPROTO_RTMPTE", Curl, ConstValue::Int(4194304)),
    constant!("CURLPROTO_RTMPTS", Curl, ConstValue::Int(16777216)),
    constant!("CURLPROTO_RTSP", Curl, ConstValue::Int(262144)),
    constant!("CURLPROTO_SCP", Curl, ConstValue::Int(16)),
    constant!("CURLPROTO_SFTP", Curl, ConstValue::Int(32)),
    constant!("CURLPROTO_SMB", Curl, ConstValue::Int(67108864)),
    constant!("CURLPROTO_SMBS", Curl, ConstValue::Int(134217728)),
    constant!("CURLPROTO_SMTP", Curl, ConstValue::Int(65536)),
    constant!("CURLPROTO_SMTPS", Curl, ConstValue::Int(131072)),
    constant!("CURLPROTO_TELNET", Curl, ConstValue::Int(64)),
    constant!("CURLPROTO_TFTP", Curl, ConstValue::Int(2048)),
    constant!("CURLPROXY_HTTP", Curl, ConstValue::Int(0)),
    constant!("CURLPROXY_HTTPS", Curl, ConstValue::Int(2)),
    constant!("CURLPROXY_HTTP_1_0", Curl, ConstValue::Int(1)),
    constant!("CURLPROXY_SOCKS4", Curl, ConstValue::Int(4)),
    constant!("CURLPROXY_SOCKS4A", Curl, ConstValue::Int(6)),
    constant!("CURLPROXY_SOCKS5", Curl, ConstValue::Int(5)),
    constant!("CURLPROXY_SOCKS5_HOSTNAME", Curl, ConstValue::Int(7)),
    constant!("CURLPX_BAD_ADDRESS_TYPE", Curl, ConstValue::Int(1), since: Php82),
    constant!("CURLPX_BAD_VERSION", Curl, ConstValue::Int(2), since: Php82),
    constant!("CURLPX_CLOSED", Curl, ConstValue::Int(3), since: Php82),
    constant!("CURLPX_GSSAPI", Curl, ConstValue::Int(4), since: Php82),
    constant!("CURLPX_GSSAPI_PERMSG", Curl, ConstValue::Int(5), since: Php82),
    constant!("CURLPX_GSSAPI_PROTECTION", Curl, ConstValue::Int(6), since: Php82),
    constant!("CURLPX_IDENTD", Curl, ConstValue::Int(7), since: Php82),
    constant!("CURLPX_IDENTD_DIFFER", Curl, ConstValue::Int(8), since: Php82),
    constant!("CURLPX_LONG_HOSTNAME", Curl, ConstValue::Int(9), since: Php82),
    constant!("CURLPX_LONG_PASSWD", Curl, ConstValue::Int(10), since: Php82),
    constant!("CURLPX_LONG_USER", Curl, ConstValue::Int(11), since: Php82),
    constant!("CURLPX_NO_AUTH", Curl, ConstValue::Int(12), since: Php82),
    constant!("CURLPX_OK", Curl, ConstValue::Int(0), since: Php82),
    constant!("CURLPX_RECV_ADDRESS", Curl, ConstValue::Int(13), since: Php82),
    constant!("CURLPX_RECV_AUTH", Curl, ConstValue::Int(14), since: Php82),
    constant!("CURLPX_RECV_CONNECT", Curl, ConstValue::Int(15), since: Php82),
    constant!("CURLPX_RECV_REQACK", Curl, ConstValue::Int(16), since: Php82),
    constant!("CURLPX_REPLY_ADDRESS_TYPE_NOT_SUPPORTED", Curl, ConstValue::Int(17), since: Php82),
    constant!("CURLPX_REPLY_COMMAND_NOT_SUPPORTED", Curl, ConstValue::Int(18), since: Php82),
    constant!("CURLPX_REPLY_CONNECTION_REFUSED", Curl, ConstValue::Int(19), since: Php82),
    constant!("CURLPX_REPLY_GENERAL_SERVER_FAILURE", Curl, ConstValue::Int(20), since: Php82),
    constant!("CURLPX_REPLY_HOST_UNREACHABLE", Curl, ConstValue::Int(21), since: Php82),
    constant!("CURLPX_REPLY_NETWORK_UNREACHABLE", Curl, ConstValue::Int(22), since: Php82),
    constant!("CURLPX_REPLY_NOT_ALLOWED", Curl, ConstValue::Int(23), since: Php82),
    constant!("CURLPX_REPLY_TTL_EXPIRED", Curl, ConstValue::Int(24), since: Php82),
    constant!("CURLPX_REPLY_UNASSIGNED", Curl, ConstValue::Int(25), since: Php82),
    constant!("CURLPX_REQUEST_FAILED", Curl, ConstValue::Int(26), since: Php82),
    constant!("CURLPX_RESOLVE_HOST", Curl, ConstValue::Int(27), since: Php82),
    constant!("CURLPX_SEND_AUTH", Curl, ConstValue::Int(28), since: Php82),
    constant!("CURLPX_SEND_CONNECT", Curl, ConstValue::Int(29), since: Php82),
    constant!("CURLPX_SEND_REQUEST", Curl, ConstValue::Int(30), since: Php82),
    constant!("CURLPX_UNKNOWN_FAIL", Curl, ConstValue::Int(31), since: Php82),
    constant!("CURLPX_UNKNOWN_MODE", Curl, ConstValue::Int(32), since: Php82),
    constant!("CURLPX_USER_REJECTED", Curl, ConstValue::Int(33), since: Php82),
    constant!("CURLSHOPT_NONE", Curl, ConstValue::Int(0)),
    constant!("CURLSHOPT_SHARE", Curl, ConstValue::Int(1)),
    constant!("CURLSHOPT_UNSHARE", Curl, ConstValue::Int(2)),
    constant!("CURLSSH_AUTH_AGENT", Curl, ConstValue::Int(16)),
    constant!("CURLSSH_AUTH_ANY", Curl, ConstValue::Int(4294967295)),
    constant!("CURLSSH_AUTH_DEFAULT", Curl, ConstValue::Int(4294967295)),
    constant!("CURLSSH_AUTH_GSSAPI", Curl, ConstValue::Int(32)),
    constant!("CURLSSH_AUTH_HOST", Curl, ConstValue::Int(4)),
    constant!("CURLSSH_AUTH_KEYBOARD", Curl, ConstValue::Int(8)),
    constant!("CURLSSH_AUTH_NONE", Curl, ConstValue::Int(0)),
    constant!("CURLSSH_AUTH_PASSWORD", Curl, ConstValue::Int(2)),
    constant!("CURLSSH_AUTH_PUBLICKEY", Curl, ConstValue::Int(1)),
    constant!("CURLSSLOPT_ALLOW_BEAST", Curl, ConstValue::Int(1)),
    constant!("CURLSSLOPT_AUTO_CLIENT_CERT", Curl, ConstValue::Int(32), since: Php82),
    constant!("CURLSSLOPT_NATIVE_CA", Curl, ConstValue::Int(16), since: Php82),
    constant!("CURLSSLOPT_NO_PARTIALCHAIN", Curl, ConstValue::Int(4), since: Php82),
    constant!("CURLSSLOPT_NO_REVOKE", Curl, ConstValue::Int(2)),
    constant!("CURLSSLOPT_REVOKE_BEST_EFFORT", Curl, ConstValue::Int(8), since: Php82),
    constant!("CURLUSESSL_ALL", Curl, ConstValue::Int(3)),
    constant!("CURLUSESSL_CONTROL", Curl, ConstValue::Int(2)),
    constant!("CURLUSESSL_NONE", Curl, ConstValue::Int(0)),
    constant!("CURLUSESSL_TRY", Curl, ConstValue::Int(1)),
    constant!("CURLVERSION_NOW", Curl, ConstValue::Int(11)),
    constant!("CURLWS_RAW_MODE", Curl, ConstValue::Int(1), since: Php83),
    constant!("CURL_FNMATCHFUNC_FAIL", Curl, ConstValue::Int(2)),
    constant!("CURL_FNMATCHFUNC_MATCH", Curl, ConstValue::Int(0)),
    constant!("CURL_FNMATCHFUNC_NOMATCH", Curl, ConstValue::Int(1)),
    constant!("CURL_HTTP_VERSION_1_0", Curl, ConstValue::Int(1)),
    constant!("CURL_HTTP_VERSION_1_1", Curl, ConstValue::Int(2)),
    constant!("CURL_HTTP_VERSION_2", Curl, ConstValue::Int(3)),
    constant!("CURL_HTTP_VERSION_2TLS", Curl, ConstValue::Int(4)),
    constant!("CURL_HTTP_VERSION_2_0", Curl, ConstValue::Int(3)),
    constant!("CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE", Curl, ConstValue::Int(5)),
    constant!("CURL_HTTP_VERSION_3", Curl, ConstValue::Int(30), since: Php84),
    constant!("CURL_HTTP_VERSION_3ONLY", Curl, ConstValue::Int(31), since: Php84),
    constant!("CURL_HTTP_VERSION_NONE", Curl, ConstValue::Int(0)),
    constant!("CURL_IPRESOLVE_V4", Curl, ConstValue::Int(1)),
    constant!("CURL_IPRESOLVE_V6", Curl, ConstValue::Int(2)),
    constant!("CURL_IPRESOLVE_WHATEVER", Curl, ConstValue::Int(0)),
    constant!("CURL_LOCK_DATA_CONNECT", Curl, ConstValue::Int(5)),
    constant!("CURL_LOCK_DATA_COOKIE", Curl, ConstValue::Int(2)),
    constant!("CURL_LOCK_DATA_DNS", Curl, ConstValue::Int(3)),
    constant!("CURL_LOCK_DATA_PSL", Curl, ConstValue::Int(6)),
    constant!("CURL_LOCK_DATA_SSL_SESSION", Curl, ConstValue::Int(4)),
    constant!("CURL_MAX_READ_SIZE", Curl, ConstValue::Int(10485760)),
    constant!("CURL_NETRC_IGNORED", Curl, ConstValue::Int(0)),
    constant!("CURL_NETRC_OPTIONAL", Curl, ConstValue::Int(1)),
    constant!("CURL_NETRC_REQUIRED", Curl, ConstValue::Int(2)),
    constant!("CURL_PREREQFUNC_ABORT", Curl, ConstValue::Int(1), since: Php84),
    constant!("CURL_PREREQFUNC_OK", Curl, ConstValue::Int(0), since: Php84),
    constant!("CURL_PUSH_DENY", Curl, ConstValue::Int(1)),
    constant!("CURL_PUSH_OK", Curl, ConstValue::Int(0)),
    constant!("CURL_READFUNC_PAUSE", Curl, ConstValue::Int(268435457)),
    constant!("CURL_REDIR_POST_301", Curl, ConstValue::Int(1)),
    constant!("CURL_REDIR_POST_302", Curl, ConstValue::Int(2)),
    constant!("CURL_REDIR_POST_303", Curl, ConstValue::Int(4)),
    constant!("CURL_REDIR_POST_ALL", Curl, ConstValue::Int(7)),
    constant!("CURL_RTSPREQ_ANNOUNCE", Curl, ConstValue::Int(3)),
    constant!("CURL_RTSPREQ_DESCRIBE", Curl, ConstValue::Int(2)),
    constant!("CURL_RTSPREQ_GET_PARAMETER", Curl, ConstValue::Int(8)),
    constant!("CURL_RTSPREQ_OPTIONS", Curl, ConstValue::Int(1)),
    constant!("CURL_RTSPREQ_PAUSE", Curl, ConstValue::Int(6)),
    constant!("CURL_RTSPREQ_PLAY", Curl, ConstValue::Int(5)),
    constant!("CURL_RTSPREQ_RECEIVE", Curl, ConstValue::Int(11)),
    constant!("CURL_RTSPREQ_RECORD", Curl, ConstValue::Int(10)),
    constant!("CURL_RTSPREQ_SETUP", Curl, ConstValue::Int(4)),
    constant!("CURL_RTSPREQ_SET_PARAMETER", Curl, ConstValue::Int(9)),
    constant!("CURL_RTSPREQ_TEARDOWN", Curl, ConstValue::Int(7)),
    constant!("CURL_SSLVERSION_DEFAULT", Curl, ConstValue::Int(0)),
    constant!("CURL_SSLVERSION_MAX_DEFAULT", Curl, ConstValue::Int(65536)),
    constant!("CURL_SSLVERSION_MAX_NONE", Curl, ConstValue::Int(0)),
    constant!("CURL_SSLVERSION_MAX_TLSv1_0", Curl, ConstValue::Int(262144)),
    constant!("CURL_SSLVERSION_MAX_TLSv1_1", Curl, ConstValue::Int(327680)),
    constant!("CURL_SSLVERSION_MAX_TLSv1_2", Curl, ConstValue::Int(393216)),
    constant!("CURL_SSLVERSION_MAX_TLSv1_3", Curl, ConstValue::Int(458752)),
    constant!("CURL_SSLVERSION_SSLv2", Curl, ConstValue::Int(2)),
    constant!("CURL_SSLVERSION_SSLv3", Curl, ConstValue::Int(3)),
    constant!("CURL_SSLVERSION_TLSv1", Curl, ConstValue::Int(1)),
    constant!("CURL_SSLVERSION_TLSv1_0", Curl, ConstValue::Int(4)),
    constant!("CURL_SSLVERSION_TLSv1_1", Curl, ConstValue::Int(5)),
    constant!("CURL_SSLVERSION_TLSv1_2", Curl, ConstValue::Int(6)),
    constant!("CURL_SSLVERSION_TLSv1_3", Curl, ConstValue::Int(7)),
    constant!("CURL_TIMECOND_IFMODSINCE", Curl, ConstValue::Int(1)),
    constant!("CURL_TIMECOND_IFUNMODSINCE", Curl, ConstValue::Int(2)),
    constant!("CURL_TIMECOND_LASTMOD", Curl, ConstValue::Int(3)),
    constant!("CURL_TIMECOND_NONE", Curl, ConstValue::Int(0)),
    constant!("CURL_TLSAUTH_SRP", Curl, ConstValue::Int(1)),
    constant!("CURL_VERSION_ALTSVC", Curl, ConstValue::Int(16777216)),
    constant!("CURL_VERSION_ASYNCHDNS", Curl, ConstValue::Int(128)),
    constant!("CURL_VERSION_BROTLI", Curl, ConstValue::Int(8388608)),
    constant!("CURL_VERSION_CONV", Curl, ConstValue::Int(4096)),
    constant!("CURL_VERSION_CURLDEBUG", Curl, ConstValue::Int(8192)),
    constant!("CURL_VERSION_DEBUG", Curl, ConstValue::Int(64)),
    constant!("CURL_VERSION_GSASL", Curl, ConstValue::Int(536870912), since: Php82),
    constant!("CURL_VERSION_GSSAPI", Curl, ConstValue::Int(131072)),
    constant!("CURL_VERSION_GSSNEGOTIATE", Curl, ConstValue::Int(32)),
    constant!("CURL_VERSION_HSTS", Curl, ConstValue::Int(268435456), since: Php82),
    constant!("CURL_VERSION_HTTP2", Curl, ConstValue::Int(65536)),
    constant!("CURL_VERSION_HTTP3", Curl, ConstValue::Int(33554432), since: Php82),
    constant!("CURL_VERSION_HTTPS_PROXY", Curl, ConstValue::Int(2097152)),
    constant!("CURL_VERSION_IDN", Curl, ConstValue::Int(1024)),
    constant!("CURL_VERSION_IPV6", Curl, ConstValue::Int(1)),
    constant!("CURL_VERSION_KERBEROS4", Curl, ConstValue::Int(2)),
    constant!("CURL_VERSION_KERBEROS5", Curl, ConstValue::Int(262144)),
    constant!("CURL_VERSION_LARGEFILE", Curl, ConstValue::Int(512)),
    constant!("CURL_VERSION_LIBZ", Curl, ConstValue::Int(8)),
    constant!("CURL_VERSION_MULTI_SSL", Curl, ConstValue::Int(4194304)),
    constant!("CURL_VERSION_NTLM", Curl, ConstValue::Int(16)),
    constant!("CURL_VERSION_NTLM_WB", Curl, ConstValue::Int(32768)),
    constant!("CURL_VERSION_PSL", Curl, ConstValue::Int(1048576)),
    constant!("CURL_VERSION_SPNEGO", Curl, ConstValue::Int(256)),
    constant!("CURL_VERSION_SSL", Curl, ConstValue::Int(4)),
    constant!("CURL_VERSION_SSPI", Curl, ConstValue::Int(2048)),
    constant!("CURL_VERSION_TLSAUTH_SRP", Curl, ConstValue::Int(16384)),
    constant!("CURL_VERSION_UNICODE", Curl, ConstValue::Int(134217728), since: Php82),
    constant!("CURL_VERSION_UNIX_SOCKETS", Curl, ConstValue::Int(524288)),
    constant!("CURL_VERSION_ZSTD", Curl, ConstValue::Int(67108864), since: Php82),
    constant!("CURL_WRITEFUNC_PAUSE", Curl, ConstValue::Int(268435457)),
];
