//! Purpose:
//! Canonical contracts for every PHP builtin class-like elephc provides, with the PHP module
//! that owns each one. Seeded once from the compiler's former class-name lists and the built
//! prelude declarations; authoritative from then on.
//!
//! Called from:
//! - `crate::symbol_registry` for validation and lookup.
//!
//! Key details:
//! - Entries are sorted by canonical lowercase name; the registry rejects any other order.
//! - `ext/curl` classes are here, unconditionally: the compiler's curl prelude declares them in
//!   every build, only their Magician support follows the `curl` feature (see `support.rs`).

use crate::{BuiltinId, ClassContract, ClassKind, ClassRoute, PhpModule, PhpVersion};

macro_rules! class {
    (
        $name:literal, $canonical:literal, $kind:ident, $module:ident, $route:ident
        $(, since: $since:ident)? $(, extension: $extension:literal)? $(, internal: $internal:literal)? $(,)?
    ) => {
        ClassContract {
            id: BuiltinId::from_canonical_name($canonical),
            name: $name,
            kind: ClassKind::$kind,
            module: PhpModule::$module,
            since: class!(@since $($since)?),
            aot: ClassRoute::$route,
            extension: class!(@flag $($extension)?),
            internal: class!(@flag $($internal)?),
            php_manual: None,
        }
    };
    (@since $since:ident) => { Some(PhpVersion::$since) };
    (@since) => { None };
    (@flag $value:literal) => { $value };
    (@flag) => { false };
}

pub(crate) static CLASSES: &[ClassContract] = &[
    class!("__ElephcCallableSessionHandler", "__elephccallablesessionhandler", Class, Elephc, Prelude, internal: true),
    class!("__ElephcMysqliResultIterator", "__elephcmysqliresultiterator", Class, Elephc, Prelude, internal: true),
    class!("__ElephcPDOPgsqlLobStream", "__elephcpdopgsqllobstream", Class, Elephc, Prelude, internal: true),
    class!("__ElephcPDOSqliteBlobStream", "__elephcpdosqliteblobstream", Class, Elephc, Prelude, internal: true),
    class!("__ElephcPDOStatementIterator", "__elephcpdostatementiterator", Class, Elephc, Prelude, internal: true),
    class!("__ElephcSessionState", "__elephcsessionstate", Class, Elephc, Prelude, internal: true),
    class!("AppendIterator", "appenditerator", Class, Spl, CheckerInjected),
    class!("ArgumentCountError", "argumentcounterror", Class, Core, CheckerInjected),
    class!("ArithmeticError", "arithmeticerror", Class, Core, CheckerInjected),
    class!("ArrayAccess", "arrayaccess", Interface, Core, CheckerInjected),
    class!("ArrayIterator", "arrayiterator", Class, Spl, CheckerInjected),
    class!("ArrayObject", "arrayobject", Class, Spl, CheckerInjected),
    class!("AssertionError", "assertionerror", Class, Standard, CheckerInjected),
    class!("BadFunctionCallException", "badfunctioncallexception", Class, Spl, CheckerInjected),
    class!("BadMethodCallException", "badmethodcallexception", Class, Spl, CheckerInjected),
    class!("CachingIterator", "cachingiterator", Class, Spl, CheckerInjected),
    class!("CairoAntialias", "cairoantialias", Class, Cairo, Prelude),
    class!("CairoContext", "cairocontext", Class, Cairo, Prelude),
    class!("CairoException", "cairoexception", Class, Cairo, Prelude),
    class!("CairoFillRule", "cairofillrule", Class, Cairo, Prelude),
    class!("CairoFontFace", "cairofontface", Class, Cairo, Prelude),
    class!("CairoFontOptions", "cairofontoptions", Class, Cairo, Prelude),
    class!("CairoFontSlant", "cairofontslant", Class, Cairo, Prelude),
    class!("CairoFontWeight", "cairofontweight", Class, Cairo, Prelude),
    class!("CairoFormat", "cairoformat", Class, Cairo, Prelude),
    class!("CairoGradientPattern", "cairogradientpattern", Class, Cairo, Prelude),
    class!("CairoImageSurface", "cairoimagesurface", Class, Cairo, Prelude),
    class!("CairoLinearGradient", "cairolineargradient", Class, Cairo, Prelude),
    class!("CairoLineCap", "cairolinecap", Class, Cairo, Prelude),
    class!("CairoLineJoin", "cairolinejoin", Class, Cairo, Prelude),
    class!("CairoMatrix", "cairomatrix", Class, Cairo, Prelude),
    class!("CairoPath", "cairopath", Class, Cairo, Prelude),
    class!("CairoPattern", "cairopattern", Class, Cairo, Prelude),
    class!("CairoPdfSurface", "cairopdfsurface", Class, Cairo, Prelude),
    class!("CairoPsSurface", "cairopssurface", Class, Cairo, Prelude),
    class!("CairoRadialGradient", "cairoradialgradient", Class, Cairo, Prelude),
    class!("CairoScaledFont", "cairoscaledfont", Class, Cairo, Prelude),
    class!("CairoSolidPattern", "cairosolidpattern", Class, Cairo, Prelude),
    class!("CairoSurface", "cairosurface", Class, Cairo, Prelude),
    class!("CairoSurfacePattern", "cairosurfacepattern", Class, Cairo, Prelude),
    class!("CairoSvgSurface", "cairosvgsurface", Class, Cairo, Prelude),
    class!("CairoToyFontFace", "cairotoyfontface", Class, Cairo, Prelude),
    class!("CallbackFilterIterator", "callbackfilteriterator", Class, Spl, CheckerInjected),
    class!("Countable", "countable", Interface, Core, CheckerInjected),
    class!("CURLFile", "curlfile", Class, Curl, Prelude),
    class!("CurlHandle", "curlhandle", Class, Curl, Prelude),
    class!("CurlMultiHandle", "curlmultihandle", Class, Curl, Prelude),
    class!("CurlShareHandle", "curlsharehandle", Class, Curl, Prelude),
    class!("CurlSharePersistentHandle", "curlsharepersistenthandle", Class, Curl, Prelude, since: Php85),
    class!("CURLStringFile", "curlstringfile", Class, Curl, Prelude, since: Php81),
    class!("DateError", "dateerror", Class, Date, CheckerInjected, since: Php83),
    class!("DateException", "dateexception", Class, Date, CheckerInjected, since: Php83),
    class!("DateInterval", "dateinterval", Class, Date, CheckerInjected),
    class!("DateInvalidOperationException", "dateinvalidoperationexception", Class, Date, CheckerInjected, since: Php83),
    class!("DateInvalidTimeZoneException", "dateinvalidtimezoneexception", Class, Date, CheckerInjected, since: Php83),
    class!("DateMalformedIntervalStringException", "datemalformedintervalstringexception", Class, Date, CheckerInjected, since: Php83),
    class!("DateMalformedPeriodStringException", "datemalformedperiodstringexception", Class, Date, CheckerInjected, since: Php83),
    class!("DateMalformedStringException", "datemalformedstringexception", Class, Date, CheckerInjected, since: Php83),
    class!("DateObjectError", "dateobjecterror", Class, Date, CheckerInjected, since: Php83),
    class!("DatePeriod", "dateperiod", Class, Date, CheckerInjected),
    class!("DateRangeError", "daterangeerror", Class, Date, CheckerInjected, since: Php83),
    class!("DateTime", "datetime", Class, Date, CheckerInjected),
    class!("DateTimeImmutable", "datetimeimmutable", Class, Date, CheckerInjected),
    class!("DateTimeInterface", "datetimeinterface", Interface, Date, CheckerInjected),
    class!("DateTimeZone", "datetimezone", Class, Date, CheckerInjected),
    class!("DateUnknownException", "dateunknownexception", Class, Date, CheckerInjected, extension: true),
    class!("DirectoryIterator", "directoryiterator", Class, Spl, CheckerInjected),
    class!("DivisionByZeroError", "divisionbyzeroerror", Class, Core, CheckerInjected),
    class!("DomainException", "domainexception", Class, Spl, CheckerInjected),
    class!("EmptyIterator", "emptyiterator", Class, Spl, CheckerInjected),
    class!("Error", "error", Class, Core, CheckerInjected),
    class!("Exception", "exception", Class, Core, CheckerInjected),
    class!("Fiber", "fiber", Class, Core, CheckerInjected, since: Php81),
    class!("FiberError", "fibererror", Class, Core, CheckerInjected, since: Php81),
    class!("FilesystemIterator", "filesystemiterator", Class, Spl, CheckerInjected),
    class!("FilterIterator", "filteriterator", Class, Spl, CheckerInjected),
    class!("GdImage", "gdimage", Class, Gd, Prelude),
    class!("Generator", "generator", Class, Core, LanguageIntrinsic),
    class!("GlobIterator", "globiterator", Class, Spl, CheckerInjected),
    class!("Gmagick", "gmagick", Class, Gmagick, Prelude),
    class!("GmagickDraw", "gmagickdraw", Class, Gmagick, Prelude),
    class!("GmagickDrawException", "gmagickdrawexception", Class, Gmagick, Prelude),
    class!("GmagickException", "gmagickexception", Class, Gmagick, Prelude),
    class!("GmagickPixel", "gmagickpixel", Class, Gmagick, Prelude),
    class!("GmagickPixelException", "gmagickpixelexception", Class, Gmagick, Prelude),
    class!("HashContext", "hashcontext", Class, Hash, Prelude),
    class!("ImageException", "imageexception", Class, Gd, Prelude, extension: true),
    class!("Imagick", "imagick", Class, Imagick, Prelude),
    class!("ImagickDraw", "imagickdraw", Class, Imagick, Prelude),
    class!("ImagickDrawException", "imagickdrawexception", Class, Imagick, Prelude),
    class!("ImagickException", "imagickexception", Class, Imagick, Prelude),
    class!("ImagickKernel", "imagickkernel", Class, Imagick, Prelude),
    class!("ImagickKernelException", "imagickkernelexception", Class, Imagick, Prelude),
    class!("ImagickPixel", "imagickpixel", Class, Imagick, Prelude),
    class!("ImagickPixelException", "imagickpixelexception", Class, Imagick, Prelude),
    class!("ImagickPixelIterator", "imagickpixeliterator", Class, Imagick, Prelude),
    class!("ImagickPixelIteratorException", "imagickpixeliteratorexception", Class, Imagick, Prelude),
    class!("InfiniteIterator", "infiniteiterator", Class, Spl, CheckerInjected),
    class!("InternalIterator", "internaliterator", Class, Core, CheckerInjected),
    class!("InvalidArgumentException", "invalidargumentexception", Class, Spl, CheckerInjected),
    class!("Iterator", "iterator", Interface, Core, CheckerInjected),
    class!("IteratorAggregate", "iteratoraggregate", Interface, Core, CheckerInjected),
    class!("IteratorIterator", "iteratoriterator", Class, Spl, CheckerInjected),
    class!("JsonException", "jsonexception", Class, Json, CheckerInjected),
    class!("JsonSerializable", "jsonserializable", Interface, Json, CheckerInjected),
    class!("LengthException", "lengthexception", Class, Spl, CheckerInjected),
    class!("LimitIterator", "limititerator", Class, Spl, CheckerInjected),
    class!("LogicException", "logicexception", Class, Spl, CheckerInjected),
    class!("MultipleIterator", "multipleiterator", Class, Spl, CheckerInjected),
    class!("mysqli", "mysqli", Class, Mysqli, Prelude),
    class!("mysqli_result", "mysqli_result", Class, Mysqli, Prelude),
    class!("mysqli_sql_exception", "mysqli_sql_exception", Class, Mysqli, Prelude),
    class!("mysqli_stmt", "mysqli_stmt", Class, Mysqli, Prelude),
    class!("NoRewindIterator", "norewinditerator", Class, Spl, CheckerInjected),
    class!("OuterIterator", "outeriterator", Interface, Spl, CheckerInjected),
    class!("OutOfBoundsException", "outofboundsexception", Class, Spl, CheckerInjected),
    class!("OutOfRangeException", "outofrangeexception", Class, Spl, CheckerInjected),
    class!("OverflowException", "overflowexception", Class, Spl, CheckerInjected),
    class!("ParentIterator", "parentiterator", Class, Spl, CheckerInjected),
    class!("PDO", "pdo", Class, Pdo, Prelude),
    class!("Pdo\\Dblib", "pdo\\dblib", Class, PdoDblib, Prelude, since: Php84),
    class!("Pdo\\Firebird", "pdo\\firebird", Class, PdoFirebird, Prelude, since: Php84),
    class!("Pdo\\Ibm", "pdo\\ibm", Class, PdoIbm, Prelude),
    class!("Pdo\\Mysql", "pdo\\mysql", Class, PdoMysql, Prelude, since: Php84),
    class!("Pdo\\Odbc", "pdo\\odbc", Class, PdoOdbc, Prelude, since: Php84),
    class!("Pdo\\Pgsql", "pdo\\pgsql", Class, PdoPgsql, Prelude, since: Php84),
    class!("Pdo\\Sqlite", "pdo\\sqlite", Class, PdoSqlite, Prelude, since: Php84),
    class!("PDOException", "pdoexception", Class, Pdo, Prelude),
    class!("PDORow", "pdorow", Class, Pdo, Prelude),
    class!("PDOStatement", "pdostatement", Class, Pdo, Prelude),
    class!("Phar", "phar", Class, Phar, CheckerInjected),
    class!("PharData", "phardata", Class, Phar, CheckerInjected),
    class!("PharFileInfo", "pharfileinfo", Class, Phar, CheckerInjected),
    class!("php_user_filter", "php_user_filter", Class, Standard, CheckerInjected),
    class!("PropertyHookType", "propertyhooktype", Enum, Reflection, CheckerInjected, since: Php84),
    class!("RangeException", "rangeexception", Class, Spl, CheckerInjected),
    class!("RecursiveArrayIterator", "recursivearrayiterator", Class, Spl, CheckerInjected),
    class!("RecursiveCachingIterator", "recursivecachingiterator", Class, Spl, CheckerInjected),
    class!("RecursiveCallbackFilterIterator", "recursivecallbackfilteriterator", Class, Spl, CheckerInjected),
    class!("RecursiveDirectoryIterator", "recursivedirectoryiterator", Class, Spl, CheckerInjected),
    class!("RecursiveFilterIterator", "recursivefilteriterator", Class, Spl, CheckerInjected),
    class!("RecursiveIterator", "recursiveiterator", Interface, Spl, CheckerInjected),
    class!("RecursiveIteratorIterator", "recursiveiteratoriterator", Class, Spl, CheckerInjected),
    class!("RecursiveRegexIterator", "recursiveregexiterator", Class, Spl, CheckerInjected),
    class!("ReflectionAttribute", "reflectionattribute", Class, Reflection, CheckerInjected),
    class!("ReflectionClass", "reflectionclass", Class, Reflection, CheckerInjected),
    class!("ReflectionClassConstant", "reflectionclassconstant", Class, Reflection, CheckerInjected),
    class!("ReflectionEnum", "reflectionenum", Class, Reflection, CheckerInjected, since: Php81),
    class!("ReflectionEnumBackedCase", "reflectionenumbackedcase", Class, Reflection, CheckerInjected, since: Php81),
    class!("ReflectionEnumUnitCase", "reflectionenumunitcase", Class, Reflection, CheckerInjected, since: Php81),
    class!("ReflectionException", "reflectionexception", Class, Reflection, CheckerInjected),
    class!("ReflectionFunction", "reflectionfunction", Class, Reflection, CheckerInjected),
    class!("ReflectionIntersectionType", "reflectionintersectiontype", Class, Reflection, CheckerInjected, since: Php81),
    class!("ReflectionMethod", "reflectionmethod", Class, Reflection, CheckerInjected),
    class!("ReflectionNamedType", "reflectionnamedtype", Class, Reflection, CheckerInjected),
    class!("ReflectionObject", "reflectionobject", Class, Reflection, CheckerInjected),
    class!("ReflectionParameter", "reflectionparameter", Class, Reflection, CheckerInjected),
    class!("ReflectionProperty", "reflectionproperty", Class, Reflection, CheckerInjected),
    class!("ReflectionUnionType", "reflectionuniontype", Class, Reflection, CheckerInjected),
    class!("RegexIterator", "regexiterator", Class, Spl, CheckerInjected),
    class!("RuntimeException", "runtimeexception", Class, Spl, CheckerInjected),
    class!("SeekableIterator", "seekableiterator", Interface, Spl, CheckerInjected),
    class!("SessionHandler", "sessionhandler", Class, Session, Prelude),
    class!("SessionHandlerInterface", "sessionhandlerinterface", Interface, Session, Prelude),
    class!("SessionIdInterface", "sessionidinterface", Interface, Session, Prelude),
    class!("SessionUpdateTimestampHandlerInterface", "sessionupdatetimestamphandlerinterface", Interface, Session, Prelude),
    class!("SortDirection", "sortdirection", Enum, Core, CheckerInjected, since: Php86),
    class!("SplDoublyLinkedList", "spldoublylinkedlist", Class, Spl, CheckerInjected),
    class!("SplFileInfo", "splfileinfo", Class, Spl, CheckerInjected),
    class!("SplFileObject", "splfileobject", Class, Spl, CheckerInjected),
    class!("SplFixedArray", "splfixedarray", Class, Spl, CheckerInjected),
    class!("SplHeap", "splheap", Class, Spl, CheckerInjected),
    class!("SplMaxHeap", "splmaxheap", Class, Spl, CheckerInjected),
    class!("SplMinHeap", "splminheap", Class, Spl, CheckerInjected),
    class!("SplObjectStorage", "splobjectstorage", Class, Spl, CheckerInjected),
    class!("SplObserver", "splobserver", Interface, Spl, CheckerInjected),
    class!("SplPriorityQueue", "splpriorityqueue", Class, Spl, CheckerInjected),
    class!("SplQueue", "splqueue", Class, Spl, CheckerInjected),
    class!("SplStack", "splstack", Class, Spl, CheckerInjected),
    class!("SplSubject", "splsubject", Interface, Spl, CheckerInjected),
    class!("SplTempFileObject", "spltempfileobject", Class, Spl, CheckerInjected),
    class!("stdClass", "stdclass", Class, Core, LanguageIntrinsic),
    class!("Stringable", "stringable", Interface, Core, CheckerInjected),
    class!("Throwable", "throwable", Interface, Core, CheckerInjected),
    class!("Traversable", "traversable", Interface, Core, CheckerInjected),
    class!("TypeError", "typeerror", Class, Core, CheckerInjected),
    class!("UnderflowException", "underflowexception", Class, Spl, CheckerInjected),
    class!("UnexpectedValueException", "unexpectedvalueexception", Class, Spl, CheckerInjected),
    class!("UnhandledMatchError", "unhandledmatcherror", Class, Core, CheckerInjected),
    class!("ValueError", "valueerror", Class, Core, CheckerInjected),
];
