//! Purpose:
//! Owns the PHP surface contracts for functions backed by the shared mbstring engine.
//!
//! Called from:
//! - The neutral contract registry before compiler and Magician bindings are joined.
//!
//! Key details:
//! - Parameter names, nullable defaults, and return types follow the PHP 8.5 baseline.
//! - The runtime implementation and target adapters carry no duplicate PHP signatures.

use crate::{Area, BuiltinContract, BuiltinId, BuiltinKind, DefaultSpec, ParamSpec, PhpModule, PhpVersion, TypeSpec};

pub(crate) static CONTRACTS: &[BuiltinContract] = &[
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_output_handler"), name: "mb_output_handler",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "status", ty: TypeSpec::Int, default: None, by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Converts an output-buffer phase using the request encodings, MIME selection, and substitution settings.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-output-handler.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("__elephc_shared_ini"), name: "__elephc_shared_ini",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "operation", ty: TypeSpec::Int, default: None, by_ref: false },
            ParamSpec { name: "option", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "value", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "details", ty: TypeSpec::Bool, default: None, by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Mixed, by_ref_return: false,
        summary: "Dispatches prelude INI operations to shared Core and mbstring request state.", examples: &[],
        php_manual: None, deprecation: None, extension: false, internal: true, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_parse_str"), name: "mb_parse_str",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "result", ty: TypeSpec::Mixed, default: None, by_ref: true },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Bool, by_ref_return: false,
        summary: "Parses URL-encoded input with shared encoding detection and writes decoded variables by reference.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-parse-str.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg"), name: "mb_ereg",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "matches", ty: TypeSpec::Mixed, default: Some(DefaultSpec::Null), by_ref: true },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Bool, by_ref_return: false,
        summary: "Searches a multibyte string and optionally writes numeric and named captures by reference.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_eregi"), name: "mb_eregi",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "matches", ty: TypeSpec::Mixed, default: Some(DefaultSpec::Null), by_ref: true },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Bool, by_ref_return: false,
        summary: "Searches without case sensitivity and optionally writes multibyte captures by reference.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-eregi.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_replace"), name: "mb_ereg_replace",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "replacement", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False, TypeSpec::Null]), by_ref_return: false,
        summary: "Replaces multibyte regex matches using numbered and named capture references.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-replace.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_replace_callback"), name: "mb_ereg_replace_callback",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "callback", ty: TypeSpec::Callable, default: None, by_ref: false },
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False, TypeSpec::Null]), by_ref_return: false,
        summary: "Replaces multibyte regex matches with the string result of a callback receiving all captures.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-replace-callback.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_eregi_replace"), name: "mb_eregi_replace",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "replacement", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False, TypeSpec::Null]), by_ref_return: false,
        summary: "Replaces multibyte regex matches without case sensitivity.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-eregi-replace.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_split"), name: "mb_split",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "limit", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(-1)), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::False]), by_ref_return: false,
        summary: "Splits a string using a multibyte regex and an optional maximum number of fields.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-split.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_search_init"), name: "mb_ereg_search_init",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "pattern", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Bool, by_ref_return: false,
        summary: "Initializes the retained multibyte regex subject and optionally compiles a search pattern.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-search-init.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_search"), name: "mb_ereg_search",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Bool, by_ref_return: false,
        summary: "Searches the retained multibyte subject and advances the shared byte position.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-search.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_search_pos"), name: "mb_ereg_search_pos",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::False]), by_ref_return: false,
        summary: "Returns the next multibyte regex match byte offset and length, or false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-search-pos.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_search_regs"), name: "mb_ereg_search_regs",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::False]), by_ref_return: false,
        summary: "Returns the next multibyte regex match and captured groups, preserving numeric and named keys.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-search-regs.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_search_getpos"), name: "mb_ereg_search_getpos",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Int, by_ref_return: false,
        summary: "Reads the current byte position in the retained multibyte regex subject.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-search-getpos.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_search_getregs"), name: "mb_ereg_search_getregs",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::False]), by_ref_return: false,
        summary: "Returns the retained multibyte regex captures from the last successful progressive search.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-search-getregs.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_search_setpos"), name: "mb_ereg_search_setpos",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "offset", ty: TypeSpec::Int, default: None, by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Bool, by_ref_return: false,
        summary: "Changes the progressive regex byte position, accepting negative offsets relative to the retained subject.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-search-setpos.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ereg_match"), name: "mb_ereg_match",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "pattern", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Bool, by_ref_return: false,
        summary: "Tests a raw multibyte regex at the string start using the current regex encoding and options.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ereg-match.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_regex_encoding"), name: "mb_regex_encoding",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false }],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::Bool]), by_ref_return: false,
        summary: "Reads or changes the multibyte regex encoding independently of the internal text encoding.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-regex-encoding.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_regex_set_options"), name: "mb_regex_set_options",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "options", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false }],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Reads multibyte regex options, or changes them and returns the previous canonical option string.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-regex-set-options.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_http_input"), name: "mb_http_input",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "type", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false }],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Returns recorded HTTP input encoding identification or the configured input encoding list.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-http-input.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_get_info"), name: "mb_get_info",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "type", ty: TypeSpec::Str, default: Some(DefaultSpec::Str("all")), by_ref: false }],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Str, TypeSpec::Int, TypeSpec::False, TypeSpec::Null]), by_ref_return: false,
        summary: "Returns the current mbstring request settings or one selected information value.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-get-info.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_encode_mimeheader"), name: "mb_encode_mimeheader",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "charset", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "transfer_encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "newline", ty: TypeSpec::Str, default: Some(DefaultSpec::Str("\r\n")), by_ref: false },
            ParamSpec { name: "indent", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(0)), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Encodes a MIME header with language defaults, Base64 or Q transfer, and folded lines.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-encode-mimeheader.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_decode_mimeheader"), name: "mb_decode_mimeheader",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false }],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Decodes MIME header words into the current internal encoding and unfolds whitespace.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-decode-mimeheader.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_convert_encoding"), name: "mb_convert_encoding",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Str]), default: None, by_ref: false },
            ParamSpec { name: "to_encoding", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "from_encoding", ty: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Str, TypeSpec::Null]), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Converts strings and recursive array keys and values between character encodings.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-convert-encoding.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_detect_encoding"), name: "mb_detect_encoding",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encodings", ty: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Str, TypeSpec::Null]),
                default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "strict", ty: TypeSpec::Bool, default: Some(DefaultSpec::Bool(false)), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Guesses the most likely candidate encoding using the request's detection settings.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-detect-encoding.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_encode_numericentity"), name: "mb_encode_numericentity",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "map", ty: TypeSpec::Array, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "hex", ty: TypeSpec::Bool, default: Some(DefaultSpec::Bool(false)), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Encodes mapped characters as decimal or hexadecimal numeric entities.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-encode-numericentity.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_decode_numericentity"), name: "mb_decode_numericentity",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "map", ty: TypeSpec::Array, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Decodes numeric entities selected by the ordered conversion map.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-decode-numericentity.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_detect_order"), name: "mb_detect_order",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "encoding", ty: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Str, TypeSpec::Null]),
            default: Some(DefaultSpec::Null), by_ref: false }],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Bool]), by_ref_return: false,
        summary: "Reads or updates the request's encoding detection order.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-detect-order.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_list_encodings"), name: "mb_list_encodings",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function, params: &[],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Array, by_ref_return: false,
        summary: "Lists every supported canonical encoding in PHP order.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-list-encodings.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_convert_case"), name: "mb_convert_case",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "mode", ty: TypeSpec::Int, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Converts case using one of the eight Unicode case modes.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-convert-case.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_lcfirst"), name: "mb_lcfirst",
        area: Area::String, module: PhpModule::Mbstring, since: Some(PhpVersion::Php84),
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Converts the first character to Unicode lowercase.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-lcfirst.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strimwidth"), name: "mb_strimwidth",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "start", ty: TypeSpec::Int, default: None, by_ref: false },
            ParamSpec { name: "width", ty: TypeSpec::Int, default: None, by_ref: false },
            ParamSpec { name: "trim_marker", ty: TypeSpec::Str, default: Some(DefaultSpec::Str("")), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Trims a string to a display width and appends a marker when needed.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strimwidth.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strlen"),
        name: "mb_strlen",
        area: Area::String,
        module: PhpModule::Mbstring,
        since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec {
                name: "string",
                ty: TypeSpec::Str,
                default: None,
                by_ref: false,
            },
            ParamSpec {
                name: "encoding",
                ty: TypeSpec::Nullable(&TypeSpec::Str),
                default: Some(DefaultSpec::Null),
                by_ref: false,
            },
        ],
        variadic: None,
        variadic_by_ref: false,
        min_args: None,
        max_args: None,
        arity_error: None,
        returns: TypeSpec::Int,
        by_ref_return: false,
        summary: "Returns the character count of a string in the requested encoding.",
        examples: &[
        ],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strlen.php"),
        deprecation: None,
        extension: false,
        internal: false,
        requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strtolower"), name: "mb_strtolower",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Converts every character to its Unicode lowercase mapping.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strtolower.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strtoupper"), name: "mb_strtoupper",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Converts every character to its Unicode uppercase mapping.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strtoupper.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strwidth"), name: "mb_strwidth",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Int, by_ref_return: false,
        summary: "Returns the display width of a string in the requested encoding.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strwidth.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ucfirst"), name: "mb_ucfirst",
        area: Area::String, module: PhpModule::Mbstring, since: Some(PhpVersion::Php84),
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Converts the first character to Unicode title case.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ucfirst.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_substr"), name: "mb_substr",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "start", ty: TypeSpec::Int, default: None, by_ref: false },
            ParamSpec { name: "length", ty: TypeSpec::Nullable(&TypeSpec::Int), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Selects a substring using character offsets and an optional character length.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-substr.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strcut"), name: "mb_strcut",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "start", ty: TypeSpec::Int, default: None, by_ref: false },
            ParamSpec { name: "length", ty: TypeSpec::Nullable(&TypeSpec::Int), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Selects complete encoded characters within a byte offset and length.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strcut.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_scrub"), name: "mb_scrub",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Replaces malformed encoded units using the current substitution setting.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-scrub.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_trim"), name: "mb_trim",
        area: Area::String, module: PhpModule::Mbstring, since: Some(PhpVersion::Php84),
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "characters", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Removes Unicode whitespace or the specified characters from both ends.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-trim.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ltrim"), name: "mb_ltrim",
        area: Area::String, module: PhpModule::Mbstring, since: Some(PhpVersion::Php84),
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "characters", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Removes Unicode whitespace or the specified characters from the beginning.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ltrim.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_rtrim"), name: "mb_rtrim",
        area: Area::String, module: PhpModule::Mbstring, since: Some(PhpVersion::Php84),
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "characters", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Removes Unicode whitespace or the specified characters from the end.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-rtrim.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_str_pad"), name: "mb_str_pad",
        area: Area::String, module: PhpModule::Mbstring, since: Some(PhpVersion::Php83),
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "length", ty: TypeSpec::Int, default: None, by_ref: false },
            ParamSpec { name: "pad_string", ty: TypeSpec::Str, default: Some(DefaultSpec::Str(" ")), by_ref: false },
            ParamSpec { name: "pad_type", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(1)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Pads a string to a character length using the requested side and encoding.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-str-pad.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_convert_kana"), name: "mb_convert_kana",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "mode", ty: TypeSpec::Str, default: Some(DefaultSpec::Str("KV")), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Str, by_ref_return: false,
        summary: "Converts Japanese width and kana according to the requested mode flags.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-convert-kana.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_substr_count"), name: "mb_substr_count",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Int, by_ref_return: false,
        summary: "Counts non-overlapping occurrences of an encoded substring.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-substr-count.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_ord"), name: "mb_ord",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Int, TypeSpec::False]), by_ref_return: false,
        summary: "Returns the first Unicode codepoint, or false for malformed input.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-ord.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_chr"), name: "mb_chr",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "codepoint", ty: TypeSpec::Int, default: None, by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Encodes a Unicode codepoint, or returns false when it cannot be represented.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-chr.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strpos"), name: "mb_strpos",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "offset", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(0)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Int, TypeSpec::False]), by_ref_return: false,
        summary: "Finds the first character position of an encoded substring, or returns false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strpos.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_stripos"), name: "mb_stripos",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "offset", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(0)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Int, TypeSpec::False]), by_ref_return: false,
        summary: "Finds the first character position using simple case folding, or returns false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-stripos.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strrpos"), name: "mb_strrpos",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "offset", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(0)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Int, TypeSpec::False]), by_ref_return: false,
        summary: "Finds the last character position of an encoded substring, or returns false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strrpos.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strripos"), name: "mb_strripos",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "offset", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(0)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Int, TypeSpec::False]), by_ref_return: false,
        summary: "Finds the last character position using simple case folding, or returns false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strripos.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strstr"), name: "mb_strstr",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "before_needle", ty: TypeSpec::Bool, default: Some(DefaultSpec::Bool(false)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Returns text before or from the first matching substring, or false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strstr.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_stristr"), name: "mb_stristr",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "before_needle", ty: TypeSpec::Bool, default: Some(DefaultSpec::Bool(false)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Returns text before or from the first case-insensitive substring match, or false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-stristr.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strrchr"), name: "mb_strrchr",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "before_needle", ty: TypeSpec::Bool, default: Some(DefaultSpec::Bool(false)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Returns text before or from the last matching substring, or false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strrchr.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_strrichr"), name: "mb_strrichr",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "haystack", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "needle", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "before_needle", ty: TypeSpec::Bool, default: Some(DefaultSpec::Bool(false)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Returns text before or from the last case-insensitive substring match, or false.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-strrichr.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_language"), name: "mb_language",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "language", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::Bool]), by_ref_return: false,
        summary: "Reads or changes the current mbstring language.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-language.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_internal_encoding"), name: "mb_internal_encoding",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::Bool]), by_ref_return: false,
        summary: "Reads or changes the default encoding used by mbstring text operations.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-internal-encoding.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_http_output"), name: "mb_http_output",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::Bool]), by_ref_return: false,
        summary: "Reads or changes the encoding selected for HTTP output conversion.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-http-output.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_encoding_aliases"), name: "mb_encoding_aliases",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "encoding", ty: TypeSpec::Str, default: None, by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Array, by_ref_return: false,
        summary: "Lists the public aliases of an encoding in PHP order.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-encoding-aliases.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_str_split"), name: "mb_str_split",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "string", ty: TypeSpec::Str, default: None, by_ref: false },
            ParamSpec { name: "length", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(1)), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Array, by_ref_return: false,
        summary: "Splits a string into chunks measured in encoded characters.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-str-split.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_preferred_mime_name"), name: "mb_preferred_mime_name",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "encoding", ty: TypeSpec::Str, default: None, by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::False]), by_ref_return: false,
        summary: "Returns the preferred MIME encoding name, or false when none is registered.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-preferred-mime-name.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_check_encoding"), name: "mb_check_encoding",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "value", ty: TypeSpec::Union(&[TypeSpec::Array, TypeSpec::Str, TypeSpec::Null]), default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "encoding", ty: TypeSpec::Nullable(&TypeSpec::Str), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Bool, by_ref_return: false,
        summary: "Checks encoded strings or array keys and values recursively for invalid byte sequences.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-check-encoding.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("mb_substitute_character"), name: "mb_substitute_character",
        area: Area::String, module: PhpModule::Mbstring, since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "substitute_character", ty: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::Int, TypeSpec::Null]), default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None, variadic_by_ref: false, min_args: None, max_args: None, arity_error: None,
        returns: TypeSpec::Union(&[TypeSpec::Str, TypeSpec::Int, TypeSpec::Bool]), by_ref_return: false,
        summary: "Reads or changes the replacement codepoint or mode used for invalid or unrepresentable characters.", examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.mb-substitute-character.php"),
        deprecation: None, extension: false, internal: false, requirements: &[],
    },
];
