//! Purpose:
//! Canonical contracts for every PHP global constant elephc predefines or declares through a
//! prelude, with value and owning PHP module. Seeded once from the compiler's former
//! `*_INT_CONSTANTS` slices, prescan, and Magician's evaluator; authoritative from then on.
//!
//! Called from:
//! - `crate::symbol_registry` for validation and lookup.
//! - Both backends, which resolve predefined constant names and values from this table.
//!
//! Key details:
//! - Entries are sorted by exact name; the registry rejects any other order.
//! - `ext/curl` constants live in `crate::catalog_constants_curl` (generated from the frozen
//!   curl surface) and are always published, independent of the `curl` feature.

use crate::{
    BuiltinId, ConstType, ConstValue, ConstantContract, ConstantRoute, PhpModule, PhpVersion,
};

macro_rules! constant {
    (
        $name:literal, $module:ident, $value:expr
        $(, since: $since:ident)? $(, route: $route:ident)? $(, extension: $extension:literal)? $(,)?
    ) => {
        ConstantContract {
            id: BuiltinId::from_canonical_name($name),
            name: $name,
            module: PhpModule::$module,
            since: constant!(@since $($since)?),
            value: $value,
            route: constant!(@route $($route)?),
            extension: constant!(@flag $($extension)?),
            internal: false,
        }
    };
    (@since $since:ident) => { Some(PhpVersion::$since) };
    (@since) => { None };
    (@route $route:ident) => { ConstantRoute::$route };
    (@route) => { ConstantRoute::Predefined };
    (@flag $value:literal) => { $value };
    (@flag) => { false };
}

pub(crate) static CONSTANTS: &[ConstantContract] = &[
    constant!("ARRAY_FILTER_USE_BOTH", Standard, ConstValue::Int(1)),
    constant!("ARRAY_FILTER_USE_KEY", Standard, ConstValue::Int(2)),
    constant!("ARRAY_FILTER_USE_VALUE", Standard, ConstValue::Int(0), extension: true),
    constant!("CAL_DOW_DAYNO", Calendar, ConstValue::Int(0)),
    constant!("CAL_DOW_LONG", Calendar, ConstValue::Int(1)),
    constant!("CAL_DOW_SHORT", Calendar, ConstValue::Int(2)),
    constant!("CAL_EASTER_ALWAYS_GREGORIAN", Calendar, ConstValue::Int(2)),
    constant!("CAL_EASTER_ALWAYS_JULIAN", Calendar, ConstValue::Int(3)),
    constant!("CAL_EASTER_DEFAULT", Calendar, ConstValue::Int(0)),
    constant!("CAL_EASTER_ROMAN", Calendar, ConstValue::Int(1)),
    constant!("CAL_FRENCH", Calendar, ConstValue::Int(3)),
    constant!("CAL_GREGORIAN", Calendar, ConstValue::Int(0)),
    constant!("CAL_JEWISH", Calendar, ConstValue::Int(2)),
    constant!("CAL_JEWISH_ADD_ALAFIM", Calendar, ConstValue::Int(4)),
    constant!("CAL_JEWISH_ADD_ALAFIM_GERESH", Calendar, ConstValue::Int(2)),
    constant!("CAL_JEWISH_ADD_GERESHAYIM", Calendar, ConstValue::Int(8)),
    constant!("CAL_JULIAN", Calendar, ConstValue::Int(1)),
    constant!("CAL_MONTH_FRENCH", Calendar, ConstValue::Int(5)),
    constant!("CAL_MONTH_GREGORIAN_LONG", Calendar, ConstValue::Int(1)),
    constant!("CAL_MONTH_GREGORIAN_SHORT", Calendar, ConstValue::Int(0)),
    constant!("CAL_MONTH_JEWISH", Calendar, ConstValue::Int(4)),
    constant!("CAL_MONTH_JULIAN_LONG", Calendar, ConstValue::Int(3)),
    constant!("CAL_MONTH_JULIAN_SHORT", Calendar, ConstValue::Int(2)),
    constant!("CAL_NUM_CALS", Calendar, ConstValue::Int(4)),
    constant!("COUNT_NORMAL", Standard, ConstValue::Int(0)),
    constant!("COUNT_RECURSIVE", Standard, ConstValue::Int(1)),
    constant!("DIRECTORY_SEPARATOR", Standard, ConstValue::TargetDependent(ConstType::Str)),
    constant!("ENT_COMPAT", Standard, ConstValue::Int(2)),
    constant!("ENT_HTML401", Standard, ConstValue::Int(0)),
    constant!("ENT_HTML5", Standard, ConstValue::Int(48)),
    constant!("ENT_IGNORE", Standard, ConstValue::Int(4)),
    constant!("ENT_NOQUOTES", Standard, ConstValue::Int(0)),
    constant!("ENT_QUOTES", Standard, ConstValue::Int(3)),
    constant!("ENT_SUBSTITUTE", Standard, ConstValue::Int(8)),
    constant!("ENT_XHTML", Standard, ConstValue::Int(32)),
    constant!("ENT_XML1", Standard, ConstValue::Int(16)),
    constant!("EXIF_USE_MBSTRING", Exif, ConstValue::Int(0), route: Prelude),
    constant!("E_ALL", Core, ConstValue::Int(32767)),
    constant!("E_COMPILE_ERROR", Core, ConstValue::Int(64)),
    constant!("E_COMPILE_WARNING", Core, ConstValue::Int(128)),
    constant!("E_CORE_ERROR", Core, ConstValue::Int(16)),
    constant!("E_CORE_WARNING", Core, ConstValue::Int(32)),
    constant!("E_DEPRECATED", Core, ConstValue::Int(8192)),
    constant!("E_ERROR", Core, ConstValue::Int(1)),
    constant!("E_NOTICE", Core, ConstValue::Int(8)),
    constant!("E_PARSE", Core, ConstValue::Int(4)),
    constant!("E_RECOVERABLE_ERROR", Core, ConstValue::Int(4096)),
    constant!("E_STRICT", Core, ConstValue::Int(2048)),
    constant!("E_USER_DEPRECATED", Core, ConstValue::Int(16384)),
    constant!("E_USER_ERROR", Core, ConstValue::Int(256)),
    constant!("E_USER_NOTICE", Core, ConstValue::Int(1024)),
    constant!("E_USER_WARNING", Core, ConstValue::Int(512)),
    constant!("E_WARNING", Core, ConstValue::Int(2)),
    constant!("FILE_APPEND", Standard, ConstValue::Int(8)),
    constant!("FILE_IGNORE_NEW_LINES", Standard, ConstValue::Int(2)),
    constant!("FILE_NO_DEFAULT_CONTEXT", Standard, ConstValue::Int(16)),
    constant!("FILE_SKIP_EMPTY_LINES", Standard, ConstValue::Int(4)),
    constant!("FILE_USE_INCLUDE_PATH", Standard, ConstValue::Int(1)),
    constant!("FNM_CASEFOLD", Standard, ConstValue::Int(16)),
    constant!("FNM_NOESCAPE", Standard, ConstValue::TargetDependent(ConstType::Int)),
    constant!("FNM_PATHNAME", Standard, ConstValue::TargetDependent(ConstType::Int)),
    constant!("FNM_PERIOD", Standard, ConstValue::Int(4)),
    constant!("GLOB_BRACE", Standard, ConstValue::Int(128)),
    constant!("GLOB_ERR", Standard, ConstValue::Int(4)),
    constant!("GLOB_MARK", Standard, ConstValue::Int(8)),
    constant!("GLOB_NOCHECK", Standard, ConstValue::Int(16)),
    constant!("GLOB_NOESCAPE", Standard, ConstValue::Int(4096)),
    constant!("GLOB_NOSORT", Standard, ConstValue::Int(32)),
    constant!("GLOB_ONLYDIR", Standard, ConstValue::Int(1073741824)),
    constant!("ICONV_IMPL", Iconv, ConstValue::TargetDependent(ConstType::Str)),
    constant!("ICONV_MIME_DECODE_CONTINUE_ON_ERROR", Iconv, ConstValue::Int(2)),
    constant!("ICONV_MIME_DECODE_STRICT", Iconv, ConstValue::Int(1)),
    constant!("ICONV_VERSION", Iconv, ConstValue::TargetDependent(ConstType::Str)),
    constant!("IMAGETYPE_AVIF", Standard, ConstValue::Int(19), since: Php81, route: Prelude),
    constant!("IMAGETYPE_BMP", Standard, ConstValue::Int(6), route: Prelude),
    constant!("IMAGETYPE_COUNT", Standard, ConstValue::Int(20), route: Prelude),
    constant!("IMAGETYPE_GIF", Standard, ConstValue::Int(1), route: Prelude),
    constant!("IMAGETYPE_ICO", Standard, ConstValue::Int(17), route: Prelude),
    constant!("IMAGETYPE_IFF", Standard, ConstValue::Int(14), route: Prelude),
    constant!("IMAGETYPE_JB2", Standard, ConstValue::Int(12), route: Prelude),
    constant!("IMAGETYPE_JP2", Standard, ConstValue::Int(10), route: Prelude),
    constant!("IMAGETYPE_JPC", Standard, ConstValue::Int(9), route: Prelude),
    constant!("IMAGETYPE_JPEG", Standard, ConstValue::Int(2), route: Prelude),
    constant!("IMAGETYPE_JPX", Standard, ConstValue::Int(11), route: Prelude),
    constant!("IMAGETYPE_PNG", Standard, ConstValue::Int(3), route: Prelude),
    constant!("IMAGETYPE_PSD", Standard, ConstValue::Int(5), route: Prelude),
    constant!("IMAGETYPE_SWC", Standard, ConstValue::Int(13), route: Prelude),
    constant!("IMAGETYPE_SWF", Standard, ConstValue::Int(4), route: Prelude),
    constant!("IMAGETYPE_TIFF_II", Standard, ConstValue::Int(7), route: Prelude),
    constant!("IMAGETYPE_TIFF_MM", Standard, ConstValue::Int(8), route: Prelude),
    constant!("IMAGETYPE_UNKNOWN", Standard, ConstValue::Int(0), route: Prelude),
    constant!("IMAGETYPE_WBMP", Standard, ConstValue::Int(15), route: Prelude),
    constant!("IMAGETYPE_WEBP", Standard, ConstValue::Int(18), route: Prelude),
    constant!("IMAGETYPE_XBM", Standard, ConstValue::Int(16), route: Prelude),
    constant!("IMG_AFFINE_ROTATE", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_AFFINE_SCALE", Gd, ConstValue::Int(1), route: Prelude),
    constant!("IMG_AFFINE_SHEAR_HORIZONTAL", Gd, ConstValue::Int(3), route: Prelude),
    constant!("IMG_AFFINE_SHEAR_VERTICAL", Gd, ConstValue::Int(4), route: Prelude),
    constant!("IMG_AFFINE_TRANSLATE", Gd, ConstValue::Int(0), route: Prelude),
    constant!("IMG_ARC_CHORD", Gd, ConstValue::Int(1), route: Prelude),
    constant!("IMG_ARC_EDGED", Gd, ConstValue::Int(4), route: Prelude),
    constant!("IMG_ARC_NOFILL", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_ARC_PIE", Gd, ConstValue::Int(0), route: Prelude),
    constant!("IMG_AVIF", Gd, ConstValue::Int(256), since: Php81, route: Prelude),
    constant!("IMG_BELL", Gd, ConstValue::Int(1), route: Prelude),
    constant!("IMG_BESSEL", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_BICUBIC", Gd, ConstValue::Int(4), route: Prelude),
    constant!("IMG_BICUBIC_FIXED", Gd, ConstValue::Int(5), route: Prelude),
    constant!("IMG_BILINEAR_FIXED", Gd, ConstValue::Int(3), route: Prelude),
    constant!("IMG_BLACKMAN", Gd, ConstValue::Int(6), route: Prelude),
    constant!("IMG_BMP", Gd, ConstValue::Int(64), route: Prelude),
    constant!("IMG_BOX", Gd, ConstValue::Int(7), route: Prelude),
    constant!("IMG_BSPLINE", Gd, ConstValue::Int(8), route: Prelude),
    constant!("IMG_CATMULLROM", Gd, ConstValue::Int(9), route: Prelude),
    constant!("IMG_CROP_BLACK", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_CROP_DEFAULT", Gd, ConstValue::Int(0), route: Prelude),
    constant!("IMG_CROP_SIDES", Gd, ConstValue::Int(4), route: Prelude),
    constant!("IMG_CROP_THRESHOLD", Gd, ConstValue::Int(5), route: Prelude),
    constant!("IMG_CROP_TRANSPARENT", Gd, ConstValue::Int(1), route: Prelude),
    constant!("IMG_CROP_WHITE", Gd, ConstValue::Int(3), route: Prelude),
    constant!("IMG_EFFECT_ALPHABLEND", Gd, ConstValue::Int(1), route: Prelude),
    constant!("IMG_EFFECT_MULTIPLY", Gd, ConstValue::Int(4), route: Prelude),
    constant!("IMG_EFFECT_NORMAL", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_EFFECT_OVERLAY", Gd, ConstValue::Int(3), route: Prelude),
    constant!("IMG_EFFECT_REPLACE", Gd, ConstValue::Int(0), route: Prelude),
    constant!("IMG_FILTER_BRIGHTNESS", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_FILTER_COLORIZE", Gd, ConstValue::Int(4), route: Prelude),
    constant!("IMG_FILTER_CONTRAST", Gd, ConstValue::Int(3), route: Prelude),
    constant!("IMG_FILTER_EDGEDETECT", Gd, ConstValue::Int(5), route: Prelude),
    constant!("IMG_FILTER_EMBOSS", Gd, ConstValue::Int(6), route: Prelude),
    constant!("IMG_FILTER_GAUSSIAN_BLUR", Gd, ConstValue::Int(7), route: Prelude),
    constant!("IMG_FILTER_GRAYSCALE", Gd, ConstValue::Int(1), route: Prelude),
    constant!("IMG_FILTER_MEAN_REMOVAL", Gd, ConstValue::Int(9), route: Prelude),
    constant!("IMG_FILTER_NEGATE", Gd, ConstValue::Int(0), route: Prelude),
    constant!("IMG_FILTER_PIXELATE", Gd, ConstValue::Int(11), route: Prelude),
    constant!("IMG_FILTER_SCATTER", Gd, ConstValue::Int(12), route: Prelude),
    constant!("IMG_FILTER_SELECTIVE_BLUR", Gd, ConstValue::Int(8), route: Prelude),
    constant!("IMG_FILTER_SMOOTH", Gd, ConstValue::Int(10), route: Prelude),
    constant!("IMG_FLIP_BOTH", Gd, ConstValue::Int(3), route: Prelude),
    constant!("IMG_FLIP_HORIZONTAL", Gd, ConstValue::Int(1), route: Prelude),
    constant!("IMG_FLIP_VERTICAL", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_GAUSSIAN", Gd, ConstValue::Int(10), route: Prelude),
    constant!("IMG_GENERALIZED_CUBIC", Gd, ConstValue::Int(11), route: Prelude),
    constant!("IMG_GIF", Gd, ConstValue::Int(1), route: Prelude),
    constant!("IMG_HAMMING", Gd, ConstValue::Int(13), route: Prelude),
    constant!("IMG_HANNING", Gd, ConstValue::Int(14), route: Prelude),
    constant!("IMG_HERMITE", Gd, ConstValue::Int(12), route: Prelude),
    constant!("IMG_JPEG", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_JPG", Gd, ConstValue::Int(2), route: Prelude),
    constant!("IMG_MITCHELL", Gd, ConstValue::Int(15), route: Prelude),
    constant!("IMG_NEAREST_NEIGHBOUR", Gd, ConstValue::Int(16), route: Prelude),
    constant!("IMG_PNG", Gd, ConstValue::Int(4), route: Prelude),
    constant!("IMG_POWER", Gd, ConstValue::Int(17), route: Prelude),
    constant!("IMG_QUADRATIC", Gd, ConstValue::Int(18), route: Prelude),
    constant!("IMG_SINC", Gd, ConstValue::Int(19), route: Prelude),
    constant!("IMG_TGA", Gd, ConstValue::Int(128), route: Prelude),
    constant!("IMG_TRIANGLE", Gd, ConstValue::Int(20), route: Prelude),
    constant!("IMG_WBMP", Gd, ConstValue::Int(8), route: Prelude),
    constant!("IMG_WEBP", Gd, ConstValue::Int(32), route: Prelude),
    constant!("IMG_WEIGHTED4", Gd, ConstValue::Int(21), route: Prelude),
    constant!("IMG_XPM", Gd, ConstValue::Int(16), route: Prelude),
    constant!("INF", Standard, ConstValue::Float(f64::INFINITY)),
    constant!("JSON_BIGINT_AS_STRING", Json, ConstValue::Int(2)),
    constant!("JSON_ERROR_CTRL_CHAR", Json, ConstValue::Int(3)),
    constant!("JSON_ERROR_DEPTH", Json, ConstValue::Int(1)),
    constant!("JSON_ERROR_INF_OR_NAN", Json, ConstValue::Int(7)),
    constant!("JSON_ERROR_INVALID_PROPERTY_NAME", Json, ConstValue::Int(9)),
    constant!("JSON_ERROR_NONE", Json, ConstValue::Int(0)),
    constant!("JSON_ERROR_RECURSION", Json, ConstValue::Int(6)),
    constant!("JSON_ERROR_STATE_MISMATCH", Json, ConstValue::Int(2)),
    constant!("JSON_ERROR_SYNTAX", Json, ConstValue::Int(4)),
    constant!("JSON_ERROR_UNSUPPORTED_TYPE", Json, ConstValue::Int(8)),
    constant!("JSON_ERROR_UTF16", Json, ConstValue::Int(10)),
    constant!("JSON_ERROR_UTF8", Json, ConstValue::Int(5)),
    constant!("JSON_FORCE_OBJECT", Json, ConstValue::Int(16)),
    constant!("JSON_HEX_AMP", Json, ConstValue::Int(2)),
    constant!("JSON_HEX_APOS", Json, ConstValue::Int(4)),
    constant!("JSON_HEX_QUOT", Json, ConstValue::Int(8)),
    constant!("JSON_HEX_TAG", Json, ConstValue::Int(1)),
    constant!("JSON_INVALID_UTF8_IGNORE", Json, ConstValue::Int(1048576)),
    constant!("JSON_INVALID_UTF8_SUBSTITUTE", Json, ConstValue::Int(2097152)),
    constant!("JSON_NUMERIC_CHECK", Json, ConstValue::Int(32)),
    constant!("JSON_OBJECT_AS_ARRAY", Json, ConstValue::Int(1)),
    constant!("JSON_PARTIAL_OUTPUT_ON_ERROR", Json, ConstValue::Int(512)),
    constant!("JSON_PRESERVE_ZERO_FRACTION", Json, ConstValue::Int(1024)),
    constant!("JSON_PRETTY_PRINT", Json, ConstValue::Int(128)),
    constant!("JSON_THROW_ON_ERROR", Json, ConstValue::Int(4194304)),
    constant!("JSON_UNESCAPED_SLASHES", Json, ConstValue::Int(64)),
    constant!("JSON_UNESCAPED_UNICODE", Json, ConstValue::Int(256)),
    constant!("LOCK_EX", Standard, ConstValue::Int(2)),
    constant!("LOCK_NB", Standard, ConstValue::Int(4)),
    constant!("LOCK_SH", Standard, ConstValue::Int(1)),
    constant!("LOCK_UN", Standard, ConstValue::Int(3)),
    constant!("MYSQLI_ASSOC", Mysqli, ConstValue::Int(1), route: Prelude),
    constant!("MYSQLI_BOTH", Mysqli, ConstValue::Int(3), route: Prelude),
    constant!("MYSQLI_CLIENT_COMPRESS", Mysqli, ConstValue::Int(32), route: Prelude),
    constant!("MYSQLI_CLIENT_FOUND_ROWS", Mysqli, ConstValue::Int(2), route: Prelude),
    constant!("MYSQLI_CLIENT_IGNORE_SPACE", Mysqli, ConstValue::Int(256), route: Prelude),
    constant!("MYSQLI_CLIENT_INTERACTIVE", Mysqli, ConstValue::Int(1024), route: Prelude),
    constant!("MYSQLI_CLIENT_SSL", Mysqli, ConstValue::Int(2048), route: Prelude),
    constant!("MYSQLI_INIT_COMMAND", Mysqli, ConstValue::Int(3), route: Prelude),
    constant!("MYSQLI_NUM", Mysqli, ConstValue::Int(2), route: Prelude),
    constant!("MYSQLI_OPT_CONNECT_TIMEOUT", Mysqli, ConstValue::Int(0), route: Prelude),
    constant!("MYSQLI_REPORT_ALL", Mysqli, ConstValue::Int(255), route: Prelude),
    constant!("MYSQLI_REPORT_ERROR", Mysqli, ConstValue::Int(1), route: Prelude),
    constant!("MYSQLI_REPORT_INDEX", Mysqli, ConstValue::Int(4), route: Prelude),
    constant!("MYSQLI_REPORT_OFF", Mysqli, ConstValue::Int(0), route: Prelude),
    constant!("MYSQLI_REPORT_STRICT", Mysqli, ConstValue::Int(2), route: Prelude),
    constant!("MYSQLI_SET_CHARSET_NAME", Mysqli, ConstValue::Int(7), route: Prelude),
    constant!("MYSQLI_STORE_RESULT", Mysqli, ConstValue::Int(0), route: Prelude),
    constant!("MYSQLI_TRANS_COR_AND_CHAIN", Mysqli, ConstValue::Int(1), route: Prelude),
    constant!("MYSQLI_TRANS_COR_AND_NO_CHAIN", Mysqli, ConstValue::Int(2), route: Prelude),
    constant!("MYSQLI_TRANS_COR_NO_RELEASE", Mysqli, ConstValue::Int(8), route: Prelude),
    constant!("MYSQLI_TRANS_COR_RELEASE", Mysqli, ConstValue::Int(4), route: Prelude),
    constant!("MYSQLI_TRANS_START_READ_ONLY", Mysqli, ConstValue::Int(4), route: Prelude),
    constant!("MYSQLI_TRANS_START_READ_WRITE", Mysqli, ConstValue::Int(2), route: Prelude),
    constant!("MYSQLI_TRANS_START_WITH_CONSISTENT_SNAPSHOT", Mysqli, ConstValue::Int(1), route: Prelude),
    constant!("MYSQLI_TYPE_BIT", Mysqli, ConstValue::Int(16), route: Prelude),
    constant!("MYSQLI_TYPE_BLOB", Mysqli, ConstValue::Int(252), route: Prelude),
    constant!("MYSQLI_TYPE_DATE", Mysqli, ConstValue::Int(10), route: Prelude),
    constant!("MYSQLI_TYPE_DATETIME", Mysqli, ConstValue::Int(12), route: Prelude),
    constant!("MYSQLI_TYPE_DECIMAL", Mysqli, ConstValue::Int(0), route: Prelude),
    constant!("MYSQLI_TYPE_DOUBLE", Mysqli, ConstValue::Int(5), route: Prelude),
    constant!("MYSQLI_TYPE_ENUM", Mysqli, ConstValue::Int(247), route: Prelude),
    constant!("MYSQLI_TYPE_FLOAT", Mysqli, ConstValue::Int(4), route: Prelude),
    constant!("MYSQLI_TYPE_GEOMETRY", Mysqli, ConstValue::Int(255), route: Prelude),
    constant!("MYSQLI_TYPE_INT24", Mysqli, ConstValue::Int(9), route: Prelude),
    constant!("MYSQLI_TYPE_JSON", Mysqli, ConstValue::Int(245), route: Prelude),
    constant!("MYSQLI_TYPE_LONG", Mysqli, ConstValue::Int(3), route: Prelude),
    constant!("MYSQLI_TYPE_LONGLONG", Mysqli, ConstValue::Int(8), route: Prelude),
    constant!("MYSQLI_TYPE_LONG_BLOB", Mysqli, ConstValue::Int(251), route: Prelude),
    constant!("MYSQLI_TYPE_MEDIUM_BLOB", Mysqli, ConstValue::Int(250), route: Prelude),
    constant!("MYSQLI_TYPE_NEWDATE", Mysqli, ConstValue::Int(14), route: Prelude),
    constant!("MYSQLI_TYPE_NEWDECIMAL", Mysqli, ConstValue::Int(246), route: Prelude),
    constant!("MYSQLI_TYPE_NULL", Mysqli, ConstValue::Int(6), route: Prelude),
    constant!("MYSQLI_TYPE_SET", Mysqli, ConstValue::Int(248), route: Prelude),
    constant!("MYSQLI_TYPE_SHORT", Mysqli, ConstValue::Int(2), route: Prelude),
    constant!("MYSQLI_TYPE_STRING", Mysqli, ConstValue::Int(254), route: Prelude),
    constant!("MYSQLI_TYPE_TIME", Mysqli, ConstValue::Int(11), route: Prelude),
    constant!("MYSQLI_TYPE_TIMESTAMP", Mysqli, ConstValue::Int(7), route: Prelude),
    constant!("MYSQLI_TYPE_TINY", Mysqli, ConstValue::Int(1), route: Prelude),
    constant!("MYSQLI_TYPE_TINY_BLOB", Mysqli, ConstValue::Int(249), route: Prelude),
    constant!("MYSQLI_TYPE_VARCHAR", Mysqli, ConstValue::Int(15), route: Prelude, extension: true),
    constant!("MYSQLI_TYPE_VAR_STRING", Mysqli, ConstValue::Int(253), route: Prelude),
    constant!("MYSQLI_TYPE_YEAR", Mysqli, ConstValue::Int(13), route: Prelude),
    constant!("MYSQLI_USE_RESULT", Mysqli, ConstValue::Int(1), route: Prelude),
    constant!("M_E", Standard, ConstValue::Float(std::f64::consts::E)),
    constant!("M_LOG10E", Standard, ConstValue::Float(std::f64::consts::LOG10_E)),
    constant!("M_LOG2E", Standard, ConstValue::Float(std::f64::consts::LOG2_E)),
    constant!("M_PI", Standard, ConstValue::Float(std::f64::consts::PI)),
    constant!("M_PI_2", Standard, ConstValue::Float(std::f64::consts::FRAC_PI_2)),
    constant!("M_PI_4", Standard, ConstValue::Float(std::f64::consts::FRAC_PI_4)),
    constant!("M_SQRT2", Standard, ConstValue::Float(std::f64::consts::SQRT_2)),
    constant!("NAN", Standard, ConstValue::Float(f64::NAN)),
    constant!("OPENSSL_DONT_ZERO_PAD_KEY", Openssl, ConstValue::Int(4)),
    constant!("OPENSSL_RAW_DATA", Openssl, ConstValue::Int(1)),
    constant!("OPENSSL_ZERO_PADDING", Openssl, ConstValue::Int(2)),
    constant!("PATHINFO_ALL", Standard, ConstValue::Int(15)),
    constant!("PATHINFO_BASENAME", Standard, ConstValue::Int(2)),
    constant!("PATHINFO_DIRNAME", Standard, ConstValue::Int(1)),
    constant!("PATHINFO_EXTENSION", Standard, ConstValue::Int(4)),
    constant!("PATHINFO_FILENAME", Standard, ConstValue::Int(8)),
    constant!("PHP_EOL", Core, ConstValue::Str("\n")),
    constant!("PHP_EXTRA_VERSION", Core, ConstValue::TargetDependent(ConstType::Str)),
    constant!("PHP_FLOAT_EPSILON", Core, ConstValue::Float(f64::EPSILON)),
    constant!("PHP_FLOAT_MAX", Core, ConstValue::Float(f64::MAX)),
    constant!("PHP_FLOAT_MIN", Core, ConstValue::Float(f64::MIN_POSITIVE)),
    constant!("PHP_INT_MAX", Core, ConstValue::Int(i64::MAX)),
    constant!("PHP_INT_MIN", Core, ConstValue::Int(i64::MIN)),
    constant!("PHP_MAJOR_VERSION", Core, ConstValue::TargetDependent(ConstType::Int)),
    constant!("PHP_MINOR_VERSION", Core, ConstValue::TargetDependent(ConstType::Int)),
    constant!("PHP_OS", Core, ConstValue::TargetDependent(ConstType::Str)),
    constant!("PHP_RELEASE_VERSION", Core, ConstValue::TargetDependent(ConstType::Int)),
    constant!("PHP_ROUND_HALF_DOWN", Standard, ConstValue::Int(2)),
    constant!("PHP_ROUND_HALF_EVEN", Standard, ConstValue::Int(3)),
    constant!("PHP_ROUND_HALF_ODD", Standard, ConstValue::Int(4)),
    constant!("PHP_ROUND_HALF_UP", Standard, ConstValue::Int(1)),
    constant!("PHP_SAPI", Core, ConstValue::TargetDependent(ConstType::Str)),
    constant!("PHP_SESSION_ACTIVE", Session, ConstValue::Int(2)),
    constant!("PHP_SESSION_DISABLED", Session, ConstValue::Int(0)),
    constant!("PHP_SESSION_NONE", Session, ConstValue::Int(1)),
    constant!("PHP_URL_FRAGMENT", Standard, ConstValue::Int(7)),
    constant!("PHP_URL_HOST", Standard, ConstValue::Int(1)),
    constant!("PHP_URL_PASS", Standard, ConstValue::Int(4)),
    constant!("PHP_URL_PATH", Standard, ConstValue::Int(5)),
    constant!("PHP_URL_PORT", Standard, ConstValue::Int(2)),
    constant!("PHP_URL_QUERY", Standard, ConstValue::Int(6)),
    constant!("PHP_URL_SCHEME", Standard, ConstValue::Int(0)),
    constant!("PHP_URL_USER", Standard, ConstValue::Int(3)),
    constant!("PHP_VERSION", Core, ConstValue::TargetDependent(ConstType::Str)),
    constant!("PHP_VERSION_ID", Core, ConstValue::TargetDependent(ConstType::Int)),
    constant!("PREG_OFFSET_CAPTURE", Pcre, ConstValue::Int(256)),
    constant!("PREG_PATTERN_ORDER", Pcre, ConstValue::Int(1)),
    constant!("PREG_SET_ORDER", Pcre, ConstValue::Int(2)),
    constant!("PREG_SPLIT_DELIM_CAPTURE", Pcre, ConstValue::Int(2)),
    constant!("PREG_SPLIT_NO_EMPTY", Pcre, ConstValue::Int(1)),
    constant!("PREG_SPLIT_OFFSET_CAPTURE", Pcre, ConstValue::Int(4)),
    constant!("PREG_UNMATCHED_AS_NULL", Pcre, ConstValue::Int(512)),
    constant!("PSFS_ERR_FATAL", Standard, ConstValue::Int(0)),
    constant!("PSFS_FEED_ME", Standard, ConstValue::Int(1)),
    constant!("PSFS_FLAG_FLUSH_CLOSE", Standard, ConstValue::Int(2)),
    constant!("PSFS_FLAG_FLUSH_INC", Standard, ConstValue::Int(1)),
    constant!("PSFS_FLAG_NORMAL", Standard, ConstValue::Int(0)),
    constant!("PSFS_PASS_ON", Standard, ConstValue::Int(2)),
    constant!("SID", Session, ConstValue::Str(""), route: Dynamic),
    constant!("STDERR", Core, ConstValue::StreamResource(2), since: Php83),
    constant!("STDIN", Core, ConstValue::StreamResource(0), since: Php83),
    constant!("STDOUT", Core, ConstValue::StreamResource(1), since: Php83),
    constant!("STREAM_BUFFER_FULL", Standard, ConstValue::Int(2)),
    constant!("STREAM_BUFFER_LINE", Standard, ConstValue::Int(1)),
    constant!("STREAM_BUFFER_NONE", Standard, ConstValue::Int(0)),
    constant!("STREAM_CAST_AS_STREAM", Standard, ConstValue::Int(0)),
    constant!("STREAM_CAST_FOR_SELECT", Standard, ConstValue::Int(3)),
    constant!("STREAM_CLIENT_ASYNC_CONNECT", Standard, ConstValue::Int(2)),
    constant!("STREAM_CLIENT_CONNECT", Standard, ConstValue::Int(4)),
    constant!("STREAM_CLIENT_PERSISTENT", Standard, ConstValue::Int(1)),
    constant!("STREAM_CRYPTO_METHOD_ANY_CLIENT", Standard, ConstValue::Int(127)),
    constant!("STREAM_CRYPTO_METHOD_ANY_SERVER", Standard, ConstValue::Int(126)),
    constant!("STREAM_CRYPTO_METHOD_TLS_CLIENT", Standard, ConstValue::Int(121)),
    constant!("STREAM_CRYPTO_METHOD_TLS_SERVER", Standard, ConstValue::Int(120)),
    constant!("STREAM_FILTER_ALL", Standard, ConstValue::Int(3)),
    constant!("STREAM_FILTER_READ", Standard, ConstValue::Int(1)),
    constant!("STREAM_FILTER_WRITE", Standard, ConstValue::Int(2)),
    constant!("STREAM_IGNORE_URL", Standard, ConstValue::Int(2)),
    constant!("STREAM_IPPROTO_ICMP", Standard, ConstValue::Int(1)),
    constant!("STREAM_IPPROTO_IP", Standard, ConstValue::Int(0)),
    constant!("STREAM_IPPROTO_RAW", Standard, ConstValue::Int(255)),
    constant!("STREAM_IPPROTO_TCP", Standard, ConstValue::Int(6)),
    constant!("STREAM_IPPROTO_UDP", Standard, ConstValue::Int(17)),
    constant!("STREAM_IS_URL", Standard, ConstValue::Int(1)),
    constant!("STREAM_META_ACCESS", Standard, ConstValue::Int(6)),
    constant!("STREAM_META_GROUP", Standard, ConstValue::Int(5)),
    constant!("STREAM_META_GROUP_NAME", Standard, ConstValue::Int(4)),
    constant!("STREAM_META_OWNER", Standard, ConstValue::Int(3)),
    constant!("STREAM_META_OWNER_NAME", Standard, ConstValue::Int(2)),
    constant!("STREAM_META_TOUCH", Standard, ConstValue::Int(1)),
    constant!("STREAM_MKDIR_RECURSIVE", Standard, ConstValue::Int(1)),
    constant!("STREAM_MUST_SEEK", Standard, ConstValue::Int(16)),
    constant!("STREAM_NOTIFY_AUTH_REQUIRED", Standard, ConstValue::Int(3)),
    constant!("STREAM_NOTIFY_AUTH_RESULT", Standard, ConstValue::Int(10)),
    constant!("STREAM_NOTIFY_COMPLETED", Standard, ConstValue::Int(8)),
    constant!("STREAM_NOTIFY_CONNECT", Standard, ConstValue::Int(2)),
    constant!("STREAM_NOTIFY_FAILURE", Standard, ConstValue::Int(9)),
    constant!("STREAM_NOTIFY_FILE_SIZE_IS", Standard, ConstValue::Int(5)),
    constant!("STREAM_NOTIFY_MIME_TYPE_IS", Standard, ConstValue::Int(4)),
    constant!("STREAM_NOTIFY_PROGRESS", Standard, ConstValue::Int(7)),
    constant!("STREAM_NOTIFY_REDIRECTED", Standard, ConstValue::Int(6)),
    constant!("STREAM_NOTIFY_RESOLVE", Standard, ConstValue::Int(1)),
    constant!("STREAM_NOTIFY_SEVERITY_ERR", Standard, ConstValue::Int(2)),
    constant!("STREAM_NOTIFY_SEVERITY_INFO", Standard, ConstValue::Int(0)),
    constant!("STREAM_NOTIFY_SEVERITY_WARN", Standard, ConstValue::Int(1)),
    constant!("STREAM_OOB", Standard, ConstValue::Int(1)),
    constant!("STREAM_OPTION_BLOCKING", Standard, ConstValue::Int(1)),
    constant!("STREAM_OPTION_READ_BUFFER", Standard, ConstValue::Int(2)),
    constant!("STREAM_OPTION_READ_TIMEOUT", Standard, ConstValue::Int(4)),
    constant!("STREAM_OPTION_WRITE_BUFFER", Standard, ConstValue::Int(3)),
    constant!("STREAM_PEEK", Standard, ConstValue::Int(2)),
    constant!("STREAM_PF_INET", Standard, ConstValue::Int(2)),
    constant!("STREAM_PF_UNIX", Standard, ConstValue::Int(1)),
    constant!("STREAM_REPORT_ERRORS", Standard, ConstValue::Int(8)),
    constant!("STREAM_SERVER_BIND", Standard, ConstValue::Int(4)),
    constant!("STREAM_SERVER_LISTEN", Standard, ConstValue::Int(8)),
    constant!("STREAM_SHUT_RD", Standard, ConstValue::Int(0)),
    constant!("STREAM_SHUT_RDWR", Standard, ConstValue::Int(2)),
    constant!("STREAM_SHUT_WR", Standard, ConstValue::Int(1)),
    constant!("STREAM_SOCK_DGRAM", Standard, ConstValue::Int(2)),
    constant!("STREAM_SOCK_RAW", Standard, ConstValue::Int(3)),
    constant!("STREAM_SOCK_RDM", Standard, ConstValue::Int(4)),
    constant!("STREAM_SOCK_SEQPACKET", Standard, ConstValue::Int(5)),
    constant!("STREAM_SOCK_STREAM", Standard, ConstValue::Int(1)),
    constant!("STREAM_URL_STAT_LINK", Standard, ConstValue::Int(1)),
    constant!("STREAM_URL_STAT_QUIET", Standard, ConstValue::Int(2)),
    constant!("STREAM_USE_PATH", Standard, ConstValue::Int(1)),
    constant!("STR_PAD_BOTH", Standard, ConstValue::Int(2)),
    constant!("STR_PAD_LEFT", Standard, ConstValue::Int(0)),
    constant!("STR_PAD_RIGHT", Standard, ConstValue::Int(1)),
    constant!("SUNFUNCS_RET_DOUBLE", Date, ConstValue::Int(2)),
    constant!("SUNFUNCS_RET_STRING", Date, ConstValue::Int(1)),
    constant!("SUNFUNCS_RET_TIMESTAMP", Date, ConstValue::Int(0)),
];
