//! Purpose:
//! Canonical contracts for process and shell-related PHP builtins introduced
//! with the Windows runtime surface.
//!
//! Called from:
//! - `crate::registry::contracts()` while building the shared builtin registry.
//!
//! Key details:
//! - Process functions remain standard-extension functions and are host-only in
//!   the AOT backend; that target policy belongs to compiler semantics, not here.

use crate::{
    Area, BuiltinContract, BuiltinId, BuiltinKind, DefaultSpec, ParamSpec, PhpModule, TypeSpec,
};

/// Process-control, secure-randomness, and shell-escaping contracts.
pub(crate) static CONTRACTS: &[BuiltinContract] = &[
    BuiltinContract {
        id: BuiltinId::from_canonical_name("escapeshellarg"),
        name: "escapeshellarg",
        area: Area::String,
        module: PhpModule::Standard,
        since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "arg", ty: TypeSpec::Str, default: None, by_ref: false }],
        variadic: None,
        variadic_by_ref: false,
        min_args: None,
        max_args: None,
        arity_error: None,
        returns: TypeSpec::Str,
        by_ref_return: false,
        summary: "Quotes one argument for safe use in a shell command.",
        examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.escapeshellarg.php"),
        deprecation: None,
        extension: false,
        internal: false,
        requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("escapeshellcmd"),
        name: "escapeshellcmd",
        area: Area::String,
        module: PhpModule::Standard,
        since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "command", ty: TypeSpec::Str, default: None, by_ref: false }],
        variadic: None,
        variadic_by_ref: false,
        min_args: None,
        max_args: None,
        arity_error: None,
        returns: TypeSpec::Str,
        by_ref_return: false,
        summary: "Escapes shell metacharacters in a command string.",
        examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.escapeshellcmd.php"),
        deprecation: None,
        extension: false,
        internal: false,
        requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("proc_close"),
        name: "proc_close",
        area: Area::Io,
        module: PhpModule::Standard,
        since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "process", ty: TypeSpec::Mixed, default: None, by_ref: false }],
        variadic: None,
        variadic_by_ref: false,
        min_args: None,
        max_args: None,
        arity_error: None,
        returns: TypeSpec::Int,
        by_ref_return: false,
        summary: "Close a process opened by proc_open and return the exit status.",
        examples: &[],
        php_manual: Some("function.proc-close"),
        deprecation: None,
        extension: false,
        internal: false,
        requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("proc_get_status"),
        name: "proc_get_status",
        area: Area::Io,
        module: PhpModule::Standard,
        since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "process", ty: TypeSpec::Mixed, default: None, by_ref: false }],
        variadic: None,
        variadic_by_ref: false,
        min_args: None,
        max_args: None,
        arity_error: None,
        returns: TypeSpec::Mixed,
        by_ref_return: false,
        summary: "Retrieves the current status of a process opened by proc_open.",
        examples: &[],
        php_manual: Some("function.proc-get-status"),
        deprecation: None,
        extension: false,
        internal: false,
        requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("proc_open"),
        name: "proc_open",
        area: Area::Io,
        module: PhpModule::Standard,
        since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "command", ty: TypeSpec::Mixed, default: None, by_ref: false },
            ParamSpec { name: "descriptor_spec", ty: TypeSpec::Mixed, default: None, by_ref: false },
            ParamSpec { name: "pipes", ty: TypeSpec::Mixed, default: None, by_ref: true },
            ParamSpec { name: "cwd", ty: TypeSpec::Mixed, default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "env_vars", ty: TypeSpec::Mixed, default: Some(DefaultSpec::Null), by_ref: false },
            ParamSpec { name: "options", ty: TypeSpec::Mixed, default: Some(DefaultSpec::Null), by_ref: false },
        ],
        variadic: None,
        variadic_by_ref: false,
        min_args: None,
        max_args: None,
        arity_error: None,
        returns: TypeSpec::Mixed,
        by_ref_return: false,
        summary: "Execute a command and open file pointers for process I/O.",
        examples: &[],
        php_manual: Some("function.proc-open"),
        deprecation: None,
        extension: false,
        internal: false,
        requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("proc_terminate"),
        name: "proc_terminate",
        area: Area::Io,
        module: PhpModule::Standard,
        since: None,
        kind: BuiltinKind::Function,
        params: &[
            ParamSpec { name: "process", ty: TypeSpec::Mixed, default: None, by_ref: false },
            ParamSpec { name: "signal", ty: TypeSpec::Int, default: Some(DefaultSpec::Int(15)), by_ref: false },
        ],
        variadic: None,
        variadic_by_ref: false,
        min_args: None,
        max_args: None,
        arity_error: None,
        returns: TypeSpec::Bool,
        by_ref_return: false,
        summary: "Terminates a process opened by proc_open.",
        examples: &[],
        php_manual: Some("function.proc-terminate"),
        deprecation: None,
        extension: false,
        internal: false,
        requirements: &[],
    },
    BuiltinContract {
        id: BuiltinId::from_canonical_name("random_bytes"),
        name: "random_bytes",
        area: Area::Math,
        module: PhpModule::Random,
        since: None,
        kind: BuiltinKind::Function,
        params: &[ParamSpec { name: "length", ty: TypeSpec::Int, default: None, by_ref: false }],
        variadic: None,
        variadic_by_ref: false,
        min_args: None,
        max_args: None,
        arity_error: None,
        returns: TypeSpec::Str,
        by_ref_return: false,
        summary: "Get a cryptographically secure random string of the given length.",
        examples: &[],
        php_manual: Some("https://www.php.net/manual/en/function.random-bytes.php"),
        deprecation: None,
        extension: false,
        internal: false,
        requirements: &[],
    },
];
