//! Purpose:
//! Provides the generated PHP mbstring encoding catalog and codec bindings.
//!
//! Called from:
//! - `super::catalog` for encoding lookup and metadata.
//!
//! Key details:
//! - Regenerate with `python3 scripts/mbstring/generate_encodings.py`.
//! - Canonical spelling, order, and aliases come from PHP's reflection fixture.

use super::{catalog::{Codec, EncodingInfo, Slicing}, doublebyte::DoubleByte, euctw::EucTw, gb18030::Gb18030, hz::Hz, iso2022kr::Iso2022Kr, jis::{Jis, Variant}, jis2004::Jis2004, mobile_utf8::MobileUtf8, mobile_sjis::MobileSjis, singlebyte::SingleByte, transfer::Transfer, utf7::Utf7, UnicodeEncoding};

/// Complete encoding list in PHP's public enumeration order.
pub(super) const ENCODINGS: &[EncodingInfo] = &[
    EncodingInfo {
        name: "BASE64",
        aliases: &[],
        mime: Some("BASE64"),
        supports_ord_chr: false,
        supports_detection: false,
        codec: Codec::Transfer(Transfer::Base64),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "UUENCODE",
        aliases: &[],
        mime: Some("x-uuencode"),
        supports_ord_chr: false,
        supports_detection: false,
        codec: Codec::Transfer(Transfer::Uuencode),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "HTML-ENTITIES",
        aliases: &["HTML", "html"],
        mime: Some("HTML-ENTITIES"),
        supports_ord_chr: false,
        supports_detection: false,
        codec: Codec::Transfer(Transfer::Html),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "Quoted-Printable",
        aliases: &["qprint"],
        mime: Some("Quoted-Printable"),
        supports_ord_chr: false,
        supports_detection: false,
        codec: Codec::Transfer(Transfer::QuotedPrintable),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "7bit",
        aliases: &[],
        mime: Some("7bit"),
        supports_ord_chr: true,
        supports_detection: false,
        codec: Codec::Unicode(UnicodeEncoding::Ascii),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "8bit",
        aliases: &["binary"],
        mime: Some("8bit"),
        supports_ord_chr: true,
        supports_detection: false,
        codec: Codec::Unicode(UnicodeEncoding::EightBit),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "UCS-4",
        aliases: &["ISO-10646-UCS-4", "UCS4"],
        mime: Some("UCS-4"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Ucs4),
        slicing: Slicing::Fixed(4),
    },
    EncodingInfo {
        name: "UCS-4BE",
        aliases: &["byte4be"],
        mime: Some("UCS-4BE"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Ucs4Be),
        slicing: Slicing::Fixed(4),
    },
    EncodingInfo {
        name: "UCS-4LE",
        aliases: &["byte4le"],
        mime: Some("UCS-4LE"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Ucs4Le),
        slicing: Slicing::Fixed(4),
    },
    EncodingInfo {
        name: "UCS-2",
        aliases: &["ISO-10646-UCS-2", "UCS2", "UNICODE"],
        mime: Some("UCS-2"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Ucs2),
        slicing: Slicing::Fixed(2),
    },
    EncodingInfo {
        name: "UCS-2BE",
        aliases: &["byte2be"],
        mime: Some("UCS-2BE"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Ucs2Be),
        slicing: Slicing::Fixed(2),
    },
    EncodingInfo {
        name: "UCS-2LE",
        aliases: &["byte2le"],
        mime: Some("UCS-2LE"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Ucs2Le),
        slicing: Slicing::Fixed(2),
    },
    EncodingInfo {
        name: "UTF-32",
        aliases: &["utf32"],
        mime: Some("UTF-32"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Utf32),
        slicing: Slicing::Fixed(4),
    },
    EncodingInfo {
        name: "UTF-32BE",
        aliases: &[],
        mime: Some("UTF-32BE"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Utf32Be),
        slicing: Slicing::Fixed(4),
    },
    EncodingInfo {
        name: "UTF-32LE",
        aliases: &[],
        mime: Some("UTF-32LE"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Utf32Le),
        slicing: Slicing::Fixed(4),
    },
    EncodingInfo {
        name: "UTF-16",
        aliases: &["utf16"],
        mime: Some("UTF-16"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Utf16),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "UTF-16BE",
        aliases: &[],
        mime: Some("UTF-16BE"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Utf16Be),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "UTF-16LE",
        aliases: &[],
        mime: Some("UTF-16LE"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Utf16Le),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "UTF-8",
        aliases: &["utf8"],
        mime: Some("UTF-8"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Utf8),
        slicing: Slicing::LeadingByte(include_bytes!("data/utf-8-boundaries.bin")),
    },
    EncodingInfo {
        name: "UTF-7",
        aliases: &["utf7"],
        mime: Some("UTF-7"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Utf7(Utf7(false)),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "UTF7-IMAP",
        aliases: &["mUTF-7"],
        mime: None,
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Utf7(Utf7(true)),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "ASCII",
        aliases: &["ANSI_X3.4-1968", "iso-ir-6", "ANSI_X3.4-1986", "ISO_646.irv:1991", "US-ASCII", "ISO646-US", "us", "IBM367", "IBM-367", "cp367", "csASCII"],
        mime: Some("US-ASCII"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Unicode(UnicodeEncoding::Ascii),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "EUC-JP",
        aliases: &["EUC", "EUC_JP", "eucJP", "x-euc-jp"],
        mime: Some("EUC-JP"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/euc-jp-single.bin"), pairs: include_bytes!("data/euc-jp-pairs.bin"), triples: include_bytes!("data/euc-jp-triples.bin"), points: include_bytes!("data/euc-jp-points.bin"), encode: include_bytes!("data/euc-jp-encode.bin"), bytes: include_bytes!("data/euc-jp-bytes.bin"), composites: include_bytes!("data/euc-jp-composites.bin"), escapes: include_bytes!("data/euc-jp-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/euc-jp-boundaries.bin")),
    },
    EncodingInfo {
        name: "SJIS",
        aliases: &["x-sjis", "SHIFT-JIS"],
        mime: Some("Shift_JIS"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/sjis-single.bin"), pairs: include_bytes!("data/sjis-pairs.bin"), triples: include_bytes!("data/sjis-triples.bin"), points: include_bytes!("data/sjis-points.bin"), encode: include_bytes!("data/sjis-encode.bin"), bytes: include_bytes!("data/sjis-bytes.bin"), composites: include_bytes!("data/sjis-composites.bin"), escapes: include_bytes!("data/sjis-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/sjis-boundaries.bin")),
    },
    EncodingInfo {
        name: "eucJP-win",
        aliases: &["eucJP-open", "eucJP-ms"],
        mime: Some("EUC-JP"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/eucjp-win-single.bin"), pairs: include_bytes!("data/eucjp-win-pairs.bin"), triples: include_bytes!("data/eucjp-win-triples.bin"), points: include_bytes!("data/eucjp-win-points.bin"), encode: include_bytes!("data/eucjp-win-encode.bin"), bytes: include_bytes!("data/eucjp-win-bytes.bin"), composites: include_bytes!("data/eucjp-win-composites.bin"), escapes: include_bytes!("data/eucjp-win-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/eucjp-win-boundaries.bin")),
    },
    EncodingInfo {
        name: "EUC-JP-2004",
        aliases: &["EUC_JP-2004"],
        mime: Some("EUC-JP"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/euc-jp-2004-single.bin"), pairs: include_bytes!("data/euc-jp-2004-pairs.bin"), triples: include_bytes!("data/euc-jp-2004-triples.bin"), points: include_bytes!("data/euc-jp-2004-points.bin"), encode: include_bytes!("data/euc-jp-2004-encode.bin"), bytes: include_bytes!("data/euc-jp-2004-bytes.bin"), composites: include_bytes!("data/euc-jp-2004-composites.bin"), escapes: include_bytes!("data/euc-jp-2004-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/euc-jp-2004-boundaries.bin")),
    },
    EncodingInfo {
        name: "SJIS-Mobile#DOCOMO",
        aliases: &["SJIS-DOCOMO", "shift_jis-imode", "x-sjis-emoji-docomo"],
        mime: Some("Shift_JIS"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::MobileSjis(MobileSjis { base: DoubleByte { single: include_bytes!("data/sjis-mobile-docomo-single.bin"), pairs: include_bytes!("data/sjis-mobile-docomo-pairs.bin"), triples: include_bytes!("data/sjis-mobile-docomo-triples.bin"), points: include_bytes!("data/sjis-mobile-docomo-points.bin"), encode: include_bytes!("data/sjis-mobile-docomo-encode.bin"), bytes: include_bytes!("data/sjis-mobile-docomo-bytes.bin"), composites: include_bytes!("data/sjis-mobile-docomo-composites.bin"), escapes: include_bytes!("data/sjis-mobile-docomo-escapes.bin") }, flags: false }),
        slicing: Slicing::LeadingByte(include_bytes!("data/sjis-mobile-docomo-boundaries.bin")),
    },
    EncodingInfo {
        name: "SJIS-Mobile#KDDI",
        aliases: &["SJIS-KDDI", "shift_jis-kddi", "x-sjis-emoji-kddi"],
        mime: Some("Shift_JIS"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::MobileSjis(MobileSjis { base: DoubleByte { single: include_bytes!("data/sjis-mobile-kddi-single.bin"), pairs: include_bytes!("data/sjis-mobile-kddi-pairs.bin"), triples: include_bytes!("data/sjis-mobile-kddi-triples.bin"), points: include_bytes!("data/sjis-mobile-kddi-points.bin"), encode: include_bytes!("data/sjis-mobile-kddi-encode.bin"), bytes: include_bytes!("data/sjis-mobile-kddi-bytes.bin"), composites: include_bytes!("data/sjis-mobile-kddi-composites.bin"), escapes: include_bytes!("data/sjis-mobile-kddi-escapes.bin") }, flags: true }),
        slicing: Slicing::LeadingByte(include_bytes!("data/sjis-mobile-kddi-boundaries.bin")),
    },
    EncodingInfo {
        name: "SJIS-Mobile#SOFTBANK",
        aliases: &["SJIS-SOFTBANK", "shift_jis-softbank", "x-sjis-emoji-softbank"],
        mime: Some("Shift_JIS"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::MobileSjis(MobileSjis { base: DoubleByte { single: include_bytes!("data/sjis-mobile-softbank-single.bin"), pairs: include_bytes!("data/sjis-mobile-softbank-pairs.bin"), triples: include_bytes!("data/sjis-mobile-softbank-triples.bin"), points: include_bytes!("data/sjis-mobile-softbank-points.bin"), encode: include_bytes!("data/sjis-mobile-softbank-encode.bin"), bytes: include_bytes!("data/sjis-mobile-softbank-bytes.bin"), composites: include_bytes!("data/sjis-mobile-softbank-composites.bin"), escapes: include_bytes!("data/sjis-mobile-softbank-escapes.bin") }, flags: true }),
        slicing: Slicing::LeadingByte(include_bytes!("data/sjis-mobile-softbank-boundaries.bin")),
    },
    EncodingInfo {
        name: "SJIS-mac",
        aliases: &["MacJapanese", "x-Mac-Japanese"],
        mime: Some("Shift_JIS"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/sjis-mac-single.bin"), pairs: include_bytes!("data/sjis-mac-pairs.bin"), triples: include_bytes!("data/sjis-mac-triples.bin"), points: include_bytes!("data/sjis-mac-points.bin"), encode: include_bytes!("data/sjis-mac-encode.bin"), bytes: include_bytes!("data/sjis-mac-bytes.bin"), composites: include_bytes!("data/sjis-mac-composites.bin"), escapes: include_bytes!("data/sjis-mac-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/sjis-mac-boundaries.bin")),
    },
    EncodingInfo {
        name: "SJIS-2004",
        aliases: &["SJIS2004", "Shift_JIS-2004"],
        mime: Some("Shift_JIS"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/sjis-2004-single.bin"), pairs: include_bytes!("data/sjis-2004-pairs.bin"), triples: include_bytes!("data/sjis-2004-triples.bin"), points: include_bytes!("data/sjis-2004-points.bin"), encode: include_bytes!("data/sjis-2004-encode.bin"), bytes: include_bytes!("data/sjis-2004-bytes.bin"), composites: include_bytes!("data/sjis-2004-composites.bin"), escapes: include_bytes!("data/sjis-2004-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/sjis-2004-boundaries.bin")),
    },
    EncodingInfo {
        name: "UTF-8-Mobile#DOCOMO",
        aliases: &["UTF-8-DOCOMO", "UTF8-DOCOMO"],
        mime: Some("UTF-8"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::MobileUtf8(MobileUtf8 { decode: include_bytes!("data/utf8-mobile-docomo-decode.bin"), points: include_bytes!("data/utf8-mobile-docomo-points.bin"), encode: include_bytes!("data/utf8-mobile-docomo-encode.bin"), bytes: include_bytes!("data/utf8-mobile-docomo-bytes.bin"), composites: include_bytes!("data/utf8-mobile-docomo-composites.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/utf-8-mobile-docomo-boundaries.bin")),
    },
    EncodingInfo {
        name: "UTF-8-Mobile#KDDI-A",
        aliases: &[],
        mime: Some("UTF-8"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::MobileUtf8(MobileUtf8 { decode: include_bytes!("data/utf8-mobile-kddi-a-decode.bin"), points: include_bytes!("data/utf8-mobile-kddi-a-points.bin"), encode: include_bytes!("data/utf8-mobile-kddi-a-encode.bin"), bytes: include_bytes!("data/utf8-mobile-kddi-a-bytes.bin"), composites: include_bytes!("data/utf8-mobile-kddi-a-composites.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/utf-8-mobile-kddi-a-boundaries.bin")),
    },
    EncodingInfo {
        name: "UTF-8-Mobile#KDDI-B",
        aliases: &["UTF-8-Mobile#KDDI", "UTF-8-KDDI", "UTF8-KDDI"],
        mime: Some("UTF-8"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::MobileUtf8(MobileUtf8 { decode: include_bytes!("data/utf8-mobile-kddi-b-decode.bin"), points: include_bytes!("data/utf8-mobile-kddi-b-points.bin"), encode: include_bytes!("data/utf8-mobile-kddi-b-encode.bin"), bytes: include_bytes!("data/utf8-mobile-kddi-b-bytes.bin"), composites: include_bytes!("data/utf8-mobile-kddi-b-composites.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/utf-8-mobile-kddi-b-boundaries.bin")),
    },
    EncodingInfo {
        name: "UTF-8-Mobile#SOFTBANK",
        aliases: &["UTF-8-SOFTBANK", "UTF8-SOFTBANK"],
        mime: Some("UTF-8"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::MobileUtf8(MobileUtf8 { decode: include_bytes!("data/utf8-mobile-softbank-decode.bin"), points: include_bytes!("data/utf8-mobile-softbank-points.bin"), encode: include_bytes!("data/utf8-mobile-softbank-encode.bin"), bytes: include_bytes!("data/utf8-mobile-softbank-bytes.bin"), composites: include_bytes!("data/utf8-mobile-softbank-composites.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/utf-8-mobile-softbank-boundaries.bin")),
    },
    EncodingInfo {
        name: "CP932",
        aliases: &["MS932", "Windows-31J", "MS_Kanji"],
        mime: Some("Shift_JIS"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/cp932-single.bin"), pairs: include_bytes!("data/cp932-pairs.bin"), triples: include_bytes!("data/cp932-triples.bin"), points: include_bytes!("data/cp932-points.bin"), encode: include_bytes!("data/cp932-encode.bin"), bytes: include_bytes!("data/cp932-bytes.bin"), composites: include_bytes!("data/cp932-composites.bin"), escapes: include_bytes!("data/cp932-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/cp932-boundaries.bin")),
    },
    EncodingInfo {
        name: "SJIS-win",
        aliases: &["SJIS-ms", "SJIS-open"],
        mime: Some("Shift_JIS"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/sjis-win-single.bin"), pairs: include_bytes!("data/sjis-win-pairs.bin"), triples: include_bytes!("data/sjis-win-triples.bin"), points: include_bytes!("data/sjis-win-points.bin"), encode: include_bytes!("data/sjis-win-encode.bin"), bytes: include_bytes!("data/sjis-win-bytes.bin"), composites: include_bytes!("data/sjis-win-composites.bin"), escapes: include_bytes!("data/sjis-win-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/sjis-win-boundaries.bin")),
    },
    EncodingInfo {
        name: "CP51932",
        aliases: &["cp51932"],
        mime: Some("CP51932"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/cp51932-single.bin"), pairs: include_bytes!("data/cp51932-pairs.bin"), triples: include_bytes!("data/cp51932-triples.bin"), points: include_bytes!("data/cp51932-points.bin"), encode: include_bytes!("data/cp51932-encode.bin"), bytes: include_bytes!("data/cp51932-bytes.bin"), composites: include_bytes!("data/cp51932-composites.bin"), escapes: include_bytes!("data/cp51932-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/cp51932-boundaries.bin")),
    },
    EncodingInfo {
        name: "JIS",
        aliases: &[],
        mime: Some("ISO-2022-JP"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Jis(Jis { base: DoubleByte { single: include_bytes!("data/euc-jp-single.bin"), pairs: include_bytes!("data/euc-jp-pairs.bin"), triples: include_bytes!("data/euc-jp-triples.bin"), points: include_bytes!("data/euc-jp-points.bin"), encode: include_bytes!("data/euc-jp-encode.bin"), bytes: include_bytes!("data/euc-jp-bytes.bin"), composites: include_bytes!("data/euc-jp-composites.bin"), escapes: include_bytes!("data/euc-jp-escapes.bin") }, encode: include_bytes!("data/jis-encode.bin"), error_encode: include_bytes!("data/iso-2022-jp-encode.bin"), supplementary: &[], composites: &[], variant: Variant::Jis }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "ISO-2022-JP",
        aliases: &[],
        mime: Some("ISO-2022-JP"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Jis(Jis { base: DoubleByte { single: include_bytes!("data/euc-jp-single.bin"), pairs: include_bytes!("data/euc-jp-pairs.bin"), triples: include_bytes!("data/euc-jp-triples.bin"), points: include_bytes!("data/euc-jp-points.bin"), encode: include_bytes!("data/euc-jp-encode.bin"), bytes: include_bytes!("data/euc-jp-bytes.bin"), composites: include_bytes!("data/euc-jp-composites.bin"), escapes: include_bytes!("data/euc-jp-escapes.bin") }, encode: include_bytes!("data/iso-2022-jp-encode.bin"), error_encode: include_bytes!("data/iso-2022-jp-encode.bin"), supplementary: &[], composites: &[], variant: Variant::Iso2022 }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "ISO-2022-JP-MS",
        aliases: &["ISO2022JPMS"],
        mime: Some("ISO-2022-JP"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Jis(Jis { base: DoubleByte { single: include_bytes!("data/cp51932-single.bin"), pairs: include_bytes!("data/cp51932-pairs.bin"), triples: include_bytes!("data/cp51932-triples.bin"), points: include_bytes!("data/cp51932-points.bin"), encode: include_bytes!("data/cp51932-encode.bin"), bytes: include_bytes!("data/cp51932-bytes.bin"), composites: include_bytes!("data/cp51932-composites.bin"), escapes: include_bytes!("data/cp51932-escapes.bin") }, encode: include_bytes!("data/iso-2022-jp-ms-encode.bin"), error_encode: include_bytes!("data/iso-2022-jp-ms-encode.bin"), supplementary: &[], composites: &[], variant: Variant::Microsoft }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "GB18030",
        aliases: &["gb-18030", "gb-18030-2000"],
        mime: Some("GB18030"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Gb18030(Gb18030 { pairs: include_bytes!("data/gb18030-pairs.bin"), bmp: include_bytes!("data/gb18030-bmp.bin"), encode: include_bytes!("data/gb18030-encode.bin") }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "GB18030-2022",
        aliases: &[],
        mime: Some("GB18030-2022"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Gb18030(Gb18030 { pairs: include_bytes!("data/gb18030-2022-pairs.bin"), bmp: include_bytes!("data/gb18030-2022-bmp.bin"), encode: include_bytes!("data/gb18030-2022-encode.bin") }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "Windows-1252",
        aliases: &["cp1252"],
        mime: Some("Windows-1252"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/windows-1252-decode.bin"), encode: include_bytes!("data/windows-1252-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "Windows-1254",
        aliases: &["CP1254", "CP-1254", "WINDOWS-1254"],
        mime: Some("Windows-1254"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/windows-1254-decode.bin"), encode: include_bytes!("data/windows-1254-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-1",
        aliases: &["ISO8859-1", "latin1"],
        mime: Some("ISO-8859-1"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-1-decode.bin"), encode: include_bytes!("data/iso-8859-1-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-2",
        aliases: &["ISO8859-2", "latin2"],
        mime: Some("ISO-8859-2"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-2-decode.bin"), encode: include_bytes!("data/iso-8859-2-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-3",
        aliases: &["ISO8859-3", "latin3"],
        mime: Some("ISO-8859-3"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-3-decode.bin"), encode: include_bytes!("data/iso-8859-3-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-4",
        aliases: &["ISO8859-4", "latin4"],
        mime: Some("ISO-8859-4"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-4-decode.bin"), encode: include_bytes!("data/iso-8859-4-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-5",
        aliases: &["ISO8859-5", "cyrillic"],
        mime: Some("ISO-8859-5"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-5-decode.bin"), encode: include_bytes!("data/iso-8859-5-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-6",
        aliases: &["ISO8859-6", "arabic"],
        mime: Some("ISO-8859-6"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-6-decode.bin"), encode: include_bytes!("data/iso-8859-6-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-7",
        aliases: &["ISO8859-7", "greek"],
        mime: Some("ISO-8859-7"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-7-decode.bin"), encode: include_bytes!("data/iso-8859-7-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-8",
        aliases: &["ISO8859-8", "hebrew"],
        mime: Some("ISO-8859-8"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-8-decode.bin"), encode: include_bytes!("data/iso-8859-8-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-9",
        aliases: &["ISO8859-9", "latin5"],
        mime: Some("ISO-8859-9"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-9-decode.bin"), encode: include_bytes!("data/iso-8859-9-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-10",
        aliases: &["ISO8859-10", "latin6"],
        mime: Some("ISO-8859-10"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-10-decode.bin"), encode: include_bytes!("data/iso-8859-10-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-13",
        aliases: &["ISO8859-13"],
        mime: Some("ISO-8859-13"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-13-decode.bin"), encode: include_bytes!("data/iso-8859-13-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-14",
        aliases: &["ISO8859-14", "latin8"],
        mime: Some("ISO-8859-14"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-14-decode.bin"), encode: include_bytes!("data/iso-8859-14-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-15",
        aliases: &["ISO8859-15"],
        mime: Some("ISO-8859-15"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-15-decode.bin"), encode: include_bytes!("data/iso-8859-15-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-8859-16",
        aliases: &["ISO8859-16"],
        mime: Some("ISO-8859-16"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/iso-8859-16-decode.bin"), encode: include_bytes!("data/iso-8859-16-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "EUC-CN",
        aliases: &["CN-GB", "EUC_CN", "eucCN", "x-euc-cn", "gb2312"],
        mime: Some("CN-GB"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/euc-cn-single.bin"), pairs: include_bytes!("data/euc-cn-pairs.bin"), triples: include_bytes!("data/euc-cn-triples.bin"), points: include_bytes!("data/euc-cn-points.bin"), encode: include_bytes!("data/euc-cn-encode.bin"), bytes: include_bytes!("data/euc-cn-bytes.bin"), composites: include_bytes!("data/euc-cn-composites.bin"), escapes: include_bytes!("data/euc-cn-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/euc-cn-boundaries.bin")),
    },
    EncodingInfo {
        name: "CP936",
        aliases: &["CP-936", "GBK"],
        mime: Some("CP936"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/cp936-single.bin"), pairs: include_bytes!("data/cp936-pairs.bin"), triples: include_bytes!("data/cp936-triples.bin"), points: include_bytes!("data/cp936-points.bin"), encode: include_bytes!("data/cp936-encode.bin"), bytes: include_bytes!("data/cp936-bytes.bin"), composites: include_bytes!("data/cp936-composites.bin"), escapes: include_bytes!("data/cp936-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/cp936-boundaries.bin")),
    },
    EncodingInfo {
        name: "HZ",
        aliases: &[],
        mime: Some("HZ-GB-2312"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Hz(Hz(DoubleByte { single: include_bytes!("data/euc-cn-single.bin"), pairs: include_bytes!("data/euc-cn-pairs.bin"), triples: include_bytes!("data/euc-cn-triples.bin"), points: include_bytes!("data/euc-cn-points.bin"), encode: include_bytes!("data/euc-cn-encode.bin"), bytes: include_bytes!("data/euc-cn-bytes.bin"), composites: include_bytes!("data/euc-cn-composites.bin"), escapes: include_bytes!("data/euc-cn-escapes.bin") })),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "EUC-TW",
        aliases: &["EUC_TW", "eucTW", "x-euc-tw"],
        mime: Some("EUC-TW"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::EucTw(EucTw { planes: include_bytes!("data/euc-tw-planes.bin"), encode: include_bytes!("data/euc-tw-encode.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/euc-tw-boundaries.bin")),
    },
    EncodingInfo {
        name: "BIG-5",
        aliases: &["CN-BIG5", "BIG-FIVE", "BIGFIVE"],
        mime: Some("BIG5"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/big-5-single.bin"), pairs: include_bytes!("data/big-5-pairs.bin"), triples: include_bytes!("data/big-5-triples.bin"), points: include_bytes!("data/big-5-points.bin"), encode: include_bytes!("data/big-5-encode.bin"), bytes: include_bytes!("data/big-5-bytes.bin"), composites: include_bytes!("data/big-5-composites.bin"), escapes: include_bytes!("data/big-5-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/big-5-boundaries.bin")),
    },
    EncodingInfo {
        name: "CP950",
        aliases: &[],
        mime: Some("BIG5"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/cp950-single.bin"), pairs: include_bytes!("data/cp950-pairs.bin"), triples: include_bytes!("data/cp950-triples.bin"), points: include_bytes!("data/cp950-points.bin"), encode: include_bytes!("data/cp950-encode.bin"), bytes: include_bytes!("data/cp950-bytes.bin"), composites: include_bytes!("data/cp950-composites.bin"), escapes: include_bytes!("data/cp950-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/cp950-boundaries.bin")),
    },
    EncodingInfo {
        name: "EUC-KR",
        aliases: &["EUC_KR", "eucKR", "x-euc-kr"],
        mime: Some("EUC-KR"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/euc-kr-single.bin"), pairs: include_bytes!("data/euc-kr-pairs.bin"), triples: include_bytes!("data/euc-kr-triples.bin"), points: include_bytes!("data/euc-kr-points.bin"), encode: include_bytes!("data/euc-kr-encode.bin"), bytes: include_bytes!("data/euc-kr-bytes.bin"), composites: include_bytes!("data/euc-kr-composites.bin"), escapes: include_bytes!("data/euc-kr-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/euc-kr-boundaries.bin")),
    },
    EncodingInfo {
        name: "UHC",
        aliases: &["CP949"],
        mime: Some("UHC"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::DoubleByte(DoubleByte { single: include_bytes!("data/uhc-single.bin"), pairs: include_bytes!("data/uhc-pairs.bin"), triples: include_bytes!("data/uhc-triples.bin"), points: include_bytes!("data/uhc-points.bin"), encode: include_bytes!("data/uhc-encode.bin"), bytes: include_bytes!("data/uhc-bytes.bin"), composites: include_bytes!("data/uhc-composites.bin"), escapes: include_bytes!("data/uhc-escapes.bin") }),
        slicing: Slicing::LeadingByte(include_bytes!("data/uhc-boundaries.bin")),
    },
    EncodingInfo {
        name: "ISO-2022-KR",
        aliases: &[],
        mime: Some("ISO-2022-KR"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::Iso2022Kr(Iso2022Kr(DoubleByte { single: include_bytes!("data/uhc-single.bin"), pairs: include_bytes!("data/uhc-pairs.bin"), triples: include_bytes!("data/uhc-triples.bin"), points: include_bytes!("data/uhc-points.bin"), encode: include_bytes!("data/uhc-encode.bin"), bytes: include_bytes!("data/uhc-bytes.bin"), composites: include_bytes!("data/uhc-composites.bin"), escapes: include_bytes!("data/uhc-escapes.bin") })),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "Windows-1251",
        aliases: &["CP1251", "CP-1251", "WINDOWS-1251"],
        mime: Some("Windows-1251"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/windows-1251-decode.bin"), encode: include_bytes!("data/windows-1251-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "CP866",
        aliases: &["CP-866", "IBM866", "IBM-866"],
        mime: Some("CP866"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/cp866-decode.bin"), encode: include_bytes!("data/cp866-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "KOI8-R",
        aliases: &["KOI8R"],
        mime: Some("KOI8-R"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/koi8-r-decode.bin"), encode: include_bytes!("data/koi8-r-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "KOI8-U",
        aliases: &["KOI8U"],
        mime: Some("KOI8-U"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/koi8-u-decode.bin"), encode: include_bytes!("data/koi8-u-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ArmSCII-8",
        aliases: &["ArmSCII8", "ARMSCII-8", "ARMSCII8"],
        mime: Some("ArmSCII-8"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/armscii-8-decode.bin"), encode: include_bytes!("data/armscii-8-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "CP850",
        aliases: &["CP-850", "IBM850", "IBM-850"],
        mime: Some("CP850"),
        supports_ord_chr: true,
        supports_detection: true,
        codec: Codec::SingleByte(SingleByte { decode: include_bytes!("data/cp850-decode.bin"), encode: include_bytes!("data/cp850-encode.bin") }),
        slicing: Slicing::Fixed(1),
    },
    EncodingInfo {
        name: "ISO-2022-JP-2004",
        aliases: &[],
        mime: Some("ISO-2022-JP-2004"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Jis2004(Jis2004 { classic: DoubleByte { single: include_bytes!("data/euc-jp-single.bin"), pairs: include_bytes!("data/euc-jp-pairs.bin"), triples: include_bytes!("data/euc-jp-triples.bin"), points: include_bytes!("data/euc-jp-points.bin"), encode: include_bytes!("data/euc-jp-encode.bin"), bytes: include_bytes!("data/euc-jp-bytes.bin"), composites: include_bytes!("data/euc-jp-composites.bin"), escapes: include_bytes!("data/euc-jp-escapes.bin") }, extended: DoubleByte { single: include_bytes!("data/euc-jp-2004-single.bin"), pairs: include_bytes!("data/euc-jp-2004-pairs.bin"), triples: include_bytes!("data/euc-jp-2004-triples.bin"), points: include_bytes!("data/euc-jp-2004-points.bin"), encode: include_bytes!("data/euc-jp-2004-encode.bin"), bytes: include_bytes!("data/euc-jp-2004-bytes.bin"), composites: include_bytes!("data/euc-jp-2004-composites.bin"), escapes: include_bytes!("data/euc-jp-2004-escapes.bin") } }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "ISO-2022-JP-MOBILE#KDDI",
        aliases: &["ISO-2022-JP-KDDI"],
        mime: Some("ISO-2022-JP"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Jis(Jis { base: DoubleByte { single: include_bytes!("data/euc-jp-single.bin"), pairs: include_bytes!("data/euc-jp-pairs.bin"), triples: include_bytes!("data/euc-jp-triples.bin"), points: include_bytes!("data/euc-jp-points.bin"), encode: include_bytes!("data/euc-jp-encode.bin"), bytes: include_bytes!("data/euc-jp-bytes.bin"), composites: include_bytes!("data/euc-jp-composites.bin"), escapes: include_bytes!("data/euc-jp-escapes.bin") }, encode: include_bytes!("data/iso-2022-jp-mobile#kddi-encode.bin"), error_encode: include_bytes!("data/iso-2022-jp-mobile#kddi-encode.bin"), supplementary: include_bytes!("data/jis-kddi-supplementary.bin"), composites: include_bytes!("data/jis-kddi-composites.bin"), variant: Variant::Kddi }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "CP50220",
        aliases: &["cp50220raw", "cp50220-raw", "JIS-ms"],
        mime: Some("ISO-2022-JP"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Jis(Jis { base: DoubleByte { single: include_bytes!("data/euc-jp-single.bin"), pairs: include_bytes!("data/euc-jp-pairs.bin"), triples: include_bytes!("data/euc-jp-triples.bin"), points: include_bytes!("data/euc-jp-points.bin"), encode: include_bytes!("data/euc-jp-encode.bin"), bytes: include_bytes!("data/euc-jp-bytes.bin"), composites: include_bytes!("data/euc-jp-composites.bin"), escapes: include_bytes!("data/euc-jp-escapes.bin") }, encode: include_bytes!("data/cp50221-encode.bin"), error_encode: include_bytes!("data/cp50221-encode.bin"), supplementary: &[], composites: &[], variant: Variant::Cp50220 }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "CP50221",
        aliases: &[],
        mime: Some("ISO-2022-JP"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Jis(Jis { base: DoubleByte { single: include_bytes!("data/euc-jp-single.bin"), pairs: include_bytes!("data/euc-jp-pairs.bin"), triples: include_bytes!("data/euc-jp-triples.bin"), points: include_bytes!("data/euc-jp-points.bin"), encode: include_bytes!("data/euc-jp-encode.bin"), bytes: include_bytes!("data/euc-jp-bytes.bin"), composites: include_bytes!("data/euc-jp-composites.bin"), escapes: include_bytes!("data/euc-jp-escapes.bin") }, encode: include_bytes!("data/cp50221-encode.bin"), error_encode: include_bytes!("data/cp50221-encode.bin"), supplementary: &[], composites: &[], variant: Variant::Cp50221 }),
        slicing: Slicing::Converted,
    },
    EncodingInfo {
        name: "CP50222",
        aliases: &[],
        mime: Some("ISO-2022-JP"),
        supports_ord_chr: false,
        supports_detection: true,
        codec: Codec::Jis(Jis { base: DoubleByte { single: include_bytes!("data/euc-jp-single.bin"), pairs: include_bytes!("data/euc-jp-pairs.bin"), triples: include_bytes!("data/euc-jp-triples.bin"), points: include_bytes!("data/euc-jp-points.bin"), encode: include_bytes!("data/euc-jp-encode.bin"), bytes: include_bytes!("data/euc-jp-bytes.bin"), composites: include_bytes!("data/euc-jp-composites.bin"), escapes: include_bytes!("data/euc-jp-escapes.bin") }, encode: include_bytes!("data/cp50222-encode.bin"), error_encode: include_bytes!("data/cp50222-encode.bin"), supplementary: &[], composites: &[], variant: Variant::Cp50222 }),
        slicing: Slicing::Converted,
    },
];
