//! Purpose:
//! AArch64 `__rt_strip_tags` state machine for PHP 8.5 `strip_tags()`.
//!
//! Called from:
//! - `super::emit_strip_tags()` on macos-aarch64, ios-arm64, ios-sim-arm64,
//!   and linux-aarch64.
//!
//! Key details:
//! - ABI: `x1`/`x2` = subject pointer/length, `x3`/`x4` = allow pointer/length.
//! - Result: `x1`/`x2` = stripped pointer/length, published through
//!   `__rt_concat_publish`.
//! - Zero allow length is treated as no allow-list.

use crate::codegen_support::emit::Emitter;

use super::emit_st;

/// Emits the AArch64 `__rt_strip_tags` helper.
pub(super) fn emit_strip_tags_aarch64(emitter: &mut Emitter) {
    emitter.blank();
    emitter.comment("--- runtime: strip_tags ---");
    emitter.label_global("__rt_strip_tags");

    emit_st(emitter, "sub sp, sp, #224");
    emit_st(emitter, "stp x29, x30, [sp, #208]");
    emit_st(emitter, "add x29, sp, #208");
    emit_st(emitter, "stp x19, x20, [x29, #-200]");
    emit_st(emitter, "stp x21, x22, [x29, #-184]");
    emit_st(emitter, "str x23, [x29, #-168]");
    emit_st(emitter, "str x1, [x29, #-8]");
    emit_st(emitter, "str x2, [x29, #-16]");
    emit_st(emitter, "str x3, [x29, #-24]");
    emit_st(emitter, "str x4, [x29, #-32]");

    emitter.comment("-- reserve output, and allow/tag/norm scratch when an allow-list is present --");
    emit_st(emitter, "mov x0, x2");
    emit_st(emitter, "cbz x4, __rt_strip_tags_reserve");
    emit_st(emitter, "adds x9, x2, x2");
    emit_st(emitter, "b.cs __rt_strip_tags_overflow");
    emit_st(emitter, "adds x9, x9, x2");
    emit_st(emitter, "b.cs __rt_strip_tags_overflow");
    emit_st(emitter, "adds x9, x9, x4");
    emit_st(emitter, "b.cs __rt_strip_tags_overflow");
    emit_st(emitter, "adds x9, x9, #4");
    emit_st(emitter, "b.cs __rt_strip_tags_overflow");
    emit_st(emitter, "mov x0, x9");
    emitter.label("__rt_strip_tags_reserve");
    emit_st(emitter, "bl __rt_concat_reserve");
    emit_st(emitter, "str x0, [x29, #-40]");
    emit_st(emitter, "str x0, [x29, #-48]");
    emit_st(emitter, "str xzr, [x29, #-56]");
    emit_st(emitter, "str xzr, [x29, #-64]");
    emit_st(emitter, "str xzr, [x29, #-72]");
    emit_st(emitter, "str xzr, [x29, #-80]");
    emit_st(emitter, "str xzr, [x29, #-88]");
    emit_st(emitter, "ldr x9, [x29, #-32]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_init");

    emitter.comment("-- partition the reservation: out | allow_lc | tag | norm --");
    emit_st(emitter, "ldr x10, [x29, #-40]");
    emit_st(emitter, "ldr x11, [x29, #-16]");
    emit_st(emitter, "add x10, x10, x11");
    emit_st(emitter, "str x10, [x29, #-72]");
    emit_st(emitter, "str x9, [x29, #-80]");
    emit_st(emitter, "add x10, x10, x9");
    emit_st(emitter, "str x10, [x29, #-56]");
    emit_st(emitter, "add x12, x11, #2");
    emit_st(emitter, "add x10, x10, x12");
    emit_st(emitter, "str x10, [x29, #-88]");
    emit_st(emitter, "ldr x1, [x29, #-24]");
    emit_st(emitter, "ldr x2, [x29, #-72]");
    emit_st(emitter, "mov x3, xzr");
    emitter.label("__rt_strip_tags_lc_allow");
    emit_st(emitter, "cmp x3, x9");
    emit_st(emitter, "b.hs __rt_strip_tags_init");
    emit_st(emitter, "ldrb w4, [x1, x3]");
    emit_st(emitter, "cmp w4, #65");
    emit_st(emitter, "b.lo __rt_strip_tags_lc_store");
    emit_st(emitter, "cmp w4, #90");
    emit_st(emitter, "b.hi __rt_strip_tags_lc_store");
    emit_st(emitter, "orr w4, w4, #32");
    emitter.label("__rt_strip_tags_lc_store");
    emit_st(emitter, "strb w4, [x2, x3]");
    emit_st(emitter, "add x3, x3, #1");
    emit_st(emitter, "b __rt_strip_tags_lc_allow");

    emitter.label("__rt_strip_tags_init");
    emit_st(emitter, "str xzr, [x29, #-96]");
    emit_st(emitter, "str xzr, [x29, #-104]");
    emit_st(emitter, "str xzr, [x29, #-112]");
    emit_st(emitter, "str xzr, [x29, #-120]");
    emit_st(emitter, "str xzr, [x29, #-128]");
    emit_st(emitter, "str xzr, [x29, #-136]");
    emit_st(emitter, "str xzr, [x29, #-144]");
    emit_st(emitter, "ldr x19, [x29, #-8]");
    emit_st(emitter, "ldr x20, [x29, #-16]");

    emitter.label("__rt_strip_tags_loop");
    emit_st(emitter, "ldr x21, [x29, #-96]");
    emit_st(emitter, "cmp x21, x20");
    emit_st(emitter, "b.hs __rt_strip_tags_done");
    emit_st(emitter, "ldrb w22, [x19, x21]");
    emit_st(emitter, "ldr x9, [x29, #-104]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_s0");
    emit_st(emitter, "cmp x9, #1");
    emit_st(emitter, "b.eq __rt_strip_tags_s1");
    emit_st(emitter, "cmp x9, #2");
    emit_st(emitter, "b.eq __rt_strip_tags_s2");
    emit_st(emitter, "cmp x9, #3");
    emit_st(emitter, "b.eq __rt_strip_tags_s3");
    emit_st(emitter, "b __rt_strip_tags_s4");

    emit_state0_aarch64(emitter);
    emit_state1_aarch64(emitter);
    emit_state2_aarch64(emitter);
    emit_state3_aarch64(emitter);
    emit_state4_aarch64(emitter);
    emit_helpers_aarch64(emitter);

    emitter.label("__rt_strip_tags_done");
    emit_st(emitter, "ldr x1, [x29, #-40]");
    emit_st(emitter, "ldr x2, [x29, #-48]");
    emit_st(emitter, "sub x2, x2, x1");
    emit_st(emitter, "bl __rt_concat_publish");
    emit_st(emitter, "ldp x19, x20, [x29, #-200]");
    emit_st(emitter, "ldp x21, x22, [x29, #-184]");
    emit_st(emitter, "ldr x23, [x29, #-168]");
    emit_st(emitter, "ldp x29, x30, [sp, #208]");
    emit_st(emitter, "add sp, sp, #224");
    emit_st(emitter, "ret");

    emitter.label("__rt_strip_tags_overflow");
    emit_st(emitter, "b __rt_alloc_overflow");
}

/// Emits output-state handling (state 0).
fn emit_state0_aarch64(emitter: &mut Emitter) {
    emitter.comment("-- state 0: copy bytes until a real tag opener --");
    emitter.label("__rt_strip_tags_s0");
    emit_st(emitter, "cbz w22, __rt_strip_tags_advance");
    emit_st(emitter, "cmp w22, #60");
    emit_st(emitter, "b.ne __rt_strip_tags_s0_gt");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbnz x9, __rt_strip_tags_advance");
    emit_st(emitter, "bl __rt_strip_tags_next");
    emit_st(emitter, "bl __rt_strip_tags_isspace");
    emit_st(emitter, "cbz w0, __rt_strip_tags_s0_open");
    emit_st(emitter, "mov w0, #60");
    emit_st(emitter, "bl __rt_strip_tags_putc");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s0_open");
    emit_st(emitter, "mov x9, #60");
    emit_st(emitter, "str x9, [x29, #-136]");
    emit_st(emitter, "mov x9, #1");
    emit_st(emitter, "str x9, [x29, #-104]");
    emit_st(emitter, "ldr x9, [x29, #-80]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_s0_open_adv");
    emit_st(emitter, "str xzr, [x29, #-64]");
    emit_st(emitter, "mov w0, #60");
    emit_st(emitter, "bl __rt_strip_tags_collect");
    emitter.label("__rt_strip_tags_s0_open_adv");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
    emitter.label("__rt_strip_tags_s0_gt");
    emit_st(emitter, "cmp w22, #62");
    emit_st(emitter, "b.ne __rt_strip_tags_s0_copy");
    emit_st(emitter, "ldr x9, [x29, #-120]");
    emit_st(emitter, "cmp x9, #0");
    emit_st(emitter, "b.le __rt_strip_tags_s0_gt_q");
    emit_st(emitter, "sub x9, x9, #1");
    emit_st(emitter, "str x9, [x29, #-120]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s0_gt_q");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbnz x9, __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s0_copy");
    emit_st(emitter, "mov w0, w22");
    emit_st(emitter, "bl __rt_strip_tags_putc");
    emit_st(emitter, "b __rt_strip_tags_advance");
}

/// Emits HTML-tag-state handling (state 1).
fn emit_state1_aarch64(emitter: &mut Emitter) {
    emitter.comment("-- state 1: inside a normal HTML/XML tag --");
    emitter.label("__rt_strip_tags_s1");
    emit_st(emitter, "cbz w22, __rt_strip_tags_advance");
    emit_st(emitter, "cmp w22, #60");
    emit_st(emitter, "b.ne __rt_strip_tags_s1_gt");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbnz x9, __rt_strip_tags_advance");
    emit_st(emitter, "bl __rt_strip_tags_next");
    emit_st(emitter, "bl __rt_strip_tags_isspace");
    emit_st(emitter, "cbz w0, __rt_strip_tags_s1_depth");
    emit_st(emitter, "mov w0, w22");
    emit_st(emitter, "bl __rt_strip_tags_collect");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s1_depth");
    emit_st(emitter, "ldr x9, [x29, #-120]");
    emit_st(emitter, "add x9, x9, #1");
    emit_st(emitter, "str x9, [x29, #-120]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s1_gt");
    emit_st(emitter, "cmp w22, #62");
    emit_st(emitter, "b.ne __rt_strip_tags_s1_quote");
    emit_st(emitter, "ldr x9, [x29, #-120]");
    emit_st(emitter, "cmp x9, #0");
    emit_st(emitter, "b.le __rt_strip_tags_s1_gt_q");
    emit_st(emitter, "sub x9, x9, #1");
    emit_st(emitter, "str x9, [x29, #-120]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s1_gt_q");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbnz x9, __rt_strip_tags_advance");
    emit_st(emitter, "ldr x9, [x29, #-144]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_s1_close");
    emit_st(emitter, "cbz x21, __rt_strip_tags_s1_close");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #45");
    emit_st(emitter, "b.eq __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s1_close");
    emit_st(emitter, "mov x9, #62");
    emit_st(emitter, "str x9, [x29, #-136]");
    emit_st(emitter, "str xzr, [x29, #-112]");
    emit_st(emitter, "str xzr, [x29, #-104]");
    emit_st(emitter, "str xzr, [x29, #-144]");
    emit_st(emitter, "ldr x9, [x29, #-80]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_s1_close_adv");
    emit_st(emitter, "mov w0, #62");
    emit_st(emitter, "bl __rt_strip_tags_collect");
    emit_st(emitter, "bl __rt_strip_tags_tag_find");
    emit_st(emitter, "cbz w0, __rt_strip_tags_s1_clear_tag");
    emit_st(emitter, "bl __rt_strip_tags_emit_tag");
    emitter.label("__rt_strip_tags_s1_clear_tag");
    emit_st(emitter, "str xzr, [x29, #-64]");
    emitter.label("__rt_strip_tags_s1_close_adv");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
    emitter.label("__rt_strip_tags_s1_quote");
    emit_st(emitter, "cmp w22, #34");
    emit_st(emitter, "b.eq __rt_strip_tags_s1_toggle_q");
    emit_st(emitter, "cmp w22, #39");
    emit_st(emitter, "b.eq __rt_strip_tags_s1_toggle_q");
    emit_st(emitter, "cmp w22, #33");
    emit_st(emitter, "b.eq __rt_strip_tags_s1_bang");
    emit_st(emitter, "cmp w22, #63");
    emit_st(emitter, "b.eq __rt_strip_tags_s1_quest");
    emit_st(emitter, "mov w0, w22");
    emit_st(emitter, "bl __rt_strip_tags_collect");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s1_toggle_q");
    emit_st(emitter, "cbz x21, __rt_strip_tags_s1_q_collect");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_s1_q_set");
    emit_st(emitter, "cmp x9, x22");
    emit_st(emitter, "b.ne __rt_strip_tags_s1_q_collect");
    emit_st(emitter, "str xzr, [x29, #-112]");
    emit_st(emitter, "b __rt_strip_tags_s1_q_collect");
    emitter.label("__rt_strip_tags_s1_q_set");
    emit_st(emitter, "str x22, [x29, #-112]");
    emitter.label("__rt_strip_tags_s1_q_collect");
    emit_st(emitter, "mov w0, w22");
    emit_st(emitter, "bl __rt_strip_tags_collect");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s1_bang");
    emit_st(emitter, "cbz x21, __rt_strip_tags_s1_bang_col");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #60");
    emit_st(emitter, "b.ne __rt_strip_tags_s1_bang_col");
    emit_st(emitter, "mov x9, #3");
    emit_st(emitter, "str x9, [x29, #-104]");
    emit_st(emitter, "str x22, [x29, #-136]");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
    emitter.label("__rt_strip_tags_s1_bang_col");
    emit_st(emitter, "mov w0, w22");
    emit_st(emitter, "bl __rt_strip_tags_collect");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s1_quest");
    emit_st(emitter, "cbz x21, __rt_strip_tags_s1_quest_col");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #60");
    emit_st(emitter, "b.ne __rt_strip_tags_s1_quest_col");
    emit_st(emitter, "str xzr, [x29, #-128]");
    emit_st(emitter, "mov x9, #2");
    emit_st(emitter, "str x9, [x29, #-104]");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
    emitter.label("__rt_strip_tags_s1_quest_col");
    emit_st(emitter, "mov w0, w22");
    emit_st(emitter, "bl __rt_strip_tags_collect");
    emit_st(emitter, "b __rt_strip_tags_advance");
}

/// Emits PHP-tag-state handling (state 2).
fn emit_state2_aarch64(emitter: &mut Emitter) {
    emitter.comment("-- state 2: inside a PHP tag, unless `<?xml` returns to HTML --");
    emitter.label("__rt_strip_tags_s2");
    emit_st(emitter, "cmp w22, #40");
    emit_st(emitter, "b.ne __rt_strip_tags_s2_rparen");
    emit_st(emitter, "ldr x9, [x29, #-136]");
    emit_st(emitter, "cmp x9, #34");
    emit_st(emitter, "b.eq __rt_strip_tags_advance");
    emit_st(emitter, "cmp x9, #39");
    emit_st(emitter, "b.eq __rt_strip_tags_advance");
    emit_st(emitter, "mov x9, #40");
    emit_st(emitter, "str x9, [x29, #-136]");
    emit_st(emitter, "ldr x9, [x29, #-128]");
    emit_st(emitter, "add x9, x9, #1");
    emit_st(emitter, "str x9, [x29, #-128]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s2_rparen");
    emit_st(emitter, "cmp w22, #41");
    emit_st(emitter, "b.ne __rt_strip_tags_s2_gt");
    emit_st(emitter, "ldr x9, [x29, #-136]");
    emit_st(emitter, "cmp x9, #34");
    emit_st(emitter, "b.eq __rt_strip_tags_advance");
    emit_st(emitter, "cmp x9, #39");
    emit_st(emitter, "b.eq __rt_strip_tags_advance");
    emit_st(emitter, "mov x9, #41");
    emit_st(emitter, "str x9, [x29, #-136]");
    emit_st(emitter, "ldr x9, [x29, #-128]");
    emit_st(emitter, "sub x9, x9, #1");
    emit_st(emitter, "str x9, [x29, #-128]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s2_gt");
    emit_st(emitter, "cmp w22, #62");
    emit_st(emitter, "b.ne __rt_strip_tags_s2_quote");
    emit_st(emitter, "ldr x9, [x29, #-120]");
    emit_st(emitter, "cmp x9, #0");
    emit_st(emitter, "b.le __rt_strip_tags_s2_gt_q");
    emit_st(emitter, "sub x9, x9, #1");
    emit_st(emitter, "str x9, [x29, #-120]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s2_gt_q");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbnz x9, __rt_strip_tags_advance");
    emit_st(emitter, "ldr x9, [x29, #-128]");
    emit_st(emitter, "cbnz x9, __rt_strip_tags_advance");
    emit_st(emitter, "ldr x9, [x29, #-136]");
    emit_st(emitter, "cmp x9, #34");
    emit_st(emitter, "b.eq __rt_strip_tags_advance");
    emit_st(emitter, "cbz x21, __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #63");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "str xzr, [x29, #-112]");
    emit_st(emitter, "str xzr, [x29, #-104]");
    emit_st(emitter, "str xzr, [x29, #-64]");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
    emitter.label("__rt_strip_tags_s2_quote");
    emit_st(emitter, "cmp w22, #34");
    emit_st(emitter, "b.eq __rt_strip_tags_s2_q");
    emit_st(emitter, "cmp w22, #39");
    emit_st(emitter, "b.eq __rt_strip_tags_s2_q");
    emit_st(emitter, "cmp w22, #108");
    emit_st(emitter, "b.eq __rt_strip_tags_s2_xml");
    emit_st(emitter, "cmp w22, #76");
    emit_st(emitter, "b.eq __rt_strip_tags_s2_xml");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s2_q");
    emit_st(emitter, "cbz x21, __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #92");
    emit_st(emitter, "b.eq __rt_strip_tags_advance");
    emit_st(emitter, "ldr x9, [x29, #-136]");
    emit_st(emitter, "cmp x9, x22");
    emit_st(emitter, "b.ne __rt_strip_tags_s2_q_set");
    emit_st(emitter, "str xzr, [x29, #-136]");
    emit_st(emitter, "b __rt_strip_tags_s2_q_in");
    emitter.label("__rt_strip_tags_s2_q_set");
    emit_st(emitter, "cmp x9, #92");
    emit_st(emitter, "b.eq __rt_strip_tags_s2_q_in");
    emit_st(emitter, "str x22, [x29, #-136]");
    emitter.label("__rt_strip_tags_s2_q_in");
    emit_st(emitter, "cbz x21, __rt_strip_tags_advance");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_s2_q_open");
    emit_st(emitter, "cmp x9, x22");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "str xzr, [x29, #-112]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s2_q_open");
    emit_st(emitter, "str x22, [x29, #-112]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s2_xml");
    emit_st(emitter, "cmp x21, #4");
    emit_st(emitter, "b.lo __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "orr w9, w9, #32");
    emit_st(emitter, "cmp w9, #109");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #2");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "orr w9, w9, #32");
    emit_st(emitter, "cmp w9, #120");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #3");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #63");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #4");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #60");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "mov x9, #1");
    emit_st(emitter, "str x9, [x29, #-104]");
    emit_st(emitter, "str x9, [x29, #-144]");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
}

/// Emits `<!...` handling (state 3), including comments and `<!DOCTYPE`.
fn emit_state3_aarch64(emitter: &mut Emitter) {
    emitter.comment("-- state 3: `<!` markup, comments, and DOCTYPE --");
    emitter.label("__rt_strip_tags_s3");
    emit_st(emitter, "cmp w22, #62");
    emit_st(emitter, "b.ne __rt_strip_tags_s3_quote");
    emit_st(emitter, "ldr x9, [x29, #-120]");
    emit_st(emitter, "cmp x9, #0");
    emit_st(emitter, "b.le __rt_strip_tags_s3_gt_q");
    emit_st(emitter, "sub x9, x9, #1");
    emit_st(emitter, "str x9, [x29, #-120]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s3_gt_q");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbnz x9, __rt_strip_tags_advance");
    emit_st(emitter, "str xzr, [x29, #-112]");
    emit_st(emitter, "str xzr, [x29, #-104]");
    emit_st(emitter, "str xzr, [x29, #-64]");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
    emitter.label("__rt_strip_tags_s3_quote");
    emit_st(emitter, "cmp w22, #34");
    emit_st(emitter, "b.eq __rt_strip_tags_s3_q");
    emit_st(emitter, "cmp w22, #39");
    emit_st(emitter, "b.eq __rt_strip_tags_s3_q");
    emit_st(emitter, "cmp w22, #45");
    emit_st(emitter, "b.eq __rt_strip_tags_s3_dash");
    emit_st(emitter, "cmp w22, #69");
    emit_st(emitter, "b.eq __rt_strip_tags_s3_doctype");
    emit_st(emitter, "cmp w22, #101");
    emit_st(emitter, "b.eq __rt_strip_tags_s3_doctype");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s3_q");
    emit_st(emitter, "cbz x21, __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #92");
    emit_st(emitter, "b.eq __rt_strip_tags_advance");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_s3_q_open");
    emit_st(emitter, "cmp x9, x22");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "str xzr, [x29, #-112]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s3_q_open");
    emit_st(emitter, "str x22, [x29, #-112]");
    emit_st(emitter, "b __rt_strip_tags_advance");
    emitter.label("__rt_strip_tags_s3_dash");
    emit_st(emitter, "cmp x21, #2");
    emit_st(emitter, "b.lo __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #45");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #2");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #33");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "mov x9, #4");
    emit_st(emitter, "str x9, [x29, #-104]");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
    emitter.label("__rt_strip_tags_s3_doctype");
    emit_st(emitter, "cmp x21, #7");
    emit_st(emitter, "b.ls __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "orr w9, w9, #32");
    emit_st(emitter, "cmp w9, #112");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #2");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "orr w9, w9, #32");
    emit_st(emitter, "cmp w9, #121");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #3");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "orr w9, w9, #32");
    emit_st(emitter, "cmp w9, #116");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #4");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "orr w9, w9, #32");
    emit_st(emitter, "cmp w9, #99");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #5");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "orr w9, w9, #32");
    emit_st(emitter, "cmp w9, #111");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #6");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "orr w9, w9, #32");
    emit_st(emitter, "cmp w9, #100");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "mov x9, #1");
    emit_st(emitter, "str x9, [x29, #-104]");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");
}

/// Emits HTML-comment handling (state 4).
fn emit_state4_aarch64(emitter: &mut Emitter) {
    emitter.comment("-- state 4: HTML comment, closed only by `-->` --");
    emitter.label("__rt_strip_tags_s4");
    emit_st(emitter, "cmp w22, #62");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "ldr x9, [x29, #-112]");
    emit_st(emitter, "cbnz x9, __rt_strip_tags_advance");
    emit_st(emitter, "cmp x21, #2");
    emit_st(emitter, "b.lo __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #1");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #45");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "sub x10, x21, #2");
    emit_st(emitter, "ldrb w9, [x19, x10]");
    emit_st(emitter, "cmp w9, #45");
    emit_st(emitter, "b.ne __rt_strip_tags_advance");
    emit_st(emitter, "str xzr, [x29, #-112]");
    emit_st(emitter, "str xzr, [x29, #-104]");
    emit_st(emitter, "str xzr, [x29, #-64]");
    emit_st(emitter, "b __rt_strip_tags_advance");
}

/// Emits local helpers shared by the AArch64 state machine.
fn emit_helpers_aarch64(emitter: &mut Emitter) {
    emitter.label("__rt_strip_tags_advance");
    emit_st(emitter, "add x21, x21, #1");
    emit_st(emitter, "str x21, [x29, #-96]");
    emit_st(emitter, "b __rt_strip_tags_loop");

    emitter.comment("-- write one kept output byte --");
    emitter.label("__rt_strip_tags_putc");
    emit_st(emitter, "ldr x9, [x29, #-48]");
    emit_st(emitter, "strb w0, [x9], #1");
    emit_st(emitter, "str x9, [x29, #-48]");
    emit_st(emitter, "ret");

    emitter.comment("-- append one collected tag byte when an allow-list is active --");
    emitter.label("__rt_strip_tags_collect");
    emit_st(emitter, "ldr x9, [x29, #-80]");
    emit_st(emitter, "cbz x9, __rt_strip_tags_collect_ret");
    emit_st(emitter, "ldr x10, [x29, #-56]");
    emit_st(emitter, "ldr x11, [x29, #-64]");
    emit_st(emitter, "strb w0, [x10, x11]");
    emit_st(emitter, "add x11, x11, #1");
    emit_st(emitter, "str x11, [x29, #-64]");
    emitter.label("__rt_strip_tags_collect_ret");
    emit_st(emitter, "ret");

    emitter.comment("-- copy a kept allowed tag into the output --");
    emitter.label("__rt_strip_tags_emit_tag");
    emit_st(emitter, "ldr x1, [x29, #-56]");
    emit_st(emitter, "ldr x2, [x29, #-64]");
    emit_st(emitter, "ldr x3, [x29, #-48]");
    emit_st(emitter, "mov x4, xzr");
    emitter.label("__rt_strip_tags_emit_tag_loop");
    emit_st(emitter, "cmp x4, x2");
    emit_st(emitter, "b.hs __rt_strip_tags_emit_tag_done");
    emit_st(emitter, "ldrb w9, [x1, x4]");
    emit_st(emitter, "strb w9, [x3, x4]");
    emit_st(emitter, "add x4, x4, #1");
    emit_st(emitter, "b __rt_strip_tags_emit_tag_loop");
    emitter.label("__rt_strip_tags_emit_tag_done");
    emit_st(emitter, "add x3, x3, x2");
    emit_st(emitter, "str x3, [x29, #-48]");
    emit_st(emitter, "ret");

    emitter.comment("-- load the next subject byte, or 0 at EOF, into w0 --");
    emitter.label("__rt_strip_tags_next");
    emit_st(emitter, "add x9, x21, #1");
    emit_st(emitter, "cmp x9, x20");
    emit_st(emitter, "b.hs __rt_strip_tags_next_eof");
    emit_st(emitter, "ldrb w0, [x19, x9]");
    emit_st(emitter, "ret");
    emitter.label("__rt_strip_tags_next_eof");
    emit_st(emitter, "mov w0, wzr");
    emit_st(emitter, "ret");

    emitter.comment("-- C-locale isspace: 0x09-0x0d or 0x20; result in w0 --");
    emitter.label("__rt_strip_tags_isspace");
    emit_st(emitter, "cmp w0, #9");
    emit_st(emitter, "b.lo __rt_strip_tags_isspace_no");
    emit_st(emitter, "cmp w0, #13");
    emit_st(emitter, "b.ls __rt_strip_tags_isspace_yes");
    emit_st(emitter, "cmp w0, #32");
    emit_st(emitter, "b.eq __rt_strip_tags_isspace_yes");
    emitter.label("__rt_strip_tags_isspace_no");
    emit_st(emitter, "mov w0, wzr");
    emit_st(emitter, "ret");
    emitter.label("__rt_strip_tags_isspace_yes");
    emit_st(emitter, "mov w0, #1");
    emit_st(emitter, "ret");

    emitter.comment("-- php_tag_find: normalize the collected tag and strstr the allow set --");
    emitter.label("__rt_strip_tags_tag_find");
    emit_st(emitter, "ldr x2, [x29, #-64]");
    emit_st(emitter, "cbz x2, __rt_strip_tags_tag_find_no");
    emit_st(emitter, "ldr x1, [x29, #-56]");
    emit_st(emitter, "ldr x3, [x29, #-88]");
    emit_st(emitter, "mov x4, xzr");
    emit_st(emitter, "mov x5, xzr");
    emit_st(emitter, "mov x6, xzr");
    emitter.label("__rt_strip_tags_tag_find_norm");
    emit_st(emitter, "cmp x4, x2");
    emit_st(emitter, "b.hs __rt_strip_tags_tag_find_end");
    emit_st(emitter, "ldrb w0, [x1, x4]");
    emit_st(emitter, "cmp w0, #65");
    emit_st(emitter, "b.lo __rt_strip_tags_tag_find_lc_done");
    emit_st(emitter, "cmp w0, #90");
    emit_st(emitter, "b.hi __rt_strip_tags_tag_find_lc_done");
    emit_st(emitter, "orr w0, w0, #32");
    emitter.label("__rt_strip_tags_tag_find_lc_done");
    emit_st(emitter, "cmp w0, #60");
    emit_st(emitter, "b.ne __rt_strip_tags_tag_find_gt");
    emit_st(emitter, "strb w0, [x3, x5]");
    emit_st(emitter, "add x5, x5, #1");
    emit_st(emitter, "b __rt_strip_tags_tag_find_nextb");
    emitter.label("__rt_strip_tags_tag_find_gt");
    emit_st(emitter, "cmp w0, #62");
    emit_st(emitter, "b.eq __rt_strip_tags_tag_find_end");
    emit_st(emitter, "cmp w0, #9");
    emit_st(emitter, "b.lo __rt_strip_tags_tag_find_char");
    emit_st(emitter, "cmp w0, #13");
    emit_st(emitter, "b.ls __rt_strip_tags_tag_find_space");
    emit_st(emitter, "cmp w0, #32");
    emit_st(emitter, "b.ne __rt_strip_tags_tag_find_char");
    emitter.label("__rt_strip_tags_tag_find_space");
    emit_st(emitter, "cmp x6, #1");
    emit_st(emitter, "b.eq __rt_strip_tags_tag_find_end");
    emit_st(emitter, "b __rt_strip_tags_tag_find_nextb");
    emitter.label("__rt_strip_tags_tag_find_char");
    emit_st(emitter, "cbnz x6, __rt_strip_tags_tag_find_slash");
    emit_st(emitter, "mov x6, #1");
    emitter.label("__rt_strip_tags_tag_find_slash");
    emit_st(emitter, "cmp w0, #47");
    emit_st(emitter, "b.ne __rt_strip_tags_tag_find_keep");
    emit_st(emitter, "cbz x4, __rt_strip_tags_tag_find_keep");
    emit_st(emitter, "sub x7, x4, #1");
    emit_st(emitter, "ldrb w8, [x1, x7]");
    emit_st(emitter, "cmp w8, #60");
    emit_st(emitter, "b.eq __rt_strip_tags_tag_find_nextb");
    emit_st(emitter, "add x7, x4, #1");
    emit_st(emitter, "cmp x7, x2");
    emit_st(emitter, "b.hs __rt_strip_tags_tag_find_keep");
    emit_st(emitter, "ldrb w8, [x1, x7]");
    emit_st(emitter, "cmp w8, #62");
    emit_st(emitter, "b.eq __rt_strip_tags_tag_find_nextb");
    emitter.label("__rt_strip_tags_tag_find_keep");
    emit_st(emitter, "strb w0, [x3, x5]");
    emit_st(emitter, "add x5, x5, #1");
    emitter.label("__rt_strip_tags_tag_find_nextb");
    emit_st(emitter, "add x4, x4, #1");
    emit_st(emitter, "b __rt_strip_tags_tag_find_norm");
    emitter.label("__rt_strip_tags_tag_find_end");
    emit_st(emitter, "mov w0, #62");
    emit_st(emitter, "strb w0, [x3, x5]");
    emit_st(emitter, "add x5, x5, #1");
    emit_st(emitter, "ldr x4, [x29, #-72]");
    emit_st(emitter, "ldr x6, [x29, #-80]");
    emit_st(emitter, "mov x7, xzr");
    emitter.label("__rt_strip_tags_tag_find_scan");
    emit_st(emitter, "sub x8, x6, x7");
    emit_st(emitter, "cmp x8, x5");
    emit_st(emitter, "b.lo __rt_strip_tags_tag_find_no");
    emit_st(emitter, "mov x9, xzr");
    emitter.label("__rt_strip_tags_tag_find_cmp");
    emit_st(emitter, "cmp x9, x5");
    emit_st(emitter, "b.hs __rt_strip_tags_tag_find_yes");
    emit_st(emitter, "ldrb w0, [x4, x7]");
    emit_st(emitter, "ldrb w8, [x3, x9]");
    emit_st(emitter, "cmp w0, w8");
    emit_st(emitter, "b.ne __rt_strip_tags_tag_find_scan_next");
    emit_st(emitter, "add x9, x9, #1");
    emit_st(emitter, "add x7, x7, #1");
    emit_st(emitter, "b __rt_strip_tags_tag_find_cmp");
    emitter.label("__rt_strip_tags_tag_find_scan_next");
    emit_st(emitter, "sub x7, x7, x9");
    emit_st(emitter, "add x7, x7, #1");
    emit_st(emitter, "b __rt_strip_tags_tag_find_scan");
    emitter.label("__rt_strip_tags_tag_find_yes");
    emit_st(emitter, "mov w0, #1");
    emit_st(emitter, "ret");
    emitter.label("__rt_strip_tags_tag_find_no");
    emit_st(emitter, "mov w0, wzr");
    emit_st(emitter, "ret");
}
