//! Purpose:
//! Linux x86_64 `__rt_strip_tags` state machine for PHP 8.5 `strip_tags()`.
//!
//! Called from:
//! - `super::emit_strip_tags()` when the target is x86_64.
//!
//! Key details:
//! - ABI: `rdi`/`rsi` = subject pointer/length, `rdx`/`rcx` = allow pointer/length.
//! - Result: `rax`/`rdx` = stripped pointer/length, published through
//!   `__rt_concat_publish`.
//! - Zero allow length is treated as no allow-list.

use crate::codegen_support::emit::Emitter;

use super::emit_st;

/// Emits the Linux x86_64 `__rt_strip_tags` helper.
pub(super) fn emit_strip_tags_linux_x86_64(emitter: &mut Emitter) {
    emitter.blank();
    emitter.comment("--- runtime: strip_tags ---");
    emitter.label_global("__rt_strip_tags");

    emit_st(emitter, "push rbp");
    emit_st(emitter, "mov rbp, rsp");
    emit_st(emitter, "sub rsp, 208");
    emit_st(emitter, "mov QWORD PTR [rbp - 152], rbx");
    emit_st(emitter, "mov QWORD PTR [rbp - 160], r12");
    emit_st(emitter, "mov QWORD PTR [rbp - 168], r13");
    emit_st(emitter, "mov QWORD PTR [rbp - 176], r14");
    emit_st(emitter, "mov QWORD PTR [rbp - 184], r15");
    emit_st(emitter, "mov QWORD PTR [rbp - 8], rdi");
    emit_st(emitter, "mov QWORD PTR [rbp - 16], rsi");
    emit_st(emitter, "mov QWORD PTR [rbp - 24], rdx");
    emit_st(emitter, "mov QWORD PTR [rbp - 32], rcx");

    emitter.comment("-- reserve output, and allow/tag/norm scratch when an allow-list is present --");
    emit_st(emitter, "mov rax, rsi");
    emit_st(emitter, "test rcx, rcx");
    emit_st(emitter, "jz __rt_strip_tags_reserve_x86");
    emit_st(emitter, "mov rdx, rsi");
    emit_st(emitter, "shl rdx, 1");
    emit_st(emitter, "jo __rt_strip_tags_overflow_x86");
    emit_st(emitter, "add rdx, rsi");
    emit_st(emitter, "jo __rt_strip_tags_overflow_x86");
    emit_st(emitter, "add rdx, rcx");
    emit_st(emitter, "jo __rt_strip_tags_overflow_x86");
    emit_st(emitter, "add rdx, 4");
    emit_st(emitter, "jo __rt_strip_tags_overflow_x86");
    emit_st(emitter, "mov rax, rdx");
    emitter.label("__rt_strip_tags_reserve_x86");
    emit_st(emitter, "call __rt_concat_reserve");
    emit_st(emitter, "mov QWORD PTR [rbp - 40], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 48], rax");
    emit_st(emitter, "xor eax, eax");
    emit_st(emitter, "mov QWORD PTR [rbp - 56], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 64], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 72], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 80], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 88], rax");
    emit_st(emitter, "cmp QWORD PTR [rbp - 32], 0");
    emit_st(emitter, "je __rt_strip_tags_init_x86");

    emitter.comment("-- partition the reservation: out | allow_lc | tag | norm --");
    emit_st(emitter, "mov rax, QWORD PTR [rbp - 40]");
    emit_st(emitter, "add rax, QWORD PTR [rbp - 16]");
    emit_st(emitter, "mov QWORD PTR [rbp - 72], rax");
    emit_st(emitter, "mov rdx, QWORD PTR [rbp - 32]");
    emit_st(emitter, "mov QWORD PTR [rbp - 80], rdx");
    emit_st(emitter, "add rax, rdx");
    emit_st(emitter, "mov QWORD PTR [rbp - 56], rax");
    emit_st(emitter, "mov rdx, QWORD PTR [rbp - 16]");
    emit_st(emitter, "add rdx, 2");
    emit_st(emitter, "add rax, rdx");
    emit_st(emitter, "mov QWORD PTR [rbp - 88], rax");
    emit_st(emitter, "mov rsi, QWORD PTR [rbp - 24]");
    emit_st(emitter, "mov rdi, QWORD PTR [rbp - 72]");
    emit_st(emitter, "mov rcx, QWORD PTR [rbp - 32]");
    emit_st(emitter, "xor r8d, r8d");
    emitter.label("__rt_strip_tags_lc_allow_x86");
    emit_st(emitter, "cmp r8, rcx");
    emit_st(emitter, "jae __rt_strip_tags_init_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [rsi + r8]");
    emit_st(emitter, "cmp al, 65");
    emit_st(emitter, "jb __rt_strip_tags_lc_store_x86");
    emit_st(emitter, "cmp al, 90");
    emit_st(emitter, "ja __rt_strip_tags_lc_store_x86");
    emit_st(emitter, "or al, 32");
    emitter.label("__rt_strip_tags_lc_store_x86");
    emit_st(emitter, "mov BYTE PTR [rdi + r8], al");
    emit_st(emitter, "add r8, 1");
    emit_st(emitter, "jmp __rt_strip_tags_lc_allow_x86");

    emitter.label("__rt_strip_tags_init_x86");
    emit_st(emitter, "xor eax, eax");
    emit_st(emitter, "mov QWORD PTR [rbp - 96], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 120], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 128], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 136], rax");
    emit_st(emitter, "mov QWORD PTR [rbp - 144], rax");
    emit_st(emitter, "mov r12, QWORD PTR [rbp - 8]");
    emit_st(emitter, "mov r13, QWORD PTR [rbp - 16]");

    emitter.label("__rt_strip_tags_loop_x86");
    emit_st(emitter, "mov r14, QWORD PTR [rbp - 96]");
    emit_st(emitter, "cmp r14, r13");
    emit_st(emitter, "jae __rt_strip_tags_done_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14]");
    emit_st(emitter, "mov r15d, eax");
    emit_st(emitter, "mov rax, QWORD PTR [rbp - 104]");
    emit_st(emitter, "cmp rax, 0");
    emit_st(emitter, "je __rt_strip_tags_s0_x86");
    emit_st(emitter, "cmp rax, 1");
    emit_st(emitter, "je __rt_strip_tags_s1_x86");
    emit_st(emitter, "cmp rax, 2");
    emit_st(emitter, "je __rt_strip_tags_s2_x86");
    emit_st(emitter, "cmp rax, 3");
    emit_st(emitter, "je __rt_strip_tags_s3_x86");
    emit_st(emitter, "jmp __rt_strip_tags_s4_x86");

    emit_state0_x86(emitter);
    emit_state1_x86(emitter);
    emit_state2_x86(emitter);
    emit_state3_x86(emitter);
    emit_state4_x86(emitter);
    emit_helpers_x86(emitter);

    emitter.label("__rt_strip_tags_done_x86");
    emit_st(emitter, "mov rax, QWORD PTR [rbp - 40]");
    emit_st(emitter, "mov rdx, QWORD PTR [rbp - 48]");
    emit_st(emitter, "sub rdx, rax");
    emit_st(emitter, "call __rt_concat_publish");
    emit_st(emitter, "mov rbx, QWORD PTR [rbp - 152]");
    emit_st(emitter, "mov r12, QWORD PTR [rbp - 160]");
    emit_st(emitter, "mov r13, QWORD PTR [rbp - 168]");
    emit_st(emitter, "mov r14, QWORD PTR [rbp - 176]");
    emit_st(emitter, "mov r15, QWORD PTR [rbp - 184]");
    emit_st(emitter, "add rsp, 208");
    emit_st(emitter, "pop rbp");
    emit_st(emitter, "ret");

    emitter.label("__rt_strip_tags_overflow_x86");
    emit_st(emitter, "jmp __rt_alloc_overflow");
}

/// Emits output-state handling (state 0).
fn emit_state0_x86(emitter: &mut Emitter) {
    emitter.comment("-- state 0: copy bytes until a real tag opener --");
    emitter.label("__rt_strip_tags_s0_x86");
    emit_st(emitter, "test r15b, r15b");
    emit_st(emitter, "jz __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp r15b, 60");
    emit_st(emitter, "jne __rt_strip_tags_s0_gt_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "call __rt_strip_tags_next_x86");
    emit_st(emitter, "call __rt_strip_tags_isspace_x86");
    emit_st(emitter, "test eax, eax");
    emit_st(emitter, "jz __rt_strip_tags_s0_open_x86");
    emit_st(emitter, "mov eax, 60");
    emit_st(emitter, "call __rt_strip_tags_putc_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s0_open_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 136], 60");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 1");
    emit_st(emitter, "cmp QWORD PTR [rbp - 80], 0");
    emit_st(emitter, "je __rt_strip_tags_s0_open_adv_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 64], 0");
    emit_st(emitter, "mov eax, 60");
    emit_st(emitter, "call __rt_strip_tags_collect_x86");
    emitter.label("__rt_strip_tags_s0_open_adv_x86");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
    emitter.label("__rt_strip_tags_s0_gt_x86");
    emit_st(emitter, "cmp r15b, 62");
    emit_st(emitter, "jne __rt_strip_tags_s0_copy_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 120], 0");
    emit_st(emitter, "jle __rt_strip_tags_s0_gt_q_x86");
    emit_st(emitter, "sub QWORD PTR [rbp - 120], 1");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s0_gt_q_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s0_copy_x86");
    emit_st(emitter, "mov eax, r15d");
    emit_st(emitter, "call __rt_strip_tags_putc_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
}

/// Emits HTML-tag-state handling (state 1).
fn emit_state1_x86(emitter: &mut Emitter) {
    emitter.comment("-- state 1: inside a normal HTML/XML tag --");
    emitter.label("__rt_strip_tags_s1_x86");
    emit_st(emitter, "test r15b, r15b");
    emit_st(emitter, "jz __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp r15b, 60");
    emit_st(emitter, "jne __rt_strip_tags_s1_gt_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "call __rt_strip_tags_next_x86");
    emit_st(emitter, "call __rt_strip_tags_isspace_x86");
    emit_st(emitter, "test eax, eax");
    emit_st(emitter, "jz __rt_strip_tags_s1_depth_x86");
    emit_st(emitter, "mov eax, r15d");
    emit_st(emitter, "call __rt_strip_tags_collect_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s1_depth_x86");
    emit_st(emitter, "add QWORD PTR [rbp - 120], 1");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s1_gt_x86");
    emit_st(emitter, "cmp r15b, 62");
    emit_st(emitter, "jne __rt_strip_tags_s1_quote_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 120], 0");
    emit_st(emitter, "jle __rt_strip_tags_s1_gt_q_x86");
    emit_st(emitter, "sub QWORD PTR [rbp - 120], 1");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s1_gt_q_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 144], 0");
    emit_st(emitter, "je __rt_strip_tags_s1_close_x86");
    emit_st(emitter, "test r14, r14");
    emit_st(emitter, "je __rt_strip_tags_s1_close_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 1], 45");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s1_close_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 136], 62");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 144], 0");
    emit_st(emitter, "cmp QWORD PTR [rbp - 80], 0");
    emit_st(emitter, "je __rt_strip_tags_s1_close_adv_x86");
    emit_st(emitter, "mov eax, 62");
    emit_st(emitter, "call __rt_strip_tags_collect_x86");
    emit_st(emitter, "call __rt_strip_tags_tag_find_x86");
    emit_st(emitter, "test eax, eax");
    emit_st(emitter, "jz __rt_strip_tags_s1_clear_tag_x86");
    emit_st(emitter, "call __rt_strip_tags_emit_tag_x86");
    emitter.label("__rt_strip_tags_s1_clear_tag_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 64], 0");
    emitter.label("__rt_strip_tags_s1_close_adv_x86");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
    emitter.label("__rt_strip_tags_s1_quote_x86");
    emit_st(emitter, "cmp r15b, 34");
    emit_st(emitter, "je __rt_strip_tags_s1_toggle_q_x86");
    emit_st(emitter, "cmp r15b, 39");
    emit_st(emitter, "je __rt_strip_tags_s1_toggle_q_x86");
    emit_st(emitter, "cmp r15b, 33");
    emit_st(emitter, "je __rt_strip_tags_s1_bang_x86");
    emit_st(emitter, "cmp r15b, 63");
    emit_st(emitter, "je __rt_strip_tags_s1_quest_x86");
    emit_st(emitter, "mov eax, r15d");
    emit_st(emitter, "call __rt_strip_tags_collect_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s1_toggle_q_x86");
    emit_st(emitter, "test r14, r14");
    emit_st(emitter, "je __rt_strip_tags_s1_q_collect_x86");
    emit_st(emitter, "mov rax, QWORD PTR [rbp - 112]");
    emit_st(emitter, "test rax, rax");
    emit_st(emitter, "jz __rt_strip_tags_s1_q_set_x86");
    emit_st(emitter, "cmp rax, r15");
    emit_st(emitter, "jne __rt_strip_tags_s1_q_collect_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jmp __rt_strip_tags_s1_q_collect_x86");
    emitter.label("__rt_strip_tags_s1_q_set_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], r15");
    emitter.label("__rt_strip_tags_s1_q_collect_x86");
    emit_st(emitter, "mov eax, r15d");
    emit_st(emitter, "call __rt_strip_tags_collect_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s1_bang_x86");
    emit_st(emitter, "test r14, r14");
    emit_st(emitter, "je __rt_strip_tags_s1_bang_col_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 1], 60");
    emit_st(emitter, "jne __rt_strip_tags_s1_bang_col_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 3");
    emit_st(emitter, "mov QWORD PTR [rbp - 136], r15");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
    emitter.label("__rt_strip_tags_s1_bang_col_x86");
    emit_st(emitter, "mov eax, r15d");
    emit_st(emitter, "call __rt_strip_tags_collect_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s1_quest_x86");
    emit_st(emitter, "test r14, r14");
    emit_st(emitter, "je __rt_strip_tags_s1_quest_col_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 1], 60");
    emit_st(emitter, "jne __rt_strip_tags_s1_quest_col_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 128], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 2");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
    emitter.label("__rt_strip_tags_s1_quest_col_x86");
    emit_st(emitter, "mov eax, r15d");
    emit_st(emitter, "call __rt_strip_tags_collect_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
}

/// Emits PHP-tag-state handling (state 2).
fn emit_state2_x86(emitter: &mut Emitter) {
    emitter.comment("-- state 2: inside a PHP tag, unless `<?xml` returns to HTML --");
    emitter.label("__rt_strip_tags_s2_x86");
    emit_st(emitter, "cmp r15b, 40");
    emit_st(emitter, "jne __rt_strip_tags_s2_rparen_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 136], 34");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 136], 39");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 136], 40");
    emit_st(emitter, "add QWORD PTR [rbp - 128], 1");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s2_rparen_x86");
    emit_st(emitter, "cmp r15b, 41");
    emit_st(emitter, "jne __rt_strip_tags_s2_gt_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 136], 34");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 136], 39");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 136], 41");
    emit_st(emitter, "sub QWORD PTR [rbp - 128], 1");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s2_gt_x86");
    emit_st(emitter, "cmp r15b, 62");
    emit_st(emitter, "jne __rt_strip_tags_s2_quote_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 120], 0");
    emit_st(emitter, "jle __rt_strip_tags_s2_gt_q_x86");
    emit_st(emitter, "sub QWORD PTR [rbp - 120], 1");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s2_gt_q_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 128], 0");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 136], 34");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "test r14, r14");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 1], 63");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 64], 0");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
    emitter.label("__rt_strip_tags_s2_quote_x86");
    emit_st(emitter, "cmp r15b, 34");
    emit_st(emitter, "je __rt_strip_tags_s2_q_x86");
    emit_st(emitter, "cmp r15b, 39");
    emit_st(emitter, "je __rt_strip_tags_s2_q_x86");
    emit_st(emitter, "cmp r15b, 108");
    emit_st(emitter, "je __rt_strip_tags_s2_xml_x86");
    emit_st(emitter, "cmp r15b, 76");
    emit_st(emitter, "je __rt_strip_tags_s2_xml_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s2_q_x86");
    emit_st(emitter, "test r14, r14");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 1], 92");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov rax, QWORD PTR [rbp - 136]");
    emit_st(emitter, "cmp rax, r15");
    emit_st(emitter, "jne __rt_strip_tags_s2_q_set_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 136], 0");
    emit_st(emitter, "jmp __rt_strip_tags_s2_q_in_x86");
    emitter.label("__rt_strip_tags_s2_q_set_x86");
    emit_st(emitter, "cmp rax, 92");
    emit_st(emitter, "je __rt_strip_tags_s2_q_in_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 136], r15");
    emitter.label("__rt_strip_tags_s2_q_in_x86");
    emit_st(emitter, "test r14, r14");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov rax, QWORD PTR [rbp - 112]");
    emit_st(emitter, "test rax, rax");
    emit_st(emitter, "jz __rt_strip_tags_s2_q_open_x86");
    emit_st(emitter, "cmp rax, r15");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s2_q_open_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], r15");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s2_xml_x86");
    emit_st(emitter, "cmp r14, 4");
    emit_st(emitter, "jb __rt_strip_tags_advance_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14 - 1]");
    emit_st(emitter, "or al, 32");
    emit_st(emitter, "cmp al, 109");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14 - 2]");
    emit_st(emitter, "or al, 32");
    emit_st(emitter, "cmp al, 120");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 3], 63");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 4], 60");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 1");
    emit_st(emitter, "mov QWORD PTR [rbp - 144], 1");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
}

/// Emits `<!...` handling (state 3), including comments and `<!DOCTYPE`.
fn emit_state3_x86(emitter: &mut Emitter) {
    emitter.comment("-- state 3: `<!` markup, comments, and DOCTYPE --");
    emitter.label("__rt_strip_tags_s3_x86");
    emit_st(emitter, "cmp r15b, 62");
    emit_st(emitter, "jne __rt_strip_tags_s3_quote_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 120], 0");
    emit_st(emitter, "jle __rt_strip_tags_s3_gt_q_x86");
    emit_st(emitter, "sub QWORD PTR [rbp - 120], 1");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s3_gt_q_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 64], 0");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
    emitter.label("__rt_strip_tags_s3_quote_x86");
    emit_st(emitter, "cmp r15b, 34");
    emit_st(emitter, "je __rt_strip_tags_s3_q_x86");
    emit_st(emitter, "cmp r15b, 39");
    emit_st(emitter, "je __rt_strip_tags_s3_q_x86");
    emit_st(emitter, "cmp r15b, 45");
    emit_st(emitter, "je __rt_strip_tags_s3_dash_x86");
    emit_st(emitter, "cmp r15b, 69");
    emit_st(emitter, "je __rt_strip_tags_s3_doctype_x86");
    emit_st(emitter, "cmp r15b, 101");
    emit_st(emitter, "je __rt_strip_tags_s3_doctype_x86");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s3_q_x86");
    emit_st(emitter, "test r14, r14");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 1], 92");
    emit_st(emitter, "je __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov rax, QWORD PTR [rbp - 112]");
    emit_st(emitter, "test rax, rax");
    emit_st(emitter, "jz __rt_strip_tags_s3_q_open_x86");
    emit_st(emitter, "cmp rax, r15");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s3_q_open_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], r15");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
    emitter.label("__rt_strip_tags_s3_dash_x86");
    emit_st(emitter, "cmp r14, 2");
    emit_st(emitter, "jb __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 1], 45");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 2], 33");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 4");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
    emitter.label("__rt_strip_tags_s3_doctype_x86");
    emit_st(emitter, "cmp r14, 7");
    emit_st(emitter, "jbe __rt_strip_tags_advance_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14 - 1]");
    emit_st(emitter, "or al, 32");
    emit_st(emitter, "cmp al, 112");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14 - 2]");
    emit_st(emitter, "or al, 32");
    emit_st(emitter, "cmp al, 121");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14 - 3]");
    emit_st(emitter, "or al, 32");
    emit_st(emitter, "cmp al, 116");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14 - 4]");
    emit_st(emitter, "or al, 32");
    emit_st(emitter, "cmp al, 99");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14 - 5]");
    emit_st(emitter, "or al, 32");
    emit_st(emitter, "cmp al, 111");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + r14 - 6]");
    emit_st(emitter, "or al, 32");
    emit_st(emitter, "cmp al, 100");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 1");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");
}

/// Emits HTML-comment handling (state 4).
fn emit_state4_x86(emitter: &mut Emitter) {
    emitter.comment("-- state 4: HTML comment, closed only by `-->` --");
    emitter.label("__rt_strip_tags_s4_x86");
    emit_st(emitter, "cmp r15b, 62");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp r14, 2");
    emit_st(emitter, "jb __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 1], 45");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "cmp BYTE PTR [r12 + r14 - 2], 45");
    emit_st(emitter, "jne __rt_strip_tags_advance_x86");
    emit_st(emitter, "mov QWORD PTR [rbp - 112], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 104], 0");
    emit_st(emitter, "mov QWORD PTR [rbp - 64], 0");
    emit_st(emitter, "jmp __rt_strip_tags_advance_x86");
}

/// Emits local helpers shared by the x86_64 state machine.
fn emit_helpers_x86(emitter: &mut Emitter) {
    emitter.label("__rt_strip_tags_advance_x86");
    emit_st(emitter, "add QWORD PTR [rbp - 96], 1");
    emit_st(emitter, "jmp __rt_strip_tags_loop_x86");

    emitter.comment("-- write one kept output byte --");
    emitter.label("__rt_strip_tags_putc_x86");
    emit_st(emitter, "mov rdx, QWORD PTR [rbp - 48]");
    emit_st(emitter, "mov BYTE PTR [rdx], al");
    emit_st(emitter, "add rdx, 1");
    emit_st(emitter, "mov QWORD PTR [rbp - 48], rdx");
    emit_st(emitter, "ret");

    emitter.comment("-- append one collected tag byte when an allow-list is active --");
    emitter.label("__rt_strip_tags_collect_x86");
    emit_st(emitter, "cmp QWORD PTR [rbp - 80], 0");
    emit_st(emitter, "je __rt_strip_tags_collect_ret_x86");
    emit_st(emitter, "mov rdx, QWORD PTR [rbp - 56]");
    emit_st(emitter, "mov rcx, QWORD PTR [rbp - 64]");
    emit_st(emitter, "mov BYTE PTR [rdx + rcx], al");
    emit_st(emitter, "add rcx, 1");
    emit_st(emitter, "mov QWORD PTR [rbp - 64], rcx");
    emitter.label("__rt_strip_tags_collect_ret_x86");
    emit_st(emitter, "ret");

    emitter.comment("-- copy a kept allowed tag into the output --");
    emitter.label("__rt_strip_tags_emit_tag_x86");
    emit_st(emitter, "mov rsi, QWORD PTR [rbp - 56]");
    emit_st(emitter, "mov rcx, QWORD PTR [rbp - 64]");
    emit_st(emitter, "mov rdi, QWORD PTR [rbp - 48]");
    emit_st(emitter, "xor r8d, r8d");
    emitter.label("__rt_strip_tags_emit_tag_loop_x86");
    emit_st(emitter, "cmp r8, rcx");
    emit_st(emitter, "jae __rt_strip_tags_emit_tag_done_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [rsi + r8]");
    emit_st(emitter, "mov BYTE PTR [rdi + r8], al");
    emit_st(emitter, "add r8, 1");
    emit_st(emitter, "jmp __rt_strip_tags_emit_tag_loop_x86");
    emitter.label("__rt_strip_tags_emit_tag_done_x86");
    emit_st(emitter, "add rdi, rcx");
    emit_st(emitter, "mov QWORD PTR [rbp - 48], rdi");
    emit_st(emitter, "ret");

    emitter.comment("-- load the next subject byte, or 0 at EOF, into al --");
    emitter.label("__rt_strip_tags_next_x86");
    emit_st(emitter, "mov rdx, r14");
    emit_st(emitter, "add rdx, 1");
    emit_st(emitter, "cmp rdx, r13");
    emit_st(emitter, "jae __rt_strip_tags_next_eof_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r12 + rdx]");
    emit_st(emitter, "ret");
    emitter.label("__rt_strip_tags_next_eof_x86");
    emit_st(emitter, "xor eax, eax");
    emit_st(emitter, "ret");

    emitter.comment("-- C-locale isspace: 0x09-0x0d or 0x20; result in eax --");
    emitter.label("__rt_strip_tags_isspace_x86");
    emit_st(emitter, "cmp al, 9");
    emit_st(emitter, "jb __rt_strip_tags_isspace_no_x86");
    emit_st(emitter, "cmp al, 13");
    emit_st(emitter, "jbe __rt_strip_tags_isspace_yes_x86");
    emit_st(emitter, "cmp al, 32");
    emit_st(emitter, "je __rt_strip_tags_isspace_yes_x86");
    emitter.label("__rt_strip_tags_isspace_no_x86");
    emit_st(emitter, "xor eax, eax");
    emit_st(emitter, "ret");
    emitter.label("__rt_strip_tags_isspace_yes_x86");
    emit_st(emitter, "mov eax, 1");
    emit_st(emitter, "ret");

    emitter.comment("-- php_tag_find: normalize the collected tag and strstr the allow set --");
    emitter.label("__rt_strip_tags_tag_find_x86");
    emit_st(emitter, "mov rcx, QWORD PTR [rbp - 64]");
    emit_st(emitter, "test rcx, rcx");
    emit_st(emitter, "jz __rt_strip_tags_tag_find_no_x86");
    emit_st(emitter, "mov rsi, QWORD PTR [rbp - 56]");
    emit_st(emitter, "mov rdi, QWORD PTR [rbp - 88]");
    emit_st(emitter, "xor r8d, r8d");
    emit_st(emitter, "xor r9d, r9d");
    emit_st(emitter, "xor r10d, r10d");
    emitter.label("__rt_strip_tags_tag_find_norm_x86");
    emit_st(emitter, "cmp r8, rcx");
    emit_st(emitter, "jae __rt_strip_tags_tag_find_end_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [rsi + r8]");
    emit_st(emitter, "cmp al, 65");
    emit_st(emitter, "jb __rt_strip_tags_tag_find_lc_done_x86");
    emit_st(emitter, "cmp al, 90");
    emit_st(emitter, "ja __rt_strip_tags_tag_find_lc_done_x86");
    emit_st(emitter, "or al, 32");
    emitter.label("__rt_strip_tags_tag_find_lc_done_x86");
    emit_st(emitter, "cmp al, 60");
    emit_st(emitter, "jne __rt_strip_tags_tag_find_gt_x86");
    emit_st(emitter, "mov BYTE PTR [rdi + r9], al");
    emit_st(emitter, "add r9, 1");
    emit_st(emitter, "jmp __rt_strip_tags_tag_find_next_x86");
    emitter.label("__rt_strip_tags_tag_find_gt_x86");
    emit_st(emitter, "cmp al, 62");
    emit_st(emitter, "je __rt_strip_tags_tag_find_end_x86");
    emit_st(emitter, "cmp al, 9");
    emit_st(emitter, "jb __rt_strip_tags_tag_find_char_x86");
    emit_st(emitter, "cmp al, 13");
    emit_st(emitter, "jbe __rt_strip_tags_tag_find_space_x86");
    emit_st(emitter, "cmp al, 32");
    emit_st(emitter, "jne __rt_strip_tags_tag_find_char_x86");
    emitter.label("__rt_strip_tags_tag_find_space_x86");
    emit_st(emitter, "cmp r10, 1");
    emit_st(emitter, "je __rt_strip_tags_tag_find_end_x86");
    emit_st(emitter, "jmp __rt_strip_tags_tag_find_next_x86");
    emitter.label("__rt_strip_tags_tag_find_char_x86");
    emit_st(emitter, "test r10, r10");
    emit_st(emitter, "jnz __rt_strip_tags_tag_find_slash_x86");
    emit_st(emitter, "mov r10, 1");
    emitter.label("__rt_strip_tags_tag_find_slash_x86");
    emit_st(emitter, "cmp al, 47");
    emit_st(emitter, "jne __rt_strip_tags_tag_find_keep_x86");
    emit_st(emitter, "test r8, r8");
    emit_st(emitter, "je __rt_strip_tags_tag_find_keep_x86");
    emit_st(emitter, "cmp BYTE PTR [rsi + r8 - 1], 60");
    emit_st(emitter, "je __rt_strip_tags_tag_find_next_x86");
    emit_st(emitter, "mov rdx, r8");
    emit_st(emitter, "add rdx, 1");
    emit_st(emitter, "cmp rdx, rcx");
    emit_st(emitter, "jae __rt_strip_tags_tag_find_keep_x86");
    emit_st(emitter, "cmp BYTE PTR [rsi + rdx], 62");
    emit_st(emitter, "je __rt_strip_tags_tag_find_next_x86");
    emitter.label("__rt_strip_tags_tag_find_keep_x86");
    emit_st(emitter, "mov BYTE PTR [rdi + r9], al");
    emit_st(emitter, "add r9, 1");
    emitter.label("__rt_strip_tags_tag_find_next_x86");
    emit_st(emitter, "add r8, 1");
    emit_st(emitter, "jmp __rt_strip_tags_tag_find_norm_x86");
    emitter.label("__rt_strip_tags_tag_find_end_x86");
    emit_st(emitter, "mov BYTE PTR [rdi + r9], 62");
    emit_st(emitter, "add r9, 1");
    emit_st(emitter, "mov r8, QWORD PTR [rbp - 72]");
    emit_st(emitter, "mov r10, QWORD PTR [rbp - 80]");
    emit_st(emitter, "xor r11d, r11d");
    emitter.label("__rt_strip_tags_tag_find_scan_x86");
    emit_st(emitter, "mov rax, r10");
    emit_st(emitter, "sub rax, r11");
    emit_st(emitter, "cmp rax, r9");
    emit_st(emitter, "jb __rt_strip_tags_tag_find_no_x86");
    emit_st(emitter, "xor ecx, ecx");
    emitter.label("__rt_strip_tags_tag_find_cmp_x86");
    emit_st(emitter, "cmp rcx, r9");
    emit_st(emitter, "jae __rt_strip_tags_tag_find_yes_x86");
    emit_st(emitter, "movzx eax, BYTE PTR [r8 + r11]");
    emit_st(emitter, "movzx edx, BYTE PTR [rdi + rcx]");
    emit_st(emitter, "cmp al, dl");
    emit_st(emitter, "jne __rt_strip_tags_tag_find_scan_next_x86");
    emit_st(emitter, "add rcx, 1");
    emit_st(emitter, "add r11, 1");
    emit_st(emitter, "jmp __rt_strip_tags_tag_find_cmp_x86");
    emitter.label("__rt_strip_tags_tag_find_scan_next_x86");
    emit_st(emitter, "sub r11, rcx");
    emit_st(emitter, "add r11, 1");
    emit_st(emitter, "jmp __rt_strip_tags_tag_find_scan_x86");
    emitter.label("__rt_strip_tags_tag_find_yes_x86");
    emit_st(emitter, "mov eax, 1");
    emit_st(emitter, "ret");
    emitter.label("__rt_strip_tags_tag_find_no_x86");
    emit_st(emitter, "xor eax, eax");
    emit_st(emitter, "ret");
}
