[profile.default]
slow-timeout = { period = "300s", terminate-after = 1 }

[profile.ci]
failure-output = "immediate-final"
final-status-level = "slow"
slow-timeout = { period = "300s", terminate-after = 1 }
status-level = "slow"
