//! Purpose:
//! Pins the generated PHP 8.5.8 DOM/libxml/SimpleXML Reflection surface consumed by the registry.
//! Keeps provenance constants next to the embedded artifact so version drift is reviewable.
//!
//! Called from:
//! - `crate::internal_extensions::registry()`.
//!
//! Key details:
//! - The JSON is generated by `tools/php-dom/snapshot_surface.php` from the exact oracle.
//! - Changing any version, digest, or embedded bytes invalidates the locked DOM specification.

/// PHP version represented by the embedded surface.
pub const PHP_VERSION: &str = "8.5.8";

/// libxml2 version number used by the embedded oracle.
pub const LIBXML_VERSION: u32 = 21_503;

/// Complete generated DOM/libxml/SimpleXML Reflection snapshot.
pub const PHP_8_5_8_SURFACE: &str =
    include_str!("../../tests/php_dom/surface/php-8.5.8.json");
