/* build-defs.h — generated by php's configure, reproduced by Elephc.
 *
 * Upstream this records where php was installed: prefix, extension directory,
 * pear path, the full configure command line. None of it applies to a hosted
 * extension compiled into an Elephc binary — there is no php installation to
 * point at — so the values are empty rather than borrowed from whichever php
 * happened to be on the build machine.
 *
 * Extensions that read these are describing an environment Elephc does not
 * provide; an empty string is the honest answer, not a placeholder.
 */

#define CONFIGURE_COMMAND   "(hosted by elephc)"
#define PHP_PROG_SENDMAIL   ""
#define PEAR_INSTALLDIR     ""
#define PHP_INCLUDE_PATH    "."
#define PHP_EXTENSION_DIR   ""
#define PHP_PREFIX          ""
#define PHP_BINDIR          ""
#define PHP_SBINDIR         ""
#define PHP_MANDIR          ""
#define PHP_LIBDIR          ""
#define PHP_DATADIR         ""
#define PHP_SYSCONFDIR      ""
#define PHP_LOCALSTATEDIR   ""
#define PHP_CONFIG_FILE_PATH ""
#define PHP_CONFIG_FILE_SCAN_DIR ""
#define PHP_SHLIB_SUFFIX    "so"
#define PHP_SHLIB_EXT_PREFIX ""
