/* zend_config.h — generated by php's configure, reproduced by Elephc.
 *
 * On Unix this file's entire content is a redirect to the main configuration,
 * which is why supplying it costs nothing.
 */

#include <../main/php_config.h>
