//! Purpose:
//! Reads compact Unicode property and case tables generated from the pinned UCD.
//!
//! Called from:
//! - `super` for width, character properties, and case conversion.
//!
//! Key details:
//! - Records are little-endian integers, independent of the compilation target.
//! - Case records contain source, simple mapping, full length, and three outputs.

/// Unicode uppercase mappings sorted by source codepoint.
pub(super) const UPPER: &[u8] = include_bytes!("data/upper.bin");
/// Unicode lowercase mappings sorted by source codepoint.
pub(super) const LOWER: &[u8] = include_bytes!("data/lower.bin");
/// Unicode title mappings sorted by source codepoint.
pub(super) const TITLE: &[u8] = include_bytes!("data/title.bin");
/// Unicode case folding mappings sorted by source codepoint.
pub(super) const FOLD: &[u8] = include_bytes!("data/fold.bin");
/// Inclusive ranges containing the Unicode Cased property.
pub(super) const CASED: &[u8] = include_bytes!("data/cased.bin");
/// Inclusive ranges containing the Unicode Case_Ignorable property.
pub(super) const IGNORABLE: &[u8] = include_bytes!("data/case_ignorable.bin");
/// Inclusive ranges of East Asian Wide and Fullwidth characters.
pub(super) const WIDE: &[u8] = include_bytes!("data/wide.bin");

/// Reads a little-endian word from generated bytes without alignment assumptions.
fn word(bytes: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes(bytes[offset..offset + 4].try_into().expect("generated word"))
}

/// Locates the first record whose first word is greater than the requested codepoint.
fn upper_bound(table: &[u8], size: usize, code: u32) -> usize {
    let (mut low, mut high) = (0, table.len() / size);
    while low < high {
        let mid = low + (high - low) / 2;
        if word(table, mid * size) <= code {
            low = mid + 1;
        } else {
            high = mid;
        }
    }
    low
}

/// Reports whether a codepoint belongs to sorted inclusive property ranges.
pub(super) fn contains(table: &[u8], code: u32) -> bool {
    let index = upper_bound(table, 8, code);
    index != 0 && code <= word(table, (index - 1) * 8 + 4)
}

/// Appends one full or simple case mapping, preserving unmapped codepoints.
pub(super) fn append_case(table: &[u8], code: u32, simple: bool, output: &mut Vec<u32>) {
    let index = upper_bound(table, 24, code);
    if index == 0 || word(table, (index - 1) * 24) != code {
        output.push(code);
        return;
    }
    let offset = (index - 1) * 24;
    if simple {
        output.push(word(table, offset + 4));
    } else {
        let count = word(table, offset + 8) as usize;
        for index in 0..count {
            output.push(word(table, offset + 12 + index * 4));
        }
    }
}
